In [3]:
import pandas as pd

initial import

In [31]:
pd.read_csv('../Data/Speeches/cleaned_speeches.csv',sep='\t')

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
0,1,developments-in-uk-financial-markets,1,Developments in UK financial markets Speech gi...,43,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
1,1,developments-in-uk-financial-markets,2,"""The UKs new monetary framework Perhaps the si...",146,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
2,1,developments-in-uk-financial-markets,3,The framework put in place with that announcem...,33,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
3,1,developments-in-uk-financial-markets,4,"""First, the target the Bank of England is to p...",79,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
4,1,developments-in-uk-financial-markets,5,"""Secondly, it is then the responsibility of th...",120,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88401,1495,cost-of-capital-and-uk-business-investment-sli...,17,Sales surprises and the marginal propensity to...,149,False,False,False,2024-05-17,CATHERINE L MANN,True,False,False
88402,1503,remarks-given-by-swati-dhingra-at-econdat-2024...,10,Bank of England Page 12 Appendix Chart 8: Cent...,44,False,False,False,2024-05-10,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False

descriptive stats

In [32]:
df= pd.read_csv('../Data/Speeches/cleaned_speeches.csv',sep='\t')

In [33]:
df.speechID.value_counts() # 912 speeches of varying number of paragraphs

speechID
976     557
919     442
273     392
292     375
970     365
       ...
1416      1
1511      1
1359      1
1503      1
1330      1
Name: count, Length: 1202, dtype: int64

In [34]:
df

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
0,1,developments-in-uk-financial-markets,1,Developments in UK financial markets Speech gi...,43,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
1,1,developments-in-uk-financial-markets,2,"""The UKs new monetary framework Perhaps the si...",146,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
2,1,developments-in-uk-financial-markets,3,The framework put in place with that announcem...,33,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
3,1,developments-in-uk-financial-markets,4,"""First, the target the Bank of England is to p...",79,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
4,1,developments-in-uk-financial-markets,5,"""Secondly, it is then the responsibility of th...",120,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88401,1495,cost-of-capital-and-uk-business-investment-sli...,17,Sales surprises and the marginal propensity to...,149,False,False,False,2024-05-17,CATHERINE L MANN,True,False,False
88402,1503,remarks-given-by-swati-dhingra-at-econdat-2024...,10,Bank of England Page 12 Appendix Chart 8: Cent...,44,False,False,False,2024-05-10,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False

In [35]:
df.groupby('speechID')['nWords'].sum().astype(float).describe() # 1200 speeches, average 5900 words, median 4400

count      1202.000000
mean       5971.695507
std        6161.393909
min           2.000000
25%        2675.250000
50%        4411.500000
75%        7323.000000
max      107165.000000
Name: nWords, dtype: float64

In [36]:
df['para']

0        Developments in UK financial markets Speech gi...
1        "The UKs new monetary framework Perhaps the si...
2        The framework put in place with that announcem...
3        "First, the target the Bank of England is to p...
4        "Secondly, it is then the responsibility of th...
                               ...
88401    Sales surprises and the marginal propensity to...
88402    Bank of England Page 12 Appendix Chart 8: Cent...
88403    Analytical Toolkit Fools Gold: refinements to ...
88404    Analytical Toolkit Fools Gold: forecast refine...
88405    Research design to understand mechanisms Granu...
Name: para, Length: 88406, dtype: object

In [40]:
df[df['speechID'] == 5].sort_values('para')

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
206,5,the-inflation-target-five-years-on,70,"""(ii) The Inflation Report will continue, ...",117,True,False,False,1997-10-29,MERVYN KING,True,False,False
207,5,the-inflation-target-five-years-on,71,"""(iii) Appearances before the Treasury Sele...",65,True,False,False,1997-10-29,MERVYN KING,True,False,False
209,5,the-inflation-target-five-years-on,73,"""(iv) The MPC is required to send an open ...",163,True,False,False,1997-10-29,MERVYN KING,True,False,False
210,5,the-inflation-target-five-years-on,74,"""(v) Finally, the MPC is accountable to t...",61,True,False,False,1997-10-29,MERVYN KING,True,False,False
242,5,the-inflation-target-five-years-on,106,"""* Inflation is measured as the annual increas...",27,False,False,False,1997-10-29,MERVYN KING,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,5,the-inflation-target-five-years-on,65,Transparency is desirable because it improves ...,24,True,False,False,1997-10-29,MERVYN KING,True,False,False
221,5,the-inflation-target-five-years-on,85,What has been the experience of countries with...,10,False,False,False,1997-10-29,MERVYN KING,True,False,False
223,5,the-inflation-target-five-years-on,87,What is the role of inflation forecasts?,7,False,False,False,1997-10-29,MERVYN KING,True,False,False
224,5,the-inflation-target-five-years-on,88,Why is openness and transparency important?,6,False,False,False,1997-10-29,MERVYN KING,True,False,False
238,5,the-inflation-target-five-years-on,102,percent 10.0,2,False,False,False,1997-10-29,MERVYN KING,True,False,False

In [41]:
df[['because' in i and 'inflation' in i for i in df['para']]]#['para'].values

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
176,5,the-inflation-target-five-years-on,40,"""Many supply shocks are price level effects. F...",206,True,False,False,1997-10-29,MERVYN KING,True,False,False
389,9,economic-policy-with-and-without-forecasts,22,"""We have tried to interest universities in thi...",1081,False,False,False,1998-05-14,ALAN BUDD,True,False,False
439,10,edward-george-institute-of-directors,35,"""Now there are those - perhaps even one or two...",88,False,False,False,1998-11-19,EDDIE GEORGE,True,False,False
461,12,edward-george-tuc-congression,2,"""Let me start with what is perhaps your bigges...",133,False,False,False,1998-09-15,EDDIE GEORGE,True,False,False
469,12,edward-george-tuc-congression,10,"""But, even if we agree on the objective, that ...",145,False,False,False,1998-09-15,EDDIE GEORGE,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88268,1378,monetary-policy-with-a-steady-hand-speech-by-h...,13,Retaining flexibility is important. And given ...,327,False,False,False,2022-02-09,HUW PILL,True,False,False
88280,1388,on-returning-inflation-back-to-target-speech-b...,4,It is often said that monetary policy should l...,533,False,False,False,2022-01-21,CATHERINE L MANN,True,False,False
88305,1395,the-state-of-financial-stability-speech-by-jon...,3,"Such corrections happen every day, of course. ...",428,False,False,False,2022-03-02,JON CUNLIFFE,True,True,True
88312,1395,the-state-of-financial-stability-speech-by-jon...,10,"To be clear, a period of adjustment to bring t...",498,False,False,False,2022-03-02,JON CUNLIFFE,True,True,True
88370,1494,climate-change-the-macroeconomy-and-monetary-p...,11,Inflation Impacts what does the literature say...,109,False,False,False,2024-04-25,ANDREW BAILEY,True,True,True

In [39]:
df.date= pd.to_datetime(df.date, format='%Y-%m-%d')
df.sort_values('date')

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
69,3,edward-george-queen-elizabeth-conference-centre,1,"""Speech by the Governor at the Queen Elizabeth...",128,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
92,3,edward-george-queen-elizabeth-conference-centre,24,"""And I conclude, thirdly, that there remains s...",34,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
91,3,edward-george-queen-elizabeth-conference-centre,23,"""I conclude, secondly, that the markets see cu...",30,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
90,3,edward-george-queen-elizabeth-conference-centre,22,"""I conclude, first, that markets at present ar...",79,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
89,3,edward-george-queen-elizabeth-conference-centre,21,"""What can we conclude from all this, Mr Chairm...",22,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88389,1507,speech-slides-by-jonathan-haskel-on-uk-inflati...,2,"1. Some questions about inflation, uncertainty...",28,False,False,False,2024-07-08,JONATHAN HASKEL,True,False,False
88395,1511,uk-inflation-whats-done-and-whats-to-come-spee...,25,Bank of England Page 29 Price inflation CPI pu...,844,False,False,False,2024-07-08,JONATHAN HASKEL,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False

In [1]:
df = pd.read_csv(r"C:\Users\339306\Downloads\CBS_dataset_v1.0.csv",nrows = 100)

NameError: name 'pd' is not defined

In [4]:
import pandas as pd
import os

In [5]:
df = pd.read_csv(r"C:\Users\339306\Downloads\CBS_dataset_v1.0.csv")

In [6]:
df['Language'].value_counts()

Language
English             30140
Spanish               834
German                698
Italian               612
Portuguese            537
French                361
Albanian              333
Finnish               312
Swedish               231
Dutch                 222
Thai                  201
Greek                  84
Icelandic              82
Norwegian              81
Chinese                78
Turkish                74
Indonesian             67
Bulgarian              63
Korean                 59
Croatian               57
Macedonian             56
Hebrew                 44
Danish                 42
Russian                35
Lithuanian             34
Slovak                 30
Arabic                 22
Czech                  16
Kazakh                 14
Armenian               14
Slovenian              13
Creole                 12
Polish                  9
Khmer                   6
French and Dutch        5
Bosnian                 3
Nepali                  2
Filipino                2
Samoan                  2
Name: count, dtype: int64

In [7]:
df[df['Language']=='English']['CentralBank'].value_counts()

CentralBank
Board of Governors of the Federal Reserve    2658
European Central Bank                        2522
Bank of England                              1354
Reserve Bank of India                        1071
Central Bank of the Philippines               990
                                             ...
Central Bank of Bolivia                         1
Central Bank of Jordan                          1
Bank of the Republic of Burundi                 1
Central Bank of Ecuador                         1
Central Bank of Uruguay                         1
Name: count, Length: 132, dtype: int64

In [8]:
pd.to_datetime(df['Date']).min(),pd.to_datetime(df['Date']).max()

(Timestamp('1986-01-06 00:00:00'), Timestamp('2023-12-29 00:00:00'))

In [9]:
print(df[df['Language']=='English'][['text','Date']].iloc[-1])

text    Speeches\n\nBeyond Short-Term Interests\n\nJac...
Date                                           2003-11-21
Name: 35486, dtype: object

In [10]:
import os

In [11]:
os.listdir("../Data/Speeches/")

['.DS_Store',
 'cleaned_speeches_BOE_from_website.csv',
 'speechContent.txt',
 'speeches_by_central_bank',
 'speechMetadata.csv']

In [12]:
for i in df[df['Language']=='English']['CentralBank'].value_counts().iloc[0:50].reset_index().iterrows():
    print(i)
    #print(df[df['Language']=='English'][df['CentralBank']==i]['text'].values[0][:100])
    print('\n')

(0, CentralBank    Board of Governors of the Federal Reserve
count                                               2658
Name: 0, dtype: object)


(1, CentralBank    European Central Bank
count                           2522
Name: 1, dtype: object)


(2, CentralBank    Bank of England
count                     1354
Name: 2, dtype: object)


(3, CentralBank    Reserve Bank of India
count                           1071
Name: 3, dtype: object)


(4, CentralBank    Central Bank of the Philippines
count                                      990
Name: 4, dtype: object)


(5, CentralBank    Monetary Authority of Singapore
count                                      914
Name: 5, dtype: object)


(6, CentralBank    Deutsche Bundesbank
count                          903
Name: 6, dtype: object)


(7, CentralBank    Bank of Japan
count                    826
Name: 7, dtype: object)


(8, CentralBank    Central Bank of Ireland
count                              728
Name: 8, dtype: object)


(9, CentralBank    Central Bank of Malaysia
count                               699
Name: 9, dtype: object)


(10, CentralBank    Reserve Bank of Australia
count                                641
Name: 10, dtype: object)


(11, CentralBank    Bank of Canada
count                     640
Name: 11, dtype: object)


(12, CentralBank    Federal Reserve Bank of New York
count                                       614
Name: 12, dtype: object)


(13, CentralBank    Sveriges Riksbank
count                        532
Name: 13, dtype: object)


(14, CentralBank    Federal Reserve Bank of Atlanta
count                                      527
Name: 14, dtype: object)


(15, CentralBank    Swiss National Bank
count                          493
Name: 15, dtype: object)


(16, CentralBank    South African Reserve Bank
count                                 453
Name: 16, dtype: object)


(17, CentralBank    Federal Reserve Bank of San Francisco
count                                            449
Name: 17, dtype: object)


(18, CentralBank    Bank of France
count                     435
Name: 18, dtype: object)


(19, CentralBank    Hong Kong Monetary Authority
count                                   434
Name: 19, dtype: object)


(20, CentralBank    Bank of Italy
count                    428
Name: 20, dtype: object)


(21, CentralBank    Bank of Spain
count                    419
Name: 21, dtype: object)


(22, CentralBank    Federal Reserve Bank of Chicago
count                                      418
Name: 22, dtype: object)


(23, CentralBank    Bank of Uganda
count                     365
Name: 23, dtype: object)


(24, CentralBank    Federal Reserve Bank of Cleveland
count                                        353
Name: 24, dtype: object)


(25, CentralBank    Norges Bank
count                  308
Name: 25, dtype: object)


(26, CentralBank    Bank of Albania
count                      299
Name: 26, dtype: object)


(27, CentralBank    Bank of Thailand
count                       291
Name: 27, dtype: object)


(28, CentralBank    De Nederlandsche Bank
count                            283
Name: 28, dtype: object)


(29, CentralBank    Federal Reserve Bank of Philadelphia
count                                           282
Name: 29, dtype: object)


(30, CentralBank    Bank of Finland
count                      282
Name: 30, dtype: object)


(31, CentralBank    Central Bank of Kenya
count                            275
Name: 31, dtype: object)


(32, CentralBank    State Bank of Pakistan
count                             267
Name: 32, dtype: object)


(33, CentralBank    Federal Reserve Bank of Richmond
count                                       266
Name: 33, dtype: object)


(34, CentralBank    Central Bank of Hungary
count                              263
Name: 34, dtype: object)


(35, CentralBank    Bangladesh Bank
count                      254
Name: 35, dtype: object)


(36, CentralBank    Federal Reserve Bank of St Louis
count                                       252
Name: 36, dtype: object)


(37, CentralBank    Reserve Bank of New Zealand
count                                  252
Name: 37, dtype: object)


(38, CentralBank    Federal Reserve Bank of Boston
count                                     231
Name: 38, dtype: object)


(39, CentralBank    Federal Reserve Bank of Dallas
count                                     230
Name: 39, dtype: object)


(40, CentralBank    Bank of Mauritius
count                        228
Name: 40, dtype: object)


(41, CentralBank    People's Bank of China
count                             221
Name: 41, dtype: object)


(42, CentralBank    Bulgarian National Bank
count                              201
Name: 42, dtype: object)


(43, CentralBank    Bank of Greece
count                     198
Name: 43, dtype: object)


(44, CentralBank    Central Bank of the Republic of Turkey
count                                             197
Name: 44, dtype: object)


(45, CentralBank    Bank of Zambia
count                     196
Name: 45, dtype: object)


(46, CentralBank    Bank of Portugal
count                       185
Name: 46, dtype: object)


(47, CentralBank    National Bank of Serbia
count                              173
Name: 47, dtype: object)


(48, CentralBank    Federal Reserve Bank of Kansas City
count                                          170
Name: 48, dtype: object)


(49, CentralBank    Reserve Bank of Fiji
count                           169
Name: 49, dtype: object)

In [13]:
df.iloc[-1]

URL              https://fraser.stlouisfed.org/title/statements...
PDF              https://fraser.stlouisfed.org/files/docs/histo...
Title            Beyond Short-Term Interests : Atlanta Regional...
Subtitle                                                       NaN
Date                                                    2003-11-21
Authorname                                              Jack Guynn
Role                                                      Governor
Gender                                                        Male
CentralBank                        Federal Reserve Bank of Atlanta
Country                                                        USA
text             Speeches\n\nBeyond Short-Term Interests\n\nJac...
text_original                                                  NaN
Filename                        beyond-short-term-interests-521702
Language                                                   English
Source                                                    Archives
Name: 35486, dtype: object

In [14]:
for i in df[(df['Language']=='English') & (df['CentralBank']=='Bank of England')].sort_values('Date').sort_values('Date').iloc[-1]['text'].split('.'):
    print(i)

Bank of England Page 1 Monetary policy as engineering? - soeech by Sarah Breeden Given at the Institute of International Finance's Talking Policy Series 19 December 2023 Bank of England Page 2 Speech 1
 This is my first speech as a Deputy Governor and member of the Monetary Policy Committee (MPC) at the Bank of England
 I am going to use the speech to describe my approach to monetary policy and how I am applying it to the situation the MPC currently finds itself in
 I can think of few better places to do so than a 'Talking Policy' seminar, and I am very grateful to have been invited along to speak to you all today
 2
 I will focus on a few important questions
 Where is the economy now? How did we get here? What could happen next? What does that mean for my approach to monetary policymaking? And finally, why is that approach the right thing for the economy? Where is the economy now? 3
 Monetary policymakers like to talk about uncertainty
 But it is fair to say that working out what the state of the UK economy is and where it's heading is especially uncertain at the moment
 There are measurement issues?, volatility in the data and exceptionally large data revisions
* The bottom line is that it is more difficult to extract a clear signal from the noise
* That said, I will start by briefly painting a picture of what I think is happening in the economy in general terms
 4
 First, economic activity has been practically flat since the end of 2022
 That is of course stronger than the MPC and other forecasters expected this time last year, in part because of the adjustment to energy supply headwinds and the steep fall in energy prices since then
 But in historical terms it is very weak
 GDP has grown by about 0
5% over the past year, which compares to average annual growth of 1
5% since the Global Financial Crisis - itself a period of low growth by historical standards
 5
 Second, the labour market is loosening but it remains tight
 The survey-based employment indicators point to a tentative slowdown in hiring
 The level of vacancies has fallen from a peak of 1
3 million in the middle of last year to just under a million in the latest data
 But that is still more than 100,000 above its pre-Covid level, which itself was elevated by historical standards
 And importantly, whilst wage growth has finally begun to fall it is still greater than 7% on most measures, which given the current weakness in productivity growth in the UK is several percentage points higher than a level that, if sustained, would be consistent with the inflation target
 6
 Third, inflation has been falling over the past year but it remains far too high
 It peaked at 11
1% in October 2022 and was 4
6% in the October data
 A naive calculation would imply that we have done more than two thirds of the work to get inflation back to target
 1 Alan Greenspan called uncertainty the 'defining characteristic' of the monetary policy landscape
 2 For example, the ONS is dealing with issues caused by a decline in the response rate to the Labour Force Survey, which is the MPC's most important source of information on the unemployment rate
 3 For example, the revision to the final UK PMI for September 2023 was the 3rd largest since records began
 4 My colleague Ben Broadbent yesterday set out some challenges around understanding the state of the UK economy at the moment, and how the MPC's usual policymaking approach focuses on a range of indicators
 5 In the MPC's November 2022 forecast GDP was expected to fall by 2% over the year to Q4 2023
 6 Bank staff estimate that the rate of trend productivity growth in the economy as a whole is around 1%
 In combination with inflation of 2%, that implies nominal wage growth of 3% on average, all else equal
 Bank of England Page 3 But much of the fall in inflation so far owes to base effects: the mechanical counterpart of the unprecedented increase in the level of energy prices that came to an end just over a year ago, with a much smaller contribution so far from the significant monetary policy tightening
' Taken at face value, the MPC's November forecast implies that inflation will not return to the 2% target for another two years, so we expect to have a way to go
 How did we get here? 7
 It is worth stepping back to review how we got here
 I think a few points of context are particularly important to bear in mind
 First, the UK economy has been hit by a series of unprecedented shocks
 The UK's departure from the European Union coincided with a once-in-a-hundred year pandemic during which much of the UK and global economies were shut down
 The process of reopening those economies met with supply chain frictions that pushed up materially on the prices of globally traded goods
 Then in 2022 Russia staged an unprovoked and unjustified invasion of Ukraine, starting the biggest war in Europe for 80 years, and pushing up European energy prices by many multiples as a consequence
 Most of these shocks - but of course not all of them - have affected other advanced economies too
 All have contributed to volatility in economic activity and inflation
 Second, high inflation since 2021, which was initially caused by imported goods and energy prices, has led to the emergence of second-round effects on wages and prices in the UK
 This process has been supported by exceptional tightness in the labour market, and has been stubborn even in the face of the shocks I just described
 These second-round effects have contributed to persistence in inflation in the UK and, albeit to a lesser extent, in other advanced economies
' 10
 Third, demand has been resilient and supply has been very weak
 The tight labour 11 market and elevated inflation - especially for goods and services that tend to have a larger domestic cost component - point to a UK economy that is operating at or above capacity
 But the data suggest that economic activity has been flat
 That implies that supply has been very weak, which is a natural consequence of some of the shocks I mentioned earlier

 These have combined to deliver a series of significant forecast surprises in the UK and other advanced economies
 Focusing on the UK, until very recently inflation had been much higher over the past couple of years than we had expected
 And as I said before, economic activity has been more resilient than we expected
 Chart 1 shows that the scale of these surprises - based on one-year-ahead forecasts - has been larger than at any point since the Global Financial Crisis
1'' Some of the surprises, for example in 7 As I said in my parliamentary appointment questionnaire, inflation could have been three to five percentage points higher at its peak had the MPC not increased Bank Rate at all
 8 The Governor Andrew Bailey has described this as 'a time of macroeconomic upheaval'
 See a recent speech by my colleague Jonathan Haskel for more on this
 10 When inflation and wage growth are high, they also tend to be more volatile, which adds to issues around extracting a signal from the data
 I return to this idea later in the speech
 11 The MPC's forecasts condition on market expectations for Bank Rate and energy prices, among other things
 Part of the increase in forecast surprises has been driven by volatility in those variables
 Bank of England Page 4 late 2022, looked like textbook supply shocks, with stronger inflation coming at the same time as weaker GDP
 More recently GDP has been much stronger than our forecasts a year ago, with inflation weaker than expected, suggesting some unwind of prior supply shocks
 Chart 1: Over the past few years the MPC have had to deal with larger forecast surprises than at any point since the Global Financial Crisis @) One-year-ahead forecast surprises (data minus forecast, pp) 7 6 e e 5 Late 2022 ---" e 4 e) e 3 ee e a 25 @ 2008-2020 eed 1 ry e@ Since 2020 fo 05 1 -2 -3 -25 -20 15 -10 5 0 5 GDP growth Source: Bank of England, ONS (a) The chart shows the difference between quarterly data outturns for year on year growth in GDP and CPI inflation and the MPC's modal forecast for those variables made one year earlier
 The forecasts condition on market expectations for Bank Rate, energy prices and other factors at the time the forecasts were made
 12
In general these surprises tend to have been serially correlated - particularly for inflation - meaning that positive surprises tend to have been followed by further positive surprises
'? These large inflation surprises have been common across advanced economies, including the US and the euro area
 13
To state the obvious, this context has made monetary policymaking difficult
 I have learned two important lessons
 First inflation and wage growth have been stronger than our models would have predicted, suggesting greater second-round effects than I would have expected before this inflationary episode
 Second, there is more uncertainty than usual about the speed and scale of the monetary transmission mechanism, especially given the unprecedented tightening we have seen
 14
What I take from this is that we are in a state of the world where monetary policymaking is best considered as engineering rather than science
 The shocks and data surprises are too large for us to have any hope of understanding the detail of what is happening in a complex system and fine tuning economic outcomes through our 12 The trailing two year correlation between the one-year-ahead quarter-on-quarter inflation surprise and its own lag increased to around 0
7-0
8 over the past year and a half
 The BIS have also shown that one-year- ahead inflation surprises have been positively correlated with two-year-ahead surprises historically
 Bank of England Page 5 models
 Instead - like engineers - we should pay attention to real world outcomes and adjust accordingly
? 15
 That means we have had to remain open-minded to make sure that we continually learn how the economy is responding to these shocks
 We have had to remain humble about how well economic models perform when movements in important variables are 'out of sample' - in other words historically unprecedented
 We have had to place more emphasis than usual on what we know has happened, or is happening, in the economy and acknowledge that future projections are more uncertain than usual
'* And given the uncertainty around the things we are simply unable to observe but that matter a lot now for policy - most obviously trends in supply - we have had to rely more on extracting signals from so-called 'late cycle' indicators, such as inflation and wage growth, rather than indicators of economic activity
' 16
One approach that I think helpful is to think through a range of possible scenarios for the UK economy, where those scenarios reflect how real world outcomes have differed from our expectations - our lessons learned from engineering, if you like
 Why is scenario analysis helpful? 17
Scenarios enable us to explore policy relevant potential outcomes rather than focusing only on the thing that is most likely to happen
 It's an approach we often use in financial stability - including on the Financial Policy Committee - where policymakers are inherently interested in tail outcomes rather than the central case, which naturally requires analysis of scenarios
 But I have also found scenario analysis to be a useful guide for monetary policymaking during a time of major shocks
 And I hope through explaining the role that scenario analysis has had in my own thinking on monetary policy I can make the case for the MPC to do more of it in the future
 18
So what are the relevant scenarios for the UK economy at the moment? In my view the potential distribution of inflation outcomes is wider than it used to be - by which I mean that the probabilities of meaningfully above and meaningfully below target inflation are much higher than we might usually expect - and I have less confidence than I used to in any given inflation profile coming to pass
 19
 Similarly, whilst the MPC's latest forecast implies that inflation is most likely to be 1
9% in two years - and the mean, or expected value, is 2
2% - there is a material probability that it could be much higher or much lower
* 13 I would like to thank Tim Jackson (an engineer and my husband) for inspiring the theme of this speech, although I have since discovered that Professor Gregory Mankiw also used the analogy in the 2000s here
 14 See, for example, the February 2023 MPC minutes, which mentioned "additional weight being put on recent strength in the labour market and inflation data, and relatively less on the medium-term projections'
 15 See a recent speech by my colleague Ben Broadbent, which covers this theme
 He also covered the theme in his speech yesterday
 16 See a recent speech by my former colleague Silvana Tenreyro, which contains more discussion of the fan charts and of forecasting in the face of major economic shocks
 Bank of England Page 6 What are the relevant scenarios? 20
1 am going to set out two scenarios in this speech, reflecting two states of the world that would have very different implications for inflation and for monetary policy
 These scenarios have informed my approach to setting policy, and in particular how I've approached setting policy in an environment where there are these competing risks
'" 21
Chart 2 shows in (I should emphasise) illustrative terms what these scenarios could look like
 In one scenario - the 'low inflation scenario' - there is a negative shock and demand weakens much more quickly than expected as the MPC's previous tightening in monetary policy takes hold
 Ultimately, and assuming for now no change in the path of Bank Rate, inflation would fall well below target
 In the other scenario - the 'high inflation scenario' - inflation remains stubbornly persistent as a result of continued and strengthened second-round effects
 ' Chart 2: Illustrative high and low inflation scenarios for the UK economy, alongside the MPC's most likely forecast in November 2023 @) Inflation in scenarios (percent) 12 November 2023 (market rates) -- High inflation: second-round effects Low inflation: weaker demand 2021 2022 2023 2024 2025 2026 Source: Bank of England (a) The chart shows the MPC's November 2023 modal forecast for CPI inflation, conditioned on market expectations for Bank Rate at that time
 The high inflation scenario could be thought of as one in which, for instance, the labour market remains tight and second-round effects are very significant
 The low inflation scenario could instead be thought of as one in which the economy is hit by negative demand shocks that reduce demand materially relative to the November forecast
 The scenarios should be interpreted as illustrative only
 22
This of course begs the question of how policy should respond in these states of the world
 That is impossible to describe in the abstract
 But one possible window into it is 17 The MPC's November 2023 minutes touched on a similar theme, saying that the 'decision whether to increase or to maintain Bank Rate at this meeting was again finely balanced between the risks of not tightening policy enough when underlying inflationary pressures could prove more persistent, and the risks of tightening policy too much given the impact of policy that was still to come through'
 18 My colleague Huw Pill called this 'intrinsic inflation persistence' in a recent speech
 Bank of England Page 7 the so-called 'optimal policy projection'
1 This is just one particular, simple, representation of how interest rates might have to respond to the scenarios, and in this version it assumes that the policymaker is focused only on returning inflation to target
 It is clearly just a straw person
 But it is nevertheless a useful yardstick to size quite how material these scenarios could be for Bank Rate
 Chart 3: Estimated optimal monetary policy response to high and low inflation scenarios for the UK economy, assuming the policymaker places no weight on output stabilisation, for illustrative purposes ) Bank Rate in scenarios (percent) 10 eee History 9 -- High inflation: second-round effects 8 Low inflation: weaker demand 7 6 5 4 3 2 1 0 2021 2022 2023 2024 2025 2026 Source: Bank of England (a) The chart shows the estimated 'optimal policy projection' associated with the high and low inflation scenarios
 See this annex for further details
 In these scenarios - which are designed to focus on potential inflation outcomes, rather than any trade-offs with output stabilisation - we assume a lambda parameter of zero, and some preference for interest rate smoothing
 The high inflation scenario assumes that the labour market remains tight and second-round effects are very significant
 The low inflation scenario assumes that the economy is hit by negative demand shocks that reduce demand materially relative to the November forecast
 The scenarios should be interpreted as illustrative only
 23
Chart 3 shows how in this thought experiment the scenarios would, unsurprisingly, have very different implications for Bank Rate
 In the low inflation scenario, Bank Rate would fall from the end of this year onwards, to prevent inflation from falling materially below target
 In the high inflation scenario, Bank Rate would rise throughout 2024 to bring inflation down, before broadly stabilising somewhere well above 6%
? 24
Let me underline, these scenarios are meant to be illustrative only and not a precise read on what I think monetary policy would have to do
 The projection has a number of 19 See the annex to this previous speech by my colleague Ben Broadbent for more on the details of the 'optimal policy projection'
 In these particular illustrative scenarios - which are designed to focus on potential inflation outcomes, rather than the potential trade-off with output stabilisation - we assume a lambda parameter of zero
 20 In both cases, the optimal policy projection would of course deliver a path for inflation that is closer to target than the underlying inflation scenarios
 Bank of England Page 8 unrealistic simplifying assumptions, including that everyone knows and understands the path for the economy
 It also depends on a precise estimate of the monetary transmission mechanism, which is very uncertain as I noted above
 But it does show the potential for very different paths for Bank Rate depending on which scenario we find ourselves in
 Monetary policy from here 25
How might such scenario analysis be useful in considering policy? It is impossible to place precise probabilities on the likelihood of either of these scenarios, although I think the MPC's modal forecast is more likely to occur than either of them
 Nevertheless understanding how a policymaker would respond in either scenario is useful to anyone who is interested in understanding the outlook for policy from here
 The approach also underlines how, when there are significant risks, policy may need to be nimble as we learn more about which state of the world we might be in
 (Indeed, in much the same way, my colleague Ben Broadbent talked yesterday about trading off timeliness against forming a better understanding of what's going on in the economy
*') That process of working out what's going on should rely on the accumulation of evidence rather than any individual data point
 Finally, in my view, the high inflation scenario would be clearly the more costly scenario - and it is therefore the most important scenario to lean against when we are setting monetary policy
 26
Where does that leave monetary policy over the next few months? The economy is moving in the right direction to return inflation to the 2% target, but our job isn't done
 The question I am focused on is whether there is evidence of more persistent inflationary pressures which means we may need to tighten further
 Regardless, monetary policy still needs to be restrictive for an extended period of time to keep pushing down on inflation and to return it sustainably to target
 27

In [20]:
df['CentralBank'].value_counts()

CentralBank
European Central Bank                        2665
Board of Governors of the Federal Reserve    2658
Deutsche Bundesbank                          1418
Bank of England                              1354
Reserve Bank of India                        1071
                                             ...
Banque Centrale de Mauritanie                   1
Central Bank of Bolivia                         1
Central Bank of Jordan                          1
Central Bank of Ecuador                         1
Banco Central de Venezuela                      1
Name: count, Length: 143, dtype: int64

In [22]:
for i in df['CentralBank'].value_counts().index:
    if i in df['CentralBank'].value_counts().index:
        
        speeches = df[(df['CentralBank']==i)]#['text']#.values[0][:100]
        
        if f"{i}" not in os.listdir('../Data/Speeches/speeches_by_central_bank/'):
            print(i)
            display(speeches)
            print(os.listdir(f"../Data/Speeches/speeches_by_central_bank/"))
            print('creating',f"../Data/Speeches/speeches_by_central_bank/{i}")
            os.makedirs(f"../Data/Speeches/speeches_by_central_bank/{i}")
        #os.makedirs
        speeches.to_csv(f"../Data/Speeches/speeches_by_central_bank/{i}/{i}.csv", index=False, sep='\t')

Swiss National Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1384,https://www.snb.ch/en/mmr/speeches/id/ref_1997...,NaN,"Introductory remarks, End-of-year press confer...",NaN,1997-12-12,Bruno Gehrig,Board member,Male,Swiss National Bank,CHE,"Year-end press conference, Zurich, 12 December...","Confrence de presse de fin d'anne, Zurich, le ...",che_ref_19971212_bge,French,CB websites
1385,https://www.snb.ch/en/mmr/speeches/id/ref_1997...,NaN,"Introductory remarks, End-of-year press confer...",NaN,1997-12-12,Hans Meyer,Governor,Male,Swiss National Bank,CHE,"End-of-year press conference, Zurich, 12 Decem...",NaN,che_ref_19971212_hm,English,CB websites
1386,https://www.snb.ch/en/mmr/speeches/id/ref_1997...,NaN,"Introductory remarks, End-of-year press confer...",NaN,1997-12-12,Jean-Pierre Roth,Deputy Governor,Male,Swiss National Bank,CHE,"Year-end press conference, Zurich, 12 December...","Confrence de presse de fin d'anne, Zurich, le ...",che_ref_19971212_jpr,French,CB websites
1387,https://www.snb.ch/en/mmr/speeches/id/ref_1998...,NaN,On monetary policy in the new year,NaN,1998-01-14,Hans Meyer,Governor,Male,Swiss National Bank,CHE,Monetary policy in the new year Dr. Hans Meyer...,"Zur Geldpolitik im neuen Jahr Dr. Hans Meyer, ...",che_ref_19980114_m,German,CB websites
1388,https://www.snb.ch/en/mmr/speeches/id/ref_1998...,NaN,Aspects of competitiveness,NaN,1998-01-19,Hans Meyer,Governor,Male,Swiss National Bank,CHE,Aspects of competitiveness Dr. Hans Meyer Chai...,Aspekte der Konkurrenzfhigkeit Dr. Hans Meyer ...,che_ref_19980119_m,German,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28323,https://www.bis.org/review/r971112a.pdf,https://www.bis.org/review/r971112a.pdf,M. Roth s'interroge sur la relation entre le f...,"Expos de M. Jean-Pierre Roth, Vice-prsident de...",1997-10-27,Jean-Pierre Roth,Deputy Governor,Male,Swiss National Bank,CHE,Mr. Roth wonders about the relationship betwee...,NaN,r971112a,English,BIS
28395,https://www.bis.org/review/r980327b.pdf,https://www.bis.org/review/r980327b.pdf,Mr. Meyer addresses the competitiveness of fin...,Address by the Chairman of the Governing Board...,1998-03-23,Hans Meyer,Governor,Male,Swiss National Bank,CHE,Mr. Patrikis discusses global electronic comme...,NaN,r980327b,English,BIS
28603,https://www.bis.org/review/r990430b.pdf,https://www.bis.org/review/r990430b.pdf,Mr Gehrig focuses on special structural charac...,"Speech by Prof Bruno Gehrig, a member of the G...",1999-04-30,Bruno Gehrig,Board member,Male,Swiss National Bank,CHE,Mr Gehrig focuses on special structural charac...,NaN,r990430b,English,BIS
28644,https://www.bis.org/review/r990622b.pdf,https://www.bis.org/review/r990622b.pdf,Mr Roth discusses demonitisation of gold in Sw...,"Speech by Mr Jean-Pierre Roth, Vice-Chairman o...",1999-06-14,Jean-Pierre Roth,Deputy Governor,Male,Swiss National Bank,CHE,Mr Roth discusses demonitisation of gold in Sw...,NaN,r990622b,English,BIS
28701,https://www.bis.org/review/r991006b.pdf,https://www.bis.org/review/r991006b.pdf,Mr Meyer gives a central banker's view from Sw...,"Speech given by Mr Hans Meyer, Chairman of the...",1999-10-01,Hans Meyer,Governor,Male,Swiss National Bank,CHE,Mr Meyer gives a central bankers view from Swi...,NaN,r991006b,English,BIS

['Bank of Canada', 'Bank of England', 'Bank of Italy', 'Bank of Japan', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank']
creating ../Data/Speeches/speeches_by_central_bank/Swiss National Bank
Bank of Albania

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
108,https://www.bankofalbania.org/Shtypi/Fjalime_i...,https://www.bankofalbania.org/rc/doc/parl99120...,On the discussions held with the International...,NaN,1999-12-08,Shklqim Cani,Governor,Male,Bank of Albania,ALB,"Governor's Word at the Economics, Finance and ...","Fjala e Guvernatorit n Komisionin e Ekonomis, ...",alb_36502_shkelqim cani_albanian,Albanian,CB websites
109,https://www.bankofalbania.org/Shtypi/Fjalime_i...,https://www.bankofalbania.org/rc/doc/parl00012...,Press conference of the Governor of the Bank o...,NaN,2000-01-25,Shklqim Cani,Governor,Male,Bank of Albania,ALB,Monetary indicators at the end of 1999 and sup...,Treguesit monetar n fund t vitit 1999 dhe masa...,alb_36550_shkelqim cani_albanian,Albanian,CB websites
110,https://www.bankofalbania.org/Shtypi/Fjalime_i...,https://www.bankofalbania.org/rc/doc/parl00050...,Presentation of the Annual Report of the Bank ...,NaN,2000-05-04,Shklqim Cani,Governor,Male,Bank of Albania,ALB,Presentation of the Bank of Albania's 1999 Ann...,Prezantimi i Raportit Vjetor t Banks s Shqipri...,alb_36650_shkelqim cani_albanian,Albanian,CB websites
111,https://www.bankofalbania.org/Shtypi/Fjalime_i...,NaN,Changing banking structure and supervisory pra...,NaN,2000-12-02,Shklqim Cani,Governor,Male,Bank of Albania,ALB,"06/08/2022, 09:10 Opening word at the First Na...","06/08/2022, 09:10 Fjala e hapjes n Konferencn ...",alb_36862_shkelqim cani_albanian,Albanian,CB websites
112,https://www.bankofalbania.org/Shtypi/Fjalime_i...,https://www.bankofalbania.org/rc/doc/ringjallj...,Prospects for economic development of the region.,NaN,2000-12-21,Shklqim Cani,Governor,Male,Bank of Albania,ALB,Resurrection of the Tirana Stock Exchange 29/0...,"Ringjallja e Burss s Tirans 29/07/22, 15:08 it...",alb_36881_shkelqim cani_albanian,Albanian,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27818,http://www.bis.org/review/r230712e.htm,http://www.bis.org/review/r230712e.pdf,Gent Sejko: Albania's economic and financial d...,"Address by Mr Gent Sejko, Governor of the Bank...",2023-07-06,Gent Sejko,Governor,Male,Bank of Albania,ALB,Gent Sejko: Address - Assembly of the Republic...,NaN,r230712e,English,BIS
27854,http://www.bis.org/review/r230803b.htm,http://www.bis.org/review/r230803b.pdf,Gent Sejko: Statement - press conference on mo...,"Statement by Mr Gent Sejko, Governor of the Ba...",2023-08-02,Gent Sejko,Governor,Male,Bank of Albania,ALB,Gent Sejko: Statement - press conference on mo...,NaN,r230803b,English,BIS
28052,https://www.bis.org/review/r231115t.htm,https://www.bis.org/review/r231115t.pdf,"Gent Sejko: Climate, macroeconomy, and finance...","Welcome address by Mr Gent Sejko, Governor of ...",2023-11-08,Gent Sejko,Governor,Male,Bank of Albania,ALB,"Gent Sejko: Climate, macroeconomy, and finance...",NaN,r231115t,English,BIS
28093,https://www.bis.org/review/r231204m.htm,https://www.bis.org/review/r231204m.pdf,Gent Sejko: Welcome remarks - 17th SEE Economi...,"Welcome remarks by Mr Gent Sejko, Governor of ...",2023-12-04,Gent Sejko,Governor,Male,Bank of Albania,ALB,Gent Sejko: Welcome remarks - 17th SEE Economi...,NaN,r231204m,English,BIS
28094,https://www.bis.org/review/r231204n.htm,https://www.bis.org/review/r231204n.pdf,Gent Sejko: Competition and stability in the A...,"Speech by Mr Gent Sejko, Governor of the Bank ...",2023-11-23,Gent Sejko,Governor,Male,Bank of Albania,ALB,Gent Sejko: Competition and stability in the A...,NaN,r231204n,English,BIS

['Bank of Canada', 'Bank of England', 'Bank of Italy', 'Bank of Japan', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Albania
Bank of Spain

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
5592,NaN,https://www.bde.es/f/webbde/GAP/Secciones/Sala...,Speech at the award of the XVIII King of Spain...,NaN,2022-03-23,Pablo Hernndez de Cos,Governor,Male,Bank of Spain,ESP,23.03.2022 Address at the presentation of the ...,NaN,esp_220323hdc-en,English,CB websites
5593,NaN,https://www.bde.es/f/webbde/GAP/prensa/interve...,Appearance before the Senate Budget Committee,NaN,2000-11-20,Jaime Caruana,Governor,Male,Bank of Spain,ESP,Jaime Caruna Governor of the Bank of Spain Nov...,Jaime Caruna Gobernador del Banco de Espaa 20 ...,esp_36850_jaime_caruana_spanish,Spanish,CB websites
5594,NaN,https://www.bde.es/f/webbde/GAP/prensa/interve...,"Closing speech at the ""Euro 2002"" conference",NaN,2001-04-04,Jaime Caruana,Governor,Male,Bank of Spain,ESP,Jaime Caruna Governor of the Bank of Spain Apr...,Jaime Caruna Gobernador del Banco de Espaa 4 d...,esp_36985_jaime_caruana_spanish,Spanish,CB websites
5595,NaN,https://www.bde.es/f/webbde/GAP/prensa/interve...,Remarks at the presentation of the Germn Bernc...,NaN,2001-04-06,Jaime Caruana,Governor,Male,Bank of Spain,ESP,Jaime Caruna Governor of the Bank of Spain Apr...,Jaime Caruna Gobernador del Banco de Espaa 6 d...,esp_36987_jaime_caruana_spanish,Spanish,CB websites
5596,NaN,https://www.bde.es/f/webbde/GAP/prensa/interve...,Speech delivered at the Ordinary General Assem...,NaN,2001-04-18,Jaime Caruana,Governor,Male,Bank of Spain,ESP,Jaime Caruna Governor of the Bank of Spain Apr...,Jaime Caruna Gobernador del Banco de Espaa 18 ...,esp_36999_jaime_caruana_spanish,Spanish,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28053,https://www.bis.org/review/r231115v.htm,https://www.bis.org/review/r231115v.pdf,The Spanish banking industry - developments an...,"Speech by Mr Pablo Hernndez de Cos, Governor o...",2023-10-09,Pablo Hernndez de Cos,Governor,Male,Bank of Spain,ESP,Eurosistema 09.10.2023 The Spanish banking ind...,NaN,r231115v,English,BIS
28054,https://www.bis.org/review/r231115x.htm,https://www.bis.org/review/r231115x.pdf,CSO (Chief Sustainability Officer) Club Inaugu...,"Remarks by Ms Margarita Delgado, Deputy Govern...",2023-09-29,Margarita Delgado,Deputy Governor,Female,Bank of Spain,ESP,Eurosistema 29.09.2023 CSO Club Inauguration D...,NaN,r231115x,English,BIS
28070,https://www.bis.org/review/r231121h.htm,https://www.bis.org/review/r231121h.pdf,Pablo Hernndez de Cos: Population ageing and e...,"Speech by Mr Pablo Hernndez de Cos, Governor o...",2023-11-17,Pablo Hernndez de Cos,Governor,Male,Bank of Spain,ESP,BANCODEESPANA Eurosistema 17.11.2023 Populatio...,NaN,r231121h,English,BIS
28071,https://www.bis.org/review/r231121i.htm,https://www.bis.org/review/r231121i.pdf,Pablo Hernndez de Cos: The digital euro projec...,"Speech by Mr Pablo Hernndez de Cos, Governor o...",2023-11-20,Pablo Hernndez de Cos,Governor,Male,Bank of Spain,ESP,Pablo Hernandez de Cos: The digital euro proje...,NaN,r231121i,English,BIS
28131,https://www.bis.org/review/r231215d.htm,https://www.bis.org/review/r231215d.pdf,Pablo Hernndez de Cos: Speech - Cinco Dias Bus...,"Speech by Mr Pablo Hernndez de Cos, Governor o...",2023-12-04,Pablo Hernndez de Cos,Governor,Male,Bank of Spain,ESP,04.12.2023 16th Cinco Dias Business Innovation...,NaN,r231215d,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Italy', 'Bank of Japan', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Spain
Bank of Finland

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
5866,https://www.suomenpankki.fi/globalassets/en/me...,NaN,Speech at a seminar of the Housing Reform Asso...,NaN,2001-03-21,Matti Louekoski,Deputy Governor,Male,Bank of Finland,FIN,"Matti Louekoski, Vice Chairman of the Board of...",Suomen Pankin johtokunnan varapuheenjohtaja Ma...,fin_010321louekoski,Finnish,CB websites
5867,https://www.suomenpankki.fi/globalassets/en/me...,NaN,Speech at the European Day reception of the As...,NaN,2001-05-09,Matti Louekoski,Deputy Governor,Male,Bank of Finland,FIN,BANK OF FINLAND Press release FINLANDS BANK Pr...,SUOMEN PANKKI Lehdisttiedote FINLANDS BANK Pre...,fin_010509louekoski,Finnish,CB websites
5868,https://www.suomenpankki.fi/globalassets/en/me...,NaN,"Conference: ""Economic and Monetary Union: Chal...",NaN,2001-05-11,Sinikka Salo,Board member,Female,Bank of Finland,FIN,SUOMEN PANKKI FINLANDS BANK BANK OF FINLAND 11...,NaN,fin_010511salo,English,CB websites
5869,https://www.suomenpankki.fi/globalassets/en/me...,NaN,"Speech at the seminar ""Hirvensalmi in Europe""",NaN,2001-07-08,Sinikka Salo,Board member,Female,Bank of Finland,FIN,SUOMEN PANKKI FINLANDS BANK BANK OF FINLAND Me...,SUOMEN PANKKI FINLANDS BANK BANK OF FINLAND Jo...,fin_010709salo,Finnish,CB websites
5870,https://www.suomenpankki.fi/globalassets/en/me...,NaN,Speech at the Euro Enters Everyday Life seminar,NaN,2001-10-05,Matti Louekoski,Deputy Governor,Male,Bank of Finland,FIN,Matti Louekoski The euro enters everyday life ...,Matti Louekoski Euro astuu arkeen seminaari Tu...,fin_011005euroml,Finnish,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27917,http://www.bis.org/review/r230922g.htm,http://www.bis.org/review/r230922g.pdf,Tuomas Vlimki: Monetary policy implementation ...,"Speech by Mr Tuomas Vlimki, Board Member of th...",2023-09-06,Tuomas Vlimki,Board member,Male,Bank of Finland,FIN,Tuomas Valimaki: Monetary policy implementatio...,NaN,r230922g,English,BIS
27968,https://www.bis.org/review/r231017e.htm,https://www.bis.org/review/r231017e.pdf,Tuomas Vlimki: Finland's experiences with sect...,"Speech by Mr Tuomas Vlimki, Board Member of th...",2023-09-26,Tuomas Vlimki,Board member,Male,Bank of Finland,FIN,Tuomas Valimaki: Finland's experiences with se...,NaN,r231017e,English,BIS
28166,https://www.bis.org/review/r970115b.pdf,https://www.bis.org/review/r970115b.pdf,Dr. Hmlinen reviews developments in the Finnis...,"Review by the Governor of the Bank of Finland,...",1997-01-10,Sirkka Hmlinen,Governor,Female,Bank of Finland,FIN,Dr. Hamalainen reviews developments in the Fin...,NaN,r970115b,English,BIS
28410,https://www.bis.org/review/r980518d.pdf,https://www.bis.org/review/r980518d.pdf,Ms. Hmlinen discusses monetary policy in EMU ...,Discourse by the Governor of the Bank of Finla...,1998-04-22,Sirkka Hmlinen,Governor,Female,Bank of Finland,FIN,Ms. Hamalainen discusses monetary policy in EM...,NaN,r980518d,English,BIS
28429,https://www.bis.org/review/r980527b.pdf,https://www.bis.org/review/r980527b.pdf,Ms. Hmlinen discusses achieving a credible cur...,Address by the Governor of the Bank of Finland...,1998-05-05,Sirkka Hmlinen,Governor,Female,Bank of Finland,FIN,Ms. Hamalainen discusses achieving a credible ...,NaN,r980527b,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Italy', 'Bank of Japan', 'Bank of Spain', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Finland
Bank of France

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
6321,NaN,NaN,White paper internet the prudential consequences,NaN,2001-01-30,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,30 janvier 2001 Speech by Jean-Claude TRICHET ...,NaN,fra_20010130_trichet_en,English,Archives
6322,NaN,NaN,General Assembly of the French Association of ...,NaN,2003-06-24,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,SPEECH BY JEAN-CLAUDE TRICHET GOVERNOR OF THE ...,ALLOCUTION DE JEAN-CLAUDE TRICHET GOUVERNEUR D...,fra_20030624_trichet_fr,French,Archives
6323,NaN,NaN,Annual report of the French banking commission...,NaN,2003-06-28,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,PRESENTATION OF THE 2002 ANNUAL REPORT OF THE ...,NaN,fra_20030628_trichet_en,English,Archives
6324,NaN,NaN,Declaration after appointment to the ECB,NaN,2003-10-16,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,"Brussels, 16 October 2003 Statement made by Mr...","Bruxelles, le 16 octobre 2003 Dclaration faite...",fra_20031016_trichet_fr,French,Archives
6325,NaN,NaN,Accession to the euro,NaN,2004-03-05,Christian Noyer,Governor,Male,Bank of France,FRA,Seminar of 5 March 2004: Introductory statemen...,Sminaire du 5 mars 2004 : Dclaration introduct...,fra_20040305_noyer_fr,French,Archives
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28261,https://www.bis.org/review/r970626a.pdf,https://www.bis.org/review/r970626a.pdf,Mr. Trichet discusses Franco-German monetary c...,"Speech by the Governor of the Bank of France, ...",1997-06-02,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,Mr. Trichet discusses Franco-German monetary c...,NaN,r970626a,English,BIS
28342,https://www.bis.org/review/r971208f.pdf,https://www.bis.org/review/r971208f.pdf,Mr. Hannoun discusses the operational framewor...,Speech by the Deputy Governor of the Banque de...,1997-11-20,Herv Hannoun,Board member,Male,Bank of France,FRA,Mr. Hannoun discusses the operational framewor...,NaN,r971208f,English,BIS
28566,https://www.bis.org/review/r990301a.pdf,https://www.bis.org/review/r990301a.pdf,Monsieur Trichet claire les conditions du succ...,"Discours de Jean-Claude Trichet, le Gouverneur...",1999-02-22,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,Mr Trichet sheds light on the conditions for t...,NaN,r990301a,English,BIS
28630,https://www.bis.org/review/r990531a.pdf,https://www.bis.org/review/r990531a.pdf,Mr Trichet presents the Annual Report of the B...,"Address by Jean-Claude Trichet, Governor of th...",1999-05-21,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,Mr Trichet presents the Annual Report of the B...,NaN,r990531a,English,BIS
28654,https://www.bis.org/review/r990709a.pdf,https://www.bis.org/review/r990709a.pdf,Mr Trichet gives an address on the risks and c...,Text of the Third Hong Kong Monetary Authority...,1999-07-08,Jean-Claude Trichet,Governor,Male,Bank of France,FRA,Mr Trichet gives an address on the risks and c...,NaN,r990709a,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of Italy', 'Bank of Japan', 'Bank of Spain', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of France
Hong Kong Monetary Authority

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7212,https://www.hkma.gov.hk/eng/news-and-media/spe...,NaN,The Asian Financial Crisis: What Have We Learnt?,NaN,1999-06-07,Norman T L Chan,Governor,Male,Hong Kong Monetary Authority,HKG,"19/09/22, 16:25 Hong Kong Monetary Authority -...",NaN,hkg_19990607-1,English,CB websites
7213,https://www.hkma.gov.hk/eng/news-and-media/spe...,NaN,Governor's Statement,NaN,2001-05-11,Norman T L Chan,Governor,Male,Hong Kong Monetary Authority,HKG,"19/09/22, 16:12 Hong Kong Monetary Authority -...",NaN,hkg_20010511,English,CB websites
7214,https://www.hkma.gov.hk/eng/news-and-media/spe...,NaN,Opening Remarks at the Signing Ceremony for th...,NaN,2001-08-20,Tony Latter,Board member,Male,Hong Kong Monetary Authority,HKG,"19/09/22, 16:12 Hong Kong Monetary Authority -...",NaN,hkg_20010820,English,CB websites
7215,https://www.hkma.gov.hk/eng/news-and-media/spe...,NaN,Opening Remarks at the Signing Ceremony for th...,NaN,2001-10-22,Tony Latter,Board member,Male,Hong Kong Monetary Authority,HKG,"19/09/22, 16:11 Hong Kong Monetary Authority -...",NaN,hkg_20011022,English,CB websites
7216,https://www.hkma.gov.hk/eng/news-and-media/spe...,NaN,Welcoming Remarks at the Forum on Implementati...,NaN,2001-11-19,Tony Latter,Board member,Male,Hong Kong Monetary Authority,HKG,"19/09/22, 16:11 Hong Kong Monetary Authority -...",NaN,hkg_20011119,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28688,https://www.bis.org/review/r990922c.pdf,https://www.bis.org/review/r990922c.pdf,Mr Carse discusses the importance of ethics in...,"Speech given by Mr David Carse, Deputy Chief E...",1999-09-15,David Carse,Deputy Governor,Male,Hong Kong Monetary Authority,HKG,Mr Carse discusses the importance of ethics in...,NaN,r990922c,English,BIS
28695,https://www.bis.org/review/r990930a.pdf,https://www.bis.org/review/r990930a.pdf,from crisis to recovery (Central Bank Article...,Speech by the Chief Executive of the Hong Kong...,1999-09-28,Joseph Yam,Governor,Male,Hong Kong Monetary Authority,HKG,Mr Yam comments on Hong Kong: from crisis to r...,NaN,r990930a,English,BIS
28706,https://www.bis.org/review/r991012c.pdf,https://www.bis.org/review/r991012c.pdf,Mr Carse speaks about the regulatory framework...,"Keynote Speech by Mr David Carse, Deputy Chief...",1999-10-08,David Carse,Deputy Governor,Male,Hong Kong Monetary Authority,HKG,Mr Carse speaks about the regulatory framework...,NaN,r991012c,English,BIS
28726,https://www.bis.org/review/r991103a.pdf,https://www.bis.org/review/r991103a.pdf,Mr Yam looks towards a stronger financial syst...,"Speech given by Mr Joseph Yam JP, Chief Execut...",1999-10-29,Joseph Yam,Governor,Male,Hong Kong Monetary Authority,HKG,Mr Yam looks towards a stronger financial syst...,NaN,r991103a,English,BIS
28757,https://www.bis.org/review/r991210c.pdf,https://www.bis.org/review/r991210c.pdf,Mr Latter gives a tour d'horizon of the curren...,"Text of the opening address by Tony Latter, a ...",1999-12-07,Tony Latter,Deputy Governor,Male,Hong Kong Monetary Authority,HKG,Mr Latter gives a tour dhorizon of the current...,NaN,r991210c,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Spain', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Hong Kong Monetary Authority
Bank of Thailand

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12511,https://www.bis.org/review/r000403c.pdf,https://www.bis.org/review/r000403c.pdf,"Mr Sonakul covers a number of aspects, includi...","Speech by Mr M R Chatu Mongol Sonakul, Governo...",2000-03-22,M R Chatu Mongol Sonakul,Governor,Male,Bank of Thailand,THA,"Mr Sonakul covers a number of aspects, includi...",NaN,r000403c,English,BIS
12514,https://www.bis.org/review/r000405c.pdf,https://www.bis.org/review/r000405c.pdf,Thoughts and reflections on the development of...,"Speech by Mr M R Chatu Mongol Sonakul, Governo...",2000-03-28,M R Chatu Mongol Sonakul,Governor,Male,Bank of Thailand,THA,M R Chatu Mongol Sonakul: Thoughts and reflect...,NaN,r000405c,English,BIS
12630,https://www.bis.org/review/r001011c.pdf,https://www.bis.org/review/r001011c.pdf,New challenges for finance and capital markets...,"Speech by Ms Tanya Sirivedhin, Deputy Governor...",2000-09-28,Tanya Sirivedhin,Deputy Governor,Female,Bank of Thailand,THA,Tanya Sirivedhin: New challenges for finance a...,NaN,r001011c,English,BIS
12631,https://www.bis.org/review/r001012a.pdf,https://www.bis.org/review/r001012a.pdf,Thailand - where we are now and what we are tr...,"Speech by Mr M R Chatu Mongol Sonakul, Governo...",2000-10-03,M R Chatu Mongol Sonakul,Governor,Male,Bank of Thailand,THA,M R Chatu Mongol Sonakul: Thailand - where we ...,NaN,r001012a,English,BIS
12671,https://www.bis.org/review/r001127a.pdf,https://www.bis.org/review/r001127a.pdf,Inflation targeting - a new monetary policy ap...,"Speech by Mr MR Chatu Mongol Sonakul, Governor...",2000-10-20,M R Chatu Mongol Sonakul,Governor,Male,Bank of Thailand,THA,MR Chatu Mongol Sonakul: Inflation targeting -...,NaN,r001127a,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30400,NaN,https:/www.bot.or.th/Thai/PressandSpeeches/Spe...,"Remarks at the 2003 Symposium ""Economic Recove...",NaN,2003-08-20,Pridiyathorn Devakul,Governor,Male,Bank of Thailand,THA,saying Mr.W. Prisiyathon Devakul Governor of t...,"... 2546 "" "" - 20 2546 9.00 . ...",tha_symposium46,Thai,CB websites
30401,NaN,https:/www.bot.or.th/Thai/PressandSpeeches/Spe...,Thailand and the Next Generation of Asian Econ...,NaN,2006-08-09,Pridiyathorn Devakul,Governor,Male,Bank of Thailand,THA,saying Mr.W. Pridiyathon Devakul Governor of t...,"... 2549 ""' - 9 2549 9:30-10:00 . ...",tha_symposium49_gov,Thai,CB websites
30402,NaN,https:/www.bot.or.th/Thai/PressandSpeeches/Spe...,Thailand : Towards the Challenges of the New E...,NaN,2001-05-09,M R Chatu Mongol Sonakul,Governor,Male,Bank of Thailand,THA,"""Thailand : Towards the challenges of the new ...",NaN,tha_thailand towards the challenges of the new...,English,CB websites
30403,NaN,https:/www.bot.or.th/Thai/PressandSpeeches/Spe...,Securing Thailand's Future with Capital Market...,NaN,2008-02-17,Tarisa Watanagase,Governor,Female,Bank of Thailand,THA,Securing Thailands Future with Capital Market ...,NaN,tha_thailand_20focus_20speech_final_dr.tarisa_...,English,CB websites
30404,NaN,https:/www.bot.or.th/Thai/PressandSpeeches/Spe...,"Governor's Annual Statement to the Public, Ban...",NaN,2009-01-28,Tarisa Watanagase,Governor,Female,Bank of Thailand,THA,The governor's annual statement to the public....,. 28 2552 2552 2552 ...,tha_yearlyspeechforpublic2009_dr.tarisa_28jan09,Thai,CB websites

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Spain', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Thailand
De Nederlandsche Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10959,https://pywb.nationaalarchief.nl/nl/all/201901...,NaN,De Nederlandsche Bank: an (inter)national bank,Met veel plezier heb ik de uitnodiging aanvaar...,2002-01-31,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,De Nederlandsche Bank: an (inter)national bank...,De Nederlandsche Bank: een (inter)nationale ba...,nld_37287_nout_wellkink_2,Dutch,Archives
10960,https://pywb.nationaalarchief.nl/nl/all/201901...,NaN,Recent macroeconomic developments in the Nethe...,Het doet me genoegen aanwezig te zijn bij de s...,2002-01-31,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,Recent macroeconomic developments in the Nethe...,De recente macro-economische ontwikkelingen in...,nld_37287_nout_wellkink,Dutch,Archives
10961,https://pywb.nationaalarchief.nl/nl/all/201901...,NaN,"The Nazi robbery of 146,000 kg of gold at the ...",1 In de oorlogsjaren is 145.649 kg goud uit de...,2002-03-15,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,"The Nazi robbery of 146,000 kg of gold at the ...",De nazi-roof van 146.000 kg goud bij De Nederl...,nld_37330_nout_wellkink,Dutch,Archives
10962,https://pywb.nationaalarchief.nl/nl/all/201901...,NaN,"An economically healthy SME, a social interest",Hartelijk dank voor dit interessante onderzoek...,2002-03-18,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,"An economically healthy SME, a social interest...","Een economisch gezond MKB, een maatschappelijk...",nld_37333_nout_wellkink,Dutch,Archives
10963,https://pywb.nationaalarchief.nl/nl/all/201901...,NaN,The introduction of the euro and current econo...,1. Het onderwerp voor vandaag is tweeledig: de...,2002-03-19,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,The introduction of the euro and current econo...,De invoering van de euro en de economische act...,nld_37334_nout_wellkink,Dutch,Archives
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28379,https://www.bis.org/review/r980311a.pdf,https://www.bis.org/review/r980311a.pdf,Mr. de Swaan addresses capital adequacy regula...,"Speech by Mr. Tom de Swaan, an Executive Direc...",1998-02-27,Tom de Swaan,Board member,Male,De Nederlandsche Bank,NLD,Mr. de Swaan addresses capital adequacy regula...,NaN,r980311a,English,BIS
28447,https://www.bis.org/review/r980713a.pdf,https://www.bis.org/review/r980713a.pdf,Mr. Wellink looks at the United Kingdom and EM...,Speech by the President of the Nederlandsche B...,1998-06-16,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,Mr. Wellink looks at the United Kingdom and EM...,NaN,r980713a,English,BIS
28502,https://www.bis.org/review/r981109c.pdf,https://www.bis.org/review/r981109c.pdf,Mr. Wellink gives a central banker's view of p...,Speech by the President of the Netherlands Ban...,1998-10-23,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,Mr. Wellink gives a central bankers view of pr...,NaN,r981109c,English,BIS
28519,https://www.bis.org/review/r981203a.pdf,https://www.bis.org/review/r981203a.pdf,Mr Wellink considers monetary relations betwee...,Speech by the President of the Netherlands Ban...,1998-11-23,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,Mr Wellink considers monetary relations betwee...,NaN,r981203a,English,BIS
28702,https://www.bis.org/review/r991008a.pdf,https://www.bis.org/review/r991008a.pdf,Mr Wellink speaks about trends in the European...,"Speech held by Dr A H E M Wellink, President o...",1999-10-06,Nout Wellink,Governor,Male,De Nederlandsche Bank,NLD,Mr Wellink speaks about trends in the European...,NaN,r991008a,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Spain', 'Bank of Thailand', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/De Nederlandsche Bank
Bank of Portugal

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12061,https://www.bportugal.pt/en/intervencoes/sworn...,NaN,Sworning-in statement given by the Governor,NaN,2000-02-23,Vitor Constancio,Governor,Male,Bank of Portugal,PRT,Sworning-in statement given by the Governor 23...,NaN,prt_36579_vitor_constancio_english,English,CB websites
12062,https://www.bportugal.pt/en/intervencoes/intro...,NaN,Introductory statement given by Governador Vit...,NaN,2000-05-24,Vitor Constancio,Governor,Male,Bank of Portugal,PRT,Introductory statement given by Governador Vit...,NaN,prt_36670_vitor_gaspar_english,English,CB websites
12063,https://www.bportugal.pt/en/intervencoes/intro...,NaN,Introductory statement given by Governador Vit...,NaN,2000-07-27,Vitor Constancio,Governor,Male,Bank of Portugal,PRT,Introductory statement given by Governador Vit...,NaN,prt_36734_vitor_gaspar_english,English,CB websites
12064,https://www.bportugal.pt/en/intervencoes/intro...,NaN,Introductory statement given by Governor Vitor...,NaN,2001-01-25,Vitor Constancio,Governor,Male,Bank of Portugal,PRT,Introductory statement given by Governor Vitor...,NaN,prt_36916_vitor_gaspar_english,English,CB websites
12065,https://www.bportugal.pt/intervencoes/discurso...,NaN,"Speech by the Governor at the Conference ""Info...",NaN,2001-05-15,Vitor Constancio,Governor,Male,Bank of Portugal,PRT,Speech of the Governor at the Conference... Sp...,Discurso do Governador na Confernc... Discurso...,prt_37026_vitor_constancio_portuguese,Portuguese,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27173,http://www.bis.org/review/r221003f.htm,http://www.bis.org/review/r221003f.pdf,Mrio Centeno: Policy mix of the future - the r...,"Keynote intervention by Mr Mrio Centeno, Gover...",2022-09-29,Mrio Centeno,Governor,Male,Bank of Portugal,PRT,Mario Centeno: Policy mix of the future - the ...,NaN,r221003f,English,BIS
27197,http://www.bis.org/review/r221010c.htm,http://www.bis.org/review/r221010c.pdf,Mrio Centeno: The importance of financial educ...,Keynote intervention (virtual) by Mr Mrio Cent...,2022-10-03,Mrio Centeno,Governor,Male,Bank of Portugal,PRT,Mario Centeno: The importance of financial edu...,NaN,r221010c,English,BIS
27374,http://www.bis.org/review/r221122h.htm,http://www.bis.org/review/r221122h.pdf,Lus Mximo dos Santos: Opening address - FinCoN...,"Opening address by Mr Lus Mximo dos Santos, Vi...",2022-11-21,Lus Mximo dos Santos,Deputy Governor,Male,Bank of Portugal,PRT,Luis Maximo dos Santos: Opening address - FinC...,NaN,r221122h,English,BIS
27969,https://www.bis.org/review/r231018a.htm,https://www.bis.org/review/r231018a.pdf,Lus Mximo dos Santos: The reform of the framew...,"Speech by Mr Lus Mximo dos Santos, Vice-Govern...",2023-10-09,Lus Mximo dos Santos,Deputy Governor,Male,Bank of Portugal,PRT,"Good afternoon, everyone. I would like to begi...",NaN,r231018a,English,BIS
27989,https://www.bis.org/review/r231023e.htm,https://www.bis.org/review/r231023e.pdf,Lus Mximo dos Santos: The strategic importance...,"Opening remarks by Mr Lus Mximo dos Santos, Vi...",2023-10-18,Lus Mximo dos Santos,Deputy Governor,Male,Bank of Portugal,PRT,Luis Maximo dos Santos: The strategic importan...,NaN,r231023e,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Spain', 'Bank of Thailand', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Portugal
South African Reserve Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12498,https://www.bis.org/review/r000321a.pdf,https://www.bis.org/review/r000321a.pdf,The role of the South African Reserve Bank in ...,"Address by Mr T T Mboweni, Governor of the Sou...",2000-03-14,T T Mboweni,Governor,Male,South African Reserve Bank,ZAF,Mr Mboweni: The role of the South African Rese...,NaN,r000321a,English,BIS
12526,https://www.bis.org/review/r000417b.pdf,https://www.bis.org/review/r000417b.pdf,The objectives of monetary policy with referen...,"Address by Mr T T Mboweni, Governor of the Sou...",2000-04-12,T T Mboweni,Governor,Male,South African Reserve Bank,ZAF,T T Mboweni: The objectives of monetary policy...,NaN,r000417b,English,BIS
12538,https://www.bis.org/review/r000516a.pdf,https://www.bis.org/review/r000516a.pdf,Recent developments in South Africa's financia...,"Address by Mr T T Mboweni, Governor of the Sou...",2000-05-12,T T Mboweni,Governor,Male,South African Reserve Bank,ZAF,T T Mboweni: Recent developments in South Afri...,NaN,r000516a,English,BIS
12583,https://www.bis.org/review/r000721b.pdf,https://www.bis.org/review/r000721b.pdf,Issues for consideration in mergers and takeov...,"Speech by Ms Gill Marcus, Deputy Governor of t...",2000-07-18,Gill Marcus,Governor,Female,South African Reserve Bank,ZAF,Gill Marcus: Issues for consideration in merge...,NaN,r000721b,English,BIS
12606,https://www.bis.org/review/r000914b.pdf,https://www.bis.org/review/r000914b.pdf,A broadbrush picture of recent financial and e...,"Address by Mr T T Mboweni, Governor of the Sou...",2000-08-29,T T Mboweni,Governor,Male,South African Reserve Bank,ZAF,T T Mboweni: A broadbrush picture of recent fi...,NaN,r000914b,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34980,https://www.resbank.co.za/en/home/publications...,https://www.resbank.co.za/content/dam/sarb/pub...,Address at the Council of Retirement Funds for...,NaN,2016-06-06,Leon Myburgh,Senior management,Male,South African Reserve Bank,ZAF,Address by Mr Leon Myburgh Head of the Financi...,NaN,zaf_speech---leon-myburgh---batseta-07-june-2016,English,CB websites
34981,https://www.resbank.co.za/en/home/publications...,https://www.resbank.co.za/content/dam/sarb/pub...,Address at the Africa Sovereign Funds Roundtab...,NaN,2015-02-27,Leon Myburgh,Senior management,Male,South African Reserve Bank,ZAF,Address by Mr Leon Myburgh Head: Financial Mar...,NaN,zaf_speech-sf-roundtable-2015,English,CB websites
34982,https://www.resbank.co.za/en/home/publications...,https://www.resbank.co.za/content/dam/sarb/pub...,Address at the Standard Bank 6th Annual Centra...,NaN,2014-11-03,Leon Myburgh,Senior management,Male,South African Reserve Bank,ZAF,"Welcome Address by Mr Leon Myburgh, Head: Fina...",NaN,zaf_standard-bank-seminar---2014_11,English,CB websites
34983,https://www.resbank.co.za/en/home/publications...,https://www.resbank.co.za/content/dam/sarb/pub...,Remarks at the Nedbank 2019 Treasurers Conference,NaN,2019-06-12,Fundi Tshazibana,Senior management,Female,South African Reserve Bank,ZAF,"Remarks by Fundi Tshazibana, Adviser to the Go...",NaN,zaf_the-role-of-monetary-policy-settings-in-th...,English,CB websites
34984,https://www.resbank.co.za/en/home/publications...,https://www.resbank.co.za/content/dam/sarb/pub...,THE OUTLOOK FOR MONETARY POLICY,NaN,2005-06-22,T T Mboweni,Governor,Male,South African Reserve Bank,ZAF,- 1 - THE OUTLOOK FOR MONETARY POLICY Address ...,NaN,zaf_the+outlook+for+monetary+policy_1,English,CB websites

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/South African Reserve Bank
Norges Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
11222,https://www.norges-bank.no/aktuelt/nyheter-og-...,NaN,Economic perspectives,NaN,1997-02-06,Kjell Storvik,Governor,Male,Norges Bank,NOR,Financial perspek ver Speech by Governor Kjell...,RSTALE konomiske perspek ver Foredrag av sentr...,nor_1997_1997-02-06,Norwegian,CB websites
11223,https://www.norges-bank.no/aktuelt/nyheter-og-...,NaN,Bank of Norway's role as manager of Norway's f...,NaN,1997-02-27,Leif Eide,Senior management,Male,Norges Bank,NOR,Bank of Norway's role as manager of Norway's f...,NaN,nor_1997_1997-02-27,English,CB websites
11224,https://www.norges-bank.no/aktuelt/nyheter-og-...,NaN,Stabilisation policy challenges for the centra...,NaN,1997-05-21,Kjell Storvik,Governor,Male,Norges Bank,NOR,Stabilisation policy in discourse for the cent...,FOREDRAG Stabiliseringspoli ske u ordringer fo...,nor_1997_1997-05-21,Norwegian,CB websites
11225,https://www.norges-bank.no/aktuelt/nyheter-og-...,NaN,Management of the Government Petroleum Fund,NaN,1997-06-05,Kjell Storvik,Governor,Male,Norges Bank,NOR,Management of the Government Petroleum Fund Sp...,FOREDRAG Forvaltningen av statens petroleumsfo...,nor_1997_1997-06-05,Norwegian,CB websites
11226,https://www.norges-bank.no/aktuelt/nyheter-og-...,NaN,The outlook for the Norwegian economy,NaN,1997-09-24,Jarle Bergo,Deputy Governor,Male,Norges Bank,NOR,The outlook for the Norwegian economy Deputy G...,FOREDRAG Utsiktene for norsk konomi Visesentra...,nor_1997_1997-09-24,Norwegian,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28557,https://www.bis.org/review/r990211c.pdf,https://www.bis.org/review/r990211c.pdf,Mr Bergo looks at the impact of the euro on th...,Speech by the Deputy Governor of the Central B...,1999-02-03,Jarle Bergo,Deputy Governor,Male,Norges Bank,NOR,Mr Bergo looks at the impact of the euro on th...,NaN,r990211c,English,BIS
28563,https://www.bis.org/review/r990224a.pdf,https://www.bis.org/review/r990224a.pdf,Mr Gjedrem reports on economic perspectives in...,Annual address by the Governor of the Central ...,1999-02-18,Svein Gjedrem,Governor,Male,Norges Bank,NOR,Mr Gjedrem reports on economic perspectives in...,NaN,r990224a,English,BIS
28611,https://www.bis.org/review/r990510c.pdf,https://www.bis.org/review/r990510c.pdf,Mr Gjedrem focuses on monetary policy challeng...,"Article by Mr Gjedrem, Governor of Norges Bank...",1999-05-03,Svein Gjedrem,Governor,Male,Norges Bank,NOR,Mr Gjedrem focuses on monetary policy challeng...,NaN,r990510c,English,BIS
28728,https://www.bis.org/review/r991105a.pdf,https://www.bis.org/review/r991105a.pdf,Mr Gjedrem reports on the Norwegian economy an...,"Speech given by Mr Svein Gjedrem, Governor of ...",1999-10-28,Svein Gjedrem,Governor,Male,Norges Bank,NOR,Mr Gjedrem reports on the Norwegian economy an...,NaN,r991105a,English,BIS
28732,https://www.bis.org/review/r991111a.pdf,https://www.bis.org/review/r991111a.pdf,Mr Gjedrem focuses on the issue of financial s...,"Speech given by Mr Svein Gjedrem, Governor of ...",1999-10-21,Svein Gjedrem,Governor,Male,Norges Bank,NOR,Mr Gjedrem focuses on the issue of financial s...,NaN,r991111a,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Norges Bank
Bank of Uganda

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
14227,https://www.bis.org/review/r050509f.pdf,https://www.bis.org/review/r050509f.pdf,Recent initiatives designed to increase the ef...,"Address by Mr Emmanuel Tumusiime-Mutebile, Gov...",2005-03-04,Emmanuel Tumusiime-Mutebile,Governor,Male,Bank of Uganda,UGA,Emmanuel Tumusiime-Mutebile: Recent initiative...,NaN,r050509f,English,BIS
14230,https://www.bis.org/review/r050509i.pdf,https://www.bis.org/review/r050509i.pdf,Bank of Uganda - recent achievements,"Opening address by Mr David G Opiokello, Deput...",2005-03-04,David G Opiokello,Deputy Governor,Male,Bank of Uganda,UGA,David G Opiokello: Bank of Uganda - recent ach...,NaN,r050509i,English,BIS
14703,https://www.bis.org/review/r060407f.pdf,https://www.bis.org/review/r060407f.pdf,Review of the past five years and prospects fo...,"Speech by Mr Emmanuel Tumusiime-Mutebile, Gove...",2006-03-17,Emmanuel Tumusiime-Mutebile,Governor,Male,Bank of Uganda,UGA,Emmanuel Tumusiime-Mutebile: Review of the pas...,NaN,r060407f,English,BIS
14880,https://www.bis.org/review/r060718d.pdf,https://www.bis.org/review/r060718d.pdf,The way ahead for central banking in East Africa,"Speech by Mr Emmanuel Tumusiime-Mutebile, Gove...",2006-07-03,Emmanuel Tumusiime-Mutebile,Governor,Male,Bank of Uganda,UGA,Emmanuel Tumusiime-Mutebile: The way ahead for...,NaN,r060718d,English,BIS
14881,https://www.bis.org/review/r060718e.pdf,https://www.bis.org/review/r060718e.pdf,The state of the financial sector in Uganda,"Address by Mr Emmanuel Tumusiime-Mutebile, Gov...",2006-06-23,Emmanuel Tumusiime-Mutebile,Governor,Male,Bank of Uganda,UGA,Emmanuel Tumusiime-Mutebile: The state of the ...,NaN,r060718e,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30828,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,Remarks by Michael Ating-Ego Deputy Governor a...,NaN,2023-09-19,Michael Atingi-Ego,Deputy Governor,Male,Bank of Uganda,UGA,Remarks by Michael Ating-Ego Deputy Governor B...,NaN,uga_remarks-by-dg-farewell-and-welcome-party-s...,English,CB websites
30829,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,Remarks by Michael Atingi-Ego at Jinja TownHal...,NaN,2022-05-27,Michael Atingi-Ego,Deputy Governor,Male,Bank of Uganda,UGA,Remarks by Michael Atingi-Ego Deputy Governor ...,NaN,uga_remarks-by-michael-atingi-ego-at-jinja-tow...,English,CB websites
30830,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,Remarks by Mr Michael Atingi-Ego Deputy Govern...,NaN,2022-07-15,Michael Atingi-Ego,Deputy Governor,Male,Bank of Uganda,UGA,Remarks by Michael Atingi-Ego Deputy Governor ...,NaN,uga_remarks-by-mr-mae-dg-bou-sp2022-2027-offic...,English,CB websites
30831,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,Speech by Michael Atingi-Ego at UBA Women Econ...,NaN,2023-10-24,Michael Atingi-Ego,Deputy Governor,Male,Bank of Uganda,UGA,Opening Remarks Michael Atingi-Ego Deputy Gove...,NaN,uga_uba-womeneconomicempowermentforum,English,CB websites
30832,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,https://www.bou.or.ug/bouwebsite/bouwebsitecon...,Remarks Michael Atingi-Ego Deputy Governor Chi...,NaN,2023-11-01,Michael Atingi-Ego,Deputy Governor,Male,Bank of Uganda,UGA,Remarks Michael Atingi-Ego Deputy Governor Chi...,NaN,uga_wendi,English,CB websites

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Uganda
Central Bank of Chile

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1612,https://www.bcentral.cl/content/-/details/chal...,https://www.bcentral.cl/documents/33528/133214...,Challenges Facing the World Economy in the Med...,NaN,2004-09-02,Vittorio Corbo,Governor,Male,Central Bank of Chile,CHL,d2Challenges Facing the World Economy in the M...,NaN,chl_35892_carlos_massad,English,CB websites
1613,https://www.bcentral.cl/content/-/details/impl...,https://www.bcentral.cl/documents/33528/133214...,Implications of Chinas Regional and Global Int...,NaN,2004-11-16,Vittorio Corbo,Governor,Male,Central Bank of Chile,CHL,Implications of Chinad5s Regional and Global I...,NaN,chl_35912_jorge_marshall_rivera,English,CB websites
1614,https://www.bcentral.cl/content/-/details/conc...,https://www.bcentral.cl/documents/33528/133214...,Concluding Remarks,NaN,2005-11-18,Vittorio Corbo,Governor,Male,Central Bank of Chile,CHL,First Monetary Policy Research Workshop in Lat...,NaN,chl_35929_carlos_massad,English,CB websites
1615,https://www.bcentral.cl/content/-/details/oppo...,https://www.bcentral.cl/documents/33528/133214...,Opportunities and Challenges in Latin America:...,NaN,2010-05-10,Sebastin Claro,Board member,Male,Central Bank of Chile,CHL,The UCLA Anderson 2010 Latin American Conferen...,NaN,chl_35935_carlos_massad,English,CB websites
1616,https://www.bcentral.cl/content/-/details/cycl...,https://www.bcentral.cl/documents/33528/133214...,Cyclical and Structural Challenges for Latin A...,NaN,2010-12-02,Sebastin Claro,Board member,Male,Central Bank of Chile,CHL,II Latin American Business Symposium 2010 The ...,NaN,chl_36012_carlos_massad,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27662,http://www.bis.org/review/r230427c.htm,http://www.bis.org/review/r230427c.pdf,Rosanna Costa: Opening address - IV Meeting of...,"Opening address by Ms Rosanna Costa, Governor ...",2023-04-26,Rosanna Costa,Governor,Female,Central Bank of Chile,CHL,Rosanna Costa: Opening address - IV meeting of...,NaN,r230427c,English,BIS
27816,http://www.bis.org/review/r230712c.htm,http://www.bis.org/review/r230712c.pdf,Rosanna Costa: Chile's June 2023 Monetary Poli...,"Presentation by Ms Rosanna Costa, Governor of ...",2023-06-20,Rosanna Costa,Governor,Female,Central Bank of Chile,CHL,MONETARY POLICY REPORT BEFORE THE PRESENTATION...,NaN,r230712c,English,BIS
27835,http://www.bis.org/review/r230718s.htm,http://www.bis.org/review/r230718s.pdf,Pablo Garca Silva: Enhancing resilience throug...,"Speech by Mr Pablo Garca Silva, Deputy Governo...",2023-06-28,Pablo Garca Silva,Deputy Governor,Male,Central Bank of Chile,CHL,THROUGH IN ENHANCING RESILIENCE MACROECONOMIC ...,NaN,r230718s,English,BIS
28112,https://www.bis.org/review/r231206e.htm,https://www.bis.org/review/r231206e.pdf,Rosanna Costa: Implications of climate change ...,"Opening remarks by Ms Rosanna Costa, Governor ...",2023-11-27,Rosanna Costa,Governor,Female,Central Bank of Chile,CHL,Rosanna Costa: Implications of climate change ...,NaN,r231206e,English,BIS
28156,https://www.bis.org/review/r240130i.htm,https://www.bis.org/review/r240130i.pdf,"Leadership and management - managing change, c...","Speech virtual by Ms Rosanna Costa, Governor...",2023-11-08,Rosanna Costa,Governor,Female,Central Bank of Chile,CHL,Rosanna Costa: Leadership and management - man...,NaN,r240130i,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Chile
Bank of Mexico

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10134,https://www.banxico.org.mx/publications-and-pr...,https://www.banxico.org.mx/publications-and-pr...,Signing of Banxico-INEGI collaboration agreements,NaN,2010-10-13,Agustn Carstens,Governor,Male,Bank of Mexico,MEX,"Remarks by the Governor of the Bank of Mexico,...","Palabras del Gobernador del Banco de Mxico, do...",mex_0330d70a-1fb4-ea49-9c86-be2dfbb8b869,Spanish,CB websites
10135,https://www.banxico.org.mx/publications-and-pr...,https://www.banxico.org.mx/publications-and-pr...,Monetary policy in Mexico at the beginning of ...,NaN,2018-01-18,Javier Guzmn Calafell,Deputy Governor,Male,Bank of Mexico,MEX,"""MONETARY POLICY IN MEXICO AT THE BEGINNING OF...",LA POLTICA MONETARIA EN MXICO AL INICIO DE UN ...,mex_0480b294-8d16-db48-2c7c-13d7aaee8729,Spanish,CB websites
10136,https://www.banxico.org.mx/publications-and-pr...,https://www.banxico.org.mx/publications-and-pr...,Award ceremony of the fifth edition of the BAN...,NaN,2020-06-11,Alejandro Daz de Len,Governor,Male,Bank of Mexico,MEX,"Remarks by Mr. Alejandro Diaz de Leon, Governo...","Palabras del Lic. Alejandro Daz de Len, Gobern...",mex_08440b2a-6bc0-55a5-5862-1ad471ceea50,Spanish,CB websites
10137,https://www.banxico.org.mx/publications-and-pr...,https://www.banxico.org.mx/publications-and-pr...,Inauguration of the new permanent hall,NaN,2011-11-23,Agustn Carstens,Governor,Male,Bank of Mexico,MEX,"Remarks by the Governor of the Bank of Mexico,...","Palabras del Gobernador del Banco de Mxico, Ag...",mex_0a84213c-55b7-063c-246e-507deb92738b,Spanish,CB websites
10138,https://www.banxico.org.mx/publications-and-pr...,https://www.banxico.org.mx/publications-and-pr...,Christmas traditions in the world,NaN,2018-11-29,Irene Espinosa Cantellano,Deputy Governor,Female,Bank of Mexico,MEX,"Words of Mtra. Irene Espinosa Cantellano, Depu...",Palabras de la Mtra. Irene Espinosa Cantellano...,mex_0d6bd385-2c2f-42d0-4923-7993153d31c0,Spanish,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27135,http://www.bis.org/review/r220921h.htm,http://www.bis.org/review/r220921h.pdf,Irene Espinosa Cantellano: Mexico - macroecono...,"Remarks by Ms Irene Espinosa Cantellano, Deput...",2022-09-07,Irene Espinosa Cantellano,Deputy Governor,Female,Bank of Mexico,MEX,Mexico: Macroeconomic outlook and opportunitie...,NaN,r220921h,English,BIS
27137,http://www.bis.org/review/r220921j.htm,http://www.bis.org/review/r220921j.pdf,Gerardo Esquivel Hernndez: Opening remarks - 1...,"Opening remarks by Gerardo Esquivel Hernndez, ...",2022-09-20,Gerardo Esquivel Hernndez,Deputy Governor,Male,Bank of Mexico,MEX,"Opening remarks by Gerardo Esquivel Hernandez,...",NaN,r220921j,English,BIS
27176,http://www.bis.org/review/r221004a.htm,http://www.bis.org/review/r221004a.pdf,Gerardo Esquivel Hernndez: Welcome remarks - i...,"Welcome remarks by Gerardo Esquivel Hernndez, ...",2022-09-30,Gerardo Esquivel Hernndez,Deputy Governor,Male,Bank of Mexico,MEX,Gerardo Esquivel Hernandez: Welcome remarks - ...,NaN,r221004a,English,BIS
27260,http://www.bis.org/review/r221031b.htm,http://www.bis.org/review/r221031b.pdf,Irene Espinosa Cantellano: Moving beyond clima...,Keynote (pre-recorded) by Ms Irene Espinosa Ca...,2022-09-29,Irene Espinosa Cantellano,Deputy Governor,Female,Bank of Mexico,MEX,Irene Espinosa Cantellano: Moving beyond clima...,NaN,r221031b,English,BIS
27492,http://www.bis.org/review/r230207b.htm,http://www.bis.org/review/r230207b.pdf,Irene Espinosa Cantellano: Moving beyond clima...,Keynote (virtually) by Ms Irene Espinosa Cante...,2023-01-27,Irene Espinosa Cantellano,Deputy Governor,Female,Bank of Mexico,MEX,Irene Espinosa Cantellano: Moving beyond clima...,NaN,r230207b,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Central Bank of Chile', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Mexico
Central Bank of Kenya

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9586,NaN,https://www.centralbank.go.ke/uploads/speeches...,Groundbreaking Ceremony National Police Leader...,NaN,2021-01-26,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,CENTRAL BANK OF KENYA GROUNDBREAKING CEREMONY ...,NaN,ken_1020268431,English,CB websites
9587,NaN,https://www.centralbank.go.ke/uploads/speeches...,How the Credit Information Sharing System Will...,NaN,2020-04-22,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,How the Credit Information Sharing System Will...,NaN,ken_1030009253,English,CB websites
9588,NaN,https://www.centralbank.go.ke/uploads/speeches...,KIB Annual Dinner- 2015,NaN,2015-11-20,Mohammed Nyaoga,Board member,Male,Central Bank of Kenya,KEN,CENTRAL BANK OF KENYA KENYA INSTITUTE OF BANKE...,NaN,ken_1196695635,English,CB websites
9589,NaN,https://www.centralbank.go.ke/uploads/speeches...,Speech during Kenyatta University 45th Gradua...,NaN,2018-12-17,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,CENTRAL BANK OF KENYA KENYATTA UNIVERSITY 45TH...,NaN,ken_1235367703,English,CB websites
9590,NaN,https://www.centralbank.go.ke/uploads/speeches...,Launch of Maisha MFB,NaN,2016-09-22,Mohammed Nyaoga,Board member,Male,Central Bank of Kenya,KEN,CENTRAL BANK OF KENYA MAISHA MICROFINANCE BANK...,NaN,ken_1427645911,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26673,https://www.bis.org/review/r211213q.htm,https://www.bis.org/review/r211213q.pdf,Launch of the Banking Industry Sign Language S...,"Remarks by Dr Patrick Njoroge, Governor of the...",2021-12-02,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,Patrick Njoroge: Launch of the Banking Industr...,NaN,r211213q,English,BIS
26675,https://www.bis.org/review/r211213t.htm,https://www.bis.org/review/r211213t.pdf,Food systems summit dialogue strengthening and...,"Remarks by Dr Patrick Njoroge, Governor of the...",2021-06-18,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,Patrick Njoroge: Food systems summit dialogue ...,NaN,r211213t,English,BIS
26842,http://www.bis.org/review/r220315c.htm,http://www.bis.org/review/r220315c.pdf,Patrick Njoroge: Kenya's Finaccess Survey 2021,"Remarks by Dr Patrick Njoroge, Governor of the...",2022-03-01,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,Patrick Njoroge: Kenya's Finaccess Survey 2021...,NaN,r220315c,English,BIS
27814,http://www.bis.org/review/r230712a.htm,http://www.bis.org/review/r230712a.pdf,Patrick Njoroge: Launch of Banking Industry Fi...,"Remarks by Dr Patrick Njoroge, Governor of the...",2023-06-08,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,Patrick Njoroge: Launch of Banking Industry Fi...,NaN,r230712a,English,BIS
27815,http://www.bis.org/review/r230712b.htm,http://www.bis.org/review/r230712b.pdf,"Patrick Njoroge: Remarks ""Global Forum on Rem...","Remarks by Dr Patrick Njoroge, Governor of the...",2023-06-14,Patrick Njoroge,Governor,Male,Central Bank of Kenya,KEN,"Patrick Njoroge: Remarks - ""Global Forum on Re...",NaN,r230712b,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Central Bank of Chile', 'Central Bank of Ireland', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Kenya
Central Bank of the Republic of Turkey

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12469,https://www.bis.org/review/r000203b.pdf,https://www.bis.org/review/r000203b.pdf,Mr Erel reviews the monetary side of Turkey's ...,"Speech given by Mr Gazi Erel, Governor of the ...",2000-01-25,Gazi Erel,Governor,Male,Central Bank of the Republic of Turkey,TUR,Mr Ercel reviews the monetary side of Turkeys ...,NaN,r000203b,English,BIS
12532,https://www.bis.org/review/r000510a.pdf,https://www.bis.org/review/r000510a.pdf,Risk management - within reserve management po...,"Opening remarks by Mr Gazi Erel, Governor of t...",2000-05-04,Gazi Erel,Governor,Male,Central Bank of the Republic of Turkey,TUR,Gazi Ercel: Risk management - within reserve m...,NaN,r000510a,English,BIS
12617,https://www.bis.org/review/r000927b.pdf,https://www.bis.org/review/r000927b.pdf,Globalization and international financial envi...,"Remarks by Mr Gazi Erel, Governor of The Centr...",2000-09-22,Gazi Erel,Governor,Male,Central Bank of the Republic of Turkey,TUR,Gazi Ercel: Globalization and international fi...,NaN,r000927b,English,BIS
12652,https://www.bis.org/review/r001030c.pdf,https://www.bis.org/review/r001030c.pdf,Focus on inflation targeting (Central Bank Ar...,"Opening remarks by Mr Gazi Erel, Governor of t...",2000-10-19,Gazi Erel,Governor,Male,Central Bank of the Republic of Turkey,TUR,Gazi Ercel: Focus on inflation targeting Openi...,NaN,r001030c,English,BIS
12680,https://www.bis.org/review/r001130c.pdf,https://www.bis.org/review/r001130c.pdf,The role of the euro from the Turkish standpoi...,"Speech by Mr Gazi Erel, Governor of the Centra...",2000-11-09,Gazi Erel,Governor,Male,Central Bank of the Republic of Turkey,TUR,Gazi Ercel: The role of the euro from the Turk...,NaN,r001130c,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30614,https://www.tcmb.gov.tr/wps/wcm/connect/5b404b...,https://www.tcmb.gov.tr/wps/wcm/connect/5b404b...,"Speech on ""Dollarization"" at the Opening Cerem...",NaN,2005-10-03,Sreyya Serdengeti,Governor,Male,Central Bank of the Republic of Turkey,TUR,Central Bank of the Republic of Turkey DOLLARI...,Trkiye Cumhuriyet Merkez Bankas DOLARZASYON / ...,tur_sunumeskisehir,Turkish,CB websites
30615,https://www.tcmb.gov.tr/wps/wcm/connect/a9b44b...,https://www.tcmb.gov.tr/wps/wcm/connect/a9b44b...,Speech on Independence at the Finance Club,NaN,2003-02-28,Sreyya Serdengeti,Governor,Male,Central Bank of the Republic of Turkey,TUR,CENTRAL BANK OF THE REPUBLIC OF TURKEY MERKEZB...,TRKYE CUMHURYET MERKEZBANKASI MERKEZBANKASI BA...,tur_tcmbbagimsizlik,Turkish,CB websites
30616,https://www.tcmb.gov.tr/wps/wcm/connect/54b9c0...,https://www.tcmb.gov.tr/wps/wcm/connect/54b9c0...,"Speech at the Workshop on ""Global Crisis and T...",NaN,2008-12-27,Durmus Yilmaz,Governor,Male,Central Bank of the Republic of Turkey,TUR,Central Bank of the Republic of Turkey The Glo...,Trkiye Cumhuriyet Merkez Bankas Kresel Mali Kr...,tur_tek_27aralik2008,Turkish,CB websites
30617,https://tcmb.gov.tr/wps/wcm/connect/EN/TCMB+EN...,https://tcmb.gov.tr/wps/wcm/connect/570e8cec-6...,Anadolu Agencys Interview with Governor Murat ...,NaN,2020-04-19,Murat Uysal,Governor,Male,Central Bank of the Republic of Turkey,TUR,Interview with Governor Murat Uysal 19 April 2...,NaN,tur_uysal_aa_eng,English,CB websites
30618,https://www.tcmb.gov.tr/wps/wcm/connect/afb5d2...,https://www.tcmb.gov.tr/wps/wcm/connect/afb5d2...,YTL Presentation of President Serdengeti / Pre...,NaN,2004-10-25,Sreyya Serdengeti,Governor,Male,Central Bank of the Republic of Turkey,TUR,"SuREYYA SERDENGEcT, CENTRAL BANK BA KANI YEN T...","SREYYA SERDENGET , MERKEZ BANKASI BA KANI YEN ...",tur_ytl-banknot-sunumtummetin-baskan-bmgm,Turkish,CB websites

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Central Bank of Chile', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of the Republic of Turkey
State Bank of Pakistan

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
11450,https://www.sbp.org.pk/about/speech/Governors/...,https://www.sbp.org.pk/about/speech/Governors/...,Key Note address at MAPs Seminar on The State ...,NaN,2012-03-01,Yaseen Anwar,Governor,Male,State Bank of Pakistan,PAK,"Key Note address by Mr. Yaseen Anwar Governor,...",NaN,pak_01-mar-2012,English,CB websites
11451,https://www.sbp.org.pk/about/speech/Governors/...,https://www.sbp.org.pk/about/speech/Governors/...,State Bank of Pakistan Conference on Long Term...,NaN,2012-03-05,Yaseen Anwar,Governor,Male,State Bank of Pakistan,PAK,"Address by: Yaseen Anwar, Governor, State Bank...",NaN,pak_03-mar-2012,English,CB websites
11452,https://www.sbp.org.pk/about/speech/Governors/...,https://www.sbp.org.pk/about/speech/Governors/...,Speech on the Occasion of Inaugural Ceremony o...,NaN,2012-01-04,Yaseen Anwar,Governor,Male,State Bank of Pakistan,PAK,"SPEECH BY THE GOVERNOR, STATE BANK OF PAKISTAN...",NaN,pak_04-jan-2012,English,CB websites
11453,https://www.sbp.org.pk/DG-Speeches/Kazi.Abdul....,https://www.sbp.org.pk/DG-Speeches/Kazi.Abdul....,Inaugural Address,NaN,2012-12-05,Kazi Abdul Muktadir,Deputy Governor,Male,State Bank of Pakistan,PAK,6th Pakistan MIC RO FINANCE Country Forum 2012...,NaN,pak_05-dec-2012,English,CB websites
11454,https://www.sbp.org.pk/DG-Speeches/2021/06-Apr...,https://www.sbp.org.pk/DG-Speeches/2021/06-Apr...,Inaugural Remarks on Seminar Economic Modeling...,NaN,2022-04-06,Murtaza Syed,Senior management,Male,State Bank of Pakistan,PAK,SAARCFINANCE Seminar Economic Modeling and For...,NaN,pak_06-apr-2021,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24884,https://www.bis.org/review/r190520f.htm,https://www.bis.org/review/r190520f.pdf,"Pakistan's need to tackle low savings, low rev...","Keynote address by Mr Tariq Bajwa, Governor of...",2019-03-18,Tariq Bajwa,Governor,Male,State Bank of Pakistan,PAK,Governor Title Date Event Venue : Mr. Tariq Ba...,NaN,r190520f,English,BIS
25149,https://www.bis.org/review/r190911e.htm,https://www.bis.org/review/r190911e.pdf,Monetary policy and digitization of payment sy...,"Speech by Mr Jameel Ahmad, Deputy Governor for...",2019-08-28,Jameel Ahmad,Deputy Governor,Male,State Bank of Pakistan,PAK,"21st MAP Convention Speech by Deputy Governor,...",NaN,r190911e,English,BIS
25150,https://www.bis.org/review/r190911f.htm,https://www.bis.org/review/r190911f.pdf,Remarks - 23rd Zahid Husain Memorial Lecture,"Remarks by Mr Tariq Bajwa, Governor of the Sta...",2019-04-19,Tariq Bajwa,Governor,Male,State Bank of Pakistan,PAK,Governor Title Date Event Venue : Mr. Tariq Ba...,NaN,r190911f,English,BIS
27365,http://www.bis.org/review/r221121q.htm,http://www.bis.org/review/r221121q.pdf,Jameel Ahmad: Keynote address - inauguration o...,"Keynote address by Mr Jameel Ahmad, Governor o...",2022-11-14,Jameel Ahmad,Deputy Governor,Male,State Bank of Pakistan,PAK,Jameel Ahmad: Keynote address - inauguration o...,NaN,r221121q,English,BIS
27366,http://www.bis.org/review/r221121r.htm,http://www.bis.org/review/r221121r.pdf,Jameel Ahmad: Launch of Environmental and Soci...,"Keynote address by Mr Jameel Ahmad, Governor o...",2022-11-09,Jameel Ahmad,Deputy Governor,Male,State Bank of Pakistan,PAK,Jameel Ahmad: Launch of Environmental and Soci...,NaN,r221121r,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Central Bank of Chile', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/State Bank of Pakistan
Bulgarian National Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
903,https://www.bnb.bg/AboutUs/PressOffice/POState...,https://www.bnb.bg/bnbweb/groups/public/docume...,Opening address at the official opening of the...,NaN,2012-09-17,Ivan Iskrov,Governor,Male,Bulgarian National Bank,BGR,"Opening address by Mr. Ivan Iskrov, Governor o...",NaN,bgr_02_iskrov_20120917_en,English,CB websites
904,https://www.bnb.bg/AboutUs/PressOffice/POState...,https://www.bnb.bg/bnbweb/groups/public/docume...,Speech delivered before the Association of Ban...,NaN,2012-12-06,Ivan Iskrov,Governor,Male,Bulgarian National Bank,BGR,"Speech of Mr. Ivan Iskrov, Governor of the Bul...",NaN,bgr_02_iskrov_20121206_en,English,CB websites
905,https://www.bnb.bg/AboutUs/PressOffice/POState...,https://www.bnb.bg/bnbweb/groups/public/docume...,Speech at the roundtable discussion organized ...,NaN,2013-07-02,Ivan Iskrov,Governor,Male,Bulgarian National Bank,BGR,"Speech by Mr. Ivan Iskrov, Governor of the Bul...",NaN,bgr_02_iskrov_20130702_en,English,CB websites
906,https://www.bnb.bg/AboutUs/PressOffice/POState...,https://www.bnb.bg/bnbweb/groups/public/docume...,Speech delivered before the Association of Ban...,NaN,2013-12-05,Ivan Iskrov,Governor,Male,Bulgarian National Bank,BGR,"Speech of Mr. Ivan Iskrov, Governor of the Bul...",NaN,bgr_02_iskrov_20131205_en,English,CB websites
907,https://www.bnb.bg/AboutUs/PressOffice/POState...,https://www.bnb.bg/bnbweb/groups/public/docume...,Welcome address on the Occasion of the 135th A...,NaN,2014-06-06,Ivan Iskrov,Governor,Male,Bulgarian National Bank,BGR,"Welcome address by Mr. Ivan Iskrov, BNB Govern...",NaN,bgr_02_iskrov_20140606_1_en,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27483,http://www.bis.org/review/r230124q.htm,http://www.bis.org/review/r230124q.pdf,Dimitar Radev: Another year of strategic chall...,"Publication by Mr Dimitar Radev, Governor of t...",2023-01-24,Dimitar Radev,Governor,Male,Bulgarian National Bank,BGR,Dimitar Radev: Another year of strategic chall...,NaN,r230124q,English,BIS
27536,http://www.bis.org/review/r230301a.htm,http://www.bis.org/review/r230301a.pdf,Dimitar Radev: Bulgaria on the road to the euro,"Speech by Mr Dimitar Radev, Governor of the Bu...",2023-02-24,Dimitar Radev,Governor,Male,Bulgarian National Bank,BGR,Dimitar Radev: Bulgaria on the road to the eur...,NaN,r230301a,English,BIS
27632,http://www.bis.org/review/r230418i.htm,http://www.bis.org/review/r230418i.pdf,Dimitar Radev: Bulgaria in the eurozone what ...,"Speech by Mr Dimitar Radev, Governor of the Bu...",2023-04-05,Dimitar Radev,Governor,Male,Bulgarian National Bank,BGR,Dimitar Radev: Bulgaria in the eurozone - what...,NaN,r230418i,English,BIS
27704,http://www.bis.org/review/r230517l.htm,http://www.bis.org/review/r230517l.pdf,Nina Stoyanova: Bulgaria in the eurozone what...,"Speech by Ms Nina Stoyanova, Deputy Governor o...",2023-03-28,Nina Stoyanova,Deputy Governor,Female,Bulgarian National Bank,BGR,Nina Stoyanova: Bulgaria in the eurozone - wha...,NaN,r230517l,English,BIS
28144,https://www.bis.org/review/r231218j.htm,https://www.bis.org/review/r231218j.pdf,Petar Chobanov: Sustainable development - trai...,"Speech by Mr Petar Chobanov, Deputy Governor o...",2023-10-19,Petar Chobanov,Deputy Governor,Male,Bulgarian National Bank,BGR,Petar Chobanov: Sustainable development - trai...,NaN,r231218j,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Central Bank of Chile', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bulgarian National Bank
Central Bank of Hungary

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7538,https://www.mnb.hu/en/pressroom/publications-o...,NaN,A common future for three continents?,NaN,2020-06-19,Gyrgy Matolcsy,Governor,Male,Central Bank of Hungary,HUN,A COMMON FUTURE FOR THREE CONTINENTS? Kicmelt ...,NaN,hun_a-common-future-for-three-continents,English,CB websites
7539,https://www.mnb.hu/en/pressroom/publications-o...,NaN,A lifetime opportunity to buy bargains,NaN,2021-05-05,Gyrgy Matolcsy,Governor,Male,Central Bank of Hungary,HUN,A LIFETIME OPPORTUNITY TO BUY BARGAINS Kicmelt...,NaN,hun_a-lifetime-opportunity-to-buy-bargains,English,CB websites
7540,https://www.mnb.hu/en/pressroom/publications-o...,NaN,A new cycle has just begun,NaN,2020-10-07,Gyrgy Matolcsy,Governor,Male,Central Bank of Hungary,HUN,A NEW CYCLE HAS JUST BEGUN Kicmelt temak Indee...,NaN,hun_a-new-cycle-has-just-begun,English,CB websites
7541,https://www.mnb.hu/en/pressroom/publications-o...,NaN,A new deal for all of us,NaN,2021-05-14,Gyrgy Matolcsy,Governor,Male,Central Bank of Hungary,HUN,ANEW DEAL FOR ALL OF US Kicmelt temak All of u...,NaN,hun_a-new-deal-for-all-of-us,English,CB websites
7542,https://www.mnb.hu/en/pressroom/publications-o...,NaN,A new global landscape,NaN,2020-10-16,Gyrgy Matolcsy,Governor,Male,Central Bank of Hungary,HUN,A NEW GLOBAL LANDSCAPE Kicmelt temak On the on...,NaN,hun_a-new-global-landscape,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18031,https://www.bis.org/review/r101019d.pdf,https://www.bis.org/review/r101019d.pdf,Current challenges and responsibility of econo...,"Speech by Mr Ferenc Karvalits, Deputy Governor...",2010-10-13,Ferenc Karvalits,Deputy Governor,Male,Central Bank of Hungary,HUN,Ferenc Karvalits: Current challenges and respo...,NaN,r101019d,English,BIS
18100,https://www.bis.org/review/r101117d.pdf,https://www.bis.org/review/r101117d.pdf,A policy recipe for successful convergence of ...,"Speech by Ms Julia Kiraly, Deputy Governor of ...",2010-11-15,Julia Kiraly,Deputy Governor,Female,Central Bank of Hungary,HUN,Julia Kiraly: A policy recipe for successful c...,NaN,r101117d,English,BIS
18551,https://www.bis.org/review/r110606f.pdf,https://www.bis.org/review/r110606f.pdf,"Governance, efficiency and integration in reta...","Speech by Ms Jlia Kirly, Deputy Governor of Ma...",2011-05-12,Julia Kiraly,Deputy Governor,Female,Central Bank of Hungary,HUN,"Julia Kiraly: Governance, efficiency and integ...",NaN,r110606f,English,BIS
19804,https://www.bis.org/review/r121210b.pdf,https://www.bis.org/review/r121210b.pdf,Anchor 2013,"Speech by Mr Andrs Simor, Governor of Magyar N...",2012-12-07,Andras Simor,Governor,Male,Central Bank of Hungary,HUN,Andras Simor: Anchor 2013 Speech by Mr Andras ...,NaN,r121210b,English,BIS
19814,https://www.bis.org/review/r121212f.pdf,https://www.bis.org/review/r121212f.pdf,Cost and efficiency of retail payments - evide...,"Pre-dinner statement by Mr Andrs Simor, Govern...",2012-11-15,Andras Simor,Governor,Male,Central Bank of Hungary,HUN,Andras Simor: Cost and efficiency of retail pa...,NaN,r121212f,English,BIS

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Hungary
Bangladesh Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
649,https://www.bb.org.bd/governor/speech/oct10201...,NaN,Rethinking Central Banking,NaN,2010-10-10,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,Rethinking Central Banking IMF/ECB/FRB High Le...,NaN,bgd_40461_atiur_rahman,English,CB websites
650,https://www.bb.org.bd/governor/speech/oct26201...,NaN,Address in the inaugural session of the APG Ty...,NaN,2010-10-26,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,Address by Governor Bangladesh Bank in the ina...,NaN,bgd_40477_atiur_rahman,English,CB websites
651,https://www.bb.org.bd/governor/speech/nov04201...,NaN,ADB Regional Forum: Session on 'Lessons for th...,NaN,2010-11-04,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,ADB Regional Forum Session on Lessons for the ...,NaN,bgd_40486_atiur_rahman_2,English,CB websites
652,https://www.bb.org.bd/governor/speech/dec07201...,NaN,Bangladesh 2030: Strategy for Growth,NaN,2010-11-04,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,Bangladesh 2030: Strategy for Growth Organized...,NaN,bgd_40486_atiur_rahman,English,CB websites
653,https://www.bb.org.bd/governor/speech/dec07201...,NaN,Inauguration of Workshop on New INCOTERMS 2010...,NaN,2010-12-07,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,Inauguration of Workshop on New INCOTERMS 2010...,NaN,bgd_40519_atiur_rahman,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898,https://www.bb.org.bd/governor/speech/feb03201...,NaN,Speech at Financial Inclusion Literacy for Str...,NaN,2016-02-03,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,Financial Inclusion Literacy for Strengthening...,NaN,bgd_42403_atiur_rahman,English,CB websites
899,https://www.bb.org.bd/governor/speech/feb13201...,NaN,Speech at Prize Giving Ceremony-2nd Internatio...,NaN,2016-02-05,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,Prize Giving Ceremony-2nd International Nature...,NaN,bgd_42405_atiur_rahman,English,CB websites
900,https://www.bb.org.bd/governor/speech/feb07201...,NaN,Speech at Launching ceremony of 'Green Banking...,NaN,2016-02-07,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,Launching ceremony of 'Green Banking for Energ...,NaN,bgd_42407_atiur_rahman,English,CB websites
901,https://www.bb.org.bd/governor/speech/feb13201...,NaN,Speech at the National Dialogue on Developing ...,NaN,2016-02-13,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,National Dialogue on Developing NFIS Speech of...,NaN,bgd_42413_atiur_rahman,English,CB websites
902,https://www.bb.org.bd/governor/speech/mar09201...,NaN,Speech at an International Conference on Devel...,NaN,2016-03-05,Atiur Rahman,Governor,Male,Bangladesh Bank,BGD,International Conference on Development of Mic...,NaN,bgd_42434_atiur_rahman,English,CB websites

['Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bangladesh Bank
Reserve Bank of New Zealand

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
11348,https://www.rbnz.govt.nz/news-and-events/event...,https://www.rbnz.govt.nz/-/media/project/sites...,Presentation to the Annual Conference of the N...,"Bob Buckle, Emeritus Professor, Victoria Unive...",2023-06-30,Bob Buckle,Board member,Male,Reserve Bank of New Zealand,NZL,i Monetary policy and the benefits and limits ...,NaN,nzl_bob-buckle-nzae-speech-final-21-june,English,CB websites
11349,https://www.rbnz.govt.nz/hub/publications/spee...,https://www.rbnz.govt.nz/-/media/project/sites...,Testing our resilience,A speech delivered by Governor Adrian Orr at I...,2022-10-27,Adrian Orr,Governor,Male,Reserve Bank of New Zealand,NZL,Testing our resilience. Speech delivered at IN...,NaN,nzl_infinz-conference-statement-oct-2022,English,CB websites
11350,https://www.rbnz.govt.nz/news-and-events/event...,https://www.rbnz.govt.nz/-/media/project/sites...,The path back to low inflation in New Zealand,Chief Economist Paul Conway will give a speech...,2023-03-23,Paul Conway,Senior management,Male,Reserve Bank of New Zealand,NZL,The Path Back to Low Inflation in New Zealand ...,NaN,nzl_inflation-speech,English,CB websites
11351,https://www.rbnz.govt.nz/hub/publications/spee...,https://www.rbnz.govt.nz/-/media/f80abe3711634...,Informed investment decisions support financia...,NaN,2016-10-12,Grant Spencer,Governor,Male,Reserve Bank of New Zealand,NZL,Informed investment decisions support financia...,NaN,nzl_informed-investment-decisions-support-fina...,English,CB websites
11352,https://www.rbnz.govt.nz/news-and-events/event...,https://www.rbnz.govt.nz/-/media/project/sites...,Another seismic shift in New Zealand banking r...,RBNZ Director of Enforcement and Resolution Ke...,2023-09-04,Kerry Beaumont,Senior management,Male,Reserve Bank of New Zealand,NZL,UNCLASSIFIED (Another) Seismic Shift in New Ze...,NaN,nzl_kerry-beaumont-speech-another-seismic-shif...,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28652,https://www.bis.org/review/r990707b.pdf,https://www.bis.org/review/r990707b.pdf,Mr Sherwin discusses the origins of New Zealan...,"Speech by Mr Murray Sherwin, a Deputy Governor...",1999-07-01,Murray Sherwin,Deputy Governor,Male,Reserve Bank of New Zealand,NZL,Mr Sherwin discusses the origins of New Zealan...,NaN,r990707b,English,BIS
28655,https://www.bis.org/review/r990709b.pdf,https://www.bis.org/review/r990709b.pdf,Mr Brash comments on the address given by Mr T...,"Comments by Dr Donald Brash, Governor of the R...",1999-07-08,Donald T Brash,Governor,Male,Reserve Bank of New Zealand,NZL,Mr Brash comments on the address given by Mr T...,NaN,r990709b,English,BIS
28656,https://www.bis.org/review/r990712b.pdf,https://www.bis.org/review/r990712b.pdf,Mr Sherwin discusses reform of the global fina...,"Address by Murray Sherwin, Deputy Governor of ...",1999-07-09,Murray Sherwin,Deputy Governor,Male,Reserve Bank of New Zealand,NZL,Mr Sherwin discusses reform of the global fina...,NaN,r990712b,English,BIS
28668,https://www.bis.org/review/r990818a.pdf,https://www.bis.org/review/r990818a.pdf,Mr Brash comments on the economic reforms of t...,Comments on accepting the NZIER/Qantas Economi...,1999-08-18,Donald T Brash,Governor,Male,Reserve Bank of New Zealand,NZL,Mr Brash comments on the economic reforms of t...,NaN,r990818a,English,BIS
28734,https://www.bis.org/review/r991111c.pdf,https://www.bis.org/review/r991111c.pdf,Mr Brash gives an address on the development o...,"Opening address given by Dr Donald T Brash, Go...",1999-11-11,Donald T Brash,Governor,Male,Reserve Bank of New Zealand,NZL,Mr Brash gives an address on the development o...,NaN,r991111c,English,BIS

['Bangladesh Bank', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Reserve Bank of New Zealand
Bank of Mauritius

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10528,https://www.bom.mu/media/speeches/workshop-cha...,https://www.bom.mu/sites/default/files/pdf/Abo...,Workshop on Challenges and Solutions to Implem...,NaN,2002-11-29,Baboo R Gujadhur,Senior management,Male,Bank of Mauritius,MUS,Workshop on d2Challenges and Solutions to Impl...,NaN,mus_baboo_gujadhur_37589_english,English,CB websites
10529,https://www.bom.mu/media/speeches/presentation...,https://www.bom.mu/sites/default/files/pdf/Abo...,Presentation at the Invitation of the Commissi...,NaN,2003-09-20,Baboo R Gujadhur,Senior management,Male,Bank of Mauritius,MUS,"Presentation by Mr. B.R. Gujadhur, Managing Di...",NaN,mus_baboo_gujadhur_37884_english,English,CB websites
10530,https://www.bom.mu/media/speeches/hsbc-worksho...,https://www.bom.mu/sites/default/files/pdf/Abo...,Opening Remarks at the HSBC Workshop on Curren...,NaN,2003-10-30,Baboo R Gujadhur,Senior management,Male,Bank of Mauritius,MUS,HSBC Workshop on Currency Options and Structur...,NaN,mus_baboo_gujadhur_37924_english,English,CB websites
10531,https://www.bom.mu/media/speeches/regional-sem...,https://www.bom.mu/sites/default/files/pdf/Abo...,Regional Seminar on Non-bank Financial Institu...,NaN,2003-12-09,Baboo R Gujadhur,Senior management,Male,Bank of Mauritius,MUS,Regional Seminar on Non-bank financial Institu...,NaN,mus_baboo_gujadhur_37964_english,English,CB websites
10532,https://www.bom.mu/media/speeches/corporate-go...,https://www.bom.mu/sites/default/files/pdf/Abo...,Corporate Governance in the Banking Sector,NaN,2004-03-25,Baboo R Gujadhur,Senior management,Male,Bank of Mauritius,MUS,Corporate Governance in the Banking Sector Spe...,NaN,mus_baboo_gujadhur_38071_english,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27750,http://www.bis.org/review/r230606k.htm,http://www.bis.org/review/r230606k.pdf,Harvesh Seegolam: Address - G20/OECD Task Forc...,"Address by Mr Harvesh Seegolam, Governor of th...",2023-04-26,Harvesh Seegolam,Governor,Male,Bank of Mauritius,MUS,Harvesh Seegolam: Address - G20/OECD Task Forc...,NaN,r230606k,English,BIS
27751,http://www.bis.org/review/r230606l.htm,http://www.bis.org/review/r230606l.pdf,Harvesh Seegolam: The future of central bank m...,"Keynote address by Mr Harvesh Seegolam, Gover...",2023-04-26,Harvesh Seegolam,Governor,Male,Bank of Mauritius,MUS,Harvesh Seegolam: The future of central bank m...,NaN,r230606l,English,BIS
27753,http://www.bis.org/review/r230607c.htm,http://www.bis.org/review/r230607c.pdf,Harvesh Seegolam: Remarks - opening of the 3-d...,"Remarks by Mr Harvesh Seegolam, Governor of th...",2023-05-31,Harvesh Seegolam,Governor,Male,Bank of Mauritius,MUS,Harvesh Seegolam: Remarks - opening of the 3-d...,NaN,r230607c,English,BIS
27851,http://www.bis.org/review/r230731o.htm,http://www.bis.org/review/r230731o.pdf,Mardayah Kona Yerukunondu: Welcome address - l...,Welcome address of Mr Mardayah Kona Yerukunond...,2023-07-26,Mardayah Kona Yerukunondu,Deputy Governor,Male,Bank of Mauritius,MUS,Mardayah Kona Yerukunondu: Welcome address - l...,NaN,r230731o,English,BIS
27852,http://www.bis.org/review/r230731p.htm,http://www.bis.org/review/r230731p.pdf,Harvesh Seegolam: Remarks - launch of the Regi...,"Remarks by Mr Harvesh Seegolam, Governor of th...",2023-07-26,Harvesh Seegolam,Governor,Male,Bank of Mauritius,MUS,Harvesh Seegolam: Remarks - launch of the Regi...,NaN,r230731p,English,BIS

['Bangladesh Bank', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Mauritius
Bank of Greece

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7150,https://www.bankofgreece.gr/en/news-and-media/...,NaN,"Opening remarks at the ""GBA Session on Non-Per...",NaN,2019-09-11,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Opening remarks by Dimitris Malliaropulos, Chi...",NaN,grc_dimitris_malliaropulos_11_09_2019_english,English,CB websites
7151,https://www.bankofgreece.gr/en/news-and-media/...,NaN,"Opening Remarks at the IFFR Conference: ""Under...",NaN,2019-09-12,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Opening Remarks by Dimitris Malliaropulos, Chi...",NaN,grc_dimitris_malliaropulos_12_09_2019_english,English,CB websites
7152,https://www.bankofgreece.gr/enimerosi/grafeio-...,NaN,"Speech at the GetInvolved conference: ""The dec...",NaN,2019-12-13,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Speech by Dimitris Malliaropoulos, Chief Econo...",", & GetInvolved : ...",grc_dimitris_malliaropulos_13_12_2019_greek,Greek,CB websites
7153,https://www.bankofgreece.gr/en/news-and-media/...,NaN,Speech at the AHK Europa Konferenz: Remarks on...,NaN,2019-09-20,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Speech by Dimitris Malliaropulos, Chief Econom...",NaN,grc_dimitris_malliaropulos_20_09_2019_english,English,CB websites
7154,https://www.bankofgreece.gr/en/news-and-media/...,NaN,"Speech: ""Assessing the performance and regulat...",NaN,2010-02-04,Eleni D Dendrinou-Louri,Deputy Governor,Female,Bank of Greece,GRC,"Speech of the Dep. Governor E. Louri: ""Assessi...",NaN,grc_eleni_d_dendrinou-louri_04_02_2010_english,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27373,http://www.bis.org/review/r221122g.htm,http://www.bis.org/review/r221122g.pdf,Yannis Stournaras: Assessing the impact of dig...,"Speech by Mr Yannis Stournaras, Governor of th...",2022-10-31,Yannis Stournaras,Governor,Male,Bank of Greece,GRC,Yannis Stournaras: Assessing the impact of dig...,NaN,r221122g,English,BIS
27421,http://www.bis.org/review/r221212a.htm,http://www.bis.org/review/r221212a.pdf,Christina Papaconstantinou: Keynote speech - 6...,Keynote speech by Ms Christina Papaconstantino...,2022-12-09,Christina Papaconstantinou,Deputy Governor,Female,Bank of Greece,GRC,Christina Papaconstantinou: Keynote speech - 6...,NaN,r221212a,English,BIS
27478,http://www.bis.org/review/r230124k.htm,http://www.bis.org/review/r230124k.pdf,Yannis Stournaras: 2023 - a year of continued ...,"Speech by Mr Yannis Stournaras, Governor of th...",2023-01-12,Yannis Stournaras,Governor,Male,Bank of Greece,GRC,Yannis Stournaras: 2023 - a year of continued ...,NaN,r230124k,English,BIS
27997,https://www.bis.org/review/r231026g.htm,https://www.bis.org/review/r231026g.pdf,Yannis Stournaras: The Acropolis of Athens and...,"Speech by Mr Yannis Stournaras, Governor of th...",2023-10-25,Yannis Stournaras,Governor,Male,Bank of Greece,GRC,Yannis Stournaras: The Acropolis of Athens and...,NaN,r231026g,English,BIS
28687,https://www.bis.org/review/r990922b.pdf,https://www.bis.org/review/r990922b.pdf,Mr Garganas gives a speech on integrating Gree...,"Speech given by Mr Nicholas C Garganas, Deputy...",1999-09-18,Nicholas C Garganas,Deputy Governor,Male,Bank of Greece,GRC,Mr Garganas gives a speech on integrating Gree...,NaN,r990922b,English,BIS

['Bangladesh Bank', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Italy', 'Bank of Japan', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Greece
People's Bank of China

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1817,http://www.pbc.gov.cn/en/3688110/3688175/37079...,http://www.pbc.gov.cn/eportal/fileDir/image_pu...,Speech at the 18th International Conference on...,NaN,2014-09-25,Hu Xiaolian,Deputy Governor,Female,People's Bank of China,CHN,Speech at the 18th International Conference on...,NaN,chn_bankingsupervision-25082014,English,CB websites
1818,http://www.pbc.gov.cn/en/3688110/3688175/37079...,http://www.pbc.gov.cn/eportal/fileDir/image_pu...,The Multi-layered Feature of Capital Market,NaN,2013-08-31,Zhou Xiaochuan,Governor,Male,People's Bank of China,CHN,The Multi-layered Feature of Capital Market Go...,NaN,chn_capitalmarkets-31082013,English,CB websites
1819,http://www.pbc.gov.cn/en/3688110/3688175/37079...,http://www.pbc.gov.cn/eportal/fileDir/image_pu...,Speech at the 2013 Lujiazui Forum Governor Zho...,NaN,2013-06-28,Zhou Xiaochuan,Governor,Male,People's Bank of China,CHN,Speech at the 2013 Lujiazui Forum Governor Zho...,NaN,chn_lujiazuiforum-28062013,English,CB websites
1820,http://www.pbc.gov.cn/en/3688110/3688175/47264...,NaN,Moving Faster to Shore up Weaknesses in the So...,NaN,2022-11-21,Guo Shuqing,Deputy Governor,Male,People's Bank of China,CHN,Home News & Events Speeches To Read Chinese Ve...,NaN,chn_mr._guo_shuqing_44886,English,CB websites
1821,http://www.pbc.gov.cn/en/3688110/3688175/46944...,NaN,Transcript of Group Interview with Pan Gongshe...,NaN,2022-10-21,Pan Gongsheng,Deputy Governor,Male,People's Bank of China,CHN,Home News & Events Speeches Transcript of Grou...,NaN,chn_pan_gongsheng_44855,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28098,https://www.bis.org/review/r231204r.htm,https://www.bis.org/review/r231204r.pdf,Pan Gongsheng: Keynote speech - Hong Kong Mone...,"Keynote speech by Mr Pan Gongsheng, Deputy Gov...",2023-11-28,Pan Gongsheng,Deputy Governor,Male,People's Bank of China,CHN,Pan Gongsheng: Keynote speech - Hong Kong Mone...,NaN,r231204r,English,BIS
28179,https://www.bis.org/review/r970211a.pdf,https://www.bis.org/review/r970211a.pdf,Mr. Dai assesses the outlook for Hong Kong as ...,Speech by the Governor of the People's Bank of...,1996-09-30,Dai Xianglong,Governor,Male,People's Bank of China,CHN,Mr. Dai assesses the outlook for Hong Kong as ...,NaN,r970211a,English,BIS
28180,https://www.bis.org/review/r970211b.pdf,https://www.bis.org/review/r970211b.pdf,Mr. Dai looks at the possibilities of strength...,Speech by the Governor of the People's Bank of...,1996-11-13,Dai Xianglong,Governor,Male,People's Bank of China,CHN,Mr. Dai looks at the possibilities of strength...,NaN,r970211b,English,BIS
28181,https://www.bis.org/review/r970211c.pdf,https://www.bis.org/review/r970211c.pdf,Mr. Chen discusses monetary relations between ...,Speech by the Deputy Governor of the People's ...,1996-09-10,Chen Yuan,Deputy Governor,Male,People's Bank of China,CHN,Mr. Chen discusses monetary relations between ...,NaN,r970211c,English,BIS
28358,https://www.bis.org/review/r980202a.pdf,https://www.bis.org/review/r980202a.pdf,Statement by Mr. Dai Xianglong on the stabilit...,Statement by the Governor of the People's Bank...,1998-01-16,Dai Xianglong,Governor,Male,People's Bank of China,CHN,Statement by Mr. Dai Xianglong on the stabilit...,NaN,r980202a,English,BIS

['Bangladesh Bank', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/People's Bank of China
Bank of Zambia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
13257,https://www.bis.org/review/r030212f.pdf,https://www.bis.org/review/r030212f.pdf,The role of the banking sector in combating mo...,"A paper presented by Dr Caleb M Fundanga, Gove...",2003-01-23,Caleb M Fundanga,Governor,Male,Bank of Zambia,ZMB,Caleb M Fundanga: The role of the banking sect...,NaN,r030212f,English,BIS
13345,https://www.bis.org/review/r030516g.pdf,https://www.bis.org/review/r030516g.pdf,Regulatory framework for microfinance institut...,"Keynote address by Dr Denny Kalyalya, Deputy G...",2003-04-04,Denny H Kalyalya,Deputy Governor,Male,Bank of Zambia,ZMB,Denny Kalyalya: Regulatory framework for micro...,NaN,r030516g,English,BIS
13643,https://www.bis.org/review/r040317c.pdf,https://www.bis.org/review/r040317c.pdf,Media relations and key economic development i...,"Speech by Dr Caleb M Fundanga, Governor of the...",2004-03-04,Caleb M Fundanga,Governor,Male,Bank of Zambia,ZMB,Caleb M Fundanga: Media relations and key econ...,NaN,r040317c,English,BIS
13709,https://www.bis.org/review/r040512d.pdf,https://www.bis.org/review/r040512d.pdf,Recent economic developments in Zambia,"Speech by Dr Caleb M Fundanga, Governor of the...",2004-04-02,Caleb M Fundanga,Governor,Male,Bank of Zambia,ZMB,Caleb M Fundanga: Recent economic developments...,NaN,r040512d,English,BIS
13837,https://www.bis.org/review/r040908e.pdf,https://www.bis.org/review/r040908e.pdf,Achievements and accomplishments at the Bank o...,"Speech by Dr Caleb M Fundanga, Governor of the...",2004-08-05,Caleb M Fundanga,Governor,Male,Bank of Zambia,ZMB,Caleb M Fundanga: Achievements and accomplishm...,NaN,r040908e,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35020,NaN,https://www.boz.zm/PCF-dissemination.pdf,Speech at 2018 FPI & Investor Perceptions diss...,NaN,2018-12-05,Denny H Kalyalya,Governor,Male,Bank of Zambia,ZMB,2018 DISSEMINATION WORKSHOP ON FOREIGN PRIVATE...,NaN,zmb_pcf-dissemination,English,CB websites
35021,NaN,https://www.boz.zm/Speech_on_the_launch_of_the...,Official launch of the National Financial Switch,NaN,2019-06-19,Bwalya K E Ng'andu,Deputy Governor,Male,Bank of Zambia,ZMB,OFFICIAL LAUNCHING OF GOING LIVE OF THE NATION...,NaN,zmb_speech_on_the_launch_of_the_nfs_final,English,CB websites
35022,NaN,https://www.boz.zm/Speech.pdf,Speech on Credit Reporting Education and Aware...,NaN,2018-10-19,Denny H Kalyalya,Governor,Male,Bank of Zambia,ZMB,LAUNCH OF THE CREDIT REPORTING EDUCATION AND A...,NaN,zmb_speechoctober2018zambia,English,CB websites
35023,NaN,https://www.boz.zm/Talking_Notes_for_Deputy_Go...,Speech: Launch of the 2018 Digital Financial S...,NaN,2019-04-11,Bwalya K E Ng'andu,Deputy Governor,Male,Bank of Zambia,ZMB,"DR BWALYA NGANDU DEPUTY GOVERNOR - OPERATIONS,...",NaN,zmb_talking_notes_for_deputy_governor_launch_o...,English,CB websites
35024,NaN,https://www.boz.zm/WSD-Keynote.pdf,Keynote Speech at Launch of 2018 World Savings...,NaN,2018-10-31,Denny H Kalyalya,Governor,Male,Bank of Zambia,ZMB,LAUNCH OF THE 2018 WORLD SAVINGS DAY THEME: SA...,NaN,zmb_wsd-keynote,English,CB websites

['Bangladesh Bank', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Zambia
Bank Indonesia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7790,NaN,https://www.bi.go.id/id/publikasi/ruang-media/...,"Pidato Deputi Gubernur, Muliaman D. Hadad Pada...",NaN,2009-07-24,Muliaman Hadad,Deputy Governor,Male,Bank Indonesia,IDN,Deputy Governor's Welcome Pointers At the Inau...,Pointers Sambutan Deputi Gubernur Pada Peresmi...,idn_01c0cba28c3b4563921e396467cba249speech_mdh...,Indonesian,CB websites
7791,NaN,https://www.bi.go.id/en/publikasi/ruang-media/...,Keynote Speech SEACEN Payment System Directors...,NaN,2007-11-29,S Budi Rochadi,Deputy Governor,Male,Bank Indonesia,IDN,Keynote Speech SEACEN PAYMENT SYSTEM DIRECTORS...,NaN,idn_0c1bdd45878e4bd780a6a23db7700b70microsoftw...,English,CB websites
7792,NaN,https://www.bi.go.id/en/publikasi/ruang-media/...,Keynote Speech by Acting Governor of Bank Indo...,NaN,2009-06-25,Miranda S Goeltom,Deputy Governor,Female,Bank Indonesia,IDN,DEALING WITH GLOBAL FINANCIAL CRISES Welcome R...,NaN,idn_1374cbb223a740208cfcec725f954d1fspeech_msg...,English,CB websites
7793,NaN,https://www.bi.go.id/en/publikasi/ruang-media/...,Building A Better Financial Infrastructure In ...,NaN,2010-05-11,Budi Mulya,Deputy Governor,Male,Bank Indonesia,IDN,BUILDING A BETTER FINANCIAL INFRASTRUCTURE IN ...,NaN,idn_13c87dea062945f0abd237365236d06dspeech_swi...,English,CB websites
7794,NaN,https://www.bi.go.id/en/publikasi/ruang-media/...,Remarks of the Deputy of Bank Indonesia on the...,NaN,2007-03-01,S Budi Rochadi,Deputy Governor,Male,Bank Indonesia,IDN,Remarks of the Deputy of Bank Indonesia on the...,NaN,idn_163a6723fff94ccfa1f2e69911e18c73draftsambu...,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26080,https://www.bis.org/review/r201223n.htm,https://www.bis.org/review/r201223n.pdf,Synergize to build optimism for economic recovery,"Speech by Mr Perry Warjiyo, Governor of Bank I...",2020-12-03,Perry Warjiyo,Governor,Male,Bank Indonesia,IDN,BANK INDONESIAS ANNUAL MEETING 2020 1 BANK IND...,NaN,r201223n,English,BIS
27464,http://www.bis.org/review/r230111c.htm,http://www.bis.org/review/r230111c.pdf,Perry Warjiyo: Synergy and policy innovation -...,"Speech by Mr Perry Warjiyo, Governor of Bank I...",2022-11-30,Perry Warjiyo,Governor,Male,Bank Indonesia,IDN,TABLE OF CONTENT Synergy and Policy Innovation...,NaN,r230111c,English,BIS
28556,https://www.bis.org/review/r990211b.pdf,https://www.bis.org/review/r990211b.pdf,Mr Sabirin looks at how to create value with m...,Keynote address by the Governor of the Bank of...,1999-04-02,Syahril Sabirin,Governor,Male,Bank Indonesia,IDN,Mr Sabirin looks at how to create value with m...,NaN,r990211b,English,BIS
28581,https://www.bis.org/review/r990329b.pdf,https://www.bis.org/review/r990329b.pdf,Mr Sabirin discusses recent developments in th...,"Presentation by Dr Syahril Sabirin, Governor o...",1999-03-15,Syahril Sabirin,Governor,Male,Bank Indonesia,IDN,Mr Sabirin discusses recent developments in th...,NaN,r990329b,English,BIS
28591,https://www.bis.org/review/r990419b.pdf,https://www.bis.org/review/r990419b.pdf,Dr Sabirin talks about efforts to save Indones...,Presentation by the Governor of Bank Indonesia...,1999-04-07,Syrahil Sabirin,Governor,Male,Bank Indonesia,IDN,Dr. Sabirin talks about efforts to save Indone...,NaN,r990419b,English,BIS

['Bangladesh Bank', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank Indonesia
Bank of Korea

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9730,http://www.bok.or.kr/viewer/skin/doc.html?fn=F...,http://www.bok.or.kr/portal/cmmn/file/fileDown...,Remarks of all members of the Lee Il-hyung Com...,NaN,2018-03-19,Juyeol Lee,Governor,Male,Bank of Korea,KOR,Financial and Monetary Commission Press Confer...,"2018.3.19.() * . , ...",kor__2018.03.19_korean,Korean,CB websites
9731,http://www.bok.or.kr/viewer/skin/doc.html?fn=2...,http://www.bok.or.kr/portal/cmmn/file/fileDown...,"All remarks of Commissioner Ko Seung-beom ""Pre...",NaN,2018-07-18,Juyeol Lee,Governor,Male,Bank of Korea,KOR,Financial and Monetary Commissioner Press Conf...,2018.7.18.() * . . 5 1 2...,kor__2018.07.18_korean,Korean,CB websites
9732,http://www.bok.or.kr/viewer/skin/doc.html?fn=2...,http://www.bok.or.kr/portal/cmmn/file/fileDown...,Remarks of all members of the Lim-Won Committe...,NaN,2018-11-07,Juyeol Lee,Governor,Male,Bank of Korea,KOR,Financial and Monetary Commission Press Confer...,2018 11 7 * . 1. . ...,kor__2018.11.07_korean,Korean,CB websites
9733,http://www.bok.or.kr/viewer/skin/doc.html?fn=2...,http://www.bok.or.kr/portal/cmmn/file/fileDown...,Remarks of all members of the Lee Il-hyung Com...,NaN,2019-03-20,Juyeol Lee,Governor,Male,Bank of Korea,KOR,Financial and Monetary Commission Press Confer...,"2019.3.20.() ? * . , ...",kor__2019.03.20_korean,Korean,CB websites
9734,http://www.bok.or.kr/viewer/skin/doc.html?fn=2...,http://www.bok.or.kr/portal/cmmn/file/fileDown...,"Remarks of all the rookie members ""Press Confe...",NaN,2019-09-18,Juyeol Lee,Governor,Male,Bank of Korea,KOR,Financial and Monetary Commission Press Confer...,2019 9 18 * . ? 9 1 . ...,kor__2019.09.18_korean,Korean,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27459,http://www.bis.org/review/r230110h.htm,http://www.bis.org/review/r230110h.pdf,Chang Yong Rhee: New Year Speech,"New Year's address by Mr Chang Yong Rhee, Gove...",2023-01-02,Chang Yong Rhee,Governor,Male,Bank of Korea,KOR,Chang Yong Rhee: New Year Speech New Year's ad...,NaN,r230110h,English,BIS
27789,http://www.bis.org/review/r230628a.htm,http://www.bis.org/review/r230628a.pdf,Chang Yong Rhee: Welcoming remarks - Internati...,"Welcoming remarks by Mr Chang Yong Rhee, Gover...",2023-06-20,Chang Yong Rhee,Governor,Male,Bank of Korea,KOR,Chang Yong Rhee: Welcoming remarks - Internati...,NaN,r230628a,English,BIS
28475,https://www.bis.org/review/r981014g.pdf,https://www.bis.org/review/r981014g.pdf,moving on from the crisis' (Central Bank Arti...,"Address by the Governor of the Bank of Korea, ...",1998-10-08,Chol-Hwan Chon,Governor,Male,Bank of Korea,KOR,Mr. Chon speaks on the topic Korea: moving on ...,NaN,r981014g,English,BIS
28510,https://www.bis.org/review/r981113a.pdf,https://www.bis.org/review/r981113a.pdf,Mr. Chon reports on recent economic trends in ...,"Speech by the Governor of the Bank of Korea, M...",1998-11-04,Chol-Hwan Chon,Governor,Male,Bank of Korea,KOR,Mr. Chon reports on recent economic trends in ...,NaN,r981113a,English,BIS
28727,https://www.bis.org/review/r991103b.pdf,https://www.bis.org/review/r991103b.pdf,Mr Chon speaks on the topic of restructuring a...,"Speech given by Mr Chol-Hwan Chon, Governor of...",1999-10-12,Chol-Hwan Chon,Governor,Male,Bank of Korea,KOR,Mr Chon speaks on the topic of restructuring a...,NaN,r991103b,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Korea
Central Bank of Iceland

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
8460,https://www.sedlabanki.is/utgefid-efni/raedur/...,NaN,Statement regarding false claims made by two b...,NaN,2019-03-01,Mar Gudmundsson,Governor,Male,Central Bank of Iceland,ISL,01.03.2019 Statement regarding false claims ma...,01.03.2019 Yfirlsing vegna rangra fullyringa t...,isl_01_03_2019_icelandic,Icelandic,CB websites
8461,https://www.sedlabanki.is/utgefid-efni/raedur/...,https://www.sedlabanki.is/lisalib/getfile.aspx...,Rebuilding the Icelandic economy,NaN,2009-04-01,Svein Harald ygard,Governor,Male,Central Bank of Iceland,ISL,31. March 2009 Rebuilding the Icelandic econom...,31. mars 2009 Endurreisn slensks efnahagslfs s...,isl_01_04_2009_icelandic,Icelandic,CB websites
8462,https://www.sedlabanki.is/utgefid-efni/raedur/...,NaN,Article by Chief Economist at the Central Bank...,NaN,2013-03-02,rarinn G Ptursson,Senior management,Male,Central Bank of Iceland,ISL,"02.03.2013 Article by orarinn G. Petursson, Ch...","02.03.2013 Grein rarins G. Pturssonar, aalhagf...",isl_02_03_2013_icelandic,Icelandic,CB websites
8463,https://www.sedlabanki.is/utgefid-efni/raedur/...,NaN,Monetary policy and Icelandic krona,NaN,2003-04-02,Birgir Isleifur Gunnarsson,Governor,Male,Central Bank of Iceland,ISL,02.04.2003 Monetary policy and Icelandic krona...,02.04.2003 Peningastefnan og slenska krnan Bir...,isl_02_04_2003_icelandic,Icelandic,CB websites
8464,https://www.sedlabanki.is/utgefid-efni/raedur/...,NaN,Governor's introductory remarks at a meeting o...,NaN,2019-04-02,Mar Gudmundsson,Governor,Male,Central Bank of Iceland,ISL,02.04.2019 Governor's introductory remarks at ...,02.04.2019 Inngangsor selabankastjra fundi st...,isl_02_04_2019_icelandic,Icelandic,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27021,http://www.bis.org/review/r220629e.htm,http://www.bis.org/review/r220629e.pdf,sgeir Jnsson: Speech 61st Annual Meeting of t...,"Speech by Mr sgeir Jnsson, Governor of the Cen...",2022-03-31,sgeir Jnsson,Governor,Male,Central Bank of Iceland,ISL,31 March 2022 Governor's speech at the 61st An...,NaN,r220629e,English,BIS
27674,http://www.bis.org/review/r230503c.htm,http://www.bis.org/review/r230503c.pdf,sgeir Jnsson: Speech 62nd Annual Meeting of t...,"Speech by Mr sgeir Jnsson, Governor of the Cen...",2023-03-30,sgeir Jnsson,Governor,Male,Central Bank of Iceland,ISL,Asgeir Jonsson: Speech - 62nd Annual Meeting o...,NaN,r230503c,English,BIS
27675,http://www.bis.org/review/r230503d.htm,http://www.bis.org/review/r230503d.pdf,Rannveig Sigurardttir: Monetary and fiscal dim...,"Keynote speech by Ms Rannveig Sigurardttir, De...",2023-04-13,Rannveig Sigurdardttir,Deputy Governor,Female,Central Bank of Iceland,ISL,13 April 2023 Monetary and Fiscal Dimensions o...,NaN,r230503d,English,BIS
28424,https://www.bis.org/review/r980518r.pdf,https://www.bis.org/review/r980518r.pdf,Mr. Gunnarsson reports on some aspects of econ...,Address by the Governor of the Central Bank of...,1998-03-31,Birgir Isleifur Gunnarsson,Governor,Male,Central Bank of Iceland,ISL,Mr. Gunnarsson reports on some aspects of econ...,NaN,r980518r,English,BIS
28720,https://www.bis.org/review/r991029a.pdf,https://www.bis.org/review/r991029a.pdf,Mr Gunnarsson touches on a number of topics in...,"Presentation by Mr Birgir sleifur Gunnarsson, ...",1999-10-22,Birgir Isleifur Gunnarsson,Governor,Male,Central Bank of Iceland,ISL,Mr Gunnarsson touches on a number of topics in...,NaN,r991029a,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Iceland
National Bank of Serbia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
13949,https://www.bis.org/review/r041110c.pdf,https://www.bis.org/review/r041110c.pdf,"Monetary policy, current economic movements an...","Speech by Mr Radovan Jelasic, Governor of the ...",2004-10-29,Radovan Jelasic,Governor,Male,National Bank of Serbia,SRB,"Radovan Jelasic: Monetary policy, current econ...",NaN,r041110c,English,BIS
14154,https://www.bis.org/review/r050323h.pdf,https://www.bis.org/review/r050323h.pdf,121-year anniversary of the National Bank of S...,"Speech by Mr Radovan Jelasic, Governor of the ...",2005-03-16,Radovan Jelasic,Governor,Male,National Bank of Serbia,SRB,Radovan Jelasic: 121-year anniversary of the N...,NaN,r050323h,English,BIS
14975,https://www.bis.org/review/r060911d.pdf,https://www.bis.org/review/r060911d.pdf,Overall goals of the National Bank of Serbia,"Speech by Mr Radovan Jelasic, Governor of the ...",2006-07-10,Radovan Jelasic,Governor,Male,National Bank of Serbia,SRB,Radovan Jelasic: Overall goals of the National...,NaN,r060911d,English,BIS
15064,https://www.bis.org/review/r061025e.pdf,https://www.bis.org/review/r061025e.pdf,Dinar products and declining interest rates in...,"Speech by Mr Radovan Jelaic, Governor of the N...",2006-10-18,Radovan Jelasic,Governor,Male,National Bank of Serbia,SRB,Radovan Jelasi: Dinar products and declining i...,NaN,r061025e,English,BIS
15065,https://www.bis.org/review/r061025f.pdf,https://www.bis.org/review/r061025f.pdf,The National Bank of Serbia accomplishing it...,"Speech by Mr Radovan Jelaic, Governor of the N...",2006-10-10,Radovan Jelasic,Governor,Male,National Bank of Serbia,SRB,Radovan Jelasi: The National Bank of Serbia a...,NaN,r061025f,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29682,https://www.nbs.rs/export/sites/NBS_site/docum...,https://www.nbs.rs/export/sites/NBS_site/docum...,Speech at the presentation of the Inflation Re...,NaN,2021-08-18,Savo Jakovljevi,Senior management,Male,National Bank of Serbia,SRB,NATIONAL BANK OF SERBIA Speech at the presenta...,NaN,srb_44426_savo jakovljevic,English,CB websites
29683,https://nbs.rs/en/scripts/showcontent/index.ht...,Address by the NBS Governor at official openin...,Address at official opening of China Financial...,NaN,2021-09-04,Jorgovanka Tabakovi,Governor,Female,National Bank of Serbia,SRB,04/09/2021 Address by the NBS Governor at offi...,NaN,srb_44443_jorgovanka tabakovic,English,CB websites
29684,https://www.nbs.rs/export/sites/NBS_site/docum...,https://www.nbs.rs/export/sites/NBS_site/docum...,Speech at the presentation of the Inflation Re...,NaN,2021-11-17,Savo Jakovljevi,Senior management,Male,National Bank of Serbia,SRB,NATIONAL BANK OF SERBIA Speech at the presenta...,NaN,srb_44517_savo jakovljevic,English,CB websites
29685,https://www.nbs.rs/export/sites/NBS_site/docum...,NaN,Speech at the presentation of the Inflation Re...,NaN,2022-02-18,Savo Jakovljevi,Senior management,Male,National Bank of Serbia,SRB,NATIONAL BANK OF SERBIA Speech at the presenta...,NaN,srb_44610_savo jakovljevic,English,CB websites
29686,https://nbs.rs/en/scripts/showcontent/index.ht...,NaN,Address of Vice-Governor Dragana Stani at the ...,NaN,2023-03-16,Dragana Stani,Deputy Governor,Female,National Bank of Serbia,SRB,National Bank of Serbia 16/03/2023 Address of ...,NaN,srb_dragana_stanic_45001,English,CB websites

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Serbia
National Bank of the Republic of North Macedonia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10364,https://www.nbrm.mk/ns-newsarticle-obrakjanjie...,NaN,Speech to the Parliament of the Republic of Ma...,NaN,1998-04-01,Ljube Trpeski,Governor,Male,National Bank of the Republic of North Macedonia,MKD,Address by The Governor of the National Bank o...,"- , , 1998 - , ...",mkd_35886_ljube_trpeski_macedonian,Macedonian,CB websites
10365,https://www.nbrm.mk/ns-newsarticle-obrakjanjie...,NaN,55-year-old IMF and World Bank Assembly in Prague,NaN,2000-09-01,Ljube Trpeski,Governor,Male,National Bank of the Republic of North Macedonia,MKD,Address by The Governor of the National Bank o...,"- 55 , 2000 - ...",mkd_36770_ljube_trpeski_macedonian,Macedonian,CB websites
10366,https://www.nbrm.mk/ns-newsarticle-pozdravien_...,NaN,"Canvas reform seminar, Ohrid",NaN,2001-02-11,Ljube Trpeski,Governor,Male,National Bank of the Republic of North Macedonia,MKD,Welcome speech by The Governor of the National...,"- , , 09-11.02.2001 ...",mkd_36933_ljube_trpeski_macedonian,Macedonian,CB websites
10367,https://www.nbrm.mk/ns-newsarticle-ghovor_na_g...,NaN,Forum of the Business Bank,NaN,2003-02-27,Ljube Trpeski,Governor,Male,National Bank of the Republic of North Macedonia,MKD,Speech by The Governor of the National Bank of...,"- , 27.02.2003 - ...",mkd_37679_ljube_trpeski_macedonian,Macedonian,CB websites
10368,https://www.nbrm.mk/ns-newsarticle-pozdravien_...,NaN,Conference of Clearing Institutions,NaN,2003-09-20,Ljube Trpeski,Governor,Male,National Bank of the Republic of North Macedonia,MKD,Welcome speech of the National Bank of the Rep...,"- 8- , 18-20.09.2003 -...",mkd_37884_ljube_trpeski_macedonian,Macedonian,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27358,https://www.bis.org/review/r221121c.htm,https://www.bis.org/review/r221121c.pdf,Speech - National Bank of the Republic of Nort...,"Speech by Ms Anita Angelovska Bezhoska, Govern...",2022-04-28,Anita Angelovska Bezhoska,Governor,Female,National Bank of the Republic of North Macedonia,MKD,Anita Angelovska Bezhoska: Speech - National B...,NaN,r221121c,English,BIS
27653,http://www.bis.org/review/r230425p.htm,http://www.bis.org/review/r230425p.pdf,Anita Angelovska Bezhoska: Welcoming remarks -...,Welcoming remarks by Ms Anita Angelovska Bezho...,2023-03-22,Anita Angelovska Bezhoska,Deputy Governor,Female,National Bank of the Republic of North Macedonia,MKD,Anita Angelovska Bezhoska: Welcoming remarks -...,NaN,r230425p,English,BIS
27956,https://www.bis.org/review/r231011a.htm,https://www.bis.org/review/r231011a.pdf,Anita Angelovska Bezhoska: Opening speech 9th...,Opening speech by Ms Anita Angelovska Bezhoska...,2023-09-29,Anita Angelovska Bezhoska,Deputy Governor,Female,National Bank of the Republic of North Macedonia,MKD,Anita Angelovska Bezhoska: Opening speech - 9t...,NaN,r231011a,English,BIS
27957,https://www.bis.org/review/r231011b.htm,https://www.bis.org/review/r231011b.pdf,Anita Angelovska Bezhoska: International coope...,"Remarks by Ms Anita Angelovska Bezhoska, Gover...",2023-09-14,Anita Angelovska Bezhoska,Deputy Governor,Female,National Bank of the Republic of North Macedonia,MKD,Anita Angelovska Bezhoska: International coope...,NaN,r231011b,English,BIS
27958,https://www.bis.org/review/r231011c.htm,https://www.bis.org/review/r231011c.pdf,Shaping payments innovation,"Speech by Ms Anita Angelovska Bezhoska, Govern...",2023-06-30,Anita Angelovska Bezhoska,Governor,Female,National Bank of the Republic of North Macedonia,MKD,Anita Angelovska Bezhoska: Shaping payments in...,NaN,r231011c,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Serbia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of the Republic of North Macedonia
Reserve Bank of Fiji

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
6284,https://www.rbf.gov.fj/opening-address-at-the-...,/,Opening Address At The Commonwealth Secretaria...,Opening Address at the Commonwealth Secretaria...,2006-03-27,Savenaca Narube,Governor,Male,Reserve Bank of Fiji,FJI,Using CS-DRMS 2000 for Proactive Debt Manageme...,NaN,fji_38803_savenaca narube,English,CB websites
6285,https://www.rbf.gov.fj/acting-dgs-induction-sp...,rbf.gov.fj-Acting Deputy Governers.pdf,Acting Deputy Governors Induction Speech,Acting Deputy Governers Address Staff Inductio...,2008-10-31,Inia Naiyaga,Deputy Governor,Male,Reserve Bank of Fiji,FJI,Acting Deputy Governers B rbf.gov.fj/acting-dg...,NaN,fji_39752_,English,CB websites
6286,https://www.rbf.gov.fj/presentation-to-public-...,rbf.gov.fj-Presentation To Public And Private ...,Presentation To Public And Private Sector Cons...,Presentation To Public And Private Sector Cons...,2009-09-17,Sada S Reddy,Governor,Male,Reserve Bank of Fiji,FJI,Presentation To Public And Private Sector Cons...,NaN,fji_40073_sada reddy,English,CB websites
6287,https://www.rbf.gov.fj/fiji-economy-update-201...,rbf.gov.fj-Fiji Economy Update 2010 Address by...,Fiji Economy: It is time to Build Confidence B...,Fiji Economy Update 2010 Address by Deputy Go...,2010-07-01,Barry Whiteside,Governor,Male,Reserve Bank of Fiji,FJI,Fiji Economy Update - 2010 Address by Deputy G...,NaN,fji_40360_2_barry whiteside,English,CB websites
6288,https://www.rbf.gov.fj/fiji-economy-it-is-time...,rbf.gov.fj-Fiji Economy It is time to Build Co...,A Response to the above Paper by Prof. Biman P...,Fiji Economy: It is time to Build Confidence B...,2010-07-01,Barry Whiteside,Governor,Male,Reserve Bank of Fiji,FJI,Fiji Economy: It is time to Build Confidence B...,NaN,fji_40360_barry whiteside,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25505,https://www.bis.org/review/r200130d.htm,https://www.bis.org/review/r200130d.pdf,The Fijian insurance industry,"Presentation by Mr Ariff Ali, Governor of the ...",2020-01-16,Ariff Ali,Governor,Male,Reserve Bank of Fiji,FJI,PRESENTATION TO THE STANDING COMMITTEE ON ECON...,NaN,r200130d,English,BIS
26064,https://www.bis.org/review/r201222h.htm,https://www.bis.org/review/r201222h.pdf,Launch of the Pacific Insurance and Climate Ad...,"Special address by Mr Ariff Ali, Governor of t...",2020-12-02,Ariff Ali,Governor,Male,Reserve Bank of Fiji,FJI,Ariff Ali: Launch of the Pacific Insurance and...,NaN,r201222h,English,BIS
26070,https://www.bis.org/review/r201223d.htm,https://www.bis.org/review/r201223d.pdf,"Climate change, financial inclusion and inclus...","Welcoming remarks by Mr Ariff Ali, Governor of...",2020-10-19,Ariff Ali,Governor,Male,Reserve Bank of Fiji,FJI,"Ariff Ali: Climate change, financial inclusion...",NaN,r201223d,English,BIS
26071,https://www.bis.org/review/r201223e.htm,https://www.bis.org/review/r201223e.pdf,Designing Inclusive Green Finance policies and...,"Closing remarks by Mr Esala Masitabua, Deputy ...",2020-10-21,Esala Masitabua,Deputy Governor,Male,Reserve Bank of Fiji,FJI,Esala Masitabua: Designing Inclusive Green Fin...,NaN,r201223e,English,BIS
26072,https://www.bis.org/review/r201223f.htm,https://www.bis.org/review/r201223f.pdf,Updates on Fiji's economy and monetary policy ...,"Address by Mr Ariff Ali, Governor of the Reser...",2020-10-30,Ariff Ali,Governor,Male,Reserve Bank of Fiji,FJI,Ariff Ali: Updates on Fijis economy and moneta...,NaN,r201223f,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Reserve Bank of Fiji
Bank of Ghana

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7044,https://www.bog.gov.gh/speeches/governors-open...,https://www.bog.gov.gh/wp-content/uploads/2022...,Opening Remarks at AACB Seminar on Payment Sys...,NaN,2005-07-26,Paul A Acquah,Governor,Male,Bank of Ghana,GHA,ASSOCIATION OF AFRICAN CENTRAL BANKS SEMINAR O...,NaN,gha_38559_paul_a_acquah,English,CB websites
7045,https://www.bog.gov.gh/speeches/governors-spee...,https://www.bog.gov.gh/wp-content/uploads/2022...,Speech at the Maiden Annual Lecture of the ACAMB,NaN,2005-08-12,Paul A Acquah,Governor,Male,Bank of Ghana,GHA,MAIDEN ANNUAL LECTURE OF THE ASSOCIATION OF CO...,NaN,gha_38576_paul_a_acquah,English,CB websites
7046,https://www.bog.gov.gh/speeches/governors-spee...,https://www.bog.gov.gh/wp-content/uploads/2022...,Speech at the 40th Anniversary of Bank of Maur...,NaN,2007-12-04,Paul A Acquah,Governor,Male,Bank of Ghana,GHA,40th ANNIVERSARY OF BANK OF MAURITIUS LECTURE ...,NaN,gha_39420_paul_a_acquah,English,CB websites
7047,https://www.bog.gov.gh/speeches/governors-keyn...,https://www.bog.gov.gh/wp-content/uploads/2022...,Keynote Address at the Ghana Association of Ba...,NaN,2011-07-29,Kwesi Bekoe Amissah-Arthur,Governor,Male,Bank of Ghana,GHA,GHANA ASSOCIATION OF BANKERS CONDUCT OF BUSINE...,NaN,gha_40753_k_b_amissah-arthur,English,CB websites
7048,https://www.bog.gov.gh/speeches/first-deputy-g...,https://www.bog.gov.gh/wp-content/uploads/2022...,First Deputy Keynote Address at Regional Cours...,NaN,2011-09-12,Henry A Kofi Wampah,Deputy Governor,Male,Bank of Ghana,GHA,OPENING CEREMONY OF THE REGIONAL COURSE ON MAC...,NaN,gha_40798_h_a_k_wampah,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25837,https://www.bis.org/review/r201002g.htm,https://www.bis.org/review/r201002g.pdf,Integrating gender considerations into COVID-1...,"Keynote address by Dr Ernest Addison, Governor...",2020-09-14,Ernest Addison,Governor,Male,Bank of Ghana,GHA,BA NA NK OF GHA E S T. 1 95 7 AFI-BOG WEBINAR ...,NaN,r201002g,English,BIS
26076,https://www.bis.org/review/r201223j.htm,https://www.bis.org/review/r201223j.pdf,Digitization of the Afro-Asian Small and Mediu...,"Keynote address by Dr Ernest Addison, Governor...",2020-12-07,Ernest Addison,Governor,Male,Bank of Ghana,GHA,SINGAPORE FINTECH FESTIVAL 2020 KEYNOTE ADDRES...,NaN,r201223j,English,BIS
26077,https://www.bis.org/review/r201223k.htm,https://www.bis.org/review/r201223k.pdf,"Pandemic, the economy and outlook","Speech by Dr Ernest Addison, Governor of the B...",2020-12-17,Ernest Addison,Governor,Male,Bank of Ghana,GHA,"PANDEMIC, THE ECONOMY AND OUTLOOK UNIVERSITY O...",NaN,r201223k,English,BIS
26289,https://www.bis.org/review/r210504d.htm,https://www.bis.org/review/r210504d.pdf,Launch of the 20th anniversary celebration of ...,"Goodwill message by Dr Maxwell Opoku-Afari, Fi...",2021-04-23,Maxwell Opoku-Afari,Deputy Governor,Male,Bank of Ghana,GHA,BA NA NK OF GHA E S T. 1 95 7 GOODWILL MESSAGE...,NaN,r210504d,English,BIS
27119,http://www.bis.org/review/r220913b.htm,http://www.bis.org/review/r220913b.pdf,Elsie Addo Awadzi: Nurturing resilience - adop...,"Remarks by Ms Elsie Addo Awadzi, Second Deputy...",2022-08-31,Elsie Addo Awadzi,Deputy Governor,Female,Bank of Ghana,GHA,LAUNCH OF THE 75TH ANNIVERSARY CELEBRATION OF ...,NaN,r220913b,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Ghana
Bank of Russia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
15520,https://www.bis.org/review/r070608d.pdf,https://www.bis.org/review/r070608d.pdf,The macroeconomic situation and monetary polic...,"Speech by Dr Sergey Ignatiev, Chairman of the ...",2007-06-04,Sergey Ignatiev,Governor,Male,Bank of Russia,RUS,Sergey Ignatiev: The macroeconomic situation a...,NaN,r070608d,English,BIS
21412,https://www.bis.org/review/r141121f.htm,https://www.bis.org/review/r141121f.pdf,Guidelines for the Single State Monetary Polic...,"Presentation by Ms Elvira Nabiullina, Governor...",2014-10-13,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Elvira Nabiullina: Guidelines for the Single S...,NaN,r141121f,English,BIS
21545,https://www.bis.org/review/r150205d.htm,https://www.bis.org/review/r150205d.pdf,The Russian economic situation and Bank of Rus...,"Statement by Ms Elvira Nabiullina, Governor of...",2014-12-11,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Elvira Nabiullina: The Russian economic situat...,NaN,r150205d,English,BIS
21732,https://www.bis.org/review/r150507d.htm,https://www.bis.org/review/r150507d.pdf,Recent Russian economic developments and Bank ...,"Statement by Ms Elvira Nabiullina, Governor of...",2015-03-13,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Elvira Nabiullina: Recent Russian economic dev...,NaN,r150507d,English,BIS
21942,https://www.bis.org/review/r150901c.htm,https://www.bis.org/review/r150901c.pdf,Current economic environment and monetary poli...,"Statement by Ms Elvira Nabiullina, Governor of...",2015-06-16,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Elvira Nabiullina: Current economic environmen...,NaN,r150901c,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28923,https://cbr.ru/press/event/?id=5216,NaN,Speech by The Governor of the Bank of Russia a...,NaN,2015-04-07,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Speech by the Governor of the Bank E.S. Nabiul...,() () 8 800 300-30-00 .. .. XXVI ...,rus_cbr_press_event_id=5216,Russian,CB websites
28924,https://cbr.ru/press/event/?id=5222,NaN,Speech at the discussion at the American Chamb...,NaN,2015-09-24,Ksenia Yudaeva,Deputy Governor,Female,Bank of Russia,RUS,Speech by the First Deputy Chairman of the Ban...,"() . , 12, , 107016 8 800 300-30-00 .. ...",rus_cbr_press_event_id=5222,Russian,CB websites
28925,https://cbr.ru/press/event/?id=71,NaN,Statement following the meeting of the Board o...,NaN,2015-12-11,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Statement by the Governor of the Bank of Russi...,() () 8 800 300-30-00 .. 11 ...,rus_cbr_press_event_id=71,Russian,CB websites
28926,https://cbr.ru/press/event/?id=726,NaN,Bank of Russia Governor spoke at the Internati...,NaN,2016-11-14,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Bank of Russia Governor Elvira Nabiullina spok...,() () 8 800 300-30-00 .. : ...,rus_cbr_press_event_id=726,Russian,CB websites
28927,https://cbr.ru/press/event/?id=9745,NaN,Speech at a meeting with regional banks at the...,NaN,2021-04-12,Elvira Nabiullina,Governor,Female,Bank of Russia,RUS,Speech by Elvira Nabiullina at a meeting with ...,() () 8 800 300-30-00 .. 12 ...,rus_cbr_press_event_id=9745,Russian,CB websites

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Russia
Central Bank of Barbados

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1206,http://www.centralbank.org.bb/news/article/941...,NaN,50 Years of Bilateral Relations Between Barbad...,"Remarks by Central Bank of Barbados Governor, ...",2018-08-13,Cleviston Haynes,Governor,Male,Central Bank of Barbados,BRB,"Central Bank of Barbados , 150 Years of Bilate...",NaN,brb_50_years_of_bilateral_relations_between_ba...,English,CB websites
1207,http://www.centralbank.org.bb/news/article/930...,NaN,Pays Tribute to Sir Courtney,"Remarks by Novaline Brewster, Chief, Corporate...",2017-12-18,Cleviston Haynes,Governor,Male,Central Bank of Barbados,BRB,Acting Governor Cleviston Haynes Pays Tribute ...,NaN,brb_acting_governor_cleviston_haynes_pays_trib...,English,CB websites
1208,http://www.centralbank.org.bb/news/article/921...,NaN,Welcome Remarks at the 2017 Domestic Financial...,"Welcome remarks by Michelle Doyle-Lowe, Deputy...",2017-05-05,Cleviston Haynes,Governor,Male,Central Bank of Barbados,BRB,Acting Governor Haynes' Welcome Remarks at the...,NaN,brb_acting_governor_haynes_welcome_remarks_at_...,English,CB websites
1209,http://www.centralbank.org.bb/news/article/993...,NaN,Adapting to Economic Shocks,Remarks by Central Bank of Barbados Governor C...,2020-07-15,Cleviston Haynes,Governor,Male,Central Bank of Barbados,BRB,Adapting to Economic Shocks Author(s): Central...,NaN,brb_adapting_to_economic_shocks,English,CB websites
1210,http://www.centralbank.org.bb/news/article/760...,NaN,Address at the Barbados Association of Office ...,Remarks Delivered By The Honourable John Boyce...,2011-02-24,DeLisle Worrell,Governor,Male,Central Bank of Barbados,BRB,Address by Dr. DeLisle Worrell at the Barbados...,NaN,brb_address_by_dr_delisle_worrell_at_the_barba...,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27655,http://www.bis.org/review/r230425r.htm,http://www.bis.org/review/r230425r.pdf,Kevin Greenidge: Continuing the legacy of success,"Remarks by Dr Kevin Greenidge, Governor of the...",2023-04-06,Kevin Greenidge,Governor,Male,Central Bank of Barbados,BRB,Kevin Greenidge: Continuing the legacy of succ...,NaN,r230425r,English,BIS
27738,http://www.bis.org/review/r230601u.htm,http://www.bis.org/review/r230601u.pdf,Kevin Greenidge: The arts are critical to sust...,"Remarks by Dr Kevin Greenidge, Governor of the...",2023-05-26,Kevin Greenidge,Governor,Male,Central Bank of Barbados,BRB,Kevin Greenidge: The arts are critical to sust...,NaN,r230601u,English,BIS
27849,http://www.bis.org/review/r230731i.htm,http://www.bis.org/review/r230731i.pdf,Kevin Greenidge: Research is the compass that ...,"Remarks by Dr Kevin Greenidge, Governor of the...",2023-07-25,Kevin Greenidge,Governor,Male,Central Bank of Barbados,BRB,Kevin Greenidge: Research is the compass that ...,NaN,r230731i,English,BIS
28141,https://www.bis.org/review/r231218g.htm,https://www.bis.org/review/r231218g.pdf,Charting the course for sustainable and inclus...,"Remarks by Dr Kevin Greenidge, Governor of the...",2023-10-04,Dr Kevin Greenidge,Governor,Male,Central Bank of Barbados,BRB,Kevin Greenidge: Charting the course for susta...,NaN,r231218g,English,BIS
28142,https://www.bis.org/review/r231218h.htm,https://www.bis.org/review/r231218h.pdf,"Kevin Greenidge: Barbados, a safe haven in a w...","Remarks by Dr Kevin Greenidge, Governor of the...",2023-12-04,Kevin Greenidge,Governor,Male,Central Bank of Barbados,BRB,"Kevin Greenidge: Barbados, a safe haven in a w...",NaN,r231218h,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Barbados
National Bank of Denmark

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2844,https://www.nationalbanken.dk/da/presse/Docume...,https://www.nationalbanken.dk/da/presse/Docume...,Comment on the housing tax agreement,NaN,2017-05-03,Lars Rohde,Governor,Male,National Bank of Denmark,DNK,OPINION DANMARKS NATIONALBANK'S COMMENT ON THE...,UDTALELSE NATIONALBANKENS KOMMENTAR TIL BOLIGS...,dnk_17-05-03_udtalelse,Danish,CB websites
2845,https://www.nationalbanken.dk/da/presse/Docume...,https://www.nationalbanken.dk/da/presse/Docume...,Implementation of the recommendations of the C...,NaN,2013-05-22,Lars Rohde,Governor,Male,National Bank of Denmark,DNK,DANMARKS NATIONALBANK Business - and Away tm...,DANMARKS NATIONALBANK Erhverv - og Vk tmini ...,dnk_brev_til_erhvervs-_og_v_c3_a6kstministeren,Danish,CB websites
2846,https://www.nationalbanken.dk/da/viden-og-nyhe...,https://www.nationalbanken.dk/media/kf4pw5u5/n...,Speech by Governor Christian Kettel Thomsen at...,NaN,2023-05-12,Christian Kettel Thomsen,Governor,Male,National Bank of Denmark,DNK,SPEECH Governor Christian Kettel Thomsen's spe...,TALE Nationalbankdirektr Christian Kettel Thom...,dnk_christian_kettel_thomsen_45058,Danish,CB websites
2847,https://www.nationalbanken.dk/da/presse/Docume...,https://www.nationalbanken.dk/da/presse/Docume...,Speech to the Confederation of Danish Industry...,NaN,2008-08-28,Nils Bernstein,Governor,Male,National Bank of Denmark,DNK,The spoken word applies. Confederation of Dani...,Det talte ord glder. Dansk Industris erhvervsp...,dnk_dansk_industri_nbe_08_25_09,Danish,CB websites
2848,https://www.nationalbanken.dk/da/presse/Docume...,https://www.nationalbanken.dk/da/presse/Docume...,Declining borrowing need in Europe,NaN,2010-08-04,Jens Thomsen,Governor,Male,National Bank of Denmark,DNK,Declining borrowing need in Europe Speech by J...,NaN,dnk_declining_borrowing_need_in_europe,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27273,http://www.bis.org/review/r221102b.htm,http://www.bis.org/review/r221102b.pdf,Signe Krogstrup: Speech - National Bank of Den...,"Speech by Ms Signe Krogstrup, Governor of the ...",2022-10-31,Signe Krogstrup,Governor,Female,National Bank of Denmark,DNK,SPEECH Governor Signe Krogstrup's speech at Da...,NaN,r221102b,English,BIS
27416,http://www.bis.org/review/r221205d.htm,http://www.bis.org/review/r221205d.pdf,"Lars Rohde: Liquidity, economic dampening and ...","Speech by Mr Lars Rohde, Governor of the Natio...",2022-12-05,Lars Rohde,Governor,Male,National Bank of Denmark,DNK,"Lars Rohde: Liquidity, economic dampening and ...",NaN,r221205d,English,BIS
27564,http://www.bis.org/review/r230313d.htm,http://www.bis.org/review/r230313d.pdf,Signe Krogstrup: New types of digital money,"Speech by Ms Signe Krogstrup, Governor of the ...",2023-03-09,Signe Krogstrup,Governor,Female,National Bank of Denmark,DNK,SPEECH Governor Signe Krogstrup's speech at th...,NaN,r230313d,English,BIS
27689,http://www.bis.org/review/r230511c.htm,http://www.bis.org/review/r230511c.pdf,Signe Krogstrup: Financing the energy transition,"Speech by Ms Signe Krogstrup, Governor of the ...",2023-05-11,Signe Krogstrup,Governor,Female,National Bank of Denmark,DNK,SPEECH Governor Signe Krogstrup's speech at No...,NaN,r230511c,English,BIS
28134,https://www.bis.org/review/r231215g.htm,https://www.bis.org/review/r231215g.pdf,"Christian Kettel Thomsen: Danish economy, fina...","Speech by Mr Christian Kettel Thomsen, Governo...",2023-12-04,Christian Kettel Thomsen,Governor,Male,National Bank of Denmark,DNK,"Christian Kettel Thomsen: Danish economy, fina...",NaN,r231215g,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Denmark
Bank of Israel

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
8558,https://www.boi.org.il/he/NewsAndPublications/...,https://www.boi.org.il/he/NewsAndPublications/...,Remarks at the 2017 Institutional Investors Co...,NaN,2017-12-03,Nadine Baudot-Trajtenberg,Deputy Governor,Female,Bank of Israel,ISR,Remarks by the Deputy Governor of the Bank of ...,"- | 03/12/2017 2017 ."" "" "" ...",isr_03122017,Hebrew,CB websites
8559,https://www.boi.org.il/he/NewsAndPublications/...,https://www.boi.org.il/he/NewsAndPublications/...,Remarks at the Annual Conference for Directors,NaN,2019-02-05,Bar Hedva,Senior management,Male,Bank of Israel,ISR,Remarks by the Supervisor of Banks at the Annu...,"| 05/02/2019 - "" ...",isr_050229012,Hebrew,CB websites
8560,https://www.boi.org.il/he/NewsAndPublications/...,https://www.boi.org.il/he/NewsAndPublications/...,Remarks at the Leadership Conference of the Pe...,NaN,2017-11-08,Bar Hedva,Senior management,Male,Bank of Israel,ISR,Remarks by the Supervisor of Banks at the Lead...,"| 08/11/2017 . , , ...",isr_08112017,Hebrew,CB websites
8561,https://www.boi.org.il/he/NewsAndPublications/...,https://www.boi.org.il/he/NewsAndPublications/...,"Remarks at the economic conference ""End of 201...",NaN,2017-12-10,Strawczynski Michel,Senior management,Male,Bank of Israel,ISR,Remarks by the Director of the Research Depart...,"' | 10/12/2017 "" ,' ' , "" MBT...",isr_101217,Hebrew,CB websites
8562,https://www.boi.org.il/he/NewsAndPublications/...,https://www.boi.org.il/he/NewsAndPublications/...,Remarks at the press briefing on monetary poli...,NaN,2017-07-10,Karnit Flug,Governor,Female,Bank of Israel,ISR,Remarks by the Governor of the Bank of Israel ...,"| 10/07/2017 2017 , - 10...",isr_10717,Hebrew,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25311,https://www.bis.org/review/r191025f.htm,https://www.bis.org/review/r191025f.pdf,Setting goals and embracing innovation to meet...,"Remarks by Mr Yaron Amir, Governor of the Bank...",2019-09-01,Yaron Amir,Governor,Male,Bank of Israel,ISR,Yaron Amir: Setting goals and embracing innova...,NaN,r191025f,English,BIS
26081,https://www.bis.org/review/r201223o.htm,https://www.bis.org/review/r201223o.pdf,Competition and structural changes,"Remarks by Mr Yaron Amir, Governor of the Bank...",2020-12-17,Yaron Amir,Governor,Male,Bank of Israel,ISR,Yaron Amir: Competition and structural changes...,NaN,r201223o,English,BIS
26082,https://www.bis.org/review/r201223p.htm,https://www.bis.org/review/r201223p.pdf,Remarks - Eli Hurvitz Conference on Economy an...,"Remarks by Mr Yaron Amir, Governor of the Bank...",2020-12-14,Yaron Amir,Governor,Male,Bank of Israel,ISR,Yaron Amir: Remarks - Eli Hurvitz Conference o...,NaN,r201223p,English,BIS
27025,http://www.bis.org/review/r220630a.htm,http://www.bis.org/review/r220630a.pdf,Yaron Amir: A look at the future world of paym...,"Remarks (virtual) by Prof Yaron Amir, Governor...",2022-06-20,Yaron Amir,Governor,Male,Bank of Israel,ISR,"Remarks by the Governor of the Bank of Israel,...",NaN,r220630a,English,BIS
27412,http://www.bis.org/review/r221202e.htm,http://www.bis.org/review/r221202e.pdf,Andrew Abir: Remarks - Bank of Israel's Paymen...,"Remarks by Mr Andrew Abir, Deputy Governor of ...",2022-11-16,Andrew Abir,Deputy Governor,Male,Bank of Israel,ISR,Andrew Abir: Remarks - Bank of Israel's Paymen...,NaN,r221202e,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Israel
Federal Reserve Bank of Minneapolis

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
18632,https://www.bis.org/review/r110704h.pdf,https://www.bis.org/review/r110704h.pdf,Re-thinking leverage subsidies,"Speech by Mr Narayana Kocherlakota, President ...",2011-06-27,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,Narayana Kocherlakota: Re-thinking leverage su...,NaN,r110704h,English,BIS
18734,https://www.bis.org/review/r110901f.pdf,https://www.bis.org/review/r110901f.pdf,"Communication, credibility and implementation ...","Speech by Mr Narayana Kocherlakota, President ...",2011-08-30,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,"Narayana Kocherlakota: Communication, credibil...",NaN,r110901f,English,BIS
18784,https://www.bis.org/review/r110928c.pdf,https://www.bis.org/review/r110928c.pdf,Central bank independence and sovereign default,"Speech by Mr Narayana Kocherlakota, President ...",2011-09-26,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,Narayana Kocherlakota: Central bank independen...,NaN,r110928c,English,BIS
18843,https://www.bis.org/review/r111024g.pdf,https://www.bis.org/review/r111024g.pdf,Making monetary policy,"Speech by Mr Narayana Kocherlakota, President ...",2011-10-13,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,Narayana Kocherlakota: Making monetary policy ...,NaN,r111024g,English,BIS
18844,https://www.bis.org/review/r111024h.pdf,https://www.bis.org/review/r111024h.pdf,The importance of teaching teachers,"Speech by Mr Narayana Kocherlakota, President ...",2011-10-20,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,Narayana Kocherlakota: The importance of teach...,NaN,r111024h,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34826,https://www.minneapolisfed.org/speeches/2015/w...,NaN,We Can Do Better,NaN,2015-04-07,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,We Can Do Better Video of speech Audience Q&A ...,NaN,usa_we-can-do-better-bismarck,English,CB websites
34827,https://www.minneapolisfed.org/speeches/2015/w...,NaN,We Can Do Better,NaN,2015-04-10,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,We Can Do Better Minnesota Credit Union Networ...,NaN,usa_we-can-do-better-bloomington,English,CB websites
34828,https://www.minneapolisfed.org/speeches/2012/w...,NaN,Welcome Remarks for Beyond the Border Conference,The Canada-U.S. Beyond the Border Action Plans...,2012-06-28,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,Welcome Remarks for Beyond the Border Conferen...,NaN,usa_welcome-remarks-for-beyond-the-border-conf...,English,CB websites
34841,https://www.minneapolisfed.org/speeches/2012/w...,NaN,Welcoming Remarks,Conference on the Law and Economics of Indian ...,2012-08-27,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,Welcoming Remarks Conference on the Law and Ec...,NaN,usa_welcoming-remarks,English,CB websites
34844,https://www.minneapolisfed.org/speeches/2012/w...,NaN,What's Different about Economic Development in...,Growing Economies in Indian Country: A Nationa...,2012-05-01,Narayana Kocherlakota,Governor,Male,Federal Reserve Bank of Minneapolis,USA,What's Different about Economic Development in...,NaN,usa_whats-different-about-economic-development...,English,CB websites

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Federal Reserve Bank of Minneapolis
Central Bank of Trinidad and Tobago

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12796,https://www.bis.org/review/r010521c.pdf,https://www.bis.org/review/r010521c.pdf,The state of the economy in Trinidad and Tobag...,"Address by Mr Winston Dookeran, Governor of th...",2001-05-16,Winston Dookeran,Governor,Male,Central Bank of Trinidad and Tobago,TTO,Winston Dookeran: The state of the economy in ...,NaN,r010521c,English,BIS
13344,https://www.bis.org/review/r030516f.pdf,https://www.bis.org/review/r030516f.pdf,Globalization and the international financial ...,"Address by Mr Ewart Williams, Governor of the ...",2003-04-30,Ewart S Williams,Governor,Male,Central Bank of Trinidad and Tobago,TTO,Ewart Williams: Globalization and the internat...,NaN,r030516f,English,BIS
13416,https://www.bis.org/review/r030828f.pdf,https://www.bis.org/review/r030828f.pdf,The Central Bank and preparations for integrat...,"Address by Mr Ewart Williams, Governor of the ...",2003-07-08,Ewart S Williams,Governor,Male,Central Bank of Trinidad and Tobago,TTO,Ewart Williams: The Central Bank and preparati...,NaN,r030828f,English,BIS
13533,https://www.bis.org/review/r031211d.pdf,https://www.bis.org/review/r031211d.pdf,The role of credit unions in the emerging fina...,"Address by Mr Ewart S Williams, Governor of th...",2003-11-06,Ewart S Williams,Governor,Male,Central Bank of Trinidad and Tobago,TTO,Ewart S Williams: The role of credit unions in...,NaN,r031211d,English,BIS
13764,https://www.bis.org/review/r040617g.pdf,https://www.bis.org/review/r040617g.pdf,Setting the agenda for hemispheric progress - ...,"Presentation by Ms Catherine Kumar, Inspector ...",2004-06-02,Catherine Kumar,Senior management,Female,Central Bank of Trinidad and Tobago,TTO,Catherine Kumar: Setting the agenda for hemisp...,NaN,r040617g,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30442,NaN,https://www.central-bank.org.tt/sites/default/...,Feature Address at the 4th Monetary Policy Forum,NaN,2015-06-01,Jwala Rambarran,Governor,Male,Central Bank of Trinidad and Tobago,TTO,Central Bank of Trinidad &Tobago Feature Addre...,NaN,tto_speechmpfjune15finaldraft,English,CB websites
30443,NaN,https://www.central-bank.org.tt/sites/default/...,Address TSTT/Citigroup Commemorative Ceremony ...,NaN,2005-07-29,Ewart S Williams,Governor,Male,Central Bank of Trinidad and Tobago,TTO,c Central Bank of Trinidad &Tobago Eric Willia...,NaN,tto_tstt_citigroup_luncheon_july_05,English,CB websites
30444,NaN,https://www.central-bank.org.tt/sites/default/...,Media Launch of the Trinidad and Tobago Interb...,NaN,2006-01-30,Ewart S Williams,Governor,Male,Central Bank of Trinidad and Tobago,TTO,ADDRESS at the Media Launch of the Trinidad an...,NaN,tto_ttips_media_launch__january_06,English,CB websites
30445,NaN,https://www.central-bank.org.tt/sites/default/...,Understanding Capital Markets,NaN,2004-06-30,Ewart S Williams,Governor,Male,Central Bank of Trinidad and Tobago,TTO,"UNDERSTANDING CAPITAL MARKETS ADDRESS at UWI, ...",NaN,tto_uwi_institute_of_business_breakfast_meetin...,English,CB websites
30446,NaN,https://www.central-bank.org.tt/sites/default/...,Stakeholder Workshop,NaN,2004-08-26,Ewart S Williams,Governor,Male,Central Bank of Trinidad and Tobago,TTO,OPENING REMARKS at The Stakeholder Workshop ho...,NaN,tto_workshop__rebasing_gross_domestic_product_...,English,CB websites

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Trinidad and Tobago
Central Bank of Cyprus

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2100,https://www.centralbank.cy/el/the-governor/pre...,NaN,The banking sector and economic growth,NaN,2007-05-03,Athanasios Orphanides,Governor,Male,Central Bank of Cyprus,CYP,Taking up office Address by Athanasios Orphani...,", , , 3 2007 , , , ...",cyp_athanasios_orphanides_39205_greek,Greek,CB websites
2101,https://www.centralbank.cy/en/the-governor/pre...,NaN,The crisis in the eurozone and the Cypriot eco...,NaN,2007-07-10,Athanasios Orphanides,Governor,Male,Central Bank of Cyprus,CYP,The euro conversion rate of the Cyprus pound S...,NaN,cyp_athanasios_orphanides_39273_english,English,CB websites
2102,https://www.centralbank.cy/en/the-governor/pre...,NaN,The way to growth,NaN,2007-09-21,Athanasios Orphanides,Governor,Male,Central Bank of Cyprus,CYP,Comment on 'What have economists learned about...,NaN,cyp_athanasios_orphanides_39346_english,English,CB websites
2103,https://www.centralbank.cy/el/the-governor/pre...,NaN,Financial stability in Europe: a European publ...,NaN,2007-10-26,Athanasios Orphanides,Governor,Male,Central Bank of Cyprus,CYP,"""Euro, our Currency"" Address by Athanasios Orp...",", , , , , 26 2007 ...",cyp_athanasios_orphanides_39381_greek,Greek,CB websites
2104,https://www.centralbank.cy/en/the-governor/pre...,NaN,Presentation of the Bank's Annual Report for t...,NaN,2007-11-19,Athanasios Orphanides,Governor,Male,Central Bank of Cyprus,CYP,Perspectives from the monetary policy strategy...,NaN,cyp_athanasios_orphanides_39405_english,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27577,http://www.bis.org/review/r230315j.htm,http://www.bis.org/review/r230315j.pdf,Constantinos Herodotou: Financial literacy and...,"Welcome address by Mr Constantinos Herodotou, ...",2023-03-10,Constantinos Herodotou,Governor,Male,Central Bank of Cyprus,CYP,Constantinos Herodotou: Financial literacy and...,NaN,r230315j,English,BIS
27578,http://www.bis.org/review/r230315k.htm,http://www.bis.org/review/r230315k.pdf,Constantinos Herodotou: Economic trends and ou...,"Keynote address by Mr Constantinos Herodotou, ...",2023-03-07,Constantinos Herodotou,Governor,Male,Central Bank of Cyprus,CYP,Constantinos Herodotou: Economic trends and ou...,NaN,r230315k,English,BIS
27850,http://www.bis.org/review/r230731j.htm,http://www.bis.org/review/r230731j.pdf,Constantinos Herodotou: How can banks and fint...,Introductory speech by Mr Constantinos Herodot...,2023-07-04,Constantinos Herodotou,Governor,Male,Central Bank of Cyprus,CYP,Constantinos Herodotou: How can banks and fint...,NaN,r230731j,English,BIS
28143,https://www.bis.org/review/r231218i.htm,https://www.bis.org/review/r231218i.pdf,Constantinos Herodotou: Challenges and prospec...,"Speech by Mr Constantinos Herodotou, Governor ...",2023-12-09,Constantinos Herodotou,Governor,Male,Central Bank of Cyprus,CYP,Constantinos Herodotou: Speech - 29th Annual C...,NaN,r231218i,English,BIS
28147,https://www.bis.org/review/r231227b.htm,https://www.bis.org/review/r231227b.pdf,Constantinos Herodotou: Navigating the technol...,"Speech by Mr Constantinos Herodotou, Governor ...",2023-12-07,Constantinos Herodotou,Governor,Male,Central Bank of Cyprus,CYP,Constantinos Herodotou: Navigating the technol...,NaN,r231227b,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Cyprus
Bank of Jamaica

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9258,https://boj.org.jm/uploads/news/address_-_4th_...,https://boj.org.jm/uploads/news/address_-_4th_...,Address on Recent Enhancements in Jamaica Fina...,NaN,2015-10-13,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,BANK OF JAMAICA JBA Annual AML/CFT Seminar Rec...,NaN,jam_address_-_4th_annual_jba_aml-cft_conferenc...,English,CB websites
9259,https://boj.org.jm/uploads/news/address_-_msb_...,https://boj.org.jm/uploads/news/address_-_msb_...,Address to the Mona School of Business Rountab...,NaN,2010-03-04,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,"MSB Roundtable 2010 ""Managing Risk for Growth ...",NaN,jam_address_-_msb_roundtable_luncheon_2010-3-0...,English,CB websites
9260,https://boj.org.jm/uploads/news/address_-_uwi_...,https://boj.org.jm/uploads/news/address_-_uwi_...,Address at UWI Actuarial Society 9th Annual Aw...,NaN,2015-03-31,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,Address: UWI Actuarial Society 9th Annual Awar...,NaN,jam_address_-_uwi_actuarial_society_awards_din...,English,CB websites
9261,https://boj.org.jm/uploads/news/address_-_uwi_...,https://boj.org.jm/uploads/news/address_-_uwi_...,Address to the UWI Mona Campus Council,NaN,2010-03-05,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,"University of the West Indies, Mona Campus Cou...",NaN,jam_address_-_uwi_mona_campus_council_-_2010-0...,English,CB websites
9262,https://boj.org.jm/uploads/news/address_to_jma...,https://boj.org.jm/uploads/news/address_to_jma...,"Address to JMA 2014 Economic Forum entitled ""J...",NaN,2014-01-17,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,U BANK OF JAMAICA Address to Jamaica Manufactu...,NaN,jam_address_to_jma_-_2014-1-16,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19927,https://www.bis.org/review/r130215c.pdf,https://www.bis.org/review/r130215c.pdf,The role of monetary and exchange rate policy ...,"Remarks by Mr Brian Wynter, Governor of the Ba...",2013-02-12,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,Brian Wynter: The role of monetary and exchang...,NaN,r130215c,English,BIS
20436,https://www.bis.org/review/r131011c.pdf,https://www.bis.org/review/r131011c.pdf,Quarterly Monetary Policy Report - latest econ...,"Remarks by Mr Brian Wynter, Governor of the Ba...",2013-08-21,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,Brian Wynter: Quarterly Monetary Policy Report...,NaN,r131011c,English,BIS
20437,https://www.bis.org/review/r131011d.pdf,https://www.bis.org/review/r131011d.pdf,Implications of the medium-term macroeconomic ...,"Remarks by Mr Brian Wynter, Governor of the Ba...",2013-06-11,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,Brian Wynter: Implications of the medium-term ...,NaN,r131011d,English,BIS
20438,https://www.bis.org/review/r131011e.pdf,https://www.bis.org/review/r131011e.pdf,Promoting financial inclusion through public e...,"Remarks by Mr Brian Wynter, Governor of the Ba...",2013-08-29,Brian Wynter,Governor,Male,Bank of Jamaica,JAM,Brian Wynter: Promoting financial inclusion th...,NaN,r131011e,English,BIS
27502,http://www.bis.org/review/r230208e.htm,http://www.bis.org/review/r230208e.pdf,Richard Byles: Jamaica's recent inflation perf...,"Monetary Policy Statement by Mr Richard Byles,...",2022-12-14,Richard Byles,Governor,Male,Bank of Jamaica,JAM,Richard Byles: Jamaica's recent inflation perf...,NaN,r230208e,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Jamaica
Central Bank of Curaao and Sint Maarten

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2013,NaN,https://cdn.centralbank.cw/media/publications/...,Future Strategies for the Curacao Internationa...,NaN,2022-05-20,Emsley D Tromp,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,Corporate Governance Opening speech by dr. E. ...,NaN,cuw_20190316_corporate_governance,English,CB websites
2014,NaN,https://cdn.centralbank.cw/media/publications/...,The need for Corporate Governance in averting ...,NaN,2022-01-20,Emsley D Tromp,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,The Economic Situation of the Netherlands Anti...,NaN,cuw_20190316_the_economic_situation_of_the_net...,English,CB websites
2015,NaN,https://cdn.centralbank.cw/media/speeches_pres...,"Good governance, better decisions, best result...",NaN,2022-02-03,Richard Doornbosch,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,"Good governance, better decisions, best result...",NaN,cuw_20220203_speech_r_doornbosch_cifa_february...,English,CB websites
2016,NaN,https://cdn.centralbank.cw/media/speeches_pres...,EU-sanctions | Opening remarks by Richard Door...,NaN,2022-04-29,Richard Doornbosch,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,CENTRALE BANK CURASAO & SINT MAARTEN Welcome R...,NaN,cuw_20220430_speech_doornbosch_sanction_semina...,English,CB websites
2017,NaN,https://cdn.centralbank.cw/media/event_past/20...,The implications of the financial and economic...,NaN,2022-10-05,Richard Doornbosch,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,Climate Change Risks - gradual then sudden Key...,NaN,cuw_20220511_richard_doornbosch_speech_cccp_10...,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27103,http://www.bis.org/review/r220906c.htm,http://www.bis.org/review/r220906c.pdf,Leila Matroos-Lasten: Launch of the Governance...,"Opening remarks by Mrs Leila Matroos-Lasten, E...",2022-08-31,Leila Matroos-Lasten,Governor,Female,Central Bank of Curaao and Sint Maarten,CUW,Opening remarks delivered by Mrs. Leila Matroo...,NaN,r220906c,English,BIS
27105,https://www.bis.org/review/r220906f.htm,https://www.bis.org/review/r220906f.pdf,Climate change - implications for the financia...,"Keynote speech by Mr Richard Doornbosch, Presi...",2022-05-10,Richard Doornbosch,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,gradual then sudden Keynote speech delivered b...,NaN,r220906f,English,BIS
27106,http://www.bis.org/review/r220906g.htm,http://www.bis.org/review/r220906g.pdf,Richard Doornbosch: Correspondent bank relatio...,"Keynote speech by Mr Richard Doornbosch, Presi...",2022-06-16,Richard Doornbosch,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,"SLIDE 1 ""Correspondent Bank Relations in Curac...",NaN,r220906g,English,BIS
27144,http://www.bis.org/review/r220925e.htm,http://www.bis.org/review/r220925e.pdf,Richard Doornbosch: Transitioning into a new e...,"Opening address by Mr Richard Doornbosch, Pres...",2023-09-13,Richard Doornbosch,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,Richard Doornbosch: Transitioning into a new e...,NaN,r220925e,English,BIS
27938,http://www.bis.org/review/r231002b.htm,http://www.bis.org/review/r231002b.pdf,Richard Doornbosch: Managing climate risk in t...,"Opening address by Mr Richard Doornbosch, Pres...",2023-09-28,Richard Doornbosch,Governor,Male,Central Bank of Curaao and Sint Maarten,CUW,Richard Doornbosch: Managing climate risk in t...,NaN,r231002b,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Curaao and Sint Maarten
National Bank of Romania

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
14205,https://www.bis.org/review/r050426d.pdf,https://www.bis.org/review/r050426d.pdf,Inflation targeting - international experience...,"Speech by Mr Mugur Isarescu, Governor of the N...",2005-03-30,Mugur Isarescu,Governor,Male,National Bank of Romania,ROU,Mugur Isrescu: Inflation targeting - internati...,NaN,r050426d,English,BIS
16470,https://www.bis.org/review/r080923b.pdf,https://www.bis.org/review/r080923b.pdf,Hard landing unlikely for Romania,"Interview with Dr Mugur Isarescu, Governor of ...",2008-09-08,Mugur Isarescu,Governor,Male,National Bank of Romania,ROU,Mugur Isrescu: Hard landing unlikely for Roman...,NaN,r080923b,English,BIS
16664,https://www.bis.org/review/r081219b.pdf,https://www.bis.org/review/r081219b.pdf,10 years since the launch of Ziarul Financiar,"Speech by Mr Mugur Isarescu, Governor of the N...",2008-12-16,Mugur Isarescu,Governor,Male,National Bank of Romania,ROU,Mugur Isrescu: 10 years since the launch of Zi...,NaN,r081219b,English,BIS
16670,https://www.bis.org/review/r081222b.pdf,https://www.bis.org/review/r081222b.pdf,Issues related to real convergence on the path...,"Presentation by Mr Mugur Isarescu, Governor of...",2008-10-02,Mugur Isarescu,Governor,Male,National Bank of Romania,ROU,Mugur Isrescu: Issues related to real converge...,NaN,r081222b,English,BIS
16916,https://www.bis.org/review/r090508d.pdf,https://www.bis.org/review/r090508d.pdf,Nine lessons from the current financial crisis,"Speech by Dr Mugur Isrescu, Governor of the Na...",2009-04-14,Mugur Isarescu,Governor,Male,National Bank of Romania,ROU,Mugur Isrescu: Nine lessons from the current f...,NaN,r090508d,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28798,https://www.bnr.ro/Opening-speech-at-the-Confe...,NaN,Opening speech at the Conference Investments i...,NaN,2023-03-16,Mugur Isrescu,Governor,Male,National Bank of Romania,ROU,"Opening speech at the Conference ""Investments ...",NaN,rou_mugur_isarescu_45001,English,CB websites
28799,https://www.bnr.ro/Opening-speech-at-the-%e2%8...,NaN,Opening speech at the Bitcoin versus Central B...,NaN,2023-04-06,Mugur Isrescu,Governor,Male,National Bank of Romania,ROU,Opening speech at the Bitcoin versus Central B...,NaN,rou_mugur_isarescu_45022,English,CB websites
28800,https://www.bnr.ro/Opening-speech-at-Network-o...,NaN,Opening speech at Network of ESCB Data Protect...,NaN,2023-05-22,Mugur Isrescu,Governor,Male,National Bank of Romania,ROU,Opening speech at Network of ESCB Data Protect...,NaN,rou_mugur_isarescu_45068,English,CB websites
28801,https://www.bnr.ro/Speech-during-the-presentat...,NaN,Speech during the presentation of the book Vis...,NaN,2023-05-29,Mugur Isrescu,Governor,Male,National Bank of Romania,ROU,Speech during the presentation of the book Vis...,NaN,rou_mugur_isarescu_45075,English,CB websites
28802,https://www.bnr.ro/Opening-speech-at-the-annua...,NaN,Opening speech at the annual conference of the...,NaN,2023-06-08,Mugur Isrescu,Governor,Male,National Bank of Romania,ROU,Opening speech at the annual conference of the...,NaN,rou_mugur_isarescu_45085,English,CB websites

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Romania
National Bank of Ukraine

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
24641,https://www.bis.org/review/r190128b.htm,https://www.bis.org/review/r190128b.pdf,The National Bank of Ukraine's key achievement...,"Speech by Mr Yakiv Smolii, Governor of the Nat...",2019-01-16,Yakiv Smolii,Governor,Male,National Bank of Ukraine,UKR,Yakiv Smolii: The National Bank of Ukraine's k...,NaN,r190128b,English,BIS
24653,https://www.bis.org/review/r190131f.htm,https://www.bis.org/review/r190131f.pdf,National Bank of Ukraine press briefing - mone...,"Speech by Ms Kateryna Rozhkova, Acting Governo...",2019-01-31,Kateryna Rozhkova,Governor,Female,National Bank of Ukraine,UKR,Kateryna Rozhkova: National Bank of Ukraine pr...,NaN,r190131f,English,BIS
24730,https://www.bis.org/review/r190318c.htm,https://www.bis.org/review/r190318c.pdf,National Bank of Ukraine press briefing - mone...,"Speech by Mr Yakiv Smolii, Governor of the Nat...",2019-03-14,Yakiv Smolii,Governor,Male,National Bank of Ukraine,UKR,Yakiv Smolii: National Bank of Ukraine press b...,NaN,r190318c,English,BIS
24894,https://www.bis.org/review/r190523a.htm,https://www.bis.org/review/r190523a.pdf,"Opening speech ""Central Bank Communications: F...","Opening speech by Mr Yakiv Smolii, Governor of...",2019-05-23,Yakiv Smolii,Governor,Male,National Bank of Ukraine,UKR,"Yakiv Smolii: Opening speech ""Central Bank Com...",NaN,r190523a,English,BIS
24941,https://www.bis.org/review/r190607d.htm,https://www.bis.org/review/r190607d.pdf,National Bank of Ukraine press briefing - mone...,"Speech by Mr Yakiv Smolii, Governor of the Nat...",2019-04-25,Yakiv Smolii,Governor,Male,National Bank of Ukraine,UKR,Yakiv Smolii: National Bank of Ukraine press b...,NaN,r190607d,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30910,https://bank.gov.ua/en/news/all/vistup-golovi-...,NaN,Speech by NBU Governor Andriy Pyshnyy at Press...,NaN,2023-06-15,Andriy Pyshnyy,Governor,Male,National Bank of Ukraine,UKR,mi About d Consumer protection 9 Accessibility...,NaN,ukr_45092_andriy_pyshnyy,English,CB websites
30911,https://bank.gov.ua/en/news/all/vstupne-slovo-...,NaN,Introductory Speech of Deputy Governor of the ...,NaN,2023-06-22,Sergiy Nikolaychuk,Deputy Governor,Male,National Bank of Ukraine,UKR,mi About d Consumer protection 9 Accessibility...,NaN,ukr_45099_sergiy_nikolaychuk,English,CB websites
30912,https://bank.gov.ua/en/news/all/vistup-golovi-...,NaN,Speech by NBU Governor Andriy Pyshnyy at Press...,NaN,2023-09-14,Andriy Pyshnyy,Governor,Male,National Bank of Ukraine,UKR,mi About d Consumer protection 9 Accessibility...,NaN,ukr_45183_andriy_pyshnyy,English,CB websites
30913,https://bank.gov.ua/en/news/all/vistup-golovi-...,NaN,Speech by NBU Governor Andriy Pyshnyy at Press...,NaN,2023-10-26,Andriy Pyshnyy,Governor,Male,National Bank of Ukraine,UKR,mi About d Consumer protection 9 Accessibility...,NaN,ukr_45225_andriy_pyshnyy,English,CB websites
30914,https://bank.gov.ua/en/news/all/vistup-golovi-...,NaN,Speech by NBU Governor Andriy Pyshnyy at Press...,NaN,2023-12-14,Andriy Pyshnyy,Governor,Male,National Bank of Ukraine,UKR,mi About d Consumer protection 9 Accessibility...,NaN,ukr_45274_andriy_pyshnyy,English,CB websites

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Ukraine
Czech National Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2225,https://www.cnb.cz/en/public/media-service/spe...,NaN,Speech to AIMA Regulatory Forum Hong Kong,AIMA Regulatory Forum,2012-03-08,Mojmir Hampl,Deputy Governor,Male,Czech National Bank,CZE,8. 3. 2012 Hampl Mojmi'r AIMA Regulatory Forum...,NaN,cze_aima_regulatory_forum_,English,CB websites
2226,https://www.cnb.cz/en/public/media-service/spe...,NaN,"Mojmr Hampl, Vice-Governor, CNB Prague",American Chamber of Commerce in the Czech Repu...,2014-06-19,Mojmir Hampl,Deputy Governor,Male,Czech National Bank,CZE,19. 6. 2014 Hampl Mojmir American Chamber of C...,NaN,cze_american_chamber_of_commerce_in_the_czech_...,English,CB websites
2227,https://www.cnb.cz/en/public/media-service/spe...,NaN,Speech to Central and South East European Fina...,Central and South East European Financial Foru...,2009-05-19,Mojmir Hampl,Deputy Governor,Male,Czech National Bank,CZE,19.5. HampLMoimi'r 2009 Central and South East...,NaN,cze_central_and_south_east_european_financial_...,English,CB websites
2228,https://www.cnb.cz/en/public/media-service/spe...,NaN,"Opening Conference for Phare Project ""Implemen...",Central Banking Community and Payment Systems,2004-04-28,Frait Jan,Board member,Male,Czech National Bank,CZE,28. 4. 2004 Frait Jan Central Banking Communit...,NaN,cze_central_banking_community_and_payment_syst...,English,CB websites
2229,https://www.cnb.cz/en/public/media-service/spe...,NaN,Vienna,CFO Summit Vienna,2011-10-12,Mojmir Hampl,Deputy Governor,Male,Czech National Bank,CZE,12. 10. 2011 Hampl Mojmir CFO Summit Vienna Mo...,NaN,cze_cfo_summit_vienna_,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27830,http://www.bis.org/review/r230718g.htm,http://www.bis.org/review/r230718g.pdf,Ale Michl: The road to the target II,"Speech by Mr Ale Michl, Governor of the Czech ...",2023-06-15,Ales Michl,Governor,Male,Czech National Bank,CZE,Ales Michl: The road to the target II Speech b...,NaN,r230718g,English,BIS
27844,http://www.bis.org/review/r230731b.htm,http://www.bis.org/review/r230731b.pdf,Ale Michl: The current level of inflation stil...,"Speech by Mr Ale Michl, Governor of the Czech ...",2023-07-27,Ales Michl,Governor,Male,Czech National Bank,CZE,Ales Michl: The current level of inflation sti...,NaN,r230731b,English,BIS
27884,http://www.bis.org/review/r230906a.htm,http://www.bis.org/review/r230906a.pdf,Ale Michl: Notes from the 2023 Jackson Hole Sy...,"Notes by Mr Ale Michl, Governor of the Czech N...",2023-08-26,Ales Michl,Governor,Male,Czech National Bank,CZE,Ales Michl: Notes from the 2023 Jackson Hole S...,NaN,r230906a,English,BIS
27974,https://www.bis.org/review/r231019a.htm,https://www.bis.org/review/r231019a.pdf,Ale Michl: The road to the target,"Speech by Mr Ale Michl, Governor of the Czech ...",2023-09-17,Ales Michl,Governor,Male,Czech National Bank,CZE,Ales Michl: The road to the target Speech by M...,NaN,r231019a,English,BIS
28200,https://www.bis.org/review/r970310b.pdf,https://www.bis.org/review/r970310b.pdf,Mr. Tosovsky gives the Czech Republic's perspe...,Text of eighth Gerhard de Kock Memorial Lectur...,1997-02-17,Josef Tosovsky,Governor,Male,Czech National Bank,CZE,Mr. Tosovsky gives the Czech Republics perspec...,NaN,r970310b,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Czech National Bank
Central Bank of Kuwait

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9845,https://www.cbk.gov.kw/en/redirects/download?c...,NaN,The 60th Meeting of the Committee of Governors...,NaN,2014-10-24,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,Speech of His Excellency the Governor of the C...,( 42-42 )4102 ...,kwt_60th-gcc-ar-115803_v20_tcm10-115803,Arabic,CB websites
9846,https://www.cbk.gov.kw/en/redirects/download?c...,NaN,"Islamic Finance Noble Goals, Innovative App...",NaN,2019-12-08,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,"In the name of God, the Merciful, the Compassi...",... . ...,kwt_8th-shura-conf-speech-146701_v20_tcm10-146701,Arabic,CB websites
9847,https://www.cbk.gov.kw/en/redirects/download?c...,NaN,CBK-IFSB Islamic Financal Conference: A Univer...,NaN,2018-05-02,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,"Keynote Speech of His Excellency the Governor,...",NaN,kwt_cbk-ifsb-speech-2018-127116_v40_tcm10-127116,English,CB websites
9848,https://www.cbk.gov.kw/en/redirects/download?c...,NaN,Funding Sustainable Development Goals,NaN,2016-10-11,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,Funding Sustainable Development Goals1 1Keynot...,NaN,kwt_dubai-summit-speech-11-oct-2016-122066_v20...,English,CB websites
9849,https://www.cbk.gov.kw/en/redirects/download?c...,NaN,Financial Stability Amid Innovations and Reforms,NaN,2016-09-27,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,Financial Stability amid Innovations and Refor...,NaN,kwt_euromoney-2016-121910_v30_tcm10-121910,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24529,https://www.bis.org/review/r181130f.htm,https://www.bis.org/review/r181130f.pdf,Steering fintech for a prosperous society,Keynote address by His Excellency Dr Mohammad ...,2018-11-27,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,STEERING FINTECH FOR A PROSPEROUS SOCIETY Intr...,NaN,r181130f,English,BIS
25189,https://www.bis.org/review/r190924e.htm,https://www.bis.org/review/r190924e.pdf,The battle for relevance,Keynote speech by His Excellency Dr Mohammad Y...,2019-09-23,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,THE BATTLE FOR RELEVANCE* Assalam-o-Alaikum an...,NaN,r190924e,English,BIS
25443,https://www.bis.org/review/r191211c.htm,https://www.bis.org/review/r191211c.pdf,Regulation and supervision - from old fault li...,Keynote speech by His Excellency Dr Mohammad Y...,2019-12-11,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,Regulation & Supervision: from old fault lines...,NaN,r191211c,English,BIS
25703,https://www.bis.org/review/r200807b.htm,https://www.bis.org/review/r200807b.pdf,"Lives and livelihoods, a delicate balance",Speech by His Excellency Dr Mohammad Y Al-Hash...,2020-06-04,Mohammad Y Al-Hashel,Governor,Male,Central Bank of Kuwait,KWT,Lives and Livelihoods A Delicate Balance Dr. M...,NaN,r200807b,English,BIS
27303,http://www.bis.org/review/r221108c.htm,http://www.bis.org/review/r221108c.pdf,Basel A Al-Haroon: Requirements and challenges...,"Speech by His Excellency Mr Basel A Al-Haroon,...",2022-09-18,Basel A Al-Haroon,Governor,Male,Central Bank of Kuwait,KWT,"""Requirements and Challenges of Rebuilding Ban...",NaN,r221108c,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Kuwait
Austrian National Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
594,NaN,https://www.oenb.at/dam/jcr:b29b8127-4ed7-4156...,Service successes boost foreign trade,NaN,2014-05-20,Andreas Ittner,Deputy Governor,Male,Austrian National Bank,AUT,PRESS CONFERENCE 20. MAY 2014 Service successe...,PRESSEKONFERENZ 20. MAI 2014 Dienstleistungser...,aut_%20presseunterlage,German,CB websites
595,NaN,https://www.oenb.at/dam/jcr:420a43b0-eb09-4359...,The Digitalization Challenge: Some Remarks Fro...,NaN,2018-06-26,Peter Mooslechner,Senior management,Male,Austrian National Bank,AUT,Peter Mooslechner Executive Director Oesterrei...,NaN,aut_20180626_mooslechner_central_bank__executi...,English,CB websites
596,NaN,https://www.oenb.at/dam/jcr:b70f2025-ba55-4143...,200 years of stock trading on the Deutsche Brs...,NaN,2020-09-09,Robert Holzmann,Governor,Male,Austrian National Bank,AUT,Univ.-Prof. Mag. Dr. Robert Holzmann Governor ...,Univ.-Prof. Mag. Dr. Robert Holzmann Gouverneu...,aut_20200909_frankfurter_b%c3%b6rse_dt,German,CB websites
597,NaN,https://www.oenb.at/dam/jcr:4d86076a-6df7-4ae4...,Economic and legal issues of banking supervisi...,NaN,2020-10-21,Robert Holzmann,Governor,Male,Austrian National Bank,AUT,Univ.-Prof. Mag. Dr. Robert Holzmann Governor ...,Univ.-Prof. Mag. Dr. Robert Holzmann Gouverneu...,aut_20201021-bwg,German,CB websites
598,NaN,https://www.oenb.at/dam/jcr:defa6a48-395f-4c9c...,Speech at the first constituent meeting of the...,NaN,2021-01-27,Robert Holzmann,Governor,Male,Austrian National Bank,AUT,Univ.-Prof. Mag. Dr. Robert Holzmann Governor ...,Univ.-Prof. Mag. Dr. Robert Holzmann Gouverneu...,aut_2021-01-27-erste-konstituierende-sitzung-a...,German,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27376,http://www.bis.org/review/r221123b.htm,http://www.bis.org/review/r221123b.pdf,Robert Holzmann: Economic and monetary policy ...,"Welcome remarks by Dr Robert Holzmann, Governo...",2022-11-21,Robert Holzmann,Governor,Male,Austrian National Bank,AUT,Robert Holzmann Governor Oesterreichische Nati...,NaN,r221123b,English,BIS
27491,http://www.bis.org/review/r230207a.htm,http://www.bis.org/review/r230207a.pdf,Robert Holzmann: Lmfalussy Lecture 2023,Text of the Lmfalussy Lecture by Dr Robert Hol...,2023-02-06,Robert Holzmann,Governor,Male,Austrian National Bank,AUT,Robert Holzmann Governor Oesterreichische Nati...,NaN,r230207a,English,BIS
28428,https://www.bis.org/review/r980522a.pdf,https://www.bis.org/review/r980522a.pdf,Mr. Liebscher discusses the role of a national...,Address by the President of the Austrian Natio...,1998-05-07,Klaus Liebscher,Governor,Male,Austrian National Bank,AUT,Mr. Liebscher discusses the role of a national...,NaN,r980522a,English,BIS
28593,https://www.bis.org/review/r990420b.pdf,https://www.bis.org/review/r990420b.pdf,Dr Liebscher talks about European Economic and...,Address by the Governor of the Oesterreichisch...,1999-04-09,Klaus Liebscher,Governor,Male,Austrian National Bank,AUT,Dr. Liebscher talks about European Economic an...,NaN,r990420b,English,BIS
28744,https://www.bis.org/review/r991126b.pdf,https://www.bis.org/review/r991126b.pdf,Mr Liebscher wonders whether financial crises ...,Luncheon speech delivered by Dr Klaus Liebsche...,1999-11-23,Klaus Liebscher,Governor,Male,Austrian National Bank,AUT,Mr Liebscher wonders whether financial crises ...,NaN,r991126b,English,BIS

['Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Austrian National Bank
Bank of Lithuania

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9956,https://www.lb.lt/en/speeches-interviews-prese...,NaN,Beyond the Horizon of Lithuanian Presidency: A...,NaN,2013-08-28,Vitas Vasiliauskas,Governor,Male,Bank of Lithuania,LTU,"03/08/22, 14:44 ffl'I:) LI_ETUVQS B-AN KAS Vit...",NaN,ltu_41514_vitas_vasiliauskas_english,English,CB websites
9957,https://www.lb.lt/en/speeches-interviews-prese...,NaN,The objectives of the Banking Union,NaN,2013-09-23,Marius Jurgilas,Board member,Male,Bank of Lithuania,LTU,"03/08/22, 14:44 ffl'I:) LI.ET UVQS B,AN KAS Ma...",NaN,ltu_41540_marius_jurgilas_english,English,CB websites
9958,https://www.lb.lt/lt/kalbos-interviu-pristatym...,NaN,"Interview to the daily ""Verslo inios""",NaN,2013-10-16,Mindaugas Vaiciulis,Senior management,Male,Bank of Lithuania,LTU,"03/08/22, 14:58 MindaugasVaiiulis, Rector of t...","03/08/22, 14:58 MindaugoVaiiulio, Lietuvos ban...",ltu_41563_mindaugas_vaiciulis_lithuanian,Lithuanian,CB websites
9959,https://www.lb.lt/en/speeches-interviews-prese...,NaN,Speech at the Interparliamentary Conference on...,NaN,2013-10-17,Vitas Vasiliauskas,Governor,Male,Bank of Lithuania,LTU,"03/08/22, 14:44 VitasVasiliauskas.Speechat the...",NaN,ltu_41564_vitas_vasiliauskas_english,English,CB websites
9960,https://www.lb.lt/en/speeches-interviews-prese...,NaN,Improving the resilience of the financial sect...,NaN,2013-10-21,Vitas Vasiliauskas,Governor,Male,Bank of Lithuania,LTU,"03/08/22, 14:43 ffl'I:) LI.ET UVQS B,AN KAS Vi...",NaN,ltu_41568_vitas_vasiliauskas_english,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26935,http://www.bis.org/review/r220523f.htm,http://www.bis.org/review/r220523f.pdf,Gediminas imkus: Investment in the Baltics - f...,Welcome and opening remarks (virtual) by Mr Ge...,2022-05-20,Gediminas imkus,Governor,Male,Bank of Lithuania,LTU,Speech by Gediminas Simkus at the joint webina...,NaN,r220523f,English,BIS
26980,http://www.bis.org/review/r220615j.htm,http://www.bis.org/review/r220615j.pdf,Gediminas imkus: Evolution of structural under...,"Initial remarks by Gediminas imkus, Chairman o...",2022-06-10,Gediminas imkus,Governor,Male,Bank of Lithuania,LTU,"Speech by Gediminas Simkus at the conference ""...",NaN,r220615j,English,BIS
27168,http://www.bis.org/review/r220930j.htm,http://www.bis.org/review/r220930j.pdf,Gediminas imkus: The future of central banking,"Welcome speech by Gediminas imkus, Chairman of...",2022-09-29,Gediminas imkus,Governor,Male,Bank of Lithuania,LTU,Speech by Gediminas Simkus at the internationa...,NaN,r220930j,English,BIS
27236,http://www.bis.org/review/r221025b.htm,http://www.bis.org/review/r221025b.pdf,Gediminas imkus: Central Europe's convergence,"Introductory remarks by Mr Gediminas imkus, Ch...",2022-10-21,Gediminas imkus,Governor,Male,Bank of Lithuania,LTU,Gediminas Simkus: Central Europe's convergence...,NaN,r221025b,English,BIS
27834,https://www.bis.org/review/r230718r.htm,https://www.bis.org/review/r230718r.pdf,The future landscape of AML,"Keynote speech by Mr Gediminas imkus, Chairman...",2023-05-17,Gediminas imkus,Governor,Male,Bank of Lithuania,LTU,Gediminas simkus: The future landscape of AML ...,NaN,r230718r,English,BIS

['Austrian National Bank', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Lithuania
Banco Central de Nicaragua

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10865,https://www.bcn.gob.ni/node/1037,NaN,Presentation of the Annual Report 2014 to the ...,NaN,2015-06-03,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,PRESENTATION OF THE 2014 ANNUAL REPORT TO THE ...,PRESENTACI<ee>N DEL INFORME ANUAL 2014 A LA AS...,nic_42158_leonardo_ovidio_reyes_ramirez_spanish,Spanish,CB websites
10866,https://www.bcn.gob.ni/node/1036,NaN,Seminar Mechanisms of Transmission of Monetary...,NaN,2015-09-24,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,SEMINAR MONETARY POLICY TRANSMISSION MECHANISM...,SEMINARIO MECANISMOS DE TRANSMISI<ee>N DE LA P...,nic_42271_leonardo_ovidio_reyes_ramirez_spanish,Spanish,CB websites
10867,https://www.bcn.gob.ni/node/1035,NaN,Launch of new bills 2015,NaN,2015-10-12,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,"LAUNCH OF NEW BANKNOTES 2015, WORDS OF THE PRE...","LANZAMIENTO DE NUEVOS BILLETES 2015, PALABRAS ...",nic_42289_leonardo_ovidio_reyes_ramirez_spanish,Spanish,CB websites
10868,https://www.bcn.gob.ni/node/1034,https://www.bcn.gob.ni/sites/default/files/not...,Transcription of Press Conference: Conclusions...,NaN,2015-10-29,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,TRANSCRIPT PRESS CONFERENCE CONCLUSIONS REVIEW...,TRANSCRIPCI<ee>N CONFERENCIA DE PRENSA CONCLUS...,nic_42306_leonardo_ovidio_reyes_ramirez_spanish,Spanish,CB websites
10869,https://www.bcn.gob.ni/node/1033,NaN,Delivery of Awards of the Contest: Award for E...,NaN,2015-12-10,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,AWARDS CEREMONY OF THE CONTEST: PRIZE OF ECONO...,ENTREGA DE PREMIOS DEL CERTAMEN: PREMIO DE ECO...,nic_42348_leonardo_ovidio_reyes_ramirez_spanish,Spanish,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10954,https://www.bcn.gob.ni/divulgacion-prensa/pres...,https://www.bcn.gob.ni/sites/default/files/not...,"President of the BCN, Ovidio Reyes R. Presenta...",NaN,2023-01-31,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,fiaenfadde Issuing confidence and stability Tu...,fiaenfadde Emitiendo confianza y estabilidad M...,nic_transcripcion310123,Spanish,CB websites
10955,https://www.bcn.gob.ni/divulgacion-prensa/pres...,https://www.bcn.gob.ni/sites/default/files/not...,Presentation of the pre-census study on housin...,NaN,2023-07-31,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,TRANSCRIPTION TRANSCRIPTION Presentation Pre-c...,Emitiendo confianza y estabilidad TRANSCRIPCIN...,nic_transcripcion310723,Spanish,CB websites
10956,https://www.bcn.gob.ni/divulgacion-prensa/inte...,https://www.bcn.gob.ni/sites/default/files/not...,Exchange of Academic Collaboration Agreement b...,NaN,2023-04-11,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,fioenfaa/de Issuing confidence and stability W...,fioenfaa/de Emitiendo confianza y estabilidad ...,nic_trascripcion110423,Spanish,CB websites
10957,https://www.bcn.gob.ni/divulgacion-prensa/entr...,https://www.bcn.gob.ni/sites/default/files/not...,Interview with President Ovidio Reyes R. on La...,NaN,2023-11-04,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,TRANSCRIPTION TRANSCRIPTION Issuing confidence...,TRANSCRIPCIN Emitiendo confianza y estabilidad...,nic_trentrpr61123,Spanish,CB websites
10958,https://www.bcn.gob.ni/divulgacion-prensa/conf...,NaN,Press Conference Report on the Results of the ...,NaN,2023-11-06,Leonardo Ovidio Reyes Ramrez,Governor,Male,Banco Central de Nicaragua,NIC,PRESS CONFERENCE REPORT OF THE RESULTS OF THE ...,CONFERENCIA DE PRENSA INFORME DE RESULTADOS RE...,nic_trndprsa311232,Spanish,CB websites

['Austrian National Bank', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Banco Central de Nicaragua
National Bank of Angola

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
15,https://www.bna.ao/#/publicacoes-e-media/inter...,NaN,New Year's Eve Greetings Presentation,NaN,2013-01-29,Jos de Lima Massano,Governor,Male,National Bank of Angola,AGO,Speech by the Governor of the National Bank of...,Home Publicaes e Media Intervenes Pblicas Disc...,ago_10,Portuguese,CB websites
16,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,nterveno de abertura do Senhor Governador Manu...,NaN,2023-06-29,Manuel Tiago Dias,Governor,Male,National Bank of Angola,AGO,Opening speech by the Governor Manuel Tiago Di...,Interveno de abertura do Senhor Governador Man...,ago_105,Portuguese,CB websites
17,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,Interveno de Abertura do Governador Manuel Tia...,NaN,2023-06-30,Manuel Tiago Dias,Governor,Male,National Bank of Angola,AGO,"Opening Speech by Governor Manuel Tiago Dias, ...",Interveno de Abertura do Governador Manuel Tia...,ago_106,Portuguese,CB websites
18,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,"Interveno do Governador Manuel Tiago Dias, no ...",NaN,2023-07-20,Manuel Tiago Dias,Governor,Male,National Bank of Angola,AGO,"Speech by Governor Manuel Tiago Dias, at the O...","Interveno do Governador Manuel Tiago Dias, n a...",ago_107,Portuguese,CB websites
19,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,Interveno de Abertura da Vice-governadora Mari...,NaN,2023-08-09,Maria Juliana Pereira,Deputy Governor,Female,National Bank of Angola,AGO,Opening Speech by Vice Governor Mai Juliana Pe...,Interveno de Abertura da Vice-govemadora Mai J...,ago_108,Portuguese,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,https://www.bna.ao/#/publicacoes-e-media/inter...,NaN,Speech at the opening of the Workshop on Comba...,NaN,2012-12-21,Jos de Lima Massano,Governor,Male,National Bank of Angola,AGO,Home Publications & Media Public Speeches Pres...,Home Publicaes e Media Intervenes Pblicas Apre...,ago_9,Portuguese,CB websites
104,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,Interveno de Abertura do Governador Jos de Lim...,NaN,2022-12-08,Jos De Lima Massano,Governor,Male,National Bank of Angola,AGO,Opening Speech by Governor Jose de Lima Massan...,Interveno de Abertura do Governador Jos de Lim...,ago_90,Portuguese,CB websites
105,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,"Intervention of the Deputy Governor, Pedro Cas...",NaN,2023-01-13,Pedro Castro e Silva,Deputy Governor,Male,National Bank of Angola,AGO,"Intervention of the Deputy Governor, Pedro Cas...",NaN,ago_92,English,CB websites
106,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,Administrator Beatriz dos Santos' Opening Spee...,NaN,2022-10-31,Beatriz Ferreira Andrade dos Santos,Board member,Female,National Bank of Angola,AGO,Administrator Beatriz dos Santos' Opening Spee...,NaN,ago_93,English,CB websites
107,https://www.bna.ao/#/pt/publicacoes-e-media/in...,NaN,Interveno de Boas-vindas do Senhor Governador ...,NaN,2023-03-22,Jos De Lima Massano,Governor,Male,National Bank of Angola,AGO,Welcome Speech by Governor Jose de Lima Massan...,Interveno de Boas-vindas do Senhor Governadc J...,ago_97,Portuguese,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Angola
Bank of Namibia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10791,https://www.bon.com.na/getattachment/0443cff3-...,https://www.bon.com.na/CMSTemplates/Bon/Files/...,Talking points at the handing over of COVID-19...,NaN,2021-01-20,Johannes !Gawaxab,Governor,Male,Bank of Namibia,NAM,Bank of Namibia TALKING POINTS BY THE GOVERNOR...,NaN,nam_0443cff3-e989-4905-b31e-5f506cdf6bff,English,CB websites
10792,NaN,https://www.bon.com.na/getattachment/05be25d6-...,Talking Points by Governor - 2021 Annual repor...,NaN,2022-03-31,Johannes !Gawaxab,Governor,Male,Bank of Namibia,NAM,"TALKING POINTS BY MR. JOHANNES IGAWAXAB, GOVER...",NaN,nam_05be25d6-7def-4bbd-8286-e5f55b5040e1,English,CB websites
10793,https://www.bon.com.na/getattachment/07e8ab71-...,https://www.bon.com.na/CMSTemplates/Bon/Files/...,Opening Remarks at Old and New Challenges on F...,NaN,2013-04-18,Ebson Uanguta,Deputy Governor,Male,Bank of Namibia,NAM,Bank of Namibia Opening Remarks: Old and New C...,NaN,nam_07e8ab71-1d91-4bd2-9877-7c79f483c989,English,CB websites
10794,NaN,https://www.bon.com.na/getattachment/0933b685-...,"Governor's Remarks - CMA Meeting, Swakopmund ...",NaN,2023-07-07,Johannes !Gawaxab,Governor,Male,Bank of Namibia,NAM,"Introductory remarks by Mr. Johannes IGawaxab,...",NaN,nam_0933b685-9830-4560-8061-235b4f2d8638,English,CB websites
10795,https://www.bon.com.na/getattachment/0be7e31b-...,https://www.bon.com.na/CMSTemplates/Bon/Files/...,Annual Address\r\n\r\n,NaN,2005-11-17,Tom K Alweendo,Governor,Male,Bank of Namibia,NAM,The role of financial regulatory bodies in inv...,NaN,nam_0be7e31b-b6f6-4453-99e9-e8bc7f3f024f,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24531,https://www.bis.org/review/r181130h.htm,https://www.bis.org/review/r181130h.pdf,Challenges facing Namibian economy,"Remarks by Mr Ipumbu Shiimi, Governor of the B...",2018-08-29,Ipumbu Shiimi,Governor,Male,Bank of Namibia,NAM,REMARKS AT CHEVENING ALUMNI EVENT Mr Iipumbu S...,NaN,r181130h,English,BIS
27392,http://www.bis.org/review/r221125h.htm,http://www.bis.org/review/r221125h.pdf,Johannes !Gawaxab: Maximising economic growth ...,"Remarks by Mr Johannes !Gawaxab, Governor of t...",2022-11-03,Johannes !Gawaxab,Governor,Male,Bank of Namibia,NAM,Johannes !Gawaxab: Maximising economic growth ...,NaN,r221125h,English,BIS
27393,https://www.bis.org/review/r221125i.htm,https://www.bis.org/review/r221125i.pdf,Talking points presidential visit to the Bank...,"Talking points by Mr Johannes Gawaxab, Govern...",2022-10-19,Johannes !Gawaxab,Governor,Male,Bank of Namibia,NAM,Johannes !Gawaxab: Talking points presidentia...,NaN,r221125i,English,BIS
27900,http://www.bis.org/review/r230913a.htm,http://www.bis.org/review/r230913a.pdf,Johannes !Gawaxab: Welcoming address - Meeting...,"Welcoming address by Mr Johannes !Gawaxab, Gov...",2023-09-08,Johannes !Gawaxab,Governor,Male,Bank of Namibia,NAM,Johannes !Gawaxab: Welcoming address - Meeting...,NaN,r230913a,English,BIS
28740,https://www.bis.org/review/r991123b.pdf,https://www.bis.org/review/r991123b.pdf,Mr Alweendo discusses Namibia's current exchan...,"Annual Speech 1999 given by Mr Tom K Alweendo,...",1999-11-17,Tom K Alweendo,Governor,Male,Bank of Namibia,NAM,Mr Alweendo discusses Namibias current exchang...,NaN,r991123b,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Namibia
Central Bank of Luxembourg

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10022,https://www.bcl.lu/en/publications/Speeches/ar...,NaN,The launch of the Central Bank in Luxembourg,NaN,1999-04-20,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,THE LAUNCH OF THE CENTRAL BANK IN LUXEMBOURG -...,LE LANCEMENT DE LA BANQUE CENTRALE LUXEMBOURG...,lux_36270_yves_mersch_french,French,CB websites
10023,https://www.bcl.lu/en/publications/Speeches/ar...,NaN,The European System of Central Banks from the ...,NaN,1999-05-13,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,THE EUROPEAN SYSTEM OF CENTRAL BANKS FROM THE ...,NaN,lux_36293_yves_mersch_english,English,CB websites
10024,https://www.bcl.lu/en/publications/Speeches/ar...,NaN,Central Banks in the Electronic Age,NaN,1999-06-25,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,CENTRAL BANKS IN THE ELECTRONIC AGE -YVES MERS...,LES BANQUES CENTRALES DANS L'RE LECTRONIQUE -Y...,lux_36336_yves_mersch_french,French,CB websites
10025,https://www.bcl.lu/en/publications/Speeches/ar...,NaN,The Banque centrale du Luxembourg and the fina...,NaN,1999-07-06,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,THE BANQUE CENTRALE DU LUXEMBOURG AND THE FINA...,LA BANQUE CENTRALE DU LUXEMBOURG ET LA PLACE F...,lux_36347_yves_mersch_french,French,CB websites
10026,https://www.bcl.lu/en/publications/Speeches/ar...,NaN,Nine months of experience in the European Syst...,NaN,1999-10-14,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,NINE MONTHS OF EXPERIENCE IN THE EUROPEAN SYST...,NEUN MONATE ERFAHRUNG IM EUROPISCHEN SYSTEM DE...,lux_36447_yves_mersch_german,German,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18846,https://www.bis.org/review/r111025b.pdf,https://www.bis.org/review/r111025b.pdf,Current challenges in the sovereign debt crisis,"Speech by Mr Yves Mersch, Governor of the Cent...",2011-10-24,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,Yves Mersch: Current challenges in the soverei...,NaN,r111025b,English,BIS
18855,https://www.bis.org/review/r111027b.pdf,https://www.bis.org/review/r111027b.pdf,Optimal currency area revisited,Text of the Pierre Werner Lecture by Mr Yves M...,2011-10-26,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,Yves Mersch: Optimal currency area revisited T...,NaN,r111027b,English,BIS
18907,https://www.bis.org/review/r111117d.pdf,https://www.bis.org/review/r111117d.pdf,Challenges of excessive indebtedness,"Keynote lecture by Mr Yves Mersch, Governor of...",2011-11-15,Yves Mersch,Governor,Male,Central Bank of Luxembourg,LUX,Yves Mersch: Challenges of excessive indebtedn...,NaN,r111117d,English,BIS
22009,https://www.bis.org/review/r151007e.htm,https://www.bis.org/review/r151007e.pdf,How to achieve stronger growth in the EU?,"Opening remarks by Mr Gaston Reinesch, Governo...",2015-09-09,Gaston Reinesch,Governor,Male,Central Bank of Luxembourg,LUX,Gaston Reinesch: How to achieve stronger growt...,NaN,r151007e,English,BIS
22178,https://www.bis.org/review/r151214h.htm,https://www.bis.org/review/r151214h.pdf,Beyond the horizon of the Luxembourg presidenc...,"Speech by Mr Gaston Reinesch, Governor of the ...",2015-10-27,Gaston Reinesch,Governor,Male,Central Bank of Luxembourg,LUX,Gaston Reinesch: Beyond the horizon of the Lux...,NaN,r151214h,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Namibia', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Luxembourg
Central Bank of Seychelles

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
23131,https://www.bis.org/review/r170324d.htm,https://www.bis.org/review/r170324d.pdf,Launching of the Financial Literacy Baseline S...,"Opening remarks by Ms Caroline Abel, Governor ...",2016-12-01,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,Launching of the Financial Literacy Baseline S...,NaN,r170324d,English,BIS
23133,https://www.bis.org/review/r170327d.htm,https://www.bis.org/review/r170327d.pdf,Development of the Seychelles' financial sector,"Opening speech by Ms Caroline Abel, Governor o...",2017-03-13,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,"Opening Speech by Ms Caroline Abel, Governor o...",NaN,r170327d,English,BIS
23232,https://www.bis.org/review/r170502e.htm,https://www.bis.org/review/r170502e.pdf,Financial leasing as an effective investment tool,"Welcoming remarks by Ms Caroline Abel, Governo...",2017-04-12,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,Seychelles Leasing Investment Forum Welcoming ...,NaN,r170502e,English,BIS
24039,https://www.bis.org/review/r180508a.htm,https://www.bis.org/review/r180508a.pdf,Launch of the Financial Markets Index,"Keynote address by Ms Caroline Abel, Governor ...",2018-04-12,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,Keynote Address by Ms Caroline Abel Governor o...,NaN,r180508a,English,BIS
24380,https://www.bis.org/review/r181018f.htm,https://www.bis.org/review/r181018f.pdf,Digital payments,"Opening remarks by MsCaroline Abel, Governor o...",2018-08-16,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,Opening Remarks by Ms Caroline Abel Governor o...,NaN,r181018f,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30133,NaN,https://www.cbs.sc/Downloads/publications/Spee...,Remarks - Guy Morel High Achievement Scholarsh...,NaN,2015-05-15,Jenifer Sullivan,Board member,Female,Central Bank of Seychelles,SYC,"Remarks by Ms Jenifer Sullivan, Second Deputy ...",NaN,syc_speech_delivered_by_the_sdg_on_the_occasio...,English,CB websites
30134,NaN,https://www.cbs.sc/Downloads/publications/Spee...,Opening Remarks - AML-CFT Webinar for Reportin...,NaN,2018-11-17,Jenifer Sullivan,Board member,Female,Central Bank of Seychelles,SYC,Addressed by Ms. Jenifer Sullivan Second Deput...,Ladres par Manmzel Jenifer Sullivan Dezyenm De...,syc_trwazyenm_diskisyon_ouver_ladig,Creole,CB websites
30135,NaN,https://www.cbs.sc/Downloads/publications/Spee...,Welcoming Remarks - CBS Board-Management Retre...,NaN,2019-05-27,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,Welcoming Remarks by Ms Caroline Abel Governor...,NaN,syc_welcoming_remarks_by_governor_-_regional_w...,English,CB websites
30136,NaN,https://www.cbs.sc/Downloads/publications/Spee...,Message - International Human Band Allocation,NaN,2020-02-16,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,Welcoming Remarks by Ms Caroline Abel Governor...,NaN,syc_welcoming_remarks_by_ms_caroline_abel_-_cb...,English,CB websites
30137,NaN,https://www.cbs.sc/Downloads/publications/Spee...,Welcoming Remarks - Capacity Building for Webs...,NaN,2016-11-04,Caroline Abel,Governor,Female,Central Bank of Seychelles,SYC,Launching of the Financial Literacy Baseline S...,NaN,syc_welcoming_speech_-_presentation_of_financi...,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Namibia', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Seychelles
Bank of Papua New Guinea

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12027,NaN,https://www.bankpng.gov.pg/wp-content/uploads/...,Address on the Update on the State of the PNG ...,CPA Conference Kokopo Speech 2014,2014-06-20,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,Update on the State of the PNG Economy Address...,NaN,png_2014_cpa_conference_kokopo_speech,English,CB websites
12028,NaN,https://www.bankpng.gov.pg/wp-content/uploads/...,Address on the Papua New Guinea Economic Persp...,PNG Update Economic Update Speech 2014,2014-06-01,Benny Popoitai,Deputy Governor,Male,Bank of Papua New Guinea,PNG,Papua New Guinea Economic Perspectives Address...,NaN,png_2014_png_update_economic_perspectives_speech,English,CB websites
12029,NaN,https://www.bankpng.gov.pg/wp-content/uploads/...,Opening of NBM Branch Waigani Central,Speech Opening of NBM Branch Waigani Central,2014-12-09,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,BANK OF PAPUA NEW GUINEA SPEECH ON THE OPENING...,NaN,png_20141210_speech_opening_of_nbm_branch_waig...,English,CB websites
12030,NaN,https://www.bankpng.gov.pg/wp-content/uploads/...,Address to the CIMC National Development Forum,"Address by Mr Loi Martin Bakani, CMG Governor,...",2015-07-01,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,"Mr Loi Martin Bakani, CMG Governor, Bank of Pa...",NaN,png_address_by_governor_to_the_cimc_1_july_2015,English,CB websites
12031,NaN,https://www.bankpng.gov.pg/wp-content/uploads/...,Address at the Annual Papua New Guinea Indepen...,Address By Governor Loi M. Bakani on the Annua...,2014-11-26,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,"Mr Loi Martin Bakani Governor, Bank of Papua N...",NaN,png_addressatpapuanewguineaindependencedayoration,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23120,https://www.bis.org/review/r170321a.htm,https://www.bis.org/review/r170321a.pdf,Improved finance for Papua New Guineans and th...,"Speech by Mr Loi M Bakani, Governor of the Ban...",2017-01-19,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,"SPEECH BY: Loi M Bakani CMG, Governor, Bank of...",NaN,r170321a,English,BIS
24024,https://www.bis.org/review/r180503e.htm,https://www.bis.org/review/r180503e.pdf,Bank of Papua New Guinea's achievements and mi...,"Speech by Mr Loi M Bakani, Governor of the Ban...",2017-11-04,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,Loi M Bakani: Bank of Papua New Guinea's achie...,NaN,r180503e,English,BIS
24278,https://www.bis.org/review/r180831g.htm,https://www.bis.org/review/r180831g.pdf,The inclusion imperatives - advancing policies...,"Keynote address by Mr Loi M Bakani, Governor o...",2018-06-27,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,Loi Bakani: The inclusion imperatives - advanc...,NaN,r180831g,English,BIS
26676,https://www.bis.org/review/r211214b.htm,https://www.bis.org/review/r211214b.pdf,The Online Finance Finder Portal Launch,"Speech by Mr Loi M Bakani, Governor of the Ban...",2021-08-11,Loi M Bakani,Governor,Male,Bank of Papua New Guinea,PNG,Loi M Bakani: The Online Finance Finder Portal...,NaN,r211214b,English,BIS
27371,http://www.bis.org/review/r221122e.htm,http://www.bis.org/review/r221122e.pdf,Benny B M Popoitai: Opening speech - Pacific F...,"Opening speech by Mr Benny B M Popoitai, Actin...",2022-11-16,Benny Popoitai,Deputy Governor,Male,Bank of Papua New Guinea,PNG,Benny B M Popoitai: Opening speech - Pacific F...,NaN,r221122e,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Namibia', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Papua New Guinea
Bank of Botswana

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1275,https://www.bankofbotswana.bw/sites/default/fi...,https://www.bankofbotswana.bw/sites/default/fi...,Launch of 2018 Monetary Policy Statement,NaN,2018-02-27,Moses D Pelaelo,Governor,Male,Bank of Botswana,BWA,BANK OF BOTSWANA 2018 MONETARY POLICY STATEMEN...,NaN,bwa_2018-mps-launch-feb-27--speech,English,CB websites
1276,https://www.bankofbotswana.bw/sites/default/fi...,https://www.bankofbotswana.bw/sites/default/fi...,The 40th Anniversary of BoB Wellcome Remarks,NaN,2017-03-17,Linah K Mohohlo,Governor,Female,Bank of Botswana,BWA,COMMEMORATION OF THE 40th ANNIVERSARY OF THE B...,NaN,bwa_40th_anniversary_governors_welcome_remarks,English,CB websites
1277,NaN,https://www.bankofbotswana.bw/sites/default/fi...,Keynote Remarks by Antoinette M Sayer - Deputy...,NaN,2022-06-13,Antoinette M Sayeh,Deputy Governor,Female,Bank of Botswana,BWA,"""Governance and Accountability in Africa: Prog...",NaN,bwa_antoinette_m_sayeh_44725_english,English,CB websites
1278,https://www.bankofbotswana.bw/sites/default/fi...,https://www.bankofbotswana.bw/sites/default/fi...,Official Opening of Tsabong Barclays Bank Branch,NaN,2001-07-18,Linah K Mohohlo,Governor,Female,Bank of Botswana,BWA,SPEECH FOR THE OFFICIAL OPENING OF TSABONG BAR...,NaN,bwa_barclays-tsabong-branch-open-july-18-2001,English,CB websites
1279,https://www.bankofbotswana.bw/sites/default/fi...,https://www.bankofbotswana.bw/sites/default/fi...,Botswana Stock Exchange A Platform for Econom...,NaN,2018-03-09,Moses D Pelaelo,Governor,Male,Bank of Botswana,BWA,BOTSWANA STOCK EXCHANGE - A PLATFORM FOR ECONO...,NaN,bwa_bse-conference--closing-remarks-march-8-2018,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25720,https://www.bis.org/review/r200811b.htm,https://www.bis.org/review/r200811b.pdf,Welcome remarks - 2020 Media Economic Briefing,"Welcome remarks by Mr Moses D Pelaelo, Governo...",2020-07-14,Moses D Pelaelo,Governor,Male,Bank of Botswana,BWA,BANK OF BOTSWANA 2020 MEDIA ECONOMIC Briefing ...,NaN,r200811b,English,BIS
26069,https://www.bis.org/review/r201223c.htm,https://www.bis.org/review/r201223c.pdf,Fostering diversification to escape the middle...,"Welcome remarks by Mr Moses D Pelaelo, Governo...",2020-02-06,Moses D Pelaelo,Governor,Male,Bank of Botswana,BWA,Botswana: Fostering Diversification to Escape ...,NaN,r201223c,English,BIS
26428,https://www.bis.org/review/r210722b.htm,https://www.bis.org/review/r210722b.pdf,Welcome remarks - 2021 Media Economic Briefing,"Welcome remarks by Mr Moses D Pelaelo, Governo...",2021-06-29,Moses D Pelaelo,Governor,Male,Bank of Botswana,BWA,Moses D Pelaelo: Welcome remarks - 2021 Media ...,NaN,r210722b,English,BIS
26635,https://www.bis.org/review/r211207e.htm,https://www.bis.org/review/r211207e.pdf,Botswana Stock Exchange opening bell ceremony,"Remarks by Mr Moses D Pelaelo, Governor of the...",2021-10-07,Moses D Pelaelo,Governor,Male,Bank of Botswana,BWA,BANK OF BOTSWANA BOTSWANA STOCK EXCHANGE OPENI...,NaN,r211207e,English,BIS
26780,http://www.bis.org/review/r220210c.htm,http://www.bis.org/review/r220210c.pdf,Moses D Pelaelo: Keynote speech at the opening...,"Keynote speech by Mr Moses D Pelaelo, Governor...",2022-02-03,Moses D Pelaelo,Governor,Male,Bank of Botswana,BWA,OFFICIAL OPENING OF ABSA BANK BOTSWANA LIMITED...,NaN,r220210c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Botswana
Saudi Central Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
14843,https://www.bis.org/review/r060627e.pdf,https://www.bis.org/review/r060627e.pdf,World class banking sector,"Speech by His Excellency Hamad Al-Sayari, Gove...",2006-05-09,Hamad Al-Sayari,Governor,Male,Saudi Central Bank,SAU,Hamad Al-Sayari: World class banking sector Sp...,NaN,r060627e,English,BIS
14905,https://www.bis.org/review/r060727c.pdf,https://www.bis.org/review/r060727c.pdf,A brief overview of the Saudi Arabian banking ...,"Speech by His Excellency Hamad Al-Sayari, Gove...",2006-05-06,Hamad Al-Sayari,Governor,Male,Saudi Central Bank,SAU,Hamad Al-Sayari: A brief overview of the Saudi...,NaN,r060727c,English,BIS
15120,https://www.bis.org/review/r061117f.pdf,https://www.bis.org/review/r061117f.pdf,Review of the Saudi Arabian economy,"Speech by His Excellency Hamad Al-Sayari, Gove...",2006-11-14,Hamad Al-Sayari,Governor,Male,Saudi Central Bank,SAU,Hamad Al-Sayari: Review of the Saudi Arabian e...,NaN,r061117f,English,BIS
15197,https://www.bis.org/review/r061220c.pdf,https://www.bis.org/review/r061220c.pdf,"The ""Banker"" program in Saudi Arabia","Speech by His Excellency Hamad Al-Sayari, Gove...",2006-11-28,Hamad Al-Sayari,Governor,Male,Saudi Central Bank,SAU,Hamad Al-Sayari: The Banker program in Saudi A...,NaN,r061220c,English,BIS
15198,https://www.bis.org/review/r061220d.pdf,https://www.bis.org/review/r061220d.pdf,Challenges posed to investment in Saudi banks,"Speech by His Excellency Hamad Al-Sayari, Gove...",2006-12-02,Hamad Al-Sayari,Governor,Male,Saudi Central Bank,SAU,Hamad Al-Sayari: Challenges posed to investmen...,NaN,r061220d,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28984,http://www.sama.gov.sa/en-US/News/Pages/news25...,NaN,"Launching Ceremony of the ""Sama Cares"" Initiative",NaN,2017-10-25,Ahmed Abdulkarim Alkholifey,Governor,Male,Saudi Central Bank,SAU,SPEECH BY THE GOVERNOR OF THE SAUDI ARABIAN MO...,NaN,sau_news25102017,English,CB websites
28985,http://www.sama.gov.sa/en-US/News/Pages/news26...,NaN,Annual 53 Report,NaN,2017-09-26,Ahmed Abdulkarim Alkholifey,Governor,Male,Saudi Central Bank,SAU,SAMA GOVERNORS SPEECH ON THE ANNUAL 53 REPORT ...,NaN,sau_news26092017,English,CB websites
28986,http://www.sama.gov.sa/en-US/News/Pages/news28...,NaN,Conference of Defense Ministers of the Islamic...,NaN,2017-11-28,Ahmed Abdulkarim Alkholifey,Governor,Male,Saudi Central Bank,SAU,THE SPEECH OF THE GOVERNOR OF THE SAUDI ARABIA...,NaN,sau_news28112017,English,CB websites
28987,http://www.sama.gov.sa/en-US/News/Pages/News29...,NaN,Announcement of the Public Budget for FY 1437/...,NaN,2015-12-29,Fahad Almubarak,Governor,Male,Saudi Central Bank,SAU,STATEMENT OF SAMAS GOVERNOR ON THE OCCASION OF...,NaN,sau_news29122015,English,CB websites
28988,http://www.sama.gov.sa/en-US/News/Pages/ViceGo...,NaN,Speech of the First Symposium on Insurance hel...,NaN,2011-04-19,Abdulrahman A Al-Hamidy,Deputy Governor,Male,Saudi Central Bank,SAU,Speech of His Excellency Vice Governor of Saud...,NaN,sau_vicegovernorsymposiumoninsurance,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Saudi Central Bank
Bank of Mozambique

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10454,https://www.presidencia.gov.mz/por/Informacao/...,NaN,Speech at the Launch of the New Family of Meti...,NaN,2006-01-12,Adriano Maleiane,Governor,Male,Bank of Mozambique,MOZ,INTERVENTION OF HIS EXCELLENCY THE GOVERNOR FR...,INTERVENO DE SUA EXCELNCIA O GOVERNADOR DO BAN...,moz_38729_adriano_maleiane,Portuguese,CB websites
10455,https://www.presidencia.gov.mz/por/Informacao/...,NaN,Speech at the 11th Meeting of Central Bank Jur...,NaN,2006-05-18,Adriano Maleiane,Governor,Male,Bank of Mozambique,MOZ,Representatives of the Central Banks of the CP...,Senhores Representantes dos Bancos Centrais da...,moz_38855__,Portuguese,CB websites
10456,https://www.presidencia.gov.mz/por/Informacao/...,NaN,End of the Economic Year 2007,NaN,2008-01-26,Ernesto Gouveia Gove,Governor,Male,Bank of Mozambique,MOZ,Presidents of the Boards of Commercial Banks; ...,NaN,moz_39473__,English,CB websites
10457,https://www.presidencia.gov.mz/por/Informacao/...,NaN,End of the Economic Year 2005,NaN,2008-02-10,Ernesto Gouveia Gove,Governor,Male,Bank of Mozambique,MOZ,Distinguished Guests; Ladies; Gentlemen In a f...,Distintos Convidados; Minhas Senhoras; Meus Se...,moz_39488__,Portuguese,CB websites
10458,https://www.presidencia.gov.mz/por/Informacao/...,NaN,End of the Economic Year 2008,NaN,2009-01-10,Ernesto Gouveia Gove,Governor,Male,Bank of Mozambique,MOZ,Members of the Board of Directors of the BM; P...,Senhores Membros do Conselho de Administrao do...,moz_39823__,Portuguese,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14954,https://www.bis.org/review/r060901a.pdf,https://www.bis.org/review/r060901a.pdf,Financial services efficiency in Mozambique,"Opening speech by Mr Adriano Maleiane, Governo...",2006-05-22,Adriano Maleiane,Governor,Male,Bank of Mozambique,MOZ,Adriano Maleiane: Financial services efficienc...,NaN,r060901a,English,BIS
14955,https://www.bis.org/review/r060901b.pdf,https://www.bis.org/review/r060901b.pdf,Notes and coins in Mozambique,"Speech by Mr Adriano Maleiane, Governor of the...",2006-06-16,Adriano Maleiane,Governor,Male,Bank of Mozambique,MOZ,Adriano Maleiane: Notes and coins in Mozambiqu...,NaN,r060901b,English,BIS
15357,https://www.bis.org/review/r070329d.pdf,https://www.bis.org/review/r070329d.pdf,The challenges in extending financial services...,"Speech by Mr Ernesto Gouveia Gove, Governor of...",2007-01-26,Ernesto Gouveia Gove,Governor,Male,Bank of Mozambique,MOZ,Ernesto Gouveia Gove: The challenges in extend...,NaN,r070329d,English,BIS
15358,https://www.bis.org/review/r070329e.pdf,https://www.bis.org/review/r070329e.pdf,Central Bank of Mozambique's review of 2006 an...,"Speech by Mr Ernesto Gouveia Gove, Governor of...",2006-12-20,Ernesto Gouveia Gove,Governor,Male,Bank of Mozambique,MOZ,Ernesto Gouveia Gove: Central Bank of Mozambiq...,NaN,r070329e,English,BIS
17902,https://www.bis.org/review/r100816c.pdf,https://www.bis.org/review/r100816c.pdf,"Reinforcement of ""South-South"" cooperation","Statement by Mr Ernesto Gouveia Gove, Governor...",2010-07-21,Ernesto Gouveia Gove,Governor,Male,Bank of Mozambique,MOZ,Ernesto Gouveia Gove: Reinforcement of SouthSo...,NaN,r100816c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Mozambique
Central Bank of Uruguay

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
19196,https://www.bis.org/review/r120328e.pdf,https://www.bis.org/review/r120328e.pdf,Financial stability nets - complementing and r...,"Speech by Mr Mario Bergara, Governor of the Ce...",2012-03-21,Mario Bergara,Governor,Male,Central Bank of Uruguay,URY,Mario Bergara: Financial stability nets compl...,NaN,r120328e,English,BIS
30915,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,Uruguay is prepared for the challenges posed b...,NaN,2015-12-16,Mario Bergara,Governor,Male,Central Bank of Uruguay,URY,December 16 Uruguay is prepared for challenges...,SPoourrtcaed=a%(/P2FaCgionmasu/nDiceafacuiolt....,ury_acde_diciembre_2015,Spanish,CB websites
30916,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,The new president of the Central Bank of Urugu...,NaN,2018-12-20,Alberto Grana,Governor,Male,Central Bank of Uruguay,URY,28 November 2018 The new president of the Cent...,SPourrtcaed=a%(/P2FaCgionmasu/nDiceafacuioltn....,ury_asumi,Spanish,CB websites
30917,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,A reflection on the transformation of the Stat...,NaN,2017-12-13,Mario Bergara,Governor,Male,Central Bank of Uruguay,URY,"December 13, 2017 A reflection on the transfor...",SPoourrtaced=a%(/P2FaCgionmasu/nDiceafacuioltn...,ury_bcu_opp_50anos,Spanish,CB websites
30918,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,Navigating in uncertainty requires understandi...,NaN,2017-07-26,Mario Bergara,Governor,Male,Central Bank of Uruguay,URY,"ADM Lunch Mario Bergara: ""Navigating uncertain...",SPourrtcaed=a%(/P2FaCgionmasu/nDiceafacuioltn....,ury_bergara_adm_2017,Spanish,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30987,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,The vice-president of the BCU spoke to car dea...,NaN,2022-07-26,Washington Ribeiro,Deputy Governor,Male,Central Bank of Uruguay,URY,"July 26, 2022 The vice president of the BCU sp...",26 de julio de 2022 El vicepresidente del BCU ...,ury_washington_ribeiro_44768,Spanish,CB websites
30988,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,The vice-president of the BCU highlighted the ...,NaN,2023-06-27,Washington Ribeiro,Deputy Governor,Male,Central Bank of Uruguay,URY,"June 27, 2023 The vice-president of the BCU st...",27 de junio de 2023 El vicepresidente del BCU ...,ury_washington_ribeiro_45104,Spanish,CB websites
30989,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,A panel moderated by the vice-president of the...,NaN,2023-08-24,Washington Ribeiro,Deputy Governor,Male,Central Bank of Uruguay,URY,"August 24, 2023 A panel moderated by the vice ...",24 de agosto de 2023 Un panel moderado por el ...,ury_washington_ribeiro_45162,Spanish,CB websites
30990,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,The vice-president of the BCU said that fintec...,NaN,2023-09-19,Washington Ribeiro,Deputy Governor,Male,Central Bank of Uruguay,URY,"September 19, 2023 The vice president of the B...",19 de septiembre de 2023 El vicepresidente del...,ury_washington_ribeiro_45188,Spanish,CB websites
30991,https://www.bcu.gub.uy/Comunicaciones/Paginas/...,NaN,The vice-president of the BCU spoke at the VII...,NaN,2023-11-24,Washington Ribeiro,Deputy Governor,Male,Central Bank of Uruguay,URY,"November 24, 2023 The vice-president of the BC...",24 de noviembre de 2023 El vicepresidente del ...,ury_washington_ribeiro_45254,Spanish,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Uruguay
Central Bank of Sri Lanka

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9945,NaN,https://www.cbsl.gov.lk/sites/default/files/cb...,Road Map 2020,NaN,2020-01-06,W D Lakshman,Governor,Male,Central Bank of Sri Lanka,LKA,Road Map: Monetary and Financial Sector Polici...,NaN,lka_43836_w_d_lakshman,English,CB websites
9946,NaN,https://www.cbsl.gov.lk/sites/default/files/cb...,Road Map 2021,NaN,2021-01-04,W D Lakshman,Governor,Male,Central Bank of Sri Lanka,LKA,Road Map 2021: Monetary and Financial Sector P...,NaN,lka_44200_w_d_lakshman,English,CB websites
9947,NaN,https://www.cbsl.gov.lk/sites/default/files/cb...,73rd Anniversary Oration of the Central Bank o...,NaN,2023-11-02,P Nandalal Weerasinghe,Governor,Male,Central Bank of Sri Lanka,LKA,CBSL 73 Anniversary Oration The Way Forward: P...,NaN,lka_speech_20231102_cbsl_73_anniversary_oration_e,English,CB websites
9948,NaN,https://www.cbsl.gov.lk/sites/default/files/cb...,"Keynote Speech By Dr Nandalal Weerasinghe, Gov...",NaN,2023-09-08,P Nandalal Weerasinghe,Governor,Male,Central Bank of Sri Lanka,LKA,Forum on Sri Lankas Sustainable Development Tr...,NaN,lka_speech_20231103_keynote_speech_at_the_foru...,English,CB websites
9949,NaN,https://www.cbsl.gov.lk/sites/default/files/cb...,Inaugural Remarks delivered by Dr. P. Nandala...,NaN,2023-10-27,P Nandalal Weerasinghe,Governor,Male,Central Bank of Sri Lanka,LKA,4th CBSL-ADBI-APAEA Workshop Monetary Policy a...,NaN,lka_speech_20231103_opening_remarks_at_cbsl_ad...,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23835,https://www.bis.org/review/r180118d.htm,https://www.bis.org/review/r180118d.pdf,Transforming Sri Lanka's export sector,"Speech by Dr Indrajit Coomaraswamy, Governor o...",2017-10-24,Indrajit Coomaraswamy,Governor,Male,Central Bank of Sri Lanka,LKA,Speech delivered by Dr. Indrajit Coomaraswamy ...,NaN,r180118d,English,BIS
23842,https://www.bis.org/review/r180123d.htm,https://www.bis.org/review/r180123d.pdf,Evolution of monetary and exchange rate policy...,"Speech by Dr P Nandalal Weerasinghe, Senior De...",2017-11-20,P Nandalal Weerasinghe,Deputy Governor,Male,Central Bank of Sri Lanka,LKA,Evolution of Monetary and Exchange Rate Policy...,NaN,r180123d,English,BIS
23849,https://www.bis.org/review/r180125b.htm,https://www.bis.org/review/r180125b.pdf,Road map - monetary and financial sector polic...,"Speech by Dr Indrajit Coomaraswamy, Governor o...",2018-01-03,Indrajit Coomaraswamy,Governor,Male,Central Bank of Sri Lanka,LKA,Road Map: Monetary and Financial Sector Polici...,NaN,r180125b,English,BIS
24635,https://www.bis.org/review/r190124b.htm,https://www.bis.org/review/r190124b.pdf,Road map - monetary and financial sector polic...,"Speech by Dr Indrajit Coomaraswamy, Governor o...",2019-01-02,Indrajit Coomaraswamy,Governor,Male,Central Bank of Sri Lanka,LKA,1 Road Map: Monetary and Financial Sector Poli...,NaN,r190124b,English,BIS
25248,https://www.bis.org/review/r191008k.htm,https://www.bis.org/review/r191008k.pdf,Social enterprise & social finance,"Keynote speech by Dr Indrajit Coomaraswamy, Go...",2019-01-28,Indrajit Coomaraswamy,Governor,Male,Central Bank of Sri Lanka,LKA,Keynote Speech made by Dr Indrajit Coomaraswam...,NaN,r191008k,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Sri Lanka
Croatian National Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7450,https://www.hnb.hr/-/11-savjetovanje-hrvatskog...,NaN,Current economic situation and monetary policy...,NaN,2003-11-17,Zeljko Rohatinski,Governor,Male,Croatian National Bank,HRV,Current economic situation and monetary policy...,HRVATSKA NARODNA BANKA Aktualna ekonomska situ...,hrv_11-savjetovanje-hrvatskog-drustva-ekonomis...,Croatian,CB websites
7451,https://www.hnb.hr/-/11-znanstveno-strucna-kon...,NaN,Monetary policy,NaN,2008-05-09,Zeljko Rohatinski,Governor,Male,Croatian National Bank,HRV,Monetary policy Published: 12/5/2008 Type Spee...,HRVATSKA NARODNA BANKA Monetarna politika Obja...,hrv_11-znanstveno-strucna-konferencija-hrvatsk...,Croatian,CB websites
7452,https://www.hnb.hr/-/12-savjetovanje-hrvatskog...,NaN,Monetary policy,NaN,2004-11-12,Zeljko Rohatinski,Governor,Male,Croatian National Bank,HRV,Monetary policy Published: 12.11.2004. Type Sp...,HRVATSKA NARODNA BANKA Monetarna politika Obja...,hrv_12-savjetovanje-hrvatskog-drustva-ekonomis...,Croatian,CB websites
7453,https://www.hnb.hr/-/12-znanstveno-strucna-kon...,NaN,Economic crisis and monetary policy,NaN,2009-05-14,Zeljko Rohatinski,Governor,Male,Croatian National Bank,HRV,Economic crisis and monetary policy Published:...,HRVATSKA NARODNA BANKA Ekonomska kriza i monet...,hrv_12-znanstveno-strucna-konferencija-hrvatsk...,Croatian,CB websites
7454,https://www.hnb.hr/-/13-znanstveno-strucna-kon...,NaN,Monetary policy in times of crisis,NaN,2010-04-12,Zeljko Rohatinski,Governor,Male,Croatian National Bank,HRV,Monetary policy in times of crisis Published: ...,HRVATSKA NARODNA BANKA Monetarna politika u vr...,hrv_13-znanstveno-strucna-konferencija-hrvatsk...,Croatian,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24573,https://www.bis.org/review/r181219f.htm,https://www.bis.org/review/r181219f.pdf,Macroeconomic developments and structural issu...,"Speech by Mr Boris Vuji, Governor of the Croat...",2018-11-09,Boris Vuji,Governor,Male,Croatian National Bank,HRV,Boris Vuji: Macroeconomic developments and str...,NaN,r181219f,English,BIS
27494,http://www.bis.org/review/r230207d.htm,http://www.bis.org/review/r230207d.pdf,Boris Vuji: Croatia's joining the euro area ma...,"Speech by Mr Boris Vuji, Governor of the Croat...",2023-01-24,Boris Vuji,Governor,Male,Croatian National Bank,HRV,Boris Vujcic: Croatia's joining the euro area ...,NaN,r230207d,English,BIS
27661,http://www.bis.org/review/r230427b.htm,http://www.bis.org/review/r230427b.pdf,Sandra valjek: Central banks - observers or le...,"Speech by Ms Sandra valjek, Deputy Governor of...",2023-03-09,Sandra valjek,Deputy Governor,Female,Croatian National Bank,HRV,Central banks: Observers or leaders of change?...,NaN,r230427b,English,BIS
27741,http://www.bis.org/review/r230606b.htm,http://www.bis.org/review/r230606b.pdf,"Boris Vuji: Resilience, adaptability, and coop...","Speech by Mr Boris Vuji, Governor of the Croat...",2023-06-03,Boris Vuji,Governor,Male,Croatian National Bank,HRV,"Boris Vuji: Resilience, adaptability, and coop...",NaN,r230606b,English,BIS
27821,http://www.bis.org/review/r230712i.htm,http://www.bis.org/review/r230712i.pdf,Boris Vuji: European finance in 2020s - new ri...,"Keynote speech by Mr Boris Vuji, Governor of t...",2023-06-29,Boris Vuji,Governor,Male,Croatian National Bank,HRV,Governor Boris Vujcic's speech at the FBF Exec...,NaN,r230712i,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Croatian National Bank
National Bank of Belgium

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
616,NaN,NaN,Ordinary General Meeting,NaN,2005-03-29,Guy Quaden,Governor,Male,National Bank of Belgium,BEL,Ordinary General Meeting of 29 March 2005 Intr...,Assembl<8e>e g<8e>n<8e>rale ordinaire du 29 ma...,bel_20050329_quaden_french,French and Dutch,Archives
617,NaN,NaN,SEPA Financial Forum Symposium,NaN,2006-05-30,Guy Quaden,Governor,Male,National Bank of Belgium,BEL,2006-05-30 FINANCIAL FORUM SYMPOSIUM ON SEPA K...,2006-05-30 COLLOQUE DU FORUM FINANCIER SUR LE ...,bel_20060530_french,French,Archives
618,NaN,NaN,What an economic and monetary europe,NaN,2006-05-31,Guy Quaden,Governor,Male,National Bank of Belgium,BEL,2006-05-31 WHAT ECONOMIC AND MONETARY EUROPE? ...,2006-05-31 QUELLE EUROPE <83>CONOMIQUE ET MON<...,bel_20060531_french,French,Archives
619,NaN,NaN,Monetary policy and the role of central banks ...,NaN,2006-10-26,Guy Quaden,Governor,Male,National Bank of Belgium,BEL,24/10/2006 DEPARTMENT OF STUDIES Cl.: I.A.4.e....,24/10/2006 D<83>PARTEMENT DES <83>TUDES Cl.: I...,bel_20061026_french,French,Archives
620,NaN,NaN,General Assembly 2007,NaN,2007-03-26,Guy Quaden,Governor,Male,National Bank of Belgium,BEL,2007-03-26 GENERAL MEETINGS 2007 Introductory ...,2007-03-26 ASSEMBLEE GENERALE 2007 Expos<8e> i...,bel_20070326_french,French and Dutch,Archives
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24344,https://www.bis.org/review/r181009i.htm,https://www.bis.org/review/r181009i.pdf,The future of central banking,"Keynote address by Mr Jan Smets, Governor of t...",2018-09-14,Jan Smets,Governor,Male,National Bank of Belgium,BEL,Jan Smets: The future of central banking Keyno...,NaN,r181009i,English,BIS
24585,https://www.bis.org/review/r181220k.htm,https://www.bis.org/review/r181220k.pdf,Central banks and money - an everchanging inte...,"Keynote address by Mr Jan Smets, Governor of t...",2018-11-30,Jan Smets,Governor,Male,National Bank of Belgium,BEL,1. Central Banks and money: an everchanging in...,NaN,r181220k,English,BIS
26978,http://www.bis.org/review/r220615h.htm,http://www.bis.org/review/r220615h.pdf,Pierre Wunsch: Household access to consumer cr...,"Keynote speech by Mr Pierre Wunsch, Governor o...",2022-06-14,Pierre Wunsch,Governor,Male,National Bank of Belgium,BEL,1. HOUSEHOLD ACCESS TO CONSUMER CREDIT AND MOR...,NaN,r220615h,English,BIS
27352,http://www.bis.org/review/r221118e.htm,http://www.bis.org/review/r221118e.pdf,"Pierre Wunsch: Germs, war and central banks","Public lecture by Mr Pierre Wunsch, Governor o...",2022-11-08,Pierre Wunsch,Governor,Male,National Bank of Belgium,BEL,"Germs, War and Central Banks Public Lecture by...",NaN,r221118e,English,BIS
28716,https://www.bis.org/review/r991022b.pdf,https://www.bis.org/review/r991022b.pdf,Mr Quaden addresses the impact of the single c...,"Speech by Mr Guy Quaden, Governor of the Natio...",1999-10-14,Guy Quaden,Governor,Male,National Bank of Belgium,BEL,Mr Quaden addresses the impact of the single c...,NaN,r991022b,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Belgium
Bank of Cabo Verde

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1936,https://www.bcv.cv/SiteCollectionDocuments/Pub...,NaN,BCV Governor's Speech,NaN,2004-12-31,Carlos Burgo,Governor,Male,Bank of Cabo Verde,CPV,Opening speech of the SEMINAR ATTF Page 1 of 2...,Discurso de abertura do seminario ATTF Page 1 ...,cpv_2004_carlos_burgo_portuguese,Portuguese,CB websites
1937,https://www.bcv.cv/SiteCollectionDocuments/Pub...,NaN,BCV Governor's Speech,NaN,2005-12-31,Carlos Burgo,Governor,Male,Bank of Cabo Verde,CPV,Governor's intervention in launching visa page...,Interveno do governador no lanamento do servio...,cpv_2005_carlos_burgo_portuguese,Portuguese,CB websites
1938,https://www.bcv.cv/SiteCollectionDocuments/Pub...,NaN,Speech on the occasion of the 1st Meeting of G...,NaN,2004-02-27,Carlos Burgo,Governor,Male,Bank of Cabo Verde,CPV,Untitled Document Page 1 of 2 Speech by the Go...,Untitled Document Page 1 of 2 Discurso do gove...,cpv_38044_carlos_burgo_portuguese,Portuguese,CB websites
1939,https://www.bcv.cv/SiteCollectionDocuments/Pub...,NaN,Speech at the opening of the 1st Assembly,NaN,2004-03-04,Carlos Burgo,Governor,Male,Bank of Cabo Verde,CPV,Untitled Document Page 1 of 2 Speech of the Go...,Untitled Document Page 1 of 2 Discurso do gove...,cpv_38050_carlos_burgo_portuguese,Portuguese,CB websites
1940,https://www.bcv.cv/SiteCollectionDocuments/Pub...,NaN,Speech at the AJOC Seminar - Association of Jo...,NaN,2004-05-02,Carlos Burgo,Governor,Male,Bank of Cabo Verde,CPV,Speech given by the Governor of the Bank of Ca...,Discurso proferido pelo Governador do Banco de...,cpv_38109_carlos_burgo_portuguese,Portuguese,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002,https://www.bcv.cv/SiteCollectionDocuments/201...,NaN,"Speech at the XXIX Lisbon Meeting, at the Gove...",NaN,2019-10-11,Joao Serra,Governor,Male,Bank of Cabo Verde,CPV,Implications of Technological Innovation in Fi...,Implicaes da Inovao Tecnolgica na Atividade Fi...,cpv_43749_joao_serra_portuguese,Portuguese,CB websites
2003,https://www.bcv.cv/pt/O%20Banco/Intervencoes/G...,NaN,Intervention at the inauguration act as Govern...,NaN,2021-01-08,Oscar Santos,Governor,Male,Bank of Cabo Verde,CPV,Intervention in the inauguration act as Govern...,Interveno no ato de tomada de posse como Gover...,cpv_44204_oscar_santos_portuguese,Portuguese,CB websites
2004,NaN,https://www.bcv.cv/SiteCollectionDocuments/202...,"Speech by the Governor, Dr. scar Santos, at th...",NaN,2022-03-15,Oscar Santos,Governor,Male,Bank of Cabo Verde,CPV,"Welcome message from the Governor, Dr. oscar S...","Mensagem de boas-vindas do Governador, Dr. sca...",cpv_44635_oscar_santos,Portuguese,CB websites
2005,NaN,https://www.bcv.cv/pt/O%20Banco/Intervencoes/G...,"Speech by the Governor, Dr. scar Santos, at th...",NaN,2022-03-18,Oscar Santos,Governor,Male,Bank of Cabo Verde,CPV,"Speech by the Governor, Dr. oscar Santos, at t...","Interveno do Governador, Dr. scar Santos, na t...",cpv_44638_oscar_santos,Portuguese,CB websites
2006,NaN,https://www.bcv.cv/pt/O%20Banco/Intervencoes/G...,"Speech by the Governor, Dr. scar Santos, ""From...",NaN,2022-06-10,Oscar Santos,Governor,Male,Bank of Cabo Verde,CPV,"Welcome from the Governor, Dr. oscar Santos, a...","Boas-vindas do Governador, Dr. scar Santos, na...",cpv_44722_oscar_santos,Portuguese,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Cabo Verde
Eastern Caribbean Central Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
11400,https://www.eccb-centralbank.org/content-manag...,NaN,Launch of the eastern caribbean partial credit...,NaN,2020-10-05,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,"STATEMENT BY TIMOTHY N. J. ANTOINE GOVERNOR, E...",NaN,oecs_eccblib-#988871-v1-governor_s_speech_-_la...,English,CB websites
11401,https://www.eccb-centralbank.org/content-manag...,NaN,4th growth and resilience dialogue,NaN,2020-02-13,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,"STATEMENT BY TIMOTHY N. J. ANTOINE GOVERNOR, E...",NaN,oecs_governor_antoine_s_speech_-_4th_growth_an...,English,CB websites
11402,https://www.eccb-centralbank.org/content-manag...,NaN,2017 christmas message,NaN,2017-12-01,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,2017 CHRISTMAS MESSAGE FROM TIMOTHY N. J. ANTO...,NaN,oecs_governor_s_speech_-_2017_christmas_message,English,CB websites
11403,https://www.eccb-centralbank.org/content-manag...,NaN,Opening of eccb 2nd annual conference with fin...,NaN,2020-11-12,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,OPENING REMARKS BY TIMOTHY N. J. ANTOINE GOVER...,NaN,oecs_governor_s_speech_-_2nd_conference_with_f...,English,CB websites
11404,https://www.eccb-centralbank.org/content-manag...,NaN,Second growth and resilience dialogue,NaN,2018-02-15,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,"STATEMENT BY TIMOTHY N. J. ANTOINE GOVERNOR, E...",NaN,oecs_governor_s_speech_-_2nd_growth_and_resili...,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20740,https://www.bis.org/review/r140205c.htm,https://www.bis.org/review/r140205c.pdf,The economics of nationhood - the political ec...,Text of the 8th Patrick Emmanuel Memorial Lect...,2013-11-21,K Dwight Venner,Governor,Male,Eastern Caribbean Central Bank,OECS,Sir K Dwight Venner: The economics of nationho...,NaN,r140205c,English,BIS
21679,https://www.bis.org/review/r150409e.htm,https://www.bis.org/review/r150409e.pdf,"Innovation, entrepreneurship and economic grow...","Speech by Sir K Dwight Venner, Governor of the...",2015-03-26,K Dwight Venner,Governor,Male,Eastern Caribbean Central Bank,OECS,"Sir K Dwight Venner: Innovation, entrepreneurs...",NaN,r150409e,English,BIS
24282,https://www.bis.org/review/r180903f.htm,https://www.bis.org/review/r180903f.pdf,Opening remarks - Single Insurance and Pension...,Opening remarks (by phone) by Mr Timothy N J A...,2018-07-02,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,Eastern Caribbean Central Bank OPENING REMARKS...,NaN,r180903f,English,BIS
25148,https://www.bis.org/review/r190911d.htm,https://www.bis.org/review/r190911d.pdf,Launch of the ECCU Public Debt and Market Info...,"Remarks by Mr Timothy N J Antoine, Governor of...",2019-07-23,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,Eastern Caribbean Central Bank REMARKS BY TIMO...,NaN,r190911d,English,BIS
27582,http://www.bis.org/review/r230316e.htm,http://www.bis.org/review/r230316e.pdf,Timothy N J Antoine: Launch of the ECCB's 40th...,"Opening remarks by Mr Timothy N J Antoine, Gov...",2023-01-19,Timothy N J Antoine,Governor,Male,Eastern Caribbean Central Bank,OECS,OPENING REMARKS BY GOVERNOR OF THE EASTERN CAR...,NaN,r230316e,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Eastern Caribbean Central Bank
Central Bank of Malta

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10441,https://www.centralbankmalta.org/site/News-Rel...,NaN,INTERVIEW: Banking on it,NaN,2021-04-07,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,"The Central Bank of Malta has a new Governor, ...",NaN,mlt_44293_edward_scicluna,English,CB websites
10442,https://www.centralbankmalta.org/en/news/14/20...,NaN,Governor discusses monetary policy with David ...,NaN,2021-10-11,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Interview with ECB Governing Council member Sc...,NaN,mlt_44480_edward_scicluna,English,CB websites
10443,https://www.centralbankmalta.org/en/news/14/20...,NaN,Resilience and financial stability in pandemic...,NaN,2021-12-03,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Address by the Governor of the Central Bank of...,NaN,mlt_44533_edward_scicluna,English,CB websites
10444,https://www.centralbankmalta.org/en/machine-le...,https://www.centralbankmalta.org/site/Governor...,Central Bank Governor concludes two-day Machin...,NaN,2023-07-07,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Concluding remarks by the Governor of the Cent...,NaN,mlt_gov-speech-machine-learning-workshop,English,CB websites
10445,https://www.centralbankmalta.org/en/fsr-2021-l...,https://www.centralbankmalta.org/site/Events/G...,Resilience in Uncertain Times Central Bank of...,NaN,2022-09-29,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Financial Stability Report 2021 Launch Resili...,NaN,mlt_governor-scicluna-fsr-welcome-address,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26427,https://www.bis.org/review/r210722a.htm,https://www.bis.org/review/r210722a.pdf,Price stability and beyond understanding the ...,"Speech by Mr Edward Scicluna, Governor of the ...",2021-07-20,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Edward Scicluna: Price stability and beyond u...,NaN,r210722a,English,BIS
27294,http://www.bis.org/review/r221104g.htm,http://www.bis.org/review/r221104g.pdf,Edward Scicluna: Central banks on the way out ...,"Speech by Mr Edward Scicluna, Governor of the ...",2022-10-31,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Edward Scicluna: Central banks on the way out ...,NaN,r221104g,English,BIS
27377,http://www.bis.org/review/r221123c.htm,http://www.bis.org/review/r221123c.pdf,Edward Scicluna: The ESG journey - a pulse che...,"Introductory speech by Prof Edward Scicluna, G...",2022-11-11,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Introductory Speech by Prof. Edward Scicluna G...,NaN,r221123c,English,BIS
27417,http://www.bis.org/review/r221205e.htm,http://www.bis.org/review/r221205e.pdf,Edward Scicluna: Pursuing price and financial ...,"Address by Prof Edward Scicluna, Governor of t...",2022-12-02,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Edward Scicluna: Pursuing price and financial ...,NaN,r221205e,English,BIS
28085,https://www.bis.org/review/r231127j.htm,https://www.bis.org/review/r231127j.pdf,Edward Scicluna: Direct transmission of tighte...,"Address by Prof Edward Scicluna, Governor of t...",2023-11-14,Edward Scicluna,Governor,Male,Central Bank of Malta,MLT,Edward Scicluna: Address - annual dinner of th...,NaN,r231127j,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Malta
Bank Al-Maghrib

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10073,NaN,https://www.bkam.ma/content/download/360912/30...,Testimony at the 10th International Colloquium...,NaN,2016-09-16,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,It is a real pleasure for me to respond to the...,C<d5>est un r<8e>el plaisir pour moi de r<8e>p...,mar_10+eme+colloque+des+fp+sept2016+_intervent...,French,CB websites
10074,NaN,https://www.bkam.ma/content/download/538553/56...,Closing remarks at the 11th international coll...,NaN,2017-09-16,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,11th International Symposium on Public Finance...,11<8f>me colloque international des finances p...,mar_11eme_colloque_des_fp_sept_2017_interventi...,French,CB websites
10075,NaN,https://www.bkam.ma/content/download/765434/85...,Third International Meeting on Social Protection,NaN,2022-07-26,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,Third International Meeting on Social protecti...,Troisime rencontre internationale sur La prote...,mar_abdellatif_jouahri_44768,French,CB websites
10076,https://www.bkam.ma/en/Speeches/2022/Opening-r...,https://www.bkam.ma/en/content/download/774089...,Opening remarks by the Director General during...,NaN,2022-11-28,Abderrahim Bouazza,Deputy Governor,Male,Bank Al-Maghrib,MAR,Regional Workshop on Cyber Resilience for Cent...,NaN,mar_abderrahim_bouazza_44893,English,CB websites
10077,https://www.bkam.ma/en/Speeches/2023/Opening-s...,https://www.bkam.ma/en/content/download/784535...,Opening speech by the Director General during ...,NaN,2023-05-16,Abderrahim Bouazza,Deputy Governor,Male,Bank Al-Maghrib,MAR,GLOBAL PAYMENTS WEEK2023 Opening speech By Mr ...,NaN,mar_abderrahim_bouazza_45062,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25157,https://www.bis.org/review/r190912b.htm,https://www.bis.org/review/r190912b.pdf,Opening remarks - Satellite Seminar on Financi...,"Opening remarks by Mr Abdellatif Jouahri, Gove...",2017-07-14,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,Satellite Seminar on Financial Inclusion held ...,NaN,r190912b,English,BIS
25158,https://www.bis.org/review/r190912c.htm,https://www.bis.org/review/r190912c.pdf,Digital transformation - Fintech opportunities...,"Intervention by Mr Abdellatif Jouahri, Governo...",2019-03-13,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,Digital Transformation Fintech opportunities a...,NaN,r190912c,English,BIS
25165,https://www.bis.org/review/r190912j.htm,https://www.bis.org/review/r190912j.pdf,Utilization of Public Credit Registry data for...,"Opening remarks by Mr Abdellatif Jouahri, Gove...",2018-02-22,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,Regional seminar of the International Financia...,NaN,r190912j,English,BIS
25747,https://www.bis.org/review/r200817e.htm,https://www.bis.org/review/r200817e.pdf,"Central banks, financial inclusion and digitiz...","Speech by Mr Abdellatif Jouahri, Governor of t...",2019-12-13,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,Financial Integration and Inclusive Developmen...,NaN,r200817e,English,BIS
26749,https://www.bis.org/review/r211230q.htm,https://www.bis.org/review/r211230q.pdf,Woman on Boards - key issues and challenges in...,"Speech by Mr Abdellatif Jouahri, Governor of B...",2021-11-14,Abdellatif Jouahri,Governor,Male,Bank Al-Maghrib,MAR,EXPO 2020 DUBAI WOMEN ON BOARDS KEY ISSUES AND...,NaN,r211230q,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank Al-Maghrib
Bank of Slovenia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
21246,https://www.bis.org/review/r141006a.htm,https://www.bis.org/review/r141006a.pdf,"Reinvigorating credit growth in central, easte...","Opening remarks by Mr Botjan Jazbec, Governor ...",2014-09-25,Bostian Jazbec,Governor,Male,Bank of Slovenia,SVN,Bostjan Jazbec: Reinvigorating credit growth i...,NaN,r141006a,English,BIS
21546,https://www.bis.org/review/r150205e.htm,https://www.bis.org/review/r150205e.pdf,Financial crises and the current situation in ...,"Address by Mr Botjan Jazbec, Governor of Bank ...",2014-11-18,Bostian Jazbec,Governor,Male,Bank of Slovenia,SVN,Bostjan Jazbec: Financial crises and the curre...,NaN,r150205e,English,BIS
22486,https://www.bis.org/review/r160526c.htm,https://www.bis.org/review/r160526c.pdf,Rethinking monetary-fiscal policy coordination,"Opening remarks by Mr Bostjan Jazbec, Governor...",2016-05-19,Bostian Jazbec,Governor,Male,Bank of Slovenia,SVN,Bostjan Jazbec: Rethinking monetary-fiscal pol...,NaN,r160526c,English,BIS
22632,https://www.bis.org/review/r160725a.htm,https://www.bis.org/review/r160725a.pdf,The bail-in tool and the challenges to its smo...,"Address given by Mr Bostjan Jazbec, Governor o...",2016-07-14,Bostian Jazbec,Governor,Male,Bank of Slovenia,SVN,Bostjan Jazbec: The bail-in tool and the chall...,NaN,r160725a,English,BIS
27104,http://www.bis.org/review/r220906d.htm,http://www.bis.org/review/r220906d.pdf,Tina umer: Steps forward in normalising intere...,"Keynote speech by Ms Tina umer, Deputy Governo...",2022-06-21,Tina umer,Deputy Governor,Female,Bank of Slovenia,SVN,"Keynote speech by Tina Zumer, Deputy Governor ...",NaN,r220906d,English,BIS
27560,http://www.bis.org/review/r230308m.htm,http://www.bis.org/review/r230308m.pdf,Botjan Vasle: Opening address for Governor Mad...,"Opening address by Mr Botjan Vasle, Governor o...",2023-03-03,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Bostjan Vasle: Opening address for Governor Ma...,NaN,r230308m,English,BIS
27654,http://www.bis.org/review/r230425q.htm,http://www.bis.org/review/r230425q.pdf,Botjan Vasle: Introducing the euro in times of...,"Opening speech by Mr Botjan Vasle, Governor of...",2023-04-20,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Bostjan Vasle: Introducing the Euro in times o...,NaN,r230425q,English,BIS
27785,http://www.bis.org/review/r230622n.htm,http://www.bis.org/review/r230622n.pdf,Botjan Vasle: Controlling inflationary pressur...,"Speech by Mr Botjan Vasle, Governor of Bank of...",2023-06-02,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Bostjan Vasle: Introducing the euro in times o...,NaN,r230622n,English,BIS
27837,http://www.bis.org/review/r230718v.htm,http://www.bis.org/review/r230718v.pdf,Tina umer: Keynote speech - Green Finance conf...,"Keynote speech by Ms Tina umer, Deputy Governo...",2023-06-23,Tina umer,Deputy Governor,Female,Bank of Slovenia,SVN,Tina Zumer: Keynote speech - Green Finance con...,NaN,r230718v,English,BIS
27848,http://www.bis.org/review/r230731h.htm,http://www.bis.org/review/r230731h.pdf,Botjan Vasle: Introductory remarks - 9th Europ...,"Introductory remarks by Mr Botjan Vasle, Gover...",2023-07-17,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Bostjan Vasle: Introductory remarks - 9th Euro...,NaN,r230731h,English,BIS
28138,https://www.bis.org/review/r231218b.htm,https://www.bis.org/review/r231218b.pdf,Botjan Vasle: Digital euro - cash meets techno...,"Opening speech by Mr Botjan Vasle, Governor of...",2023-12-15,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Bostjan Vasle: Digital euro - cash meets techn...,NaN,r231218b,English,BIS
29750,https://www.bsi.si/en/media/448/speech-by-mitj...,NaN,Speech at the international conference on the ...,NaN,2006-10-26,Mitja Gaspari,Governor,Male,Bank of Slovenia,SVN,"Speech by Mitja Gaspari, Governor of the Bank ...",NaN,svn_39016_english,English,CB websites
29751,https://www.bsi.si/en/media/436/speech-by-mitj...,NaN,Speech at the conference Slovenia 2007,NaN,2007-01-15,Mitja Gaspari,Governor,Male,Bank of Slovenia,SVN,"Speech by Mitja Gaspari, Governor of the Bank ...",NaN,svn_39097_english,English,CB websites
29752,https://bankaslovenije.blob.core.windows.net/u...,NaN,Address by the Governor of the Bank of Slovenia,NaN,2017-11-06,Bostian Jazbec,Governor,Male,Bank of Slovenia,SVN,Bostjan Jazbec ADDRESS BY THE GOVERNOR OF THE ...,NaN,svn_43045_english,English,CB websites
29753,https://www.bsi.si/en/media/1359/speech-by-bos...,NaN,Speech at the Banking conference,NaN,2019-05-29,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,"Speech by Bostjan Vasle, the Governor of the B...",NaN,svn_43614_english,English,CB websites
29754,https://www.bsi.si/en/media/1418/speech-by-the...,NaN,Speech at the Slovenian Bankers Day,NaN,2019-11-08,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Speech by the Governor Bostjan Vasle at the Sl...,NaN,svn_43777_english,English,CB websites
29755,https://www.bsi.si/en/media/1610/governors-sta...,NaN,Statement following the ECB monetary policy me...,In the face of the challenges presented by the...,2021-01-22,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement following the ECB monetary...,NaN,svn_44218_english,English,CB websites
29756,https://www.bsi.si/en/media/1614/governors-sta...,NaN,Statement: Eurosystems commitment to sustainab...,The central banks of the Eurosystem are aware ...,2021-02-04,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement: Eurosystems commitment to...,NaN,svn_44231_english,English,CB websites
29757,https://www.bsi.si/en/media/1635/governors-sta...,NaN,Statement following the meeting of the Governi...,As the recovery strengthens in the second half...,2021-03-12,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement following the meeting of t...,NaN,svn_44267_english,English,CB websites
29758,https://www.bsi.si/en/media/1659/governors-sta...,NaN,Statement following the ECBs monetary policy m...,The outlook for economic growth is improving i...,2021-04-23,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement following the ECBs monetar...,NaN,svn_44309_english,English,CB websites
29759,https://www.bsi.si/en/media/1681/governors-sta...,NaN,Statement following the ECBs monetary policy m...,With what is now a more favourable epidemiolog...,2021-06-11,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement following the ECBs monetar...,NaN,svn_44358_english,English,CB websites
29760,https://www.bsi.si/en/media/1694/governors-sta...,NaN,Statement following the meeting of the Governi...,Euro area central bank governors approved a ne...,2021-07-09,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement following the meeting of t...,NaN,svn_44386_english,English,CB websites
29761,https://www.bsi.si/en/media/1702/governors-sta...,NaN,Statement following the meeting of the Governi...,The economic picture in the euro area improved...,2021-07-23,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement following the meeting of t...,NaN,svn_44400_english,English,CB websites
29762,https://www.bsi.si/en/speeches-and-interviews/...,NaN,On digital euro,Content only in Slovene,2021-08-16,Joef Bradeko,Deputy Governor,Male,Bank of Slovenia,SVN,Vice governor Jozef Bradesko about digital eur...,Vice governor Joef Bradeko about digital euro ...,svn_44424_slovene,Slovenian,CB websites
29763,https://www.bsi.si/en/media/1717/opening-speec...,NaN,Opening speech on The Eurofi Financial Forum 2021,Governor Botjan Vasle had opening speech on Th...,2021-09-08,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Opening speech by governor on The Eurofi Finan...,NaN,svn_44447_english,English,CB websites
29764,https://www.bsi.si/en/media/1718/governors-sta...,NaN,Statement following the ECBs monetary policy m...,"In the second quarter of this year, the euro a...",2021-09-10,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors statement following the ECBs monetar...,NaN,svn_44449_english,English,CB websites
29765,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Interview for Eurofi magazin,Governer Botjan Vasle for Eurofi magazin,2021-09-21,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governer's interview for Eurofi magazin 09/21/...,NaN,svn_44460_english,English,CB websites
29766,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Address at the celebration of Banka Slovenijes...,"Cankarjev dom, 7 October 2021",2021-10-08,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,"Address by Bostjan Vasle, governor of Banka Sl...",NaN,svn_44477_english,English,CB websites
29767,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Globalisation and inflation: Insights from the...,"Article written by Tina umer, Vice Governor BS...",2021-10-14,Tina umer,Deputy Governor,Female,Bank of Slovenia,SVN,Globalisation and inflation: Insights from the...,NaN,svn_44483_english,English,CB websites
29768,https://www.bsi.si/en/speeches-and-interviews/...,NaN,How prepared is the Slovenian banking system t...,"Delo, Sobotna priloga, 16. oktober 2021 dr. P...",2021-10-18,Primo Dolenc,Deputy Governor,Male,Bank of Slovenia,SVN,How ready is the Slovenian banking system to d...,Kako pripravljen je slovenski banni sistem za ...,svn_44487_slovene,Slovenian,CB websites
29769,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Speech at Slovenian Bankers Day,Governor Botjan Vasle was speaking to attendee...,2021-11-24,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors speech at Slovenian Bankers Day 11/2...,NaN,svn_44524_english,English,CB websites
29770,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Editorial to the special issue of Banni vestnik,"The role, opportunities and challenges of the ...",2021-11-25,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governors editorial to the special issue of Ba...,NaN,svn_44525_english,English,CB websites
29771,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Article by Deputy Governor Primo Dolenc in Man...,Content in Slovene only.,2021-12-24,Primo Dolenc,Deputy Governor,Male,Bank of Slovenia,SVN,Article by Deputy Governor Primoz Dolenc in Ma...,Article by Deputy Governor Primo Dolenc in Man...,svn_44554_slovene,Slovenian,CB websites
29772,https://www.bsi.si/en/speeches-and-interviews/...,NaN,The magazine was published at the Eurofi Finan...,NaN,2022-02-23,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Article by Governor...,NaN,svn_44615,English,CB websites
29773,https://www.bsi.si/en/speeches-and-interviews/...,NaN,"Address by Tina umer, Deputy Governor of the B...",NaN,2022-06-01,Tina umer,Deputy Governor,Female,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Keynote speech by T...,NaN,svn_44713,English,CB websites
29774,https://www.bsi.si/govori-in-intervjuji/1858/k...,NaN,"Address by Tina umer, Deputy Governor of the B...",NaN,2022-06-16,Tina umer,Deputy Governor,Female,Bank of Slovenia,SVN,"Address by Tina zumer, Deputy Governor of the ...","Nagovor Tine umer, namestnice guvernerja Banke...",svn_44728,Slovenian,CB websites
29775,https://www.bsi.si/govori-in-intervjuji/1869/s...,NaN,Address by Governor Botjan Vaslet at the prese...,NaN,2022-07-04,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Address by Governor Bostjan Vasle at the prese...,Nagovor guvernerja Botjana Vasleta na predstav...,svn_44746,Slovenian,CB websites
29776,https://www.bsi.si/en/media/1897/governors-sta...,NaN,Governor statement following the Governing Cou...,NaN,2022-09-09,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Governors statement...,NaN,svn_44813,English,CB websites
29777,https://www.bsi.si/govori-in-intervjuji/1899/k...,NaN,"Deputy Governor Tina umer, Deputy Governor, pr...",NaN,2022-09-12,Tina umer,Deputy Governor,Female,Bank of Slovenia,SVN,"Address by Tina zumer, Deputy Governor, at the...","Nagovor Tine umer, namestnice guvernerja, na K...",svn_44816,Slovenian,CB websites
29778,https://www.bsi.si/govori-in-intervjuji/1903/t...,NaN,Governor for Saturday's annex Governor Botjan ...,NaN,2022-09-19,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governor's interview for Saturday's Supplement...,Intervju guvernerja za Sobotno prilogo 19.09.2...,svn_44823,Slovenian,CB websites
29779,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Address by Governor Botjan Vaslet at the Green...,NaN,2022-09-29,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EV R OS I ST E M Opening remar...,NaN,svn_44833,English,CB websites
29780,https://www.bsi.si/govori-in-intervjuji/1914/n...,NaN,Primo Dolenc's address at the Expert Meeting o...,NaN,2022-10-05,Primo Dolenc,Deputy Governor,Male,Bank of Slovenia,SVN,Address by Primoz Dolenc at the Expert Meeting...,Nagovor Primoa Dolenca na Strokovnem sreanju l...,svn_44839,Slovenian,CB websites
29781,https://www.bsi.si/govori-in-intervjuji/1917/u...,NaN,Opening remarks by Vice-Governor Joef Bradeek ...,NaN,2022-10-12,Joef Bradeek,Deputy Governor,Male,Bank of Slovenia,SVN,Introductory address by Vicegovernor Jozef Bra...,Uvodni nagovor viceguvernerja Joefa Bradeka na...,svn_44846,Slovenian,CB websites
29782,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Primo Dolenc's address at the ACI General Meet...,NaN,2022-10-24,Primo Dolenc,Deputy Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Keynote speech by P...,NaN,svn_44858,English,CB websites
29783,https://www.bsi.si/govori-in-intervjuji/1944/n...,NaN,Address by the Governor on the presentation of...,NaN,2022-11-21,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Address by the Governor at the presentation of...,Nagovor guvernerja ob predstavitvi ugotovitev ...,svn_44886,Slovenian,CB websites
29784,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Address by the Governor at the event Bulgaria ...,NaN,2022-12-09,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Governor's address ...,NaN,svn_44904,English,CB websites
29785,https://www.bsi.si/en/media/1959/governors-sta...,NaN,Governor statement following the Governing Cou...,NaN,2022-12-16,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Governors statement...,NaN,svn_44911,English,CB websites
29786,https://www.bsi.si/en/media/1986/governors-sta...,NaN,Governor's statement following the monetary me...,NaN,2023-02-03,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Governors statement...,NaN,svn_44960,English,CB websites
29787,https://www.bsi.si/govori-in-intervjuji/2027/u...,NaN,Opening remarks by Governor Botjan Vaslet at t...,NaN,2023-03-28,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Introductory address by Governor Bostjan Vasle...,Uvodni nagovor guvernerja Botjana Vasleta na r...,svn_45013,Slovenian,CB websites
29788,https://www.bsi.si/en/media/2045/governors-sta...,NaN,Statement by the Governor following the Govern...,NaN,2023-05-05,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Governors statement...,NaN,svn_45051,English,CB websites
29789,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Governor's contribution on the occasion of the...,NaN,2023-05-30,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Governors contribut...,NaN,svn_45076,English,CB websites
29790,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Address by Primo Dolenc at the General Meeting...,NaN,2023-06-12,Primo Dolenc,Deputy Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Keynote speech by P...,NaN,svn_45089,English,CB websites
29791,https://www.bsi.si/en/speeches-and-interviews/...,NaN,Opening remarks by Deputy Governor Primo Dolen...,NaN,2023-09-29,Primo Dolenc,Deputy Governor,Male,Bank of Slovenia,SVN,BANKA SLOVENIJE EVROSISTEM Opening speech by D...,NaN,svn_45198,English,CB websites
29792,https://www.bsi.si/govori-in-intervjuji/2129/n...,NaN,Address by the Governor on the handover of the...,NaN,2023-10-03,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Address by the Governor at the Presentation of...,Nagovor guvernerja ob predaji zbirateljskega k...,svn_45202,Slovenian,CB websites
29793,https://www.bsi.si/govori-in-intervjuji/2130/n...,NaN,Address by the Governor at Open Day Meet the B...,NaN,2023-10-04,Botjan Vasle,Governor,Male,Bank of Slovenia,SVN,Governor's address at the Open Day Meet the Ba...,Nagovor guvernerja na dnevu odprtih vrat Spozn...,svn_45203,Slovenian,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Slovenia
Central Bank of Argentina

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
464,http://bcra.gob.ar/Noticias/Discurso_apertura_...,NaN,Opening speech at the 2016 Money and Banking C...,NaN,2016-09-19,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Opening speech at the 2016 Money and Banking I...,NaN,arg_discurso_apertura_jmb_2016_i,English,CB websites
465,http://bcra.gob.ar/Noticias/Discurso_Sturzeneg...,NaN,Speech on the XXII Argentine Industrial Confer...,NaN,2016-11-22,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Index News (Noticias_i.asp) Federico Sturzeneg...,NaN,arg_discurso_sturzenegger_22_congreso_uia_i,English,CB websites
466,http://bcra.gob.ar/Noticias/Discurso_Sturzeneg...,NaN,Speech at the 32nd International Congress for ...,Towards an Inflation target regime,2016-09-05,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Index Speeches Federico Sturzeneggers Speech F...,NaN,arg_discurso_sturzenegger_32_%20congreso_marke...,English,CB websites
467,http://bcra.gob.ar/Noticias/El%20_Vicepresiden...,NaN,Speech in the commemorative meeting of the 39t...,Closing speech by the Governor of the Central ...,2016-09-08,Lucas Llach,Deputy Governor,Male,Central Bank of Argentina,ARG,Speech by Luchas Lach Deputy Governor of the C...,NaN,arg_el_vicepresidente_bcra_reunion_mediterrane...,English,CB websites
468,http://bcra.gob.ar/Noticias/Federico_Sturzeneg...,NaN,Speech at Argentina Business & Investment Forum,NaN,2016-09-14,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Federico Sturzenegger at Argentina Business & ...,NaN,arg_federico_sturzenegger_en_el_foro_de_invers...,English,CB websites
469,http://bcra.gob.ar/Noticias/Federico_Sturzeneg...,NaN,Speech at the XXI Global Economics Symposium,NaN,2016-08-30,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Federico Sturzenegger at the XXI Global Econom...,NaN,arg_federico_sturzenegger_en_el_simposio_inter...,English,CB websites
470,http://bcra.gob.ar/Noticias/Federico_Sturzeneg...,NaN,Speech in the XVII Jacques Polak Annual Resear...,NaN,2016-11-04,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Federico Sturzenegger in the XVII Jacques Pola...,NaN,arg_federico_sturzenegger_en_la_conferencia_an...,English,CB websites
471,http://bcra.gob.ar/Noticias/Federico_Sturzeneg...,NaN,Federico Sturzenegger closed the 13th Internat...,NaN,2016-08-18,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Maria Eugenia Molinero (../default.asp) Index ...,NaN,arg_federico_sturzenegger_en_la_unlp_i,English,CB websites
472,http://bcra.gob.ar/Noticias/FS_apertura_JJMM_2...,NaN,Opening Speech at the 2017 Money and Banking C...,NaN,2017-09-05,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,(../default.asp) Index News Opening Speech Giv...,NaN,arg_fs_apertura_jjmm_2017,English,CB websites
473,http://bcra.gob.ar/Noticias/FS_CAMARCO_post_i.asp,NaN,Speech at the 65th Annual Convention of the Ar...,NaN,2017-10-05,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Index News (Noticias_i.asp) Speech by the Gove...,NaN,arg_fs_camarco_post_i,English,CB websites
474,http://bcra.gob.ar/Noticias/FS_CPCE_post_i.asp,NaN,Address at the 12th National Conference on the...,NaN,2017-08-30,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Index News (Noticias_i.asp) Address by the Gov...,NaN,arg_fs_cpce_post_i,English,CB websites
475,http://bcra.gob.ar/Noticias/FS_Expo_Real_Estat...,NaN,Address at the Expo Real Estate Argentina 2017,NaN,2017-08-23,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Index News (Noticias_i.asp) Address by the Gov...,NaN,arg_fs_expo_real_estate_argentina_i,English,CB websites
476,http://bcra.gob.ar/Noticias/FS_world_Bank_abri...,NaN,Speech at RAMP Executive Forum,NaN,2018-04-23,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,(../default.asp) Governors Speech RAMP Executi...,NaN,arg_fs_world_bank_abril_2018_i,English,CB websites
477,http://bcra.gob.ar/Noticias/Presentacion_de_De...,NaN,Presentation in the XXXVII Annual Conference a...,NaN,2016-09-29,Demian Reidel,Deputy Governor,Male,Central Bank of Argentina,ARG,Demian Reidel Presentation in the XXXVII Annua...,NaN,arg_presentacion_de_demian_reidel_en_la_37_con...,English,CB websites
478,http://bcra.gob.ar/Noticias/Speech-on-Aprils-C...,NaN,Speech on Aprils CPI,"Federico Sturzenegger, governor of the Central...",2019-05-15,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Speech on Aprils Index Speeches CPI Speech on ...,NaN,arg_speech-on-aprils-cpi,English,CB websites
479,http://bcra.gob.ar/Noticias/Sturzenegger_Camar...,NaN,"Address at the Argentine Chamber of Exporters,...",NaN,2017-08-16,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Index News (Noticias_i.asp) Address by the Gov...,NaN,arg_sturzenegger_camara_exportadores_post_i,English,CB websites
480,http://bcra.gob.ar/Noticias/Sturzenegger_en_FE...,NaN,Speech at the Latin American Federation of Ban...,NaN,2016-11-08,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Federico Sturzenegger at the Latin American Fe...,NaN,arg_sturzenegger_en_felaban_i,English,CB websites
481,http://bcra.gob.ar/Noticias/Sturzenegger_en_ID...,NaN,Speech at the Institute for Business Developme...,NaN,2016-10-14,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Federico Sturzenegger at the Institute for Bus...,NaN,arg_sturzenegger_en_idea_i,English,CB websites
482,http://bcra.gob.ar/Noticias/Sturzenegger_en_la...,NaN,Speech at the Latin American Economic Research...,NaN,2016-09-29,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Federico Sturzenegger at the Latin American Ec...,NaN,arg_sturzenegger_en_la_fundacion_de_investigac...,English,CB websites
483,http://bcra.gob.ar/Noticias/Sturzenegger_reina...,NaN,Speech at the act of reinauguration of Banco C...,"Federico Sturzenegger, Governor of the Central...",2016-08-18,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Federico Sturzenegger at the act of reinaugura...,NaN,arg_sturzenegger_reinauguracion_casa_matriz_ba...,English,CB websites
484,http://bcra.gob.ar/Noticias/Sturzenegger_XX_Ta...,NaN,Speech at the closing of the XX Workshop in In...,NaN,2017-03-21,Federico Sturzenegger,Governor,Male,Central Bank of Argentina,ARG,Index News (Noticias_i.asp) Federico Sturzeneg...,NaN,arg_sturzenegger_xx_taller_post_i,English,CB websites
13876,https://www.bis.org/review/r041001e.pdf,https://www.bis.org/review/r041001e.pdf,The new Central Bank of Argentina's Governor a...,"Ceremony to introduce Mr Martn Redrado, the ne...",2004-09-24,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: The new Central Bank of Argent...,NaN,r041001e,English,BIS
13925,https://www.bis.org/review/r041028c.pdf,https://www.bis.org/review/r041028c.pdf,Central Bank of Argentina's key mission for th...,"Speech by Mr Martn Redrado, Governor of the Ce...",2004-10-05,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Central Bank of Argentinas key...,NaN,r041028c,English,BIS
14532,https://www.bis.org/review/r051209d.pdf,https://www.bis.org/review/r051209d.pdf,Protecting financial systems from abuse - expe...,"Presentation by Mr Martn P Redrado, Governor o...",2005-09-23,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin P Redrado: Protecting financial systems...,NaN,r051209d,English,BIS
14779,https://www.bis.org/review/r060602c.pdf,https://www.bis.org/review/r060602c.pdf,The hemispheric growth agenda - financial and ...,"Speech by Mr Martn Redrado, President of the C...",2006-05-03,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: The hemispheric growth agenda ...,NaN,r060602c,English,BIS
15244,https://www.bis.org/review/r070119c.pdf,https://www.bis.org/review/r070119c.pdf,Overview of monetary and financial policy in A...,"Speech by Mr Martn Redrado, President of the C...",2006-12-20,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Overview of monetary and finan...,NaN,r070119c,English,BIS
15286,https://www.bis.org/review/r070223c.pdf,https://www.bis.org/review/r070223c.pdf,Financial stability and the importance of AML/...,"Speech by Mr Martn Redrado, Governor of the Ce...",2007-02-13,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Financial stability and the im...,NaN,r070223c,English,BIS
15519,https://www.bis.org/review/r070608c.pdf,https://www.bis.org/review/r070608c.pdf,"Opening address at the conference ""Monetary Po...","Opening address by Mr Martn Redrado, Governor ...",2007-06-04,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Opening address at the confere...,NaN,r070608c,English,BIS
15570,https://www.bis.org/review/r070627d.pdf,https://www.bis.org/review/r070627d.pdf,Financial intermediation through institutions ...,"Opening address by Mr Martn Redrado, Governor ...",2007-06-18,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Financial intermediation throu...,NaN,r070627d,English,BIS
15585,https://www.bis.org/review/r070702e.pdf,https://www.bis.org/review/r070702e.pdf,An economy in transition,"Article by Mr Martn Redrado, Governor of the C...",2007-06-25,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: An economy in transition Artic...,NaN,r070702e,English,BIS
15592,https://www.bis.org/review/r070703e.pdf,https://www.bis.org/review/r070703e.pdf,"Closing remarks at the conference ""Monetary Po...","Closing remarks by Mr Martn Redrado, Governor ...",2007-06-04,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Closing remarks at the confere...,NaN,r070703e,English,BIS
15652,https://www.bis.org/review/r070814c.pdf,https://www.bis.org/review/r070814c.pdf,Consolidating growth through innovation,"Speech by Mr Martn Redrado, Governor of the Ce...",2007-08-07,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Consolidating growth through i...,NaN,r070814c,English,BIS
15653,https://www.bis.org/review/r070814d.pdf,https://www.bis.org/review/r070814d.pdf,The Central Bank of Argentina passed the test,"Article by Mr Martn Redrado, Governor of the C...",2007-08-05,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: The Central Bank of Argentina ...,NaN,r070814d,English,BIS
15718,https://www.bis.org/review/r070918c.pdf,https://www.bis.org/review/r070918c.pdf,The Argentine response to the financial turmoil,"Speech by Mr Martn Redrado, Governor of the Ce...",2007-09-13,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: The Argentine response to the ...,NaN,r070918c,English,BIS
15923,https://www.bis.org/review/r071204b.pdf,https://www.bis.org/review/r071204b.pdf,The monetary policy response to recent interna...,"Speech by Mr Martn Redrado, Governor of the Ce...",2007-11-22,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: The monetary policy response t...,NaN,r071204b,English,BIS
16090,https://www.bis.org/review/r080311c.pdf,https://www.bis.org/review/r080311c.pdf,Globalization and the determinants of domestic...,"Remarks by Mr Martn Redrado, Governor of the C...",2008-03-07,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Globalization and the determin...,NaN,r080311c,English,BIS
16148,https://www.bis.org/review/r080404d.pdf,https://www.bis.org/review/r080404d.pdf,The impact of global financial turbulence on f...,"Remarks by Mr Martn Redrado, Governor of the C...",2008-04-02,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: The impact of global financial...,NaN,r080404d,English,BIS
16262,https://www.bis.org/review/r080526c.pdf,https://www.bis.org/review/r080526c.pdf,A convincing strategy,"Article by Mr Martn Redrado, Governor of the C...",2008-05-18,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: A convincing strategy Article ...,NaN,r080526c,English,BIS
16342,https://www.bis.org/review/r080627d.pdf,https://www.bis.org/review/r080627d.pdf,"Fiscal space for stability, growth and social ...","Remarks by Mr Martin Redrado, Governor of the ...",2008-06-19,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,"Martin Redrado: Fiscal space for stability, gr...",NaN,r080627d,English,BIS
16349,https://www.bis.org/review/r080703c.pdf,https://www.bis.org/review/r080703c.pdf,Latin America and Argentina - the effect of in...,"Keynote speech by Mr Martin Redrado, Governor ...",2008-06-26,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Latin America and Argentina t...,NaN,r080703c,English,BIS
16355,https://www.bis.org/review/r080709c.pdf,https://www.bis.org/review/r080709c.pdf,The challenges for emerging markets,"Remarks by Mr Martin Redrado, Governor of the ...",2008-07-06,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: The challenges for emerging ma...,NaN,r080709c,English,BIS
16451,https://www.bis.org/review/r080916a.pdf,https://www.bis.org/review/r080916a.pdf,Financial turbulence - impact on developed and...,"Opening address by Mr Martin Redrado, Governor...",2008-09-01,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Financial turbulence impact o...,NaN,r080916a,English,BIS
16452,https://www.bis.org/review/r080916b.pdf,https://www.bis.org/review/r080916b.pdf,Financial turbulence - impact on developed and...,"Closing address by Mr Martin Redrado, Governor...",2008-09-01,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Financial turbulence impact o...,NaN,r080916b,English,BIS
16558,https://www.bis.org/review/r081110c.pdf,https://www.bis.org/review/r081110c.pdf,Financial risk management in emerging countries,"Remarks by Mr Martin Redrado, Governor of the ...",2008-11-07,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Financial risk management in e...,NaN,r081110c,English,BIS
16682,https://www.bis.org/review/r090112c.pdf,https://www.bis.org/review/r090112c.pdf,Presentation of the 2009 Monetary Program,"Speech by Mr Martn Redrado, President of the C...",2008-12-30,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Presentation of the 2009 Monet...,NaN,r090112c,English,BIS
16735,https://www.bis.org/review/r090213d.pdf,https://www.bis.org/review/r090213d.pdf,Monetary policy autonomy in small open economi...,"Speech by Mr Martin Redrado, Governor of the C...",2009-02-10,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Monetary policy autonomy in sm...,NaN,r090213d,English,BIS
16923,https://www.bis.org/review/r090513a.pdf,https://www.bis.org/review/r090513a.pdf,Dynamism and soundness in the face of the crisis,"Article by Mr Martin Redrado, Governor of the ...",2009-05-08,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Dynamism and soundness in the ...,NaN,r090513a,English,BIS
16986,https://www.bis.org/review/r090616b.pdf,https://www.bis.org/review/r090616b.pdf,What's wrong with the current framework of glo...,"Speech by Mr Martin Redrado, Governor of the C...",2009-06-13,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Whats wrong with the current f...,NaN,r090616b,English,BIS
17040,https://www.bis.org/review/r090716b.pdf,https://www.bis.org/review/r090716b.pdf,Where is global finance heading? Status of the...,"Speech by Mr Martin Redrado, Governor of the C...",2009-07-13,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Where is global finance headin...,NaN,r090716b,English,BIS
17119,https://www.bis.org/review/r090915c.pdf,https://www.bis.org/review/r090915c.pdf,Effects of the crisis and different policy res...,"Speech by Mr Martin Redrado, Governor of the C...",2009-09-01,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Effects of the crisis and diff...,NaN,r090915c,English,BIS
17238,https://www.bis.org/review/r091028c.pdf,https://www.bis.org/review/r091028c.pdf,Institutional framework and economic growth,"Speech by Mr Martin Redrado, Governor of the C...",2009-10-19,Martin Redrado,Governor,Male,Central Bank of Argentina,ARG,Martin Redrado: Institutional framework and ec...,NaN,r091028c,English,BIS
17937,https://www.bis.org/review/r100908c.pdf,https://www.bis.org/review/r100908c.pdf,The certainties and uncertainties in the world...,"Speech by Ms Mercedes Marco del Pont, Governor...",2010-09-02,Mercedes Marco del Pont,Governor,Female,Central Bank of Argentina,ARG,Mercedes Marco del Pont: The certainties and u...,NaN,r100908c,English,BIS
25182,https://www.bis.org/review/r190919m.htm,https://www.bis.org/review/r190919m.pdf,The ongoing need for tight monetary policy to ...,"Speech by Mr Guido Sandleris, Governor of the ...",2019-06-13,Guido Sandleris,Governor,Male,Central Bank of Argentina,ARG,Guido Sandleris: The ongoing need for tight mo...,NaN,r190919m,English,BIS
26644,https://www.bis.org/review/r211208m.htm,https://www.bis.org/review/r211208m.pdf,Closing remarks - 2021 Money and Banking Confe...,"Closing remarks by Mr Miguel Angel Pesce, Gove...",2021-11-24,Miguel Angel Pesce,Governor,Male,Central Bank of Argentina,ARG,2021 Money and Banking Conference Online Semin...,NaN,r211208m,English,BIS
27882,http://www.bis.org/review/r230905k.htm,http://www.bis.org/review/r230905k.pdf,Miguel ngel Pesce: Challenges for the macroeco...,Lecture and closing remarks by Mr Miguel ngel ...,2023-07-05,Miguel Angel Pesce,Governor,Male,Central Bank of Argentina,ARG,Miguel Angel Pesce: Challenges for the macroec...,NaN,r230905k,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Argentina
Central Bank of the Republic of Kosovo

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9826,NaN,https://bqk-kos.org/wp-content/uploads/2023/12...,Governors speech on the conference: Signing of...,NaN,2023-12-07,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,BANKA QENDRORE E REPUBLIKeS Se KOSOVeS CENTRAL...,NaN,kos_ahmet_ismaili_45267,English,CB websites
9827,NaN,https://bqk-kos.org/wp-content/uploads/2023/12...,Governors speech on the conference: Financing ...,NaN,2023-12-12,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,BANKA QENDRORE E REPUBLIKeS Se KOSOVeS CENTRAL...,NaN,kos_ahmet_ismaili_45272,English,CB websites
9828,NaN,https://bqk-kos.org/repository/docs/2018/ANG-F...,The speech in the workshop: Western Balkans: B...,NaN,2018-09-06,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,BQK BANKA QENDRORE E REPUBLICS SE KOSOVAS CENT...,NaN,kos_ang-fjalimi%20i%20guvernatorit%20prevalle,English,CB websites
9829,NaN,https://bqk-kos.org/wp-content/uploads/2021/04...,Interview for Epoka e re,NaN,2021-04-11,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Interview of the Governor Fehmi Mehmeti for Ep...,NaN,kos_eng-intervista-e-guvernatorit-fehmi-mehmet...,English,CB websites
9830,NaN,https://bqk-kos.org/wp-content/uploads/2021/04...,Interview for Klan Kosova,NaN,2021-04-09,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Interview of the Governor Fehmi Mehmeti for Kl...,NaN,kos_eng-intervista-e-guvernatorit-fehmi-mehmet...,English,CB websites
9831,NaN,https://bqk-kos.org/wp-content/uploads/2023/03...,Governors speech at the opening of the Global ...,NaN,2023-03-20,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Hello, I am pleased to welcome you to the Cent...",NaN,kos_fehm_mehmeti_45005,English,CB websites
9832,NaN,https://bqk-kos.org/wp-content/uploads/2023/04...,The Acting Governors speech at the ceremony of...,NaN,2023-04-26,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"The honourable Minister, The honourable Mr. Be...",NaN,kos_fehm_mehmeti_45042,English,CB websites
9833,NaN,https://bqk-kos.org/wp-content/uploads/2023/06...,The speech of the Acting Governor at the award...,NaN,2023-06-19,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Pershendetje, I am pleased to welcome you to t...","Prshndetje, Kam knaqsin t ju uroj mirseardhje ...",kos_fehm_mehmeti_45096,Albanian,CB websites
9834,NaN,https://bqk-kos.org/repository/docs/2018/Fjali...,The Speech in the Assembly of the Republic of ...,NaN,2018-09-14,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear Charmian of the Committee, Mr. Abdixhiku ...",NaN,kos_fjalimi%20i%20guvernatorit%20ne%20kuvendin...,English,CB websites
9835,NaN,https://bqk-kos.org/wp-content/uploads/2022/07...,Interview for iSIGURIMET,NaN,2022-02-09,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Governor's interview for iSIGURIMET The Govern...,NaN,kos_governors-interview-for-isigurimet-09.02.2022,English,CB websites
9836,NaN,https://bqk-kos.org/wp-content/uploads/2021/03...,Interview for Albanian Telegraphic Agency,NaN,2020-05-11,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Interview of CBK Governor, Mr. Fehmi Mehmeti f...",NaN,kos_interview-of-cbk-governor-mr.-fehmi-mehmet...,English,CB websites
9837,NaN,https://bqk-kos.org/wp-content/uploads/2021/03...,Interview for iSigurimet,NaN,2020-04-02,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Interview of CBK Governor, Mr. Fehmi Mehmeti f...",NaN,kos_interview-of-cbk-governor-mr.-fehmi-mehmet...,English,CB websites
9838,NaN,https://bqk-kos.org/wp-content/uploads/2021/03...,Interview for Radio Free Europe,NaN,2019-09-09,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Interview of CBK Governor, Mr. Fehmi Mehmeti f...",NaN,kos_interview-of-cbk-governor-mr.-fehmi-mehmet...,English,CB websites
9839,NaN,https://bqk-kos.org/wp-content/uploads/2021/03...,Interview for Telegrafi,NaN,2020-04-11,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Interview of CBK Governor, Mr. Fehmi Mehmeti f...",NaN,kos_interview-of-cbk-governor-mr.-fehmi-mehmet...,English,CB websites
9840,NaN,https://bqk-kos.org/wp-content/uploads/2021/03...,Interview for Voice of America,NaN,2020-05-08,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Interview of CBK Governor, Mr. Fehmi Mehmeti f...",NaN,kos_interview-of-cbk-governor-mr.-fehmi-mehmet...,English,CB websites
9841,NaN,https://bqk-kos.org/wp-content/uploads/2021/03...,Interview for Voice of America,NaN,2019-10-19,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Interview of CBK Governor, Mr. Fehmi Mehmeti f...",NaN,kos_interview-of-cbk-governor-mr.-fehmi-mehmet...,English,CB websites
9842,NaN,https://bqk-kos.org/wp-content/uploads/2021/09...,Interview for KosovaPress,NaN,2021-09-19,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Interview of the Governor Fehmi Mehmeti for Ko...,NaN,kos_interview-of-the-governor-fehmi-mehmeti-fo...,English,CB websites
9843,NaN,http://bqk-kos.org/repository/docs/2018/interv...,Interview of the former Governor Bedri Hamza f...,NaN,2017-09-27,Bedri Hamza,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"September 27, 2017 Kosovo: Local undertaking a...",27 Shtator 2017 Kosov: Ndrmarrsia vendore dhe ...,kos_intervistae%20ishg.b.h,Albanian,CB websites
9844,NaN,https://bqk-kos.org/repository/docs/2018/speec...,The speech on the occasion of organization of...,NaN,2018-06-10,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear participants, In the frame of the Pan-Nat...",NaN,kos_speech%20of%20gov%20in%20al%20of%20pz,English,CB websites
24600,https://www.bis.org/review/r181224b.htm,https://www.bis.org/review/r181224b.pdf,Banking sector is contributor to the country's...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2018-12-05,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Honoured, It is my pleasure to be here today t...",NaN,r181224b,English,BIS
24601,https://www.bis.org/review/r181224c.htm,https://www.bis.org/review/r181224c.pdf,The importance of the banking sector in Kosovo...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2018-12-06,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Honoured, I am pleased to be here with you tod...",NaN,r181224c,English,BIS
24646,https://www.bis.org/review/r190129d.htm,https://www.bis.org/review/r190129d.pdf,Financial sector marked positive developments ...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2018-12-24,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear journalists and media representatives, I ...",NaN,r190129d,English,BIS
24748,https://www.bis.org/review/r190320b.htm,https://www.bis.org/review/r190320b.pdf,Central Bank of the Republic of Kosovo dedicat...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-03-15,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Honourable Minister Shala, Honourable Chairman...",NaN,r190320b,English,BIS
24764,https://www.bis.org/review/r190327c.htm,https://www.bis.org/review/r190327c.pdf,The Central Bank of the Republic of Kosovo pla...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-03-25,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear Minister Bytyqi, Dear Mr. Marco Mantovane...",NaN,r190327c,English,BIS
24892,https://www.bis.org/review/r190521h.htm,https://www.bis.org/review/r190521h.pdf,Kosovo Credit Guarantee Fund (KCGF) has facili...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-05-16,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,The third anniversary of the establishment of ...,NaN,r190521h,English,BIS
25170,https://www.bis.org/review/r190919a.htm,https://www.bis.org/review/r190919a.pdf,Raiffeisen Bank has made a significant contrib...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-09-16,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"I am honored to be with you today, to inaugura...",NaN,r190919a,English,BIS
25325,https://www.bis.org/review/r191101c.htm,https://www.bis.org/review/r191101c.pdf,Central Bank of the Republic of Kosovo will co...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-10-31,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear teachers, Dear students, Dear guests, Wel...",NaN,r191101c,English,BIS
25402,https://www.bis.org/review/r191127b.htm,https://www.bis.org/review/r191127b.pdf,The Central Bank of the Republic of Kosovo for...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-11-19,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Speech of the Governor on the occasion of the ...,NaN,r191127b,English,BIS
25468,https://www.bis.org/review/r191219a.htm,https://www.bis.org/review/r191219a.pdf,The CBK is committed to working to the best st...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-12-17,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Honourable Ambassador Apostolova, Dear Ministe...",NaN,r191219a,English,BIS
25480,https://www.bis.org/review/r200106b.htm,https://www.bis.org/review/r200106b.pdf,Central Bank of the Republic of Kosovo is comm...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2019-12-23,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Distinguished journalists, media representativ...",NaN,r200106b,English,BIS
25599,https://www.bis.org/review/r200406b.htm,https://www.bis.org/review/r200406b.pdf,The Central Bank of the Republic of Kosovo has...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2020-04-03,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Honoured media representatives, First of all, ...",NaN,r200406b,English,BIS
25841,https://www.bis.org/review/r201005d.htm,https://www.bis.org/review/r201005d.pdf,Central Bank of the Republic of Kosovo has inv...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2020-09-29,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Prishtina 29.09.2020 Disclosure of Textbooks a...,NaN,r201005d,English,BIS
25962,https://www.bis.org/review/r201118f.htm,https://www.bis.org/review/r201118f.pdf,Central Bank of the Republic of Kosovo is clos...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2020-11-12,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear Journalists, welcome to this conference a...",NaN,r201118f,English,BIS
26092,https://www.bis.org/review/r201230a.htm,https://www.bis.org/review/r201230a.pdf,The Central Bank of the Republic of Kosovo was...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2020-12-22,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Distinguished media representatives, First of ...",NaN,r201230a,English,BIS
26186,https://www.bis.org/review/r210310g.htm,https://www.bis.org/review/r210310g.pdf,Central Bank of the Republic of Kosovo is read...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2021-03-04,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear media representatives, It was a pleasure ...",NaN,r210310g,English,BIS
26493,https://www.bis.org/review/r211012b.htm,https://www.bis.org/review/r211012b.pdf,"Revocation of the license of the Insurer ""Koso...","Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2021-09-24,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: Revocation of the license of th...,NaN,r211012b,English,BIS
26590,https://www.bis.org/review/r211128j.htm,https://www.bis.org/review/r211128j.pdf,Bank lending is continuing to contribute to ec...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2021-11-25,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: Bank lending is continuing to c...,NaN,r211128j,English,BIS
26739,https://www.bis.org/review/r211230g.htm,https://www.bis.org/review/r211230g.pdf,The financial sector was the main pillar of su...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2021-12-24,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: The financial sector was the ma...,NaN,r211230g,English,BIS
26864,http://www.bis.org/review/r220324a.htm,http://www.bis.org/review/r220324a.pdf,Fehmi Mehmeti: Kosovo's economy in 2021 marked...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2022-03-23,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: Kosovo's economy in 2021 marked...,NaN,r220324a,English,BIS
27012,http://www.bis.org/review/r220623d.htm,http://www.bis.org/review/r220623d.pdf,Fehmi Mehmeti: Financial institutions play an ...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2022-06-17,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Dear Mrs. Olmstead, Honorable Ambassador Rohde...",NaN,r220623d,English,BIS
27308,http://www.bis.org/review/r221109b.htm,http://www.bis.org/review/r221109b.pdf,Fehmi Mehmeti: The banking sector is able to w...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2022-11-03,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: The banking sector is able to w...,NaN,r221109b,English,BIS
27329,http://www.bis.org/review/r221115h.htm,http://www.bis.org/review/r221115h.pdf,Fehmi Mehmeti: The financial sector is liquid ...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2022-11-04,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: The financial sector is liquid ...,NaN,r221115h,English,BIS
27364,http://www.bis.org/review/r221121p.htm,http://www.bis.org/review/r221121p.pdf,Fehmi Mehmeti: The international arbitration r...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2022-11-19,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: The international arbitration r...,NaN,r221121p,English,BIS
27442,http://www.bis.org/review/r221219f.htm,http://www.bis.org/review/r221219f.pdf,Fehmi Mehmeti: The Central Bank of the Republi...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2022-12-15,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: The Central Bank of the Republi...,NaN,r221219f,English,BIS
27451,http://www.bis.org/review/r230104a.htm,http://www.bis.org/review/r230104a.pdf,Fehmi Mehmeti: The financial system proved cap...,"Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2022-12-22,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Fehmi Mehmeti: The financial system proved cap...,NaN,r230104a,English,BIS
27607,http://www.bis.org/review/r230404k.htm,http://www.bis.org/review/r230404k.pdf,"Fehmi Mehmeti: During my mandate, the insuranc...","Speech by Mr Fehmi Mehmeti, Governor of the Ce...",2023-03-27,Fehmi Mehmeti,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Fehmi Mehmeti: During my mandate, the insuranc...",NaN,r230404k,English,BIS
27672,http://www.bis.org/review/r230502d.htm,http://www.bis.org/review/r230502d.pdf,Bashkim Nurboja: The number of businesses with...,"Speech by Mr Bashkim Nurboja, Acting Governor ...",2023-04-26,Bashkim Nurboja,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Bashkim Nurboja: The number of businesses with...,NaN,r230502d,English,BIS
27772,http://www.bis.org/review/r230621a.htm,http://www.bis.org/review/r230621a.pdf,"Bashkim Nurboja: Through financial education, ...","Speech by Mr Bashkim Nurboja, Acting Governor ...",2023-06-20,Bashkim Nurboja,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Bashkim Nurboja: Through financial education, ...",NaN,r230621a,English,BIS
27970,https://www.bis.org/review/r231018b.htm,https://www.bis.org/review/r231018b.pdf,"Ahmet Ismaili: Opening speech ""Sustainable Fi...","Opening speech by Mr Ahmet Ismaili, Governor o...",2023-10-05,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Ahmet Ismaili: Opening speech - ""Sustainable F...",NaN,r231018b,English,BIS
28034,https://www.bis.org/review/r231114e.htm,https://www.bis.org/review/r231114e.pdf,Ahmet Ismaili: Cybersecurity in the banking in...,"Speech by Mr Ahmet Ismaili, Governor of the Ce...",2023-10-25,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Ahmet Ismaili: Cybersecurity in the banking in...,NaN,r231114e,English,BIS
28035,https://www.bis.org/review/r231114f.htm,https://www.bis.org/review/r231114f.pdf,Ahmet Ismaili: Approximate market value and sa...,"Opening speech by Mr Ahmet Ismaili, Governor o...",2023-10-27,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Ahmet Ismaili: Approximate market value and sa...,NaN,r231114f,English,BIS
28078,https://www.bis.org/review/r231127c.htm,https://www.bis.org/review/r231127c.pdf,Ahmet Ismaili: Welcoming remarks - World Savin...,"Welcoming remarks by Mr Ahmet Ismaili, Governo...",2023-10-31,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Ahmet Ismaili: Welcoming remarks - World Savin...,NaN,r231127c,English,BIS
28079,https://www.bis.org/review/r231127d.htm,https://www.bis.org/review/r231127d.pdf,Ahmet Ismaili: Creating values a gateway for ...,"Introductory remarks by Mr Ahmet Ismaili, Gove...",2023-11-08,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,Ahmet Ismaili: Creating values - a gateway for...,NaN,r231127d,English,BIS
28110,https://www.bis.org/review/r231206c.htm,https://www.bis.org/review/r231206c.pdf,"Ahmet Ismaili: Banks, fintechs and businesses ...","Welcoming speech by Mr Ahmet Ismaili, Governor...",2023-11-14,Ahmet Ismaili,Governor,Male,Central Bank of the Republic of Kosovo,XKX,"Ahmet Ismaili: Banks, fintechs and businesses ...",NaN,r231206c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of the Republic of Kosovo
National Bank of Cambodia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9678,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,45th SEACEN Governors Conference and 29th Meet...,NaN,2007-11-27,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,A Numberc9c9c9c9c9c9c9c9c9c9c9. and especially...,NaN,khm_39413_chea_chanto,English,CB websites
9679,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,SEACEN-Federal Reserve System Course on Princi...,NaN,2009-10-08,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING Unoff...,NaN,khm_40094_chea_chanto_2,English,CB websites
9680,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Celebrating the 30th Anniversary of the Re-int...,NaN,2009-10-08,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,Unofficial Translation Welcoming Remarks by H....,NaN,khm_40094_chea_chanto,English,CB websites
9681,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,SEACEN-BIS Exco Seminar,NaN,2009-10-09,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,Unofficial Translation Remarks by H.E. CHEA Ch...,NaN,khm_40095_chea_chanto,English,CB websites
9682,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,SEACEN-CCBS/BOE Advanced Course on Macroeconom...,NaN,2009-10-26,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Opening Remarks by H.E. Chea Chanto, Governor ...",NaN,khm_40112_chea_chanto,English,CB websites
9683,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,"18th APRACA General Assembly, the 61st APRACA ...",NaN,2010-02-26,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,.. Welcoming Remarks by His Excellency Mr. Che...,NaN,khm_40235_chea_chanto,English,CB websites
9684,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Fast Payment Launch,NaN,2010-02-26,Keat Chhon,Senior management,Male,National Bank of Cambodia,KHM,OPENING ADDRESS BY HIGHEST REPRESENTATIVE OF T...,NaN,khm_40235_keat_chhon,English,CB websites
9685,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,3rd SEACEN High-Level Seminar for Deputy Gover...,NaN,2010-03-22,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,. Unofficial Translation Remarks by H.E. Chea ...,NaN,khm_40259_chea_chanto,English,CB websites
9686,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,2012 Annual Dinner,NaN,2010-05-02,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Opening Remarks By H.E. Chea Chanto, Governor ...",NaN,khm_40300_chea_chanto,English,CB websites
9687,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,7th SEACEN CeM-CoA/BOJ Intermediate Course on ...,NaN,2011-01-19,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,Opening Address by the Governor of the Nationa...,NaN,khm_40562_chea_chanto,English,CB websites
9688,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,SEACEN BOJ Workshop on Capital Account Liberal...,NaN,2012-03-19,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Opening Remarks By H.E. Chea Chanto, Governor ...",NaN,khm_40987_chea_chanto,English,CB websites
9689,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,21st Conference of Governors of the Central Ba...,NaN,2012-05-30,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Opening Remarks H.E. Chea Chanto , Governor of...",NaN,khm_41059_chea_chanto,English,CB websites
9690,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,35th Anniversary of Central Banking,NaN,2012-08-27,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"OPENING REMARKS H.E. CHEA CHANTO ,Gove rnor of...",NaN,khm_41148_chea_chanto,English,CB websites
9691,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Signing Ceremony on the Code of Banking Practies,NaN,2012-12-05,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Remarks by H.E. Chea Chanto, Governor of the N...",NaN,khm_41248_chea_chanto,English,CB websites
9692,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,SEACEN-Toronto Course on Recovery and Resoluti...,NaN,2013-03-26,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Opening Remarks by H.E. Chea Chanto, Governor ...",NaN,khm_41359_chea_chanto,English,CB websites
9693,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,7th China-ASEAN Summit Forum on Financial Coop...,NaN,2013-08-26,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,". Opening Remarks by H.E. Chea Chanto, Governo...",NaN,khm_41512_chea_chanto,English,CB websites
9694,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Opening the Seminar on AML/CFT,NaN,2014-03-21,Neav Chanthana,Deputy Governor,Female,National Bank of Cambodia,KHM,. Opening Remarks at 7th Senior Level Committe...,NaN,khm_41719_neav_chanthana,English,CB websites
9695,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,30th Anniversary of the Re-establishment of Na...,NaN,2014-03-24,Neav Chanthana,Deputy Governor,Female,National Bank of Cambodia,KHM,". Opening Remarks by H.E. NEAV CHANTHANA, Depu...",NaN,khm_41722_neav_chanthana,English,CB websites
9696,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,2nd SEACEN-ADB-ASEC-AADCP Foundational Course ...,NaN,2014-03-28,Sum Sannisith,Senior management,Male,National Bank of Cambodia,KHM,"Closing Remarks by H.E.Sum Sannisith, Assistan...",NaN,khm_41726_sum_sannisith,English,CB websites
9697,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Official Launch of Cambodian Sustainable Finan...,NaN,2014-05-06,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,Number Welcome Remarks By Her Excellency CHEA ...,NaN,khm_41765_chea_serey,English,CB websites
9698,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,7th China-ASEAN on Financial Cooperation and D...,NaN,2014-05-14,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Address by His Excellency Chea Chanto, Governo...","Allocution de Son Excellence Chea Chanto, Gouv...",khm_41773_chea_chanto,French,CB websites
9699,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,ASEAN Financial Integration Framework (AFIF) C...,NaN,2014-10-06,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,".... Opening Remarks by H.E Chea Chanto, Gover...",NaN,khm_41918_chea_chanto,English,CB websites
9700,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,SEACEN-IMF STI Course on Macroeconomic Diagno...,NaN,2015-02-16,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,Unofficial Translat92on Remarks by H.E Chea Ch...,NaN,khm_42051_chea_chanto,English,CB websites
9701,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,28th Meeting of the ASEAN Working Group on Int...,NaN,2015-04-20,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"... Opening Remarks by H.E. Chea Chanto, Gover...",NaN,khm_42114_chea_chanto,English,CB websites
9702,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Results of Foreign Direct Investment Survey 2014,NaN,2015-06-03,Kim Vada,Senior management,Male,National Bank of Cambodia,KHM,Opening Remark H.E Kim Vada Director General o...,NaN,khm_42158_kim_vada,English,CB websites
9703,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Signing Ceremony of the Cambodian Sustainable ...,NaN,2015-09-19,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Remarks by His Excellency Chea Chanto, Governo...",NaN,khm_42266_chea_chanto,English,CB websites
9704,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Releasing Ceremony of Statistic Law,NaN,2015-09-25,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Remarks by His Excellency Chea Chanto, Governo...",NaN,khm_42272_chea_chanto,English,CB websites
9705,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Congratulatory dinner for the 30th Anniversary...,NaN,2015-09-29,Neav Chanthana,Deputy Governor,Female,National Bank of Cambodia,KHM,"Opening Remarks by H.E. Neav Chanthana, Deputy...",NaN,khm_42276_neav_chanthana,English,CB websites
9706,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,30th Anniversary of the Re-establishment of Na...,NaN,2016-07-15,Neav Chanthana,Deputy Governor,Female,National Bank of Cambodia,KHM,. Remark by H.E. Neav Chanthana Deputy Governo...,NaN,khm_42566_neav_chanthana,English,CB websites
9707,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,APG Typologies Workshop 2009,NaN,2016-07-28,Neav Chanthana,Deputy Governor,Female,National Bank of Cambodia,KHM,". Remarks by Her Excellency Neav Chanthana, De...",NaN,khm_42579_neav_chanthana,English,CB websites
9708,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Reserve Assets Measurement,NaN,2016-08-22,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,. Opening Remarks by His Excellency Chea Chant...,NaN,khm_42604_chea_chanto,English,CB websites
9709,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,MOU Signing Ceremony between the Institute of ...,NaN,2016-09-19,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,".... Speech By H.E. Chea Serey, Director Gener...",NaN,khm_42632_chea_serey,English,CB websites
9710,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Official Launch of the Cambodia FinTech Associ...,NaN,2016-10-18,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,"Opening Remarks H.E. Chea Chanto, Governor of ...",NaN,khm_42661_chea_chanto,English,CB websites
9711,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Central Bank of the Future Conference,NaN,2016-11-24,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,"Speech By H.E. Chea Serey, Director General of...",NaN,khm_42698_chea_serey,English,CB websites
9712,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,"WE Act Program_ ""Preparing the foundation for ...",NaN,2016-12-12,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,".. Welcome Remarks by H.E. Chea Serey, Directo...",NaN,khm_42716_chea_serey,English,CB websites
9713,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,45th South East Asia Central Banks(SEACEN)Gove...,NaN,2018-08-15,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,Speech By Her Excellency CHEA SEREY Director G...,NaN,khm_43327_chea_serey,English,CB websites
9714,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,Experience Sharing Session on Regulation and S...,NaN,2019-03-29,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,". Opening Remarks by H.E. Chea Serey, Director...",NaN,khm_43553_chea_serey,English,CB websites
9715,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,7th Senior Level Committee Meeting,NaN,2020-10-07,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,Remark by H.E. CHEA SEREY Assistant Governor a...,NaN,khm_44111_chea_serey,English,CB websites
9716,https://www.nbc.org.kh/english/news_and_events...,https://www.nbc.org.kh/../../download_files/ne...,2nd SEACEN-ADB-ASEC-AADCP Foundational Course ...,NaN,2020-11-18,Chea Serey,Senior management,Female,National Bank of Cambodia,KHM,Keynote Address by H.E CHEA SEREY Assistant Go...,NaN,khm_44153_chea_serey,English,CB websites
9717,https://www.nbc.gov.kh/english/news_and_events...,https://www.nbc.gov.kh/download_files/news_and...,Remark_MOU between MPTC and CAFT,NaN,2022-03-15,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING NATIO...,NaN,khm_44635_chea_serey_english,English,CB websites
9718,https://www.nbc.gov.kh/english/news_and_events...,https://www.nbc.gov.kh/download_files/news_and...,Opening remarks by H.E. Dr. CHEA SEREY at Fina...,NaN,2022-04-01,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING Numbe...,NaN,khm_44652_chea_serey_english,English,CB websites
9719,https://www.nbc.gov.kh/news_and_events/speeche...,https://www.nbc.gov.kh/download_files/news_and...,"Dr. Glory, Deputy Governor and Chief Executive...",NaN,2022-04-21,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,"Kingdom of Cambodia Nation, Religion: King Key...",.. :-: + ...,khm_44672_glory_khmer,Khmer,CB websites
9720,https://www.nbc.gov.kh/news_and_events/speeche...,https://www.nbc.gov.kh/download_files/news_and...,"Address by Dr. Glory, Deputy Governor and Nati...",NaN,2023-06-06,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,"Kingdom of Cambodia Nation, Religion, King Spe...",|98 (06! !.6 02! .. =...,khm_45083_glory_khmer,Khmer,CB websites
9721,https://www.nbc.gov.kh/english/news_and_events...,https://www.nbc.gov.kh/download_files/news_and...,Remarks by H.E. Dr. Chea Serey Deputy Governor...,NaN,2023-07-10,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING NATIO...,NaN,khm_45117_chea_serey_english,English,CB websites
9722,https://www.nbc.gov.kh/news_and_events/speeche...,https://www.nbc.gov.kh/download_files/news_and...,"Address Mr. Glory, Governor-General of the Nat...",NaN,2023-08-29,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,"Kingdom of Cambodia Nation, Religion, King - S...",- / .. ! ...,khm_45167_glory_khmer,Khmer,CB websites
9723,https://www.nbc.gov.kh/news_and_events/speeche...,https://www.nbc.gov.kh/download_files/news_and...,"Advocate Glory, Governor of the National Bank ...",NaN,2023-09-06,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,"Kingdom of Cambodia Nation, Religion, King Num...",... (...) .. ! (...,khm_45175_glory_khmer,Khmer,CB websites
9724,https://www.nbc.gov.kh/english/news_and_events...,https://www.nbc.gov.kh/download_files/news_and...,Opening Remarks by H.E. Dr. Chea Serey at SEAC...,NaN,2023-09-18,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING NATIO...,NaN,khm_45187_chea_serey_english,English,CB websites
9725,https://www.nbc.gov.kh/news_and_events/speeche...,https://www.nbc.gov.kh/download_files/news_and...,"Subscribe to Dr. Glory, governor of the Nation...",NaN,2023-11-10,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,"Kingdom of Cambodia Nation, Religion, King Spe...",6 |88 (68 ) .. -...,khm_45240_glory_khmer,Khmer,CB websites
9726,https://www.nbc.gov.kh/english/news_and_events...,https://www.nbc.gov.kh/download_files/news_and...,Opening Remarks by Her Excellency Dr. Chea Ser...,NaN,2023-11-30,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING NATIO...,NaN,khm_45260_chea_serey_english,English,CB websites
9727,https://www.nbc.gov.kh/english/news_and_events...,https://www.nbc.gov.kh/download_files/news_and...,"Remarks by H.E. Dr. Chea Serey, Governor of th...",NaN,2023-12-08,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING NATIO...,NaN,khm_45268_chea_serey_english,English,CB websites
9728,https://www.nbc.gov.kh/news_and_events/speeche...,https://www.nbc.gov.kh/download_files/news_and...,"Address Dr. Glory, National Bank of Cambodia G...",NaN,2023-12-08,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,"Kingdom of Cambodia Nation, Religion: King Spe...",.. 0%8+# - /|882| 0846...,khm_45268_glory_khmer,Khmer,CB websites
9729,https://www.nbc.gov.kh/english/news_and_events...,https://www.nbc.gov.kh/download_files/news_and...,"Remarks by H.E. Dr. Chea Serey, Governor of th...",NaN,2023-12-22,Chea Serey,Governor,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING NATIO...,NaN,khm_45282_chea_serey_english,English,CB websites
16896,https://www.bis.org/review/r090428e.pdf,https://www.bis.org/review/r090428e.pdf,Opening remarks at the BIS Advanced Reserve Ma...,"Opening remarks by H.E. Chea Chanto, Governor ...",2009-04-21,Chea Chanto,Governor,Male,National Bank of Cambodia,KHM,Chea Chanto: Opening remarks at the BIS Advanc...,NaN,r090428e,English,BIS
27265,http://www.bis.org/review/r221031g.htm,http://www.bis.org/review/r221031g.pdf,Serey Chea: The new era of financial education,Keynote address by Her Excellency Dr Serey Che...,2022-10-03,Serey Chea,Senior management,Female,National Bank of Cambodia,KHM,KINGDOM OF CAMBODIA NATION RELIGION KING NATIO...,NaN,r221031g,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Cambodia
Central Bank of Nigeria

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10843,NaN,https://www.cbn.gov.ng/Out/2023/CCD/Revised_Go...,Goodwill Remarks by the CBN Governor at the Co...,Goodwill Remarks by the CBN Governor at the Co...,2023-05-22,Olayemi Cardoso,Governor,Male,Central Bank of Nigeria,NGA,Central Bank of Nigeria Goodwill Remarks Godwi...,NaN,nga__olayemi_cardoso_45068,English,CB websites
10844,https://www.cbn.gov.ng/Out/2020/CCD/55th%20Ann...,https://www.cbn.gov.ng/Out/2020/CCD/55th%20Ann...,Address at the 55th Annual Bankers Dinner,NaN,2020-11-27,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Gov. Godwin Emefiele, CON Address at the 55th ...",NaN,nga_55th_annual_bankers_dinner,English,CB websites
10845,https://www.cbn.gov.ng/out/Speeches/2018/Dinne...,https://www.cbn.gov.ng/out/Speeches/2018/Dinne...,Keynote Address at the Annual Bankers Dinner,NaN,2018-12-30,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,CENTRAL BANK OF NIGERIA AN ADDRESS BY GOVERNOR...,NaN,nga_dinner,English,CB websites
10846,https://www.cbn.gov.ng/Out/2019/CCD/Five-Year%...,https://www.cbn.gov.ng/Out/2019/CCD/Five-Year%...,5 year Policy Thrust of Central Bank of Nigeria,NaN,2019-06-24,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Gov. Godwin Emefiele, CON 5 year Policy Thrust...",NaN,nga_five-year_policy_thrust_-_cbn,English,CB websites
10847,NaN,https://www.cbn.gov.ng/Out/2022/CCD/Governors%...,Governors Remarks FCT Mega Rice Pyramids,Governors Remarks FCT Mega Rice Pyramids\r\nGo...,2022-01-18,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,Central Bank of Nigeria Opening Remarks by Mr....,NaN,nga_godwin_i_emefiele_44579,English,CB websites
10848,NaN,https://www.cbn.gov.ng/Out/2022/CCD/Opening%20...,Official Launching of the 100 for 100 Policy f...,Official Launching of the 100 for 100 Policy f...,2022-01-31,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Opening Remarks by Godwin I. Emefiele, CON At ...",NaN,nga_godwin_i_emefiele_44592,English,CB websites
10849,NaN,https://www.cbn.gov.ng/Out/2023/CCD/Governor's...,"Goodwill Remarks by Godwin I. Emefiele, Con Go...","Goodwill Remarks by Godwin I. Emefiele, Con Go...",2023-05-22,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,Central Bank of Nigeria Goodwill Remarks by Go...,NaN,nga_godwin_i_emefiele_45068,English,CB websites
10850,https://www.cbn.gov.ng/out/speeches/2012/gov_b...,https://www.cbn.gov.ng/out/speeches/2012/gov_b...,Beyond Political Rhetoric: Investing In Youth ...,NaN,2012-05-05,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,CENTRAL BANK OF NIGERIA BEYOND POLITICAL RHETO...,NaN,nga_gov_beyond_rhetoric,English,CB websites
10851,https://www.cbn.gov.ng/out/speeches/2012/gov_p...,https://www.cbn.gov.ng/out/speeches/2012/gov_p...,The Role of Development Finance Institutions i...,NaN,2012-07-18,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,THE ROLE OF DEVELOPMENT FINANCE INSTITUTIONS I...,NaN,nga_gov_ppp_stakeholder_forum_160712,English,CB websites
10852,https://www.cbn.gov.ng/out/Speeches/2019/Gover...,https://www.cbn.gov.ng/out/Speeches/2019/Gover...,Opening Remarks at Meeting With Service Chiefs...,NaN,2019-07-11,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,Central Bank of Nigeria Opening Remarks by Mr....,NaN,nga_governors_address_at_meeting_with_service_...,English,CB websites
10853,https://www.cbn.gov.ng/Out/2019/CCD/Governors%...,https://www.cbn.gov.ng/Out/2019/CCD/Governors%...,Welcome Address at the Meeting with State Gove...,NaN,2019-11-22,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,CENTRAL BANK OF NIGERIA Welcome Address At The...,NaN,nga_governors_speech_for_cassava_meeting_and_m...,English,CB websites
10854,https://www.cbn.gov.ng/out/Speeches/2015/Gover...,https://www.cbn.gov.ng/out/Speeches/2015/Gover...,Opening Remarks at the NEMS Signing Ceremony,NaN,2015-02-02,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,Opening Remarks by Governor Godwin I. Emefiele...,NaN,nga_governors_talking_points_for_nems_disburse...,English,CB websites
10855,https://www.cbn.gov.ng/Out/2013/CCD/Islam%20an...,https://www.cbn.gov.ng/Out/2013/CCD/Islam%20an...,Islam and The Culture of Education: Fountain U...,NaN,2013-02-28,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Islam and the Culture of Education Convocation...,NaN,nga_islam_and_the_culture_of_education,English,CB websites
10856,https://www.cbn.gov.ng/out/2014/GVD/Speeches/K...,https://www.cbn.gov.ng/out/2014/GVD/Speeches/K...,Keynote Address Delivered at the First Nationa...,NaN,2014-05-20,Sarah Alade,Governor,Female,Central Bank of Nigeria,NGA,CENTRAL BANK OF NIGERIA KEYNOTE ADDRESS Sarah ...,NaN,nga_keynote_address_legislature_and_the_bankin...,English,CB websites
10857,https://www.cbn.gov.ng/out/Speeches/2014/Keyno...,https://www.cbn.gov.ng/out/Speeches/2014/Keyno...,Glo Xchange Mobile Money Launch,NaN,2014-08-21,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,Keynote Address by Governor Godwin I. Emefiele...,NaN,nga_keynote_speech_for_glo_xchange_launch,English,CB websites
10858,NaN,https://www.cbn.gov.ng/Out/2023/CCD/Governor_A...,"Keynote Address by Mr. Olayemi Cardoso, Govern...","Keynote Address by Mr. Olayemi Cardoso, Govern...",2023-11-24,Olayemi Cardoso,Governor,Male,Central Bank of Nigeria,NGA,CENTRAL BANK OF NIGERIA KEYNOTE ADDRESS BY Mr....,NaN,nga_olayemi_cardoso_45254,English,CB websites
10859,https://www.cbn.gov.ng/out/Speeches/2015/Openi...,https://www.cbn.gov.ng/out/Speeches/2015/Openi...,Opening Remarks at the Press Conference on FX ...,NaN,2015-06-24,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Opening Remarks By Gov. Godwin Emefiele, CON A...",NaN,nga_opening_remarks_press_conference_on_fx_ban...,English,CB websites
10860,https://www.cbn.gov.ng/Out/2016/CCD/Press%20Re...,https://www.cbn.gov.ng/Out/2016/CCD/Press%20Re...,Press Statement - CBN to stop Dollar Sales to ...,NaN,2016-01-11,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,Central Bank of Nigeria Press Statement on For...,NaN,nga_press_release_-_cbn_to_stop_dollar_sales_t...,English,CB websites
10861,https://www.cbn.gov.ng/Out/2020/CCD/PrivateSec...,https://www.cbn.gov.ng/Out/2020/CCD/PrivateSec...,Nigerian Private Sector Coalition Against COVI...,NaN,2020-03-27,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,CENTRAL BANK OF NIGERIA Press Release NIGERIAN...,NaN,nga_privatesectorcoalitioncovid-19,English,CB websites
10862,https://www.cbn.gov.ng/Out/2021/CCD/Remarks%20...,https://www.cbn.gov.ng/Out/2021/CCD/Remarks%20...,Opening Remarks at the Official Launching of ...,NaN,2021-11-25,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Opening Remarks by Dr. Godwin I. Emefiele, CON...",NaN,nga_remarks_by_gov._emefiele-_ties_launch_nov_...,English,CB websites
10863,https://www.cbn.gov.ng/Out/2015/CCD/speech-at-...,https://www.cbn.gov.ng/Out/2015/CCD/speech-at-...,Speech during a Meeting with State Government ...,NaN,2015-07-10,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Speech by Governor Godwin Emefiele, CON During...",NaN,nga_speech-at-meeting-with-states-and-rice-mil...,English,CB websites
10864,https://www.cbn.gov.ng/Out/2015/CCD/speech-at-...,https://www.cbn.gov.ng/Out/2015/CCD/speech-at-...,Speech during a Meeting with Oil Palm Value Ch...,NaN,2015-07-10,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Speech By Governor Godwin Emefiele, CON During...",NaN,nga_speech-at-oil_palm_stakeholders_meeting,English,CB websites
13354,https://www.bis.org/review/r030530d.pdf,https://www.bis.org/review/r030530d.pdf,"Central banking authority, economic stability ...","Paper presented by Dr Joseph O Sanusi, Governo...",2003-04-04,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,"Joseph O Sanusi: Central banking authority, ec...",NaN,r030530d,English,BIS
13355,https://www.bis.org/review/r030530e.pdf,https://www.bis.org/review/r030530e.pdf,Management of Nigeria's domestic debt,"Keynote address by Dr Joseph O Sanusi, Governo...",2003-05-22,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Joseph O Sanusi: Management of Nigerias domest...,NaN,r030530e,English,BIS
13356,https://www.bis.org/review/r030530f.pdf,https://www.bis.org/review/r030530f.pdf,A central bank look at fiscal policy managemen...,"Keynote address by Dr Joseph O Sanusi, Governo...",2003-05-22,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Joseph O Sanusi: A central bank look at fiscal...,NaN,r030530f,English,BIS
13361,https://www.bis.org/review/r030606c.pdf,https://www.bis.org/review/r030606c.pdf,Central Bank of Nigeria's standpoint of anti-m...,"Speech by Dr Joseph O Sanusi, Governor of the ...",2003-06-03,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Joseph O Sanusi: Central Bank of Nigeria's sta...,NaN,r030606c,English,BIS
13367,https://www.bis.org/review/r030613d.pdf,https://www.bis.org/review/r030613d.pdf,Small and medium enterprises in Nigeria,"Opening remarks by Dr Joseph O Sanusi, Governo...",2003-06-10,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Joseph O Sanusi: Small and medium enterprises ...,NaN,r030613d,English,BIS
13372,https://www.bis.org/review/r030620c.pdf,https://www.bis.org/review/r030620c.pdf,Embracing good corporate governance practices ...,"Keynote address by Dr Joseph O Sanusi, Governo...",2003-06-17,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Joseph O Sanusi: Embracing good corporate gove...,NaN,r030620c,English,BIS
13373,https://www.bis.org/review/r030620d.pdf,https://www.bis.org/review/r030620d.pdf,Information and communication technology for t...,"Special remarks by Dr Joseph O Sanusi, Governo...",2003-06-10,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Joseph O Sanusi: Information and communication...,NaN,r030620d,English,BIS
13401,https://www.bis.org/review/r030721b.pdf,https://www.bis.org/review/r030721b.pdf,Ongoing efforts towards a monetary union in th...,"Speech by Dr Joseph O Sanusi, Governor of the ...",2003-06-30,Joseph O Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Joseph O Sanusi: Ongoing efforts towards a mon...,NaN,r030721b,English,BIS
13808,https://www.bis.org/review/r040727g.pdf,https://www.bis.org/review/r040727g.pdf,Consolidating the Nigerian banking industry to...,"Address by Mr Charles Chukwuma Soludo, Governo...",2004-07-06,Charles C Soludo,Governor,Male,Central Bank of Nigeria,NGA,Charles Chukwuma Soludo: Consolidating the Nig...,NaN,r040727g,English,BIS
14233,https://www.bis.org/review/r050510c.pdf,https://www.bis.org/review/r050510c.pdf,Promoting effective and efficient customer ser...,"Opening address by Professor Charles C Soludo,...",2005-03-30,Charles C Soludo,Governor,Male,Central Bank of Nigeria,NGA,Charles C Soludo: Promoting effective and effi...,NaN,r050510c,English,BIS
14930,https://www.bis.org/review/r060824e.pdf,https://www.bis.org/review/r060824e.pdf,"Law, institutions and Nigeria's quest to join ...","Lecture by Professor Charles C Soludo, Governo...",2006-07-25,Charles C Soludo,Governor,Male,Central Bank of Nigeria,NGA,"Charles C Soludo: Law, institutions and Nigeri...",NaN,r060824e,English,BIS
15537,https://www.bis.org/review/r070613c.pdf,https://www.bis.org/review/r070613c.pdf,The safety and soundness of the Nigerian banki...,"Press statement by Professor Charles C Soludo,...",2007-06-12,Charles C Soludo,Governor,Male,Central Bank of Nigeria,NGA,Charles C Soludo: The safety and soundness of ...,NaN,r070613c,English,BIS
15672,https://www.bis.org/review/r070820a.pdf,https://www.bis.org/review/r070820a.pdf,Strategic Agenda for the Naira,"Briefing by Professor Charles C Soludo, Govern...",2007-08-14,Charles C Soludo,Governor,Male,Central Bank of Nigeria,NGA,Charles C Soludo: Strategic Agenda for the Nai...,NaN,r070820a,English,BIS
17048,https://www.bis.org/review/r090717e.pdf,https://www.bis.org/review/r090717e.pdf,Assessment of current development in the Niger...,"Speech by Mr Sanusi Lamido Aminu Sanusi, Gover...",2009-07-07,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Aminu Sanusi: Assessment of curr...,NaN,r090717e,English,BIS
17139,https://www.bis.org/review/r090922b.pdf,https://www.bis.org/review/r090922b.pdf,Developments in the banking system in Nigeria,"Address by Mr Mallam Sanusi Lamido Sanusi, Gov...",2009-08-14,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Mallam Sanusi Lamido Sanusi: Developments in t...,NaN,r090922b,English,BIS
17627,https://www.bis.org/review/r100419c.pdf,https://www.bis.org/review/r100419c.pdf,The Nigerian banking industry - what went wron...,Text of the Convocation Lecture by Mr Sanusi L...,2010-02-26,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: The Nigerian banking ind...,NaN,r100419c,English,BIS
17986,https://www.bis.org/review/r100930d.pdf,https://www.bis.org/review/r100930d.pdf,Evolving financial landscape - strategies for ...,"Keynote address by Mr Sanusi Lamido Sanusi, Go...",2010-09-23,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Evolving financial lands...,NaN,r100930d,English,BIS
18178,https://www.bis.org/review/r101210e.pdf,https://www.bis.org/review/r101210e.pdf,Growth prospects for the Nigerian economy,Convocation lecture by Mr Sanusi Lamido Sanusi...,2010-11-26,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Growth prospects for the...,NaN,r101210e,English,BIS
18252,https://www.bis.org/review/r110124c.pdf,https://www.bis.org/review/r110124c.pdf,Global financial meltdown and the reforms in t...,"Speech by Mr Sanusi Lamido Sanusi, Governor of...",2010-12-10,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Global financial meltdow...,NaN,r110124c,English,BIS
18370,https://www.bis.org/review/r110323b.pdf,https://www.bis.org/review/r110323b.pdf,Banks in Nigeria and national economic develop...,"Keynote address by Mr Sanusi Lamido Sanusi, Go...",2011-03-07,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Banks in Nigeria and nat...,NaN,r110323b,English,BIS
19171,https://www.bis.org/review/r120320d.pdf,https://www.bis.org/review/r120320d.pdf,Banking reform and its impact on the Nigerian ...,"Lecture by Mr Sanusi Lamido Sanusi, Governor o...",2012-02-17,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Banking reform and its i...,NaN,r120320d,English,BIS
19240,https://www.bis.org/review/r120417d.pdf,https://www.bis.org/review/r120417d.pdf,Neither the Washington nor Beijing Consensus -...,"Speech by Mr Sanusi Lamido Sanusi, Governor of...",2012-03-27,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Neither the Washington n...,NaN,r120417d,English,BIS
19493,https://www.bis.org/review/r120827a.pdf,https://www.bis.org/review/r120827a.pdf,Increasing women's access to finance - challen...,"Paper presented by Mr Sanusi Lamido Sanusi, Go...",2012-07-13,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Increasing womens access...,NaN,r120827a,English,BIS
19520,https://www.bis.org/review/r120907a.pdf,https://www.bis.org/review/r120907a.pdf,Brief overview on the Central Bank of Nigeria'...,"Speech by Mr Sanusi Lamido Sanusi, Governor of...",2012-08-23,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Brief overview on the Ce...,NaN,r120907a,English,BIS
19705,https://www.bis.org/review/r121105f.pdf,https://www.bis.org/review/r121105f.pdf,Nigeria's economic development aspirations and...,"Speech by Mr Sanusi Lamido Sanusi, Governor of...",2012-10-19,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Nigerias economic develo...,NaN,r121105f,English,BIS
20308,https://www.bis.org/review/r130822b.pdf,https://www.bis.org/review/r130822b.pdf,Using geospatial mapping to further the Nation...,"Keynote address by Mr Sanusi Lamido Sanusi, Go...",2013-07-08,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Using geospatial mapping...,NaN,r130822b,English,BIS
20315,https://www.bis.org/review/r130823d.pdf,https://www.bis.org/review/r130823d.pdf,Financing small and medium enterprises - strat...,"Keynote address by Mr Sanusi Lamido Sanusi, Go...",2013-08-15,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Financing small and medi...,NaN,r130823d,English,BIS
20345,https://www.bis.org/review/r130910c.pdf,https://www.bis.org/review/r130910c.pdf,Supporting the development of entrepreneurship...,"Keynote address by Mr Sanusi Lamido Sanusi, Go...",2013-09-02,Sanusi Lamido Sanusi,Governor,Male,Central Bank of Nigeria,NGA,Sanusi Lamido Sanusi: Supporting the developme...,NaN,r130910c,English,BIS
20923,https://www.bis.org/review/r140428f.htm,https://www.bis.org/review/r140428f.pdf,Promoting inclusive growth and transformative ...,"Welcome address by Dr Sarah Alade, Acting Gove...",2014-03-27,Sarah Alade,Governor,Female,Central Bank of Nigeria,NGA,Sarah Alade: Promoting inclusive growth and tr...,NaN,r140428f,English,BIS
24596,https://www.bis.org/review/r181221g.htm,https://www.bis.org/review/r181221g.pdf,Strengthening the economic recovery process in...,"Keynote address by Mr Godwein I Emefiele, Gove...",2018-11-30,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,CENTRAL BANK OF NIGERIA AN ADDRESS BY GOVERNOR...,NaN,r181221g,English,BIS
26750,https://www.bis.org/review/r211231a.htm,https://www.bis.org/review/r211231a.pdf,Developments in the Nigerian economy and outlook,"Keynote address by Mr Godwein I Emefiele, Gove...",2021-11-26,Godwin I Emefiele,Governor,Male,Central Bank of Nigeria,NGA,"Gov. Godwin Emefiele, CON Keynote Address at t...",NaN,r211231a,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Nigeria
Central Bank of Bahrain

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1121,https://www.cbb.gov.bh/media-center/middle-eas...,NaN,Middle East Asset Management Forum 2017,NaN,2017-05-15,Abdul Rahman Al-Baker,Board member,Male,Central Bank of Bahrain,BHR,Middle East Asset Management Forum 2017 Publis...,NaN,bhr_middle_east_asset_management_forum_2017___cbb,English,CB websites
1122,https://www.cbb.gov.bh/media-center/middle-eas...,NaN,1st Middle East and Africa FinTech Forum,NaN,2017-02-20,Abdul Rahman Al-Baker,Board member,Male,Central Bank of Bahrain,BHR,Middle East Insurance Forum 2017 Published on ...,NaN,bhr_middle_east_insurance_forum_2017___cbb,English,CB websites
14517,https://www.bis.org/review/r051207b.pdf,https://www.bis.org/review/r051207b.pdf,Basel II and risk management,"Address by His Excellency Rasheed M Al-Maraj, ...",2005-11-30,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed M Al-Maraj: Basel II and risk manageme...,NaN,r051207b,English,BIS
14856,https://www.bis.org/review/r060706e.pdf,https://www.bis.org/review/r060706e.pdf,Challenges facing the Islamic financial servic...,Welcome address by His Excellency Mr Anwar Kha...,2006-06-11,Anwar Al-Sadah,Deputy Governor,Male,Central Bank of Bahrain,BHR,Anwar Khalifa Al Sadah: Challenges facing the ...,NaN,r060706e,English,BIS
14952,https://www.bis.org/review/r060831d.pdf,https://www.bis.org/review/r060831d.pdf,Detection and prosecution of securities market...,Speech by His Excellency Rasheed Mohammed Al M...,2006-06-26,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Detection and prose...,NaN,r060831d,English,BIS
14968,https://www.bis.org/review/r060907b.pdf,https://www.bis.org/review/r060907b.pdf,Bahrain's experience as single regulator,Presentation by His Excellency Rasheed Mohamme...,2006-09-04,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Bahrains experience...,NaN,r060907b,English,BIS
15405,https://www.bis.org/review/r070424d.pdf,https://www.bis.org/review/r070424d.pdf,Fighting financial crime,Speech by His Excellency Rasheed Mohammed Al M...,2007-03-28,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Fighting financial ...,NaN,r070424d,English,BIS
15415,https://www.bis.org/review/r070502d.pdf,https://www.bis.org/review/r070502d.pdf,Brief review of Bahrain's financial market dev...,Speech by His Excellency Rasheed Mohammed Al M...,2007-04-28,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Brief review of Bah...,NaN,r070502d,English,BIS
15434,https://www.bis.org/review/r070510b.pdf,https://www.bis.org/review/r070510b.pdf,Key developments in Bahrain and the region,Speech by His Excellency Rasheed Mohammed Al M...,2007-05-08,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Key developments in...,NaN,r070510b,English,BIS
15476,https://www.bis.org/review/r070525b.pdf,https://www.bis.org/review/r070525b.pdf,Supervising Islamic financial institutions de...,Speech by His Excellency Rasheed Mohammed Al M...,2007-05-15,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Supervising Islamic...,NaN,r070525b,English,BIS
15477,https://www.bis.org/review/r070525c.pdf,https://www.bis.org/review/r070525c.pdf,Bahrain country showcase,Speech by His Excellency Rasheed Mohammed Al M...,2007-05-14,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Bahrain country sho...,NaN,r070525c,English,BIS
15478,https://www.bis.org/review/r070525d.pdf,https://www.bis.org/review/r070525d.pdf,Gulf Executive Development Programme,Speech by His Excellency Rasheed Mohammed Al M...,2007-04-30,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Gulf Executive Deve...,NaN,r070525d,English,BIS
15479,https://www.bis.org/review/r070525f.pdf,https://www.bis.org/review/r070525f.pdf,"Bloomberg Discussion Forum ""Sharia Alternative...","Speech by His Excellency Anwar Al-Sadah, Deput...",2007-05-22,Anwar Al-Sadah,Deputy Governor,Male,Central Bank of Bahrain,BHR,Anwar Al-Sadah: Bloomberg Discussion Forum Sha...,NaN,r070525f,English,BIS
15576,https://www.bis.org/review/r070628c.pdf,https://www.bis.org/review/r070628c.pdf,Developing the global Islamic financial markets,Speech by His Excellency Rasheed Mohammed Al M...,2007-06-18,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Developing the glob...,NaN,r070628c,English,BIS
15705,https://www.bis.org/review/r070912b.pdf,https://www.bis.org/review/r070912b.pdf,The role Islamic financial institutions play i...,Speech by His Excellency Rasheed Mohammed Al M...,2007-09-04,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: The role Islamic fi...,NaN,r070912b,English,BIS
15955,https://www.bis.org/review/r071217c.pdf,https://www.bis.org/review/r071217c.pdf,Challenges facing Islamic financial institutions,Speech by His Excellency Rasheed Mohammed Al M...,2007-12-09,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Challenges facing I...,NaN,r071217c,English,BIS
15990,https://www.bis.org/review/r080116c.pdf,https://www.bis.org/review/r080116c.pdf,Vigorous economic growth in Bahrain,Speech by His Excellency Rasheed Mohammed Al M...,2008-01-10,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Vigorous economic g...,NaN,r080116c,English,BIS
16178,https://www.bis.org/review/r080421b.pdf,https://www.bis.org/review/r080421b.pdf,Improving risk management in Bahrain,Address by His Excellency Rasheed Mohammed Al ...,2008-02-19,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Improving risk mana...,NaN,r080421b,English,BIS
16179,https://www.bis.org/review/r080421c.pdf,https://www.bis.org/review/r080421c.pdf,Impact of technological innovation in Bahrain,Address by His Excellency Rasheed Mohammed Al ...,2008-02-11,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Impact of technolog...,NaN,r080421c,English,BIS
16183,https://www.bis.org/review/r080422b.pdf,https://www.bis.org/review/r080422b.pdf,Toward a more integrated Arab insurance market,Address by His Excellency Rasheed Mohammed Al ...,2008-02-26,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Toward a more integ...,NaN,r080422b,English,BIS
16184,https://www.bis.org/review/r080422c.pdf,https://www.bis.org/review/r080422c.pdf,Financial sector education and training in Bah...,Address by His Excellency Rasheed Mohammed Al ...,2008-02-20,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Financial sector ed...,NaN,r080422c,English,BIS
16281,https://www.bis.org/review/r080606e.pdf,https://www.bis.org/review/r080606e.pdf,Financial and regulatory developments in Bahrain,Address by His Excellency Rasheed Mohammed Al ...,2008-05-05,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Financial and regul...,NaN,r080606e,English,BIS
16289,https://www.bis.org/review/r080610bc.pdf,https://www.bis.org/review/r080610bc.pdf,Overview of the Islamic fund industry in Bahrain,Address by His Excellency Rasheed Mohammed Al ...,2008-05-26,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Overview of the Isl...,NaN,r080610bc,English,BIS
16374,https://www.bis.org/review/r080717c.pdf,https://www.bis.org/review/r080717c.pdf,Challenges for Islamic finance,Keynote address by His Excellency Rasheed Moha...,2008-07-08,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Challenges for Isla...,NaN,r080717c,English,BIS
16666,https://www.bis.org/review/r081219d.pdf,https://www.bis.org/review/r081219d.pdf,Prospects for the Islamic financial industry a...,Keynote address by His Excellency Rasheed Moha...,2008-11-10,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Prospects for the I...,NaN,r081219d,English,BIS
16667,https://www.bis.org/review/r081219e.pdf,https://www.bis.org/review/r081219e.pdf,Bahrain develops its financial centre in the G...,Address by His Excellency Rasheed Mohammed Al ...,2008-11-09,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Bahrain develops it...,NaN,r081219e,English,BIS
16671,https://www.bis.org/review/r081222c.pdf,https://www.bis.org/review/r081222c.pdf,Ensuring stability - international perspective...,Inaugural plenary address by His Excellency Ra...,2008-11-24,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Ensuring stability ...,NaN,r081222c,English,BIS
16672,https://www.bis.org/review/r081222d.pdf,https://www.bis.org/review/r081222d.pdf,Impact of the current global financial crisis ...,Address by His Excellency Rasheed Mohammed Al ...,2008-11-18,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Impact of the curre...,NaN,r081222d,English,BIS
16678,https://www.bis.org/review/r081223d.pdf,https://www.bis.org/review/r081223d.pdf,Building a sound framework for the fund manage...,Keynote guest address by His Excellency Rashee...,2008-12-02,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Building a sound fr...,NaN,r081223d,English,BIS
16736,https://www.bis.org/review/r090213e.pdf,https://www.bis.org/review/r090213e.pdf,Meeting the challenges of growth,Opening keynote plenary by His Excellency Rash...,2009-02-08,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Meeting the challen...,NaN,r090213e,English,BIS
16739,https://www.bis.org/review/r090216c.pdf,https://www.bis.org/review/r090216c.pdf,Leveraging technology through turbulent times,Address by His Excellency Rasheed Mohammed Al ...,2009-02-10,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Leveraging technolo...,NaN,r090216c,English,BIS
16744,https://www.bis.org/review/r090217d.pdf,https://www.bis.org/review/r090217d.pdf,Current financial situation in Bahrain,Address by His Excellency Rasheed Mohammed Al ...,2009-02-11,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Current financial s...,NaN,r090217d,English,BIS
16920,https://www.bis.org/review/r090512c.pdf,https://www.bis.org/review/r090512c.pdf,The Corporate Governance Code of the Kingdom o...,Address by His Excellency Rasheed Mohammed Al ...,2009-05-04,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: The Corporate Gover...,NaN,r090512c,English,BIS
17256,https://www.bis.org/review/r091109c.pdf,https://www.bis.org/review/r091109c.pdf,Development of the insurance business in Bahrain,Address by His Excellency Rasheed Mohammed Al ...,2009-11-04,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Development of the ...,NaN,r091109c,English,BIS
17319,https://www.bis.org/review/r091201b.pdf,https://www.bis.org/review/r091201b.pdf,Islamic finance amid the global financial turmoil,"Address by HE Rasheed M Al-Maraj, Governor of ...",2009-11-11,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed M Al-Maraj: Islamic finance amid the g...,NaN,r091201b,English,BIS
17382,https://www.bis.org/review/r091218d.pdf,https://www.bis.org/review/r091218d.pdf,"Inaugural Plenary Session - ""Regulatory perspe...",Speech by His Excellency Rasheed Mohammed Al-M...,2009-12-07,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al-Maraj: Inaugural Plenary S...,NaN,r091218d,English,BIS
17389,https://www.bis.org/review/r091221e.pdf,https://www.bis.org/review/r091221e.pdf,Islamic finance and the financial crisis,Keynote address by His Excellency Rasheed Moha...,2009-12-14,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Islamic finance and...,NaN,r091221e,English,BIS
17411,https://www.bis.org/review/r100121b.pdf,https://www.bis.org/review/r100121b.pdf,Luxembourg - a global financial services centre,Keynote address by HE Rasheed Mohammed Al-Mara...,2010-01-11,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al-Maraj: Luxembourg a globa...,NaN,r100121b,English,BIS
17547,https://www.bis.org/review/r100319c.pdf,https://www.bis.org/review/r100319c.pdf,The Corporate Governance Code of the Kingdom o...,Welcome address by His Excellency Rasheed Moha...,2010-03-16,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: The Corporate Gover...,NaN,r100319c,English,BIS
17620,https://www.bis.org/review/r100416b.pdf,https://www.bis.org/review/r100416b.pdf,Relationship between financial institutions an...,"Remarks by HE Rasheed Mohammed Al Maraj, Gover...",2010-04-13,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Relationship betwee...,NaN,r100416b,English,BIS
17709,https://www.bis.org/review/r100518c.pdf,https://www.bis.org/review/r100518c.pdf,Global financial architecture - challenges for...,Keynote address by His Excellency Rasheed Moha...,2010-05-04,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Global financial ar...,NaN,r100518c,English,BIS
17788,https://www.bis.org/review/r100621d.pdf,https://www.bis.org/review/r100621d.pdf,Towards the next phase of growth for Islamic b...,Opening remarks by HE Rasheed Mohammed Al Mara...,2010-06-14,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Towards the next ph...,NaN,r100621d,English,BIS
17990,https://www.bis.org/review/r101004a.pdf,https://www.bis.org/review/r101004a.pdf,Business models in Islamic finance - challenge...,Keynote address by HE Rasheed Mohammed Al Mara...,2010-10-03,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Business models in ...,NaN,r101004a,English,BIS
18106,https://www.bis.org/review/r101122b.pdf,https://www.bis.org/review/r101122b.pdf,Corporate governance lessons to be learned fro...,Keynote address by HE Rasheed Mohammed Al-Mara...,2010-11-02,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al-Maraj: Corporate governanc...,NaN,r101122b,English,BIS
18156,https://www.bis.org/review/r101207c.pdf,https://www.bis.org/review/r101207c.pdf,The role of the financial services industry in...,Keynote speech by His Excellency Rasheed Moham...,2010-11-21,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: The role of the fin...,NaN,r101207c,English,BIS
18160,https://www.bis.org/review/r101208a.pdf,https://www.bis.org/review/r101208a.pdf,Regulatory perspectives - strengthening indust...,Keynote address by His Excellency Rasheed Moha...,2010-11-23,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Regulatory perspect...,NaN,r101208a,English,BIS
18280,https://www.bis.org/review/r110207a.pdf,https://www.bis.org/review/r110207a.pdf,Regulatory insights - successfully supporting ...,Keynote speech by HE Rasheed Mohammed Al Maraj...,2011-02-07,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Regulatory insights...,NaN,r110207a,English,BIS
18816,https://www.bis.org/review/r111007c.pdf,https://www.bis.org/review/r111007c.pdf,Rebuilding confidence in the financial sector,Introductory remarks by HE Rasheed Mohammed Al...,2011-10-04,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Rebuilding confiden...,NaN,r111007c,English,BIS
18856,https://www.bis.org/review/r111027c.pdf,https://www.bis.org/review/r111027c.pdf,Relevance of international standards to the Is...,"Speech by HE Rasheed Mohammed Al Maraj, Govern...",2011-10-23,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Relevance of intern...,NaN,r111027c,English,BIS
19012,https://www.bis.org/review/r111229e.pdf,https://www.bis.org/review/r111229e.pdf,Managing the challenges of industry globalization,Keynote address by His Excellency Rasheed Moha...,2011-11-22,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Managing the challe...,NaN,r111229e,English,BIS
19164,https://www.bis.org/review/r120319c.pdf,https://www.bis.org/review/r120319c.pdf,Global regulation and offshore centres - onsho...,Address by His Excellency Rasheed Mohammed Al ...,2012-03-07,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Global regulation a...,NaN,r120319c,English,BIS
19308,https://www.bis.org/review/r120522b.pdf,https://www.bis.org/review/r120522b.pdf,Corporate governance and Shari'a compliance in...,Welcome speech by His Excellency Rasheed Moham...,2012-05-07,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Mohammed Al Maraj: Corporate governanc...,NaN,r120522b,English,BIS
23155,https://www.bis.org/review/r170403f.htm,https://www.bis.org/review/r170403f.pdf,Financial technology and its impact on the ban...,Keynote address by His Excellency Rasheed Moha...,2017-03-29,Rasheed Mohammed Al Maraj,Governor,Male,Central Bank of Bahrain,BHR,Rasheed Al Maraj: Financial technology and its...,NaN,r170403f,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Bahrain
Bank of Algeria

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2932,NaN,https://www.bank-of-algeria.dz/pdf/abcasyposiu...,Opening remarks at the Governors' Symposium on...,NaN,2013-08-22,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Opening remarks by Mr. Mohamme...,BANK OF ALGERIA Remarques dOuverture par M. Mo...,dza_abcasyposium_aout2013,French,CB websites
2933,NaN,https://www.bank-of-algeria.dz/pdf/allocution_...,Speech during a video-conference of the Intern...,NaN,2020-03-27,Aymen Benabderrahmane,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Speech by the Governor of the ...,BANK OF ALGERIA sanitaires drastiques dans l'e...,dza_allocution_fmi27032020,French,CB websites
2934,https://www.bank-of-algeria.dz/allocution-de-m...,https://www.bank-of-algeria.dz/wp-content/uplo...,Speech by Governor Salah Eddine Taleb at the c...,NaN,2022-11-14,Salah-Eddine Taleb,Governor,Male,Bank of Algeria,DZA,"The opening speech of Mr. Sahlah El-Din Moss, ...","The opening speech of Mr. Sahlah El-Din Moss, ...",dza_communication14112022,Arabic,CB websites
2935,https://www.bank-of-algeria.dz/discours-de-mr-...,https://www.bank-of-algeria.dz/wp-content/uplo...,Statement by Governor Salah-Eddine Taleb at th...,NaN,2022-09-28,Salah-Eddine Taleb,Governor,Male,Bank of Algeria,DZA,C:\Users\abderrahmane.aouiti\Desktop\242520201...,C:\Users\abderrahmane.aouiti\Desktop\242520201...,dza_communication28092022,Arabic,CB websites
2936,NaN,https://www.bank-of-algeria.dz/pdf/communicati...,Communication on macroeconomic stability and b...,NaN,2015-06-11,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"Algiers, 11 June 2015 Macroeconomic stability ...","Alger, le 11 Juin 2015 Stabilit macroconomique...",dza_communicationgouv11062015,French,CB websites
2937,NaN,https://www.bank-of-algeria.dz/pdf/declaration...,"Statement in the videoconference of April 22, ...",NaN,2020-04-22,Aymen Benabderrahmane,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Responding to the COVID-19 Pan...,BANK OF ALGERIA Face la pandmie du covid-19 a...,dza_declaration22042020fmi,French,CB websites
2938,NaN,https://www.bank-of-algeria.dz/pdf/declaration...,Statement on the occasion of the 44th meeting ...,NaN,2021-10-14,Rosthom Fadli,Governor,Male,Bank of Algeria,DZA,Speech by Mr. Rosthom Fadli Governor of the Ba...,INTERNATIONAL MONETARY AND FINANCIAL COMMITTEE...,dza_declarationgouv_14102021fr,French,CB websites
2939,https://www.bank-of-algeria.dz/intervention-de...,https://www.bank-of-algeria.dz/wp-content/uplo...,Communication of the Bank of Algeria on the oc...,NaN,2022-12-26,Salah-Eddine Taleb,Governor,Male,Bank of Algeria,DZA,The Governor of Ben Ka spoke to Algeria on the...,The Governor of Ben Ka spoke to Algeria on the...,dza_discours_anniversaire26122022-1,Arabic,CB websites
2940,https://www.bank-of-algeria.dz/discours-de-mr-...,https://www.bank-of-algeria.dz/wp-content/uplo...,Speech by Governor Salah Eddine TALEB on the o...,NaN,2022-04-23,Salah-Eddine Taleb,Governor,Male,Bank of Algeria,DZA,INTERNATIONAL MONETARY AND FINANCIAL COMMITTEE...,NaN,dza_discoursgouverneur23042022ang,English,CB websites
2941,NaN,https://www.bank-of-algeria.dz/pdf/inclusion1.pdf,Message from the Governor of the Bank of Algeria,NaN,2016-04-01,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"Statement by Mr. Mohammed Laksaci, Governor of...","Dclaration de Monsieur Mohammed Laksaci, Gouve...",dza_inclusion1,French,CB websites
2942,NaN,https://www.bank-of-algeria.dz/pdf/inclusion2.pdf,Press release,NaN,2016-04-26,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Committees - Injara / :[ He has 4 : Jackcock T...,- / :[ 4 : ...,dza_inclusion2,Arabic,CB websites
2943,NaN,https://www.bank-of-algeria.dz/pdf/inclusion27...,Message from the Governor of the Bank of Algeria,NaN,2021-04-27,Rosthom Fadli,Governor,Male,Bank of Algeria,DZA,MESSAGE FROM THE GOVERNOR OF THE BANK OF ALGER...,MESSAGE DE MONSIEUR LE GOUVERNEUR DE LA BANQUE...,dza_inclusion27042021_interventiongouv,French,CB websites
2944,NaN,https://www.bank-of-algeria.dz/pdf/inclusion3.pdf,Joint statement of the Board of Governors of A...,NaN,2016-04-27,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Committees - Injara / :[ He has 4 : Jackcock T...,- / :[ 4 : ...,dza_inclusion3,Arabic,CB websites
2945,NaN,https://www.bank-of-algeria.dz/pdf/inclusion4.pdf,Arab Central Banks Governors' Common Statement,NaN,2016-04-27,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,THE COUNCIL OF ARAB CENTRAL BANKS GOVERNORS SU...,NaN,dza_inclusion4,English,CB websites
2946,NaN,https://www.bank-of-algeria.dz/pdf/inclusion5.pdf,Joint statement by the Board of Governors of A...,NaN,2016-04-27,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,THE BOARD OF GOVERNORS OF THE ARAB CENTRAL BAN...,LE CONSEIL DES GOUVERNEURS DES BANQUES CENTRAL...,dza_inclusion5,French,CB websites
2947,NaN,https://www.bank-of-algeria.dz/pdf/inclusion7.pdf,Understanding financial inclusion,NaN,2016-04-01,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,BROCHURE ON FINANCIAL INCLUSION This brochure ...,BROCHURE SUR LINCLUSION FINANCIERE Cette broch...,dza_inclusion7,French,CB websites
2948,NaN,https://www.bank-of-algeria.dz/pdf/inclusionan...,Common statement of the Council of Arab Centra...,NaN,2021-04-27,Rosthom Fadli,Governor,Male,Bank of Algeria,DZA,Press Release issued by: The Secretariat of th...,NaN,dza_inclusionanglais_com,English,CB websites
2949,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Financial stability and banking sector develop...,NaN,2009-10-04,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"BANK OF ALGERIA Istanbul, Turkey, Sunday, 4 Oc...","BANK OF ALGERIA Istanbul, Turquie, Dimanche 4 ...",dza_intervention_04102009,French,CB websites
2950,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Economic and monetary developments in 2010 and...,NaN,2012-05-05,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"BANK OF ALGERIA SPEECH BY MR MOHAMMED LAKSACI,...",BANK OF ALGERIA INTERVENTION DE MONSIEUR MOHAM...,dza_intervention_1,French,CB websites
2951,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Economic and monetary developments in Algeria,NaN,2008-10-11,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA 11 OCTOBER 2008 SPEECH OF MR. ...,BANK OF ALGERIA 11 OCTOBRE 2008 INTERVENTION D...,dza_intervention_11102008,French,CB websites
2952,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Statement to the International Monetary and Fi...,NaN,2008-04-12,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,12 APRIL 2008 SPEECH BY MR MOHAMMED LAKSACI GO...,12 AVRIL 2008 INTERVENTION DE MONSIEUR MOHAMME...,dza_intervention_12042008,French,CB websites
2953,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Intervention before the Council of the Nation,NaN,2008-07-13,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,13 July 2008 ECONOMIC AND MONETARY DEVELOPMENT...,13 juillet 2008 VOLUTIONS CONOMIQUES ET MONTAI...,dza_intervention_13072008,French,CB websites
2954,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Statement to the International Monetary and Fi...,NaN,2012-10-13,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"Algiers, 13 October 2012 SPEECH BY MR. MOHAMME...","Alger, 13 octobre 2012 INTERVENTION DE MONSIEU...",dza_intervention_13102012,French,CB websites
2955,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Statement to the International Monetary and Fi...,NaN,2011-10-16,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"Algiers, 16 October 2011 ECONOMIC AND MONETARY...","Alger, 16 octobre 2011 EVOLUTIONS ECONOMIQUES ...",dza_intervention_16102011,French,CB websites
2956,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Acceleration of inflation in 2012: the need to...,NaN,2013-02-18,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"BANK OF ALGERIA Algiers, 18 February 2013 ACCE...","BANK OF ALGERIA Alger, 18 fvrier 2013 ACCELERA...",dza_intervention_18022013,French,CB websites
2957,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Intervention at the regional conference on glo...,NaN,2008-03-18,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,18 MARCH 2008 SPEECH BY MR. MOHAMMED LAKSACI G...,18 MARS 2008 INTERVENTION DE MONSIEUR MOHAMMED...,dza_intervention_18032008,French,CB websites
2958,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Statement to the International Monetary and Fi...,NaN,2009-01-10,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Financial stability and developments in the ba...,Stabilit financire et dveloppements du secteur...,dza_intervention_2,French,CB websites
2959,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Communication at the meeting with the presiden...,NaN,2009-04-20,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"Algiers, 20 April 2009 ALGERIA'S PARTICIPATION...","Alger, le 20 Avril 2009 LA PARTICIPATION DE LA...",dza_intervention_20042009,French,CB websites
2960,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Improvement in fiduciary circulation in 2012 a...,NaN,2013-03-21,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Improving cash circulation in ...,BANK OF ALGERIA Lamlioration de la circulation...,dza_intervention_21032013,French,CB websites
2961,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Presentation of the 2010 annual report,NaN,2011-09-24,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Speech by Mr. Mohammed Laksaci Governor of the...,Intervention de Monsieur Mohammed Laksaci Gouv...,dza_intervention_24092011,French,CB websites
2962,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Statement to the International Monetary and Fi...,NaN,2011-08-25,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"BANK OF ALGERIA Algiers, 25 August 2011 ECONOM...","BANK OF ALGERIA Alger, le 25 aot 2011 EVOLUTIO...",dza_intervention_25082011,French,CB websites
2963,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Intervention before the APN on monetary and fi...,NaN,2019-02-23,Mohamed Loukal,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Message from the Governor at t...,BANK OF ALGERIA Mot du Gouverneur louverture ...,dza_intervention_abef022019,French,CB websites
2964,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Statement on the occasion of the meeting with ...,NaN,2021-12-21,Rosthom Fadli,Governor,Male,Bank of Algeria,DZA,Presentation of the Governor of the Bank of Al...,Prsentation de Mr le Gouverneur de la Banque d...,dza_intervention21122021,French,CB websites
2965,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Intervention to the National Popular Assembly ...,NaN,2017-01-29,Mohamed Loukal,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Monetary and financial trends ...,BANK OF ALGERIA Tendances montaires et financi...,dza_interventiongouverneur_apn_janvier2017fr,French,CB websites
2966,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Intervention on the role of central banks in p...,NaN,2014-05-14,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Role of central banks in promo...,BANK OF ALGERIA Rle des banques centrales dans...,dza_interventiongouverneur_dakar14et15052014,French,CB websites
2967,NaN,https://www.bank-of-algeria.dz/pdf/interventio...,Development of alternative finance in Algeria ...,NaN,2018-04-03,Mohamed Loukal,Governor,Male,Bank of Algeria,DZA,Development of alternative finance in Algeria ...,Dveloppement de la finance alternative en Algr...,dza_interventiongouverneur_parlementaire03042018,French,CB websites
2968,NaN,https://www.bank-of-algeria.dz/pdf/laksaci1804...,Statement to the International Monetary and Fi...,NaN,2015-04-18,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,BANK OF ALGERIA Statement by Mr Mohammed Laksa...,BANK OF ALGERIA Dclaration de Monsieur Mohamme...,dza_laksaci18042015fmi,French,CB websites
2969,NaN,https://www.bank-of-algeria.dz/pdf/nc42.pdf,Communication on monetary and financial trends...,NaN,2013-12-26,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,MONETARY AND FINANCIAL TRENDS IN THE FIRST NIN...,TENDANCES MONETAIRES ET FINANCIERES AU COURS D...,dza_nc42,French,CB websites
2970,NaN,https://www.bank-of-algeria.dz/pdf/renforcemen...,Strengthening control and supervision of forei...,NaN,2013-08-15,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Strengthening the control and supervision of f...,Renforcement du contrle et de la supervision d...,dza_renforcementducontroleducommerceexterieur,French,CB websites
2971,NaN,https://www.bank-of-algeria.dz/pdf/reunionimfc...,Statement to the International Monetary and Fi...,NaN,2020-04-16,Aymen Benabderrahmane,Governor,Male,Bank of Algeria,DZA,Statement to the IMFC by Mr. AIMENE BENABDERRA...,Dclaration au CMFI de M. Mr. AIMENE BENABDERRA...,dza_reunionimfc_16042020fr,French,CB websites
2972,https://www.bank-of-algeria.dz/intervention-de...,https://www.bank-of-algeria.dz/wp-content/uplo...,Speech by Governor Salah Eddine TALEB on the o...,NaN,2023-05-04,Salah-Eddine Taleb,Governor,Male,Bank of Algeria,DZA,Intervention of the Governor of Algeria Bank M...,Intervention of the Governor of Algeria Bank M...,dza_salah_eddine_45050,Arabic,CB websites
2973,https://www.bank-of-algeria.dz/discours-de-mr-...,https://www.bank-of-algeria.dz/wp-content/uplo...,Speech by Governor Salah Eddine TALEB on the o...,NaN,2023-09-17,Salah-Eddine Taleb,Governor,Male,Bank of Algeria,DZA,word H.E. Salehuddin Talib Governor of Algeria...,C:\Users\mus\AppData\Local\Microsoft\Windows\I...,dza_salah_eddine_45186,Arabic,CB websites
2974,NaN,https://www.bank-of-algeria.dz/pdf/TENDANCES%2...,Communication on monetary and financial trends...,NaN,2014-02-19,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,MONETARY AND FINANCIAL TRENDS IN THE FOURTH QU...,TENDANCES MONETAIRES ET FINANCIERES AU QUATRIE...,dza_tendances monetaires au 4e trimestre 2013,French,CB websites
2975,NaN,https://www.bank-of-algeria.dz/pdf/tendancesmo...,Communication on monetary and financial trends...,NaN,2013-09-25,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,"Algiers, 25 September 2013 Monetary and financ...","Alger, le 25 septembre 2013 Tendances montaire...",dza_tendancesmonetaires_1ersemestre2013,French,CB websites
16762,https://www.bis.org/review/r090224c.pdf,https://www.bis.org/review/r090224c.pdf,Financial system developments in Algeria - res...,"Speech by Dr Mohammed Laksaci, Governor of the...",2009-01-22,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Mohammed Laksaci: Financial system development...,NaN,r090224c,English,BIS
17395,https://www.bis.org/review/r091223d.pdf,https://www.bis.org/review/r091223d.pdf,Investment financing in Algeria,"Speech by Dr Mohammed Laksaci, Governor of the...",2009-10-07,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Mohammed Laksaci: Investment financing in Alge...,NaN,r091223d,English,BIS
21524,https://www.bis.org/review/r150127b.htm,https://www.bis.org/review/r150127b.pdf,Banking sector reform and financial stability ...,"Communication by Mr Mohammed Laksaci, Governor...",2014-09-01,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Mohammed Laksaci: Banking sector reform and fi...,NaN,r150127b,English,BIS
22485,https://www.bis.org/review/r160526b.htm,https://www.bis.org/review/r160526b.pdf,Impact of the oil price decline on the Algeria...,"Keynote address by Mr Mohammed Laksaci, Govern...",2016-04-26,Mohammed Laksaci,Governor,Male,Bank of Algeria,DZA,Mohammed Laksaci: Impact of the oil price decl...,NaN,r160526b,English,BIS
26251,https://www.bis.org/review/r210420a.htm,https://www.bis.org/review/r210420a.pdf,IMFC Statement,"Statement by Mr Rosthom Fadli, Governor of the...",2021-04-08,Rosthom Fadli,Governor,Male,Bank of Algeria,DZA,Rosthom Fadli: IMFC Statement Statement by Mr ...,NaN,r210420a,English,BIS
26252,https://www.bis.org/review/r210420b.htm,https://www.bis.org/review/r210420b.pdf,IMFC Statement,"Statement by Mr Rosthom Fadli, Governor of the...",2020-10-15,Rosthom Fadli,Governor,Male,Bank of Algeria,DZA,Rosthom Fadli: IMFC Statement Statement by Mr ...,NaN,r210420b,English,BIS
27285,http://www.bis.org/review/r221103f.htm,http://www.bis.org/review/r221103f.pdf,Salah-Eddine Taleb: IMFC Statement,"Statement by Mr Salah-Eddine Taleb, Governor o...",2022-10-14,Salah-Eddine Taleb,Governor,Male,Bank of Algeria,DZA,INTERNATIONAL MONETARY AND FINANCIAL COMMITTEE...,NaN,r221103f,English,BIS
27286,http://www.bis.org/review/r221103g.htm,http://www.bis.org/review/r221103g.pdf,Mouatassem Boudiaf: IMFC Deputies meeting Stat...,"Statement by Mr Mouatassem Boudiaf, Deputy Gov...",2022-09-20,Mouatassem Boudiaf,Deputy Governor,Male,Bank of Algeria,DZA,INTERNATIONAL MONETARY AND FINANCIAL COMMITTEE...,NaN,r221103g,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Algeria
Central Bank of Bosnia and Herzegovina

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1137,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Opening Remarks For The 3Rd Financial Forum,NaN,1999-06-02,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,OPENING REMARKS FOR THE 3rd FINANCIAL FORUM CB...,NaN,bih_02jun99_en,English,CB websites
1138,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Peace Seminar On Bosnia And Herzegovina - Buil...,NaN,2000-03-03,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,The following speech was delivered at an inter...,Govor koji slijedi je odran na meunarodnoj kon...,bih_03mart2000_en,Bosnian,CB websites
1139,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Chamber Of Commerce Speech,NaN,2000-02-08,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,"DISCUSSION AT THE ROUND TABLE ON ""DIRECT FOREI...",DISKUSIJA ZA OKRUGLIM STOLOM O DIREKTNOM STRAN...,bih_08feb2000_en,Bosnian,CB websites
1140,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Presentation for the students of the economic ...,NaN,2001-12-12,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,' THE ROLE OF THE CENTRAL BANK OF BOSNIA AND H...,NaN,bih_11.12.govorzablibrcko_en,English,CB websites
1141,https://www.cbbh.ba/content/DownloadAttachment...,NaN,The Reform Of The Banking System In Bih,NaN,2000-10-11,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Comments of the Governor of the Central Bank o...,NaN,bih_11oct2000_en,English,CB websites
1142,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Managing Foreign Exchange Risks In Bosnia And ...,NaN,1999-10-14,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,MANAGING FOREIGN EXCHANGE RISKS IN BOSNIA AND ...,NaN,bih_14-15oct99_en,English,CB websites
1143,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Opening Remarks Grand Opening Of New Banja Luk...,NaN,2000-03-15,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Speech Notes of Peter W. Nicholl Governor of t...,NaN,bih_15mar2000_en,English,CB websites
1144,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Speech Notes For The Ceremony On The Signing O...,NaN,2000-02-18,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,SPEECH NOTES FOR THE CEREMONY ON THE SIGNING O...,NaN,bih_18feb2000_en,English,CB websites
1145,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Presentation of RTGS and Giro Clearing Systems,NaN,2000-12-20,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Speech of Governor Peter Nicholl at the Presen...,NaN,bih_20dec2000_en,English,CB websites
1146,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Comments at the Peace Implementation Council M...,NaN,2000-05-23,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Governors Welcome and Opening Remarks The Tran...,NaN,bih_23-24maj2000_en,English,CB websites
1147,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Rebuilding The Domestic Economies Of The Balka...,NaN,1999-09-24,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,REBUILDING THE DOMESTIC ECONOMIES OF THE BALKA...,NaN,bih_24sept_en,English,CB websites
1148,https://www.cbbh.ba/content/DownloadAttachment...,NaN,"""Currency, inflation, interest rates and the b...",NaN,2002-02-22,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,"' Currency, inflation, interest rates and the ...",NaN,bih_25.02.govorekonomist-prevod_en,English,CB websites
1149,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Welcome and Opening Remarks - The TransTypeion...,NaN,2000-03-28,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,OPENING REMARKS GRAND OPENING OF NEW BANJA LUK...,NaN,bih_28mar2000_en,English,CB websites
1150,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Opening Remarks For The 4Th Financial Forum,NaN,1999-11-30,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,The BiH Financial System in the Year 2000 & Be...,NaN,bih_30nov99_en,English,CB websites
1151,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Speech notes on ceremony of the agreement sign...,NaN,2002-05-15,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,SPEECH NOTES FOR CEREMONY FOR KM 200 BANKNOTE....,NaN,bih_6.06.govorbamcard_en,English,CB websites
1152,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Signing of the protocol of the Eurosystem need...,NaN,2007-02-16,Andre Lys,Senior management,Male,Central Bank of Bosnia and Herzegovina,BIH,Protocol Signing Event with the European Centr...,NaN,bih_andre-lys-govornceremonija16022007_en,English,CB websites
1153,https://www.cbbh.ba/content/DownloadAttachment...,NaN,"CBBH and USAID international conference ""Macro...",NaN,2019-11-07,Marko kreb,Senior management,Male,Central Bank of Bosnia and Herzegovina,BIH,Marko skreb Closing remarks at 2nd Annual CBBH...,NaN,bih_cbbh y2 conference_closing remarks_marko_s...,English,CB websites
1154,https://www.cbbh.ba/content/DownloadAttachment...,NaN,To the German business community in,NaN,2001-09-13,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,THE PART OF THE SPEECH OF GOVERNOR OF CENTRAL ...,NaN,bih_econom-circle-13.09.2001_en,English,CB websites
1155,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Bosnia And Herzegovina And The Euro,NaN,1999-02-01,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,BOSNIA & HERZEGOVINA & The EURO By Peter Nicho...,NaN,bih_februar99_en,English,CB websites
1156,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Introduction speech at the Third Conference on...,NaN,2001-11-15,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,' THE BANKING SECTOR IN BOSNIA AND HERZEGOVINA...,NaN,bih_govor1_en,English,CB websites
1157,https://www.cbbh.ba/content/DownloadAttachment...,NaN,The First Anniversary Of The Km,NaN,1999-06-22,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,The First Anniversary of the KM Banknote Speec...,NaN,bih_juni99_en,English,CB websites
1158,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Role of Currency Board in Monetary policy,NaN,2003-04-11,Jure Pelivan,Board member,Male,Central Bank of Bosnia and Herzegovina,BIH,Jure Pelivan Member of the Governing Board of ...,NaN,bih_jure-pelivan-bankarska-konferencija-104200...,English,CB websites
1159,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Speech on the opening of the Days of BH Finances,NaN,2008-05-09,Kemal Kozaric,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,"DAYS OF BH FINANCE BANJALUKA, MARCH 8TH AND MA...","DANI BH FINANSIJA BANJALUKA, 8. I 9. MAJ 2008....",bih_kemal_kozaric_dani_bh_finansija_09052008_en,Bosnian,CB websites
1160,https://www.cbbh.ba/content/DownloadAttachment...,NaN,"""Deposit insurance in transitioning countries ...",NaN,2005-12-08,Kemal Kozaric,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,GOVERNOR KEMAL KOZARIC WELCOME ADDRESS TO THE ...,NaN,bih_kozaric-9122005_en,English,CB websites
1161,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Microfinances in BH - Speech at the Ceremonial...,NaN,2005-12-08,Kemal Kozaric,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,MICRO FINANCES IN BIH SPEECH DELIVERED BY GOVE...,NaN,bih_mikrofinansije8122006_en,English,CB websites
1162,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Opening address at the Constituent Assembly of...,NaN,2003-01-30,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,GOVERNOR PETER NICHOLL OPENING ADDRESS AT THE ...,NaN,bih_nicholl-30012003_en,English,CB websites
1163,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Speech notes for ceremony for KM 200 banknote,NaN,2002-05-30,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,"PETER NICHOLL, GOVERNOR OF THE CENTRAL BANK OF...",NaN,bih_nicholl-govor-15maj2002_en,English,CB websites
1164,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Speech at International Investment Conference:...,NaN,2004-02-26,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,SPEECH OF THE GOVERNOR OF THE CENTRAL BANK OF ...,NaN,bih_nicholl-mostar-investmentnconference260220...,English,CB websites
1165,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Speech at the conferences on investment and trade,NaN,2003-06-17,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Bosnia and Herzegovina investment and trade co...,NaN,bih_nicholl-newyork-washington-17062003_en,English,CB websites
1166,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Five years of the CBBH,NaN,2003-04-11,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,FIVE YEARS OF THE CBBH. Presentation for the C...,NaN,bih_nichollnconference-11042003_en,English,CB websites
1167,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Speech notes for round table on banking sector...,NaN,2002-10-24,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,SPEECH NOTES FOR ROUND TABLE ON BANKING SECTOR...,NaN,bih_okrugli-sto-24102002_en,English,CB websites
1168,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Presentation at the Second business roundtable...,NaN,2003-09-22,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Second business roundtable with the government...,NaN,bih_peter-nicholl-economist-23092003_en,English,CB websites
1169,https://www.cbbh.ba/content/DownloadAttachment...,NaN,Comments for Press Conference,NaN,2002-02-14,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Comments for Press Conference 14 February 2002...,NaN,bih_press14022002_en,English,CB websites
12779,https://www.bis.org/review/r010508b.pdf,https://www.bis.org/review/r010508b.pdf,Recent banking sector developments in Bosnia a...,"Speech by Mr Peter Nicholl, Governor of the Ce...",2001-05-05,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Peter Nicholl: Recent banking sector developme...,NaN,r010508b,English,BIS
12819,https://www.bis.org/review/r010608b.pdf,https://www.bis.org/review/r010608b.pdf,Perspectives on monetary policy in Bosnia and ...,"Lecture by Mr Peter Nicholl, Governor of the C...",2001-05-15,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Peter Nicholl: Perspectives on monetary policy...,NaN,r010608b,English,BIS
13359,https://www.bis.org/review/r030530i.pdf,https://www.bis.org/review/r030530i.pdf,Recent developments in the Central Bank of Bos...,"Speech by Mr Vladusic Ljubisa, Vice Governor o...",2003-05-23,Vladusic Ljubisa,Deputy Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Vladusi Ljubisa: Recent developments in the Ce...,NaN,r030530i,English,BIS
13559,https://www.bis.org/review/r031223d.pdf,https://www.bis.org/review/r031223d.pdf,Bosnia and Herzegovina - progress and partnership,"Comments by Mr Peter Nicholl, Governor of the ...",2003-12-09,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Peter Nicholl: Bosnia and Herzegovina - progre...,NaN,r031223d,English,BIS
13911,https://www.bis.org/review/r041022c.pdf,https://www.bis.org/review/r041022c.pdf,Is the capital in Bosnia and Herzegovina expen...,"Speech by Mr Peter Nicholl, Governor of the Ce...",2004-10-13,Peter Nicholl,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Peter Nicholl: Is the capital in Bosnia and He...,NaN,r041022c,English,BIS
15298,https://www.bis.org/review/r070228f.pdf,https://www.bis.org/review/r070228f.pdf,Launch of the Eurosystem Needs Assessment Program,"Speech by Mr Kemal Kozaric, Governor of the Ce...",2007-02-16,Kemal Kozaric,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Kemal Kozari: Launch of the Eurosystem Needs A...,NaN,r070228f,English,BIS
15719,https://www.bis.org/review/r070918d.pdf,https://www.bis.org/review/r070918d.pdf,Reflections on ten years of the Central Bank o...,"Speech by Mr Kemal Kozaric, Governor of the Ce...",2007-09-13,Kemal Kozaric,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Kemal Kozari: Reflections on ten years of the ...,NaN,r070918d,English,BIS
23840,https://www.bis.org/review/r180123b.htm,https://www.bis.org/review/r180123b.pdf,Regional economic perspectives for Europe,"Speech by Mr Senad Softi, Governor of the Cent...",2017-11-13,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,"Speech of the CBBH Governor Senad Softi, Ph.D....",NaN,r180123b,English,BIS
24612,https://www.bis.org/review/r190114c.htm,https://www.bis.org/review/r190114c.pdf,"Monetary policy, economic integration and ""the...","Speech by Mr Senad Softi, Governor of the Cent...",2018-11-01,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Bank of Albania and LSE Conference MONETARY PO...,NaN,r190114c,English,BIS
24632,https://www.bis.org/review/r190122a.htm,https://www.bis.org/review/r190122a.pdf,20 years of stability in Bosnia and Herzegovina,"Welcome speech by Mr Senad Softi, Governor of ...",2017-09-22,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Conference 20 Years of Stability Governor Sena...,NaN,r190122a,English,BIS
24944,https://www.bis.org/review/r190607g.htm,https://www.bis.org/review/r190607g.pdf,Bosnia and Herzegovina pursuing sound monetary...,"Speech by Mr Senad Softi, Governor of the Cent...",2019-05-17,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Senad Softi: Bosnia and Herzegovina pursuing s...,NaN,r190607g,English,BIS
25470,https://www.bis.org/review/r191220b.htm,https://www.bis.org/review/r191220b.pdf,Macroeconomic imbalances and EU convergence,"Welcome speech by Mr Senad Softi, Governor of ...",2019-11-07,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,"Senad Softi PhD Governor, Central Bank of Bosn...",NaN,r191220b,English,BIS
25698,https://www.bis.org/review/r200804d.htm,https://www.bis.org/review/r200804d.pdf,Appreciation speech,"Appreciation speech by Mr Senad Softi, Governo...",2020-06-07,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,"Senad Softi, Ph.D. Governor of the Central Ban...",NaN,r200804d,English,BIS
25779,https://www.bis.org/review/r200911d.htm,https://www.bis.org/review/r200911d.pdf,We will carefully monitor developments and pos...,"Media statement by Mr Senad Softi, Governor of...",2020-08-07,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,Senad Softi: We will carefully monitor develop...,NaN,r200911d,English,BIS
25942,https://www.bis.org/review/r201111a.htm,https://www.bis.org/review/r201111a.pdf,Challenges for central banks in a low interest...,"Introductory speech by Mr Senad Softi, Governo...",2020-11-05,Senad Softi,Governor,Male,Central Bank of Bosnia and Herzegovina,BIH,CBBH 3rd Research Conference Challenges for Ce...,NaN,r201111a,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Bosnia and Herzegovina
Bank of Estonia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
5841,https://www.eestipank.ee/en/press/peter-lohmus...,NaN,Main Trends in Estonian Economy in 1998 and 19...,NaN,1998-04-13,Peter Lhmus,Deputy Governor,Male,Bank of Estonia,EST,Peter Lohmus. Main Trends in Estonian Economy ...,NaN,est_35898_peter_lohmus,English,CB websites
5842,https://www.eestipank.ee/en/press/vahur-kraft-...,NaN,Speech at Riigikogu,NaN,1998-06-29,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft. Speech at Riigikogu POSTED: 29.06...,NaN,est_35975_vahur_kraft,English,CB websites
5843,https://www.eestipank.ee/en/press/peter-lohmus...,NaN,Recent Economic Trends in Estonia,NaN,1998-11-19,Peter Lhmus,Deputy Governor,Male,Bank of Estonia,EST,Peter lohmus. Recent Economic Trends in Estoni...,NaN,est_36118_peter_lohmus,English,CB websites
5844,https://www.eestipank.ee/en/press/vahur-kraft-...,NaN,Presentation on currency boards,NaN,1999-11-10,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft. Presentation on currency boards P...,NaN,est_36474_vahur_kraft_2,English,CB websites
5845,https://www.eestipank.ee/en/press/vahur-kraft-...,NaN,Keywords for Estonian financial stability in l...,NaN,1999-11-10,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft. Keywords for Estonian financial s...,NaN,est_36474_vahur_kraft,English,CB websites
5846,https://www.eestipank.ee/en/press/vahur-kraft-...,NaN,Estonia on its way the euro area: the position...,NaN,2000-01-27,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft. Estonia on its way the euro area:...,NaN,est_36552_vahur_kraft,English,CB websites
5847,https://www.eestipank.ee/en/press/andres-sutt-...,NaN,Introductory speech at the Workshop on insuran...,NaN,2002-02-06,Andres Sutt,Deputy Governor,Male,Bank of Estonia,EST,Andres Sutt. Introductory speech at the Worksh...,NaN,est_37293_andres_sutt,English,CB websites
5848,https://www.eestipank.ee/en/press/marten-ross-...,NaN,Challenges of Monetary Accession: the Case of ...,NaN,2002-07-10,Mrten Ross,Deputy Governor,Male,Bank of Estonia,EST,Marten Ross. Challenges of Monetary Accession:...,NaN,est_37447_marten_ross,English,CB websites
5849,https://www.eestipank.ee/en/press/andres-sutt-...,NaN,Welcoming word,NaN,2003-04-23,Andres Sutt,Deputy Governor,Male,Bank of Estonia,EST,"03/08/22, 14:10 Andres Sutt. Welcoming word IP...",NaN,est_37734_andres_sutt,English,CB websites
5850,https://www.eestipank.ee/en/press/vahur-kraft-...,NaN,European Integration - Challenges and Expectat...,NaN,2003-05-26,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft. European Integration -Challenges ...,NaN,est_37767_vahur_kraft,English,CB websites
5851,https://www.eestipank.ee/en/press/vahur-kraft-...,NaN,Factors influencing the financial system stabi...,NaN,2003-06-12,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft. Factors influencing the financial...,NaN,est_37784_vahur_kraft,English,CB websites
5852,https://www.eestipank.ee/en/press/vahur-kraft-...,NaN,Speech at the Estonian kroon anniversary recep...,NaN,2003-06-18,Vahur Kraft,Governor,Male,Bank of Estonia,EST,"03/08/22, 14:06 Vahur Kraft. Speech at the Est...",NaN,est_37790_vahur_kraft,English,CB websites
5853,https://www.eestipank.ee/en/press/andres-sutt-...,NaN,Estonian Financial System and Currency Board,NaN,2003-11-12,Andres Sutt,Deputy Governor,Male,Bank of Estonia,EST,Andres Sutt. Estonian Financial System and Cur...,NaN,est_37937_andres_sutt,English,CB websites
5854,https://www.eestipank.ee/en/press/v-kraft-econ...,NaN,Economic policy options in a knowledge-based s...,NaN,2004-09-27,Vahur Kraft,Governor,Male,Bank of Estonia,EST,V. Kraft. Economic policy options in a knowled...,NaN,est_38257_vahur_kraft,English,CB websites
5855,https://www.eestipank.ee/en/press/rein-minka-p...,NaN,Presentation at the business seminar in Lisbon,NaN,2005-11-28,Rein Minka,Deputy Governor,Male,Bank of Estonia,EST,POSTED: 28.11.2005 Presentation by Mr Rein Min...,NaN,est_38684_rein_minka,English,CB websites
5856,https://www.eestipank.ee/en/press/andres-lipst...,NaN,Presentation at the business seminar in Riga,NaN,2005-12-07,Andres Lipstok,Governor,Male,Bank of Estonia,EST,"03/08/22, 14:08 Andres Lipstok . Presentation ...",NaN,est_38693_andres_lipstok,English,CB websites
5857,https://www.eestipank.ee/en/press/andres-sutt-...,NaN,Credit growth in the Baltics: What's next?,NaN,2007-05-30,Andres Sutt,Deputy Governor,Male,Bank of Estonia,EST,Andres Sutt. Credit growth in the Salties: Wha...,NaN,est_39232_andres_sutt,English,CB websites
5858,https://www.eestipank.ee/en/press/speech-andre...,NaN,Introduction of the Annual report of 2007,NaN,2008-09-25,Andres Lipstok,Governor,Male,Bank of Estonia,EST,"Speech by ANDRES LIPSTOK, Governor of Eesti Pa...",NaN,est_39716_andres_lipstok,English,CB websites
5859,https://www.eestipank.ee/en/press/marten-ross-...,NaN,"Thoughts on the adoption of the euro, financia...",NaN,2008-10-15,Mrten Ross,Deputy Governor,Male,Bank of Estonia,EST,Marten Ross. Thoughts on the adoption of the e...,NaN,est_39736_marten_ross,English,CB websites
5860,https://www.eestipank.ee/en/press/presentation...,NaN,Presentation in the Riigikogu Finance Committee,NaN,2008-12-04,Mrten Ross,Deputy Governor,Male,Bank of Estonia,EST,Presentation by Marten Ross in the Riigikogu F...,NaN,est_39786_marten_ross,English,CB websites
5861,https://www.eestipank.ee/en/press/speech-gover...,NaN,Speech at the Riigikogu,NaN,2011-06-16,Andres Lipstok,Governor,Male,Bank of Estonia,EST,Speech of the Governor of Eesti Pank at the Ri...,NaN,est_40710_andres_lipstok,English,CB websites
5862,https://www.eestipank.ee/en/press/madis-muller...,NaN,Keynote speech at the seminar dedicated to the...,NaN,2012-01-20,Madis Mller,Deputy Governor,Male,Bank of Estonia,EST,Madis MOiier. Keynote speech at the seminar de...,NaN,est_40928_madis_muller,English,CB websites
5863,https://www.eestipank.ee/en/press/speech-gover...,NaN,Speech to the Riigikogu Presentation of the An...,NaN,2020-06-02,Madis Mller,Governor,Male,Bank of Estonia,EST,Speech by the Governor of Eesti Pank to the Ri...,NaN,est_43984_madis_muller,English,CB websites
5864,https://www.eestipank.ee/en/press/state-econom...,NaN,The second wave of the virus will postpone the...,NaN,2021-03-17,Madis Mller,Governor,Male,Bank of Estonia,EST,The state of the economy and the role of the c...,NaN,est_44272_madis_muller,English,CB websites
5865,https://www.eestipank.ee/en/press/road-recover...,NaN,Speech at the CFA Society Finland virtual Fore...,NaN,2021-04-28,Madis Mller,Governor,Male,Bank of Estonia,EST,The road to recovery and the role of central b...,NaN,est_44314_madis_muller,English,CB websites
12847,https://www.bis.org/review/r010712b.pdf,https://www.bis.org/review/r010712b.pdf,Safeguarding financial stability key issues f...,"Speech by Mr Vahur Kraft, Governor of the Bank...",2001-07-02,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft: Safeguarding financial stability ...,NaN,r010712b,English,BIS
13132,https://www.bis.org/review/r020919d.pdf,https://www.bis.org/review/r020919d.pdf,Challenges facing Estonian economy in the Euro...,"Speech by Mr Vahur Kraft, Governor of the Bank...",2002-08-19,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft: Challenges facing Estonian econom...,NaN,r020919d,English,BIS
13456,https://www.bis.org/review/r031007f.pdf,https://www.bis.org/review/r031007f.pdf,The euro in Estonia - the agenda and practical...,"Speech by Mr Vahur Kraft, Governor of the Bank...",2003-09-30,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft: The euro in Estonia - the agenda ...,NaN,r031007f,English,BIS
13702,https://www.bis.org/review/r040508b.pdf,https://www.bis.org/review/r040508b.pdf,A successful Estonia - in a successful Europe,"Speech by Mr Vahur Kraft, Governor of Eesti Pa...",2004-05-03,Vahur Kraft,Governor,Male,Bank of Estonia,EST,Vahur Kraft: A successful Estonia - in a succe...,NaN,r040508b,English,BIS
14851,https://www.bis.org/review/r060705f.pdf,https://www.bis.org/review/r060705f.pdf,Macroeconomic co-ordination and fiscal policy ...,"Statement by Mr Andres Sutt, Deputy Governor o...",2006-05-03,Andres Sutt,Deputy Governor,Male,Bank of Estonia,EST,Andres Sutt: Macroeconomic co-ordination and f...,NaN,r060705f,English,BIS
14970,https://www.bis.org/review/r060907d.pdf,https://www.bis.org/review/r060907d.pdf,Are ROEs peaking?,"Luncheon speech by Mr Andres Sutt, Deputy Gove...",2006-08-31,Andres Sutt,Deputy Governor,Male,Bank of Estonia,EST,Andres Sutt: Are ROEs peaking? Luncheon speech...,NaN,r060907d,English,BIS
15532,https://www.bis.org/review/r070612e.pdf,https://www.bis.org/review/r070612e.pdf,Opportunities of the Estonian economy in globa...,"Opening address by Mr Andres Lipstok, Governor...",2007-05-23,Andres Lipstok,Governor,Male,Bank of Estonia,EST,Andres Lipstok: Opportunities of the Estonian ...,NaN,r070612e,English,BIS
16438,https://www.bis.org/review/r080904d.pdf,https://www.bis.org/review/r080904d.pdf,Emerging energy markets - key issues,"Introductory remarks by Mr Andres Sutt, Deputy...",2008-08-21,Andres Sutt,Deputy Governor,Male,Bank of Estonia,EST,Andres Sutt: Emerging energy markets key issu...,NaN,r080904d,English,BIS
17044,https://www.bis.org/review/r090717a.pdf,https://www.bis.org/review/r090717a.pdf,How to exit the economic crisis?,"Presentation by Mr Andres Lipstok, Governor of...",2009-05-08,Andres Lipstok,Governor,Male,Bank of Estonia,EST,Andres Lipstok: How to exit the economic crisi...,NaN,r090717a,English,BIS
17050,https://www.bis.org/review/r090720b.pdf,https://www.bis.org/review/r090720b.pdf,The Estonian economy,"Speech by Mr Andres Lipstok, Governor of Bank ...",2009-05-28,Andres Lipstok,Governor,Male,Bank of Estonia,EST,Andres Lipstok: The Estonian economy Speech by...,NaN,r090720b,English,BIS
17054,https://www.bis.org/review/r090721b.pdf,https://www.bis.org/review/r090721b.pdf,Estonia's economic environment and central ban...,"Speech by Mr Andres Lipstok, Governor of the B...",2009-06-11,Andres Lipstok,Governor,Male,Bank of Estonia,EST,Andres Lipstok: Estonias economic environment ...,NaN,r090721b,English,BIS
18480,https://www.bis.org/review/r110504f.pdf,https://www.bis.org/review/r110504f.pdf,Monetary policy will not become a prisoner,"Article by Mr Andres Lipstok, Governor of Bank...",2011-03-24,Andres Lipstok,Governor,Male,Bank of Estonia,EST,Andres Lipstok: Monetary policy will not becom...,NaN,r110504f,English,BIS
19419,https://www.bis.org/review/r120717b.pdf,https://www.bis.org/review/r120717b.pdf,Overview of Bank of Estonia's first year of th...,"Speech by Mr Andres Lipstok, Governor of the B...",2012-05-29,Andres Lipstok,Governor,Male,Bank of Estonia,EST,Andres Lipstok: Overview of Bank of Estonias f...,NaN,r120717b,English,BIS
19903,https://www.bis.org/review/r130205i.pdf,https://www.bis.org/review/r130205i.pdf,New models in Northern Europe?,"Speech by Mr Madis Mller, Deputy Governor of t...",2012-11-28,Madis Mller,Deputy Governor,Male,Bank of Estonia,EST,Madis Muller: New models in Northern Europe? S...,NaN,r130205i,English,BIS
19956,https://www.bis.org/review/r130305d.pdf,https://www.bis.org/review/r130305d.pdf,Experience with and preparations for the euro,"Speech by Mr Ardo Hansson, Governor of the Ban...",2013-02-22,Ardo Hansson,Governor,Male,Bank of Estonia,EST,Ardo Hansson: Experience with and preparations...,NaN,r130305d,English,BIS
20663,https://www.bis.org/review/r131213b.htm,https://www.bis.org/review/r131213b.pdf,Nordic-Baltic financial linkages and challenges,"Opening remarks by Mr Ardo Hansson, Governor o...",2013-12-13,Ardo Hansson,Governor,Male,Bank of Estonia,EST,Ardo Hansson: Nordic-Baltic financial linkages...,NaN,r131213b,English,BIS
20966,https://www.bis.org/review/r140514i.htm,https://www.bis.org/review/r140514i.pdf,Celebrating the tenth anniversary of Estonia s...,Opening speech for Europe Day by Mr Ardo Hanss...,2014-05-09,Ardo Hansson,Governor,Male,Bank of Estonia,EST,Ardo Hansson: Celebrating the tenth anniversar...,NaN,r140514i,English,BIS
21270,https://www.bis.org/review/r141016c.htm,https://www.bis.org/review/r141016c.pdf,Availability of banking services in Estonia,"Answer by Mr Ardo Hansson, Governor of the Ban...",2014-11-22,Ardo Hansson,Governor,Male,Bank of Estonia,EST,Ardo Hansson: Availability of banking services...,NaN,r141016c,English,BIS
21408,https://www.bis.org/review/r141120f.htm,https://www.bis.org/review/r141120f.pdf,Working together for the good of the EU and Es...,"Opening speech by Mr Ardo Hansson, Governor of...",2014-11-04,Ardo Hansson,Governor,Male,Bank of Estonia,EST,Ardo Hansson: Working together for the good of...,NaN,r141120f,English,BIS
21888,https://www.bis.org/review/r150723b.htm,https://www.bis.org/review/r150723b.pdf,European and domestic economic challenges for ...,"Speech by Mr Ardo Hansson, Governor of the Ban...",2015-05-26,Ardo Hansson,Governor,Male,Bank of Estonia,EST,Ardo Hansson: European and domestic economic c...,NaN,r150723b,English,BIS
27555,http://www.bis.org/review/r230308g.htm,http://www.bis.org/review/r230308g.pdf,Madis Mller: Why is inflation so high and so d...,"Speech by Mr Madis Mller, Governor of the Bank...",2023-03-03,Madis Mller,Deputy Governor,Male,Bank of Estonia,EST,Madis Muller: Why is inflation so high and so ...,NaN,r230308g,English,BIS
28158,https://www.bis.org/review/r240215d.htm,https://www.bis.org/review/r240215d.pdf,The issues that shape the capacity for growth ...,"Speech by Mr Madis Mller, Governor of the Bank...",2023-12-08,Madis Mller,Governor,Male,Bank of Estonia,EST,Madis Muller: The issues that shape the capaci...,NaN,r240215d,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Estonia
Bank of the Republic, Colombia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1891,NaN,https://www.banrep.gov.co/sites/default/files/...,"Panel participation ""The review of the OECD Co...",NaN,2016-11-01,Ana Fernanda Maiguashca,Board member,Female,"Bank of the Republic, Colombia",COL,Seminar on Open and Orderly Capital Movements ...,NaN,col_amo_oct_2016,English,CB websites
1892,NaN,https://www.banrep.gov.co/sites/default/files/...,Some 'tips' from the conference on China,NaN,2013-01-14,Carlos Gustavo Cano,Board member,Male,"Bank of the Republic, Colombia",COL,"Some 'tips' from the Conference on China, Janu...",NaN,col_cgc_ene_2013,English,CB websites
1893,NaN,https://www.banrep.gov.co/sites/default/files/...,Carlos Gustavo Cano: On the crisis,NaN,2012-05-15,Carlos Gustavo Cano,Board member,Male,"Bank of the Republic, Colombia",COL,Carlos Gustavo Cano: On the crisis Speech by M...,NaN,col_cgc_may_2012,English,CB websites
1894,NaN,https://www.banrep.gov.co/sites/default/files/...,International Financial Conglomerates: The Per...,NaN,2017-11-29,Gerardo Hernndez,Board member,Male,"Bank of the Republic, Colombia",COL,International Financial Conglomerates: The Per...,NaN,col_ghernandez-palabras-seminario-conglomerado...,English,CB websites
1895,NaN,https://www.banrep.gov.co/sites/default/files/...,Time for a True Global Currency,NaN,2019-04-05,Jos Antonio Ocampo,Board member,Male,"Bank of the Republic, Colombia",COL,"Time for a True Global Currency Apr 5, 2019 Jo...",NaN,col_jaocampo_article_05_04_2019,English,CB websites
1896,NaN,https://www.banrep.gov.co/sites/default/files/...,Contribution to Panel: Inflation-Targeting in ...,NaN,2008-04-05,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Contribution to Panel: Inflation-Targeting in ...,NaN,col_jdu_abr_2008_3,English,CB websites
1897,NaN,https://www.banrep.gov.co/sites/default/files/...,Policy challenges facing central bankers in La...,NaN,2008-04-06,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,POLICY CHALLENGES FACING CENTRAL BANKERS IN LA...,NaN,col_jdu_abr_2008_4,English,CB websites
1898,NaN,https://www.banrep.gov.co/sites/default/files/...,The Resilience of Latin America to the Current...,NaN,2008-04-18,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,The resilience of Latin America to the current...,NaN,col_jdu_eng_abr_2008_1,English,CB websites
1899,NaN,https://www.banrep.gov.co/sites/default/files/...,Economic Acceleration and Structural Reforms i...,NaN,2013-02-13,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,PRESENTATION AT THE MACROECONOMIC AND SECTOR S...,NaN,col_jdu_feb_13_2013,English,CB websites
1900,NaN,https://www.banrep.gov.co/sites/default/files/...,Some Observations on Capital Flows in Emerging...,NaN,2010-07-01,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Some observations on capital flows in emerging...,NaN,col_jdu_jul_2010_0,English,CB websites
1901,NaN,https://www.banrep.gov.co/sites/default/files/...,A New Era of Cross-Border Flows: A Return of F...,NaN,2011-07-18,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,"Participation Notes for Jos8e Dar92o Uribe, Go...",NaN,col_jdu_jul_2011,English,CB websites
1902,NaN,https://www.banrep.gov.co/sites/default/files/...,Notes for Session III: The Great Experimentati...,NaN,2013-03-07,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,IV ANNUAL CONFERENCE OF THE REINVENTING BRETTO...,NaN,col_jdu_jul_3_2013,English,CB websites
1903,NaN,https://www.banrep.gov.co/sites/default/files/...,"Panel Discussion: ""Will Financial Globalizatio...",NaN,2012-06-22,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,"Some remarks by Jose Dario Uribe, Governor of ...",NaN,col_jdu_jun_22_2012,English,CB websites
1904,NaN,https://www.banrep.gov.co/sites/default/files/...,Internationalization of Colombian Banks: Recen...,NaN,2013-06-22,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Internationalization of Colombian banks: Recen...,NaN,col_jdu_jun_22_2013,English,CB websites
1905,NaN,https://www.banrep.gov.co/sites/default/files/...,How Can Macro-Prudential Policies or Framework...,NaN,2012-03-01,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,c0How can Macro-Prudential policies or framewo...,NaN,col_jdu_mar_1_2012,English,CB websites
1906,NaN,https://www.banrep.gov.co/sites/default/files/...,Colombia: Is There Room For Further Monetary E...,NaN,2013-03-15,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,PRESENTATION AT THE J.P. MORGAN INVESTOR SEMIN...,NaN,col_jdu_mar_15_2013,English,CB websites
1907,NaN,https://www.banrep.gov.co/sites/default/files/...,Colombia: Recent Economic Performance and Pros...,NaN,2013-03-17,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,COLOMBIA: RECENT ECONOMIC PERFORMANCE AND PROS...,NaN,col_jdu_mar_17_2013,English,CB websites
1908,NaN,https://www.banrep.gov.co/sites/default/files/...,Monetary Policy in Colombia,NaN,2008-03-05,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,MONETARY POLICY IN COLOMBIA By : Jos8e Dario U...,NaN,col_jdu_mar_2008_0,English,CB websites
1909,NaN,https://www.banrep.gov.co/sites/default/files/...,Some Comments on the Interactions between Priv...,NaN,2012-05-16,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,SOME COMMENTS ON THE INTERACTIONS BETWEEN PRIV...,NaN,col_jdu_may_16_2012,English,CB websites
1910,NaN,https://www.banrep.gov.co/sites/default/files/...,Government Borrowers Forum,NaN,2014-05-05,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,"GOVERNMENT BORROWERS FORUM May 5-8, 2014, Cart...",NaN,col_jdu_may_2014_2,English,CB websites
1911,NaN,https://www.banrep.gov.co/sites/default/files/...,"Colombia: Strong Policy Framework, Resilience ...",NaN,2015-05-11,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,"COLOMBIA: STRONG POLICY FRAMEWORK, RESILIENCE ...",NaN,col_jdu_may_2015,English,CB websites
1912,NaN,https://www.banrep.gov.co/sites/default/files/...,"Global Liquidity, Capital Flows and Policy Coo...",NaN,2013-11-20,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Fifth Summit Meeting of Central Banks on Infla...,NaN,col_jdu_nov_20_2013,English,CB websites
1913,NaN,https://www.banrep.gov.co/sites/default/files/...,Governors Presentation of the September 2016 I...,NaN,2016-09-01,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,THE GENERAL MANAGER OF THE BANK OF THE REPUBLI...,EL GERENTE GENERAL DEL BANCO DE LA REP<f2>BLIC...,col_jdu_nov_2016,Spanish,CB websites
1914,NaN,https://www.banrep.gov.co/sites/default/files/...,International Conference Central Bank Independ...,NaN,2013-10-15,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,INTERNATIONAL CONFERENCE d2CENTRAL BANK INDEPE...,NaN,col_jdu_oct_15_2013_eng,English,CB websites
1915,NaN,https://www.banrep.gov.co/sites/default/files/...,Remarks at the Bear Stearns 2006 Colombia Conf...,NaN,2006-10-23,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,"Remarks by Jos8e Dario Uribe, Governor of Banc...",NaN,col_jdu_oct_2006,English,CB websites
1916,NaN,https://www.banrep.gov.co/sites/default/files/...,Remarks at the Colombian American Association,NaN,2007-10-17,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,"Remarks by Jos8e Dar92o Uribe, Governor of the...",NaN,col_jdu_oct_2007,English,CB websites
1917,NaN,https://www.banrep.gov.co/sites/default/files/...,How Long Should Low Interest Rates Be Sustaine...,NaN,2009-10-03,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,HOW LONG SHOULD LOW INTEREST RATES BE SUSTAINE...,NaN,col_jdu_oct_2009,English,CB websites
1918,NaN,https://www.banrep.gov.co/sites/default/files/...,The Eurozone Anxiety: Preparing emerging marke...,NaN,2012-09-11,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,The Eurozone Anxiety: Preparing Emerging Marke...,NaN,col_jdu_sep_1_2012,English,CB websites
1919,NaN,https://www.banrep.gov.co/sites/default/files/...,IIF Macro Call Pandemic and the aftermath,NaN,2021-06-30,Mauricio Villamizar-Villegas,Board member,Male,"Bank of the Republic, Colombia",COL,Pandemic and the aftermath. a5 We are now ente...,NaN,col_mvillamizar-30-06-2021,English,CB websites
1920,NaN,https://www.banrep.gov.co/sites/default/files/...,Colombias Passage Trough the Current World Crisis,NaN,2009-01-26,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Colombiaabs passage through the current world ...,NaN,col_uribe_ene_2009,English,CB websites
1921,NaN,https://www.banrep.gov.co/sites/default/files/...,Monetary Policy Challenges in Latin America: S...,NaN,2009-03-29,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Monetary Policy Challenges in Latin America: S...,NaN,col_uribe_mar_2009,English,CB websites
1922,NaN,https://www.banrep.gov.co/sites/default/files/...,Managing Capital Inflows in Emerging Markets T...,NaN,2011-05-27,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Managing Capital Inflows in Emerging MarketsTh...,NaN,col_uribe_may_2011,English,CB websites
1923,NaN,https://www.banrep.gov.co/sites/default/files/...,The Colombian Economy and Monetary Policy,NaN,2008-10-07,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,The Colombian Economy and Monetary Policy Jose...,NaN,col_uribe_oct_2008,English,CB websites
1924,NaN,https://www.banrep.gov.co/sites/default/files/...,Lessons from the 2008 Financial Crisis: How fi...,NaN,2011-10-13,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Lessons from the 2008 Financial Crisis How Fin...,NaN,col_uribe_oct_2011_0,English,CB websites
1925,NaN,https://www.banrep.gov.co/sites/default/files/...,"Capital Flows, Policy Challenges and Policy Op...",NaN,2011-10-13,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,SEACEN d0 CEMLA CONFERENCE d2THE IMPLEMENTATIO...,NaN,col_uribe_oct_2011,English,CB websites
1926,NaN,https://www.banrep.gov.co/sites/default/files/...,Contribution to the Panel Discussion 12th Annu...,NaN,2008-11-01,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Contribution to the Panel Discussion 12th. ANN...,NaN,col_uribe_sep_2008,English,CB websites
1927,NaN,https://www.banrep.gov.co/sites/default/files/...,Casting Light on Shadow Banking: Data Needs fo...,NaN,2011-09-23,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,IMF Statistics Department Seminar Casting Ligh...,NaN,col_uribe_sep_2011,English,CB websites
1928,https://www.banrep.gov.co/en/responses-questio...,https://www.banrep.gov.co/en/print/pdf/node/57840,Responses to questions by Matthew Bristow from...,NaN,2022-07-13,Mauricio Villamizar-Villegas,Board member,Male,"Bank of the Republic, Colombia",COL,Keep in mind Los documentos son de caracter in...,NaN,col_villamizar-villegas_mauricio_44755,English,CB websites
13902,https://www.bis.org/review/r041019e.pdf,https://www.bis.org/review/r041019e.pdf,Declaration of the main aspects of the Nationa...,"Declaration of Dr Miguel Urrutia Montoya, Gove...",2004-08-11,Miguel Urrutia Montoya,Governor,Male,"Bank of the Republic, Colombia",COL,Miguel Urrutia Montoya: Declaration of the mai...,NaN,r041019e,English,BIS
13903,https://www.bis.org/review/r041019f.pdf,https://www.bis.org/review/r041019f.pdf,Extracts of a speech on the Colombian economy,Extracts of a speech by Dr Miguel Urrutia Mont...,2004-08-24,Miguel Urrutia Montoya,Governor,Male,"Bank of the Republic, Colombia",COL,Miguel Urrutia Montoya: Extracts of a speech o...,NaN,r041019f,English,BIS
15777,https://www.bis.org/review/r071009c.pdf,https://www.bis.org/review/r071009c.pdf,Globalization and Colombia's policy framework,"Speech by Mr Jos Daro Uribe Escobar, Governor ...",2007-10-04,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Jose Dario Uribe Escobar: Globalization and Co...,NaN,r071009c,English,BIS
15778,https://www.bis.org/review/r071009d.pdf,https://www.bis.org/review/r071009d.pdf,Recent performance of the Colombian economy an...,"Speech by Mr Jos Daro Uribe Escobar, Governor ...",2007-09-28,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Jose Dario Uribe Escobar: Recent performance o...,NaN,r071009d,English,BIS
17106,https://www.bis.org/review/r090907c.pdf,https://www.bis.org/review/r090907c.pdf,The Colombian monetary and exchange regime und...,"Speech by Mr Jos Dario Uribe, Governor of the ...",2009-08-31,Jos Daro Uribe Escobar,Governor,Male,"Bank of the Republic, Colombia",COL,Jose Dario Uribe: The Colombian monetary and e...,NaN,r090907c,English,BIS
19299,https://www.bis.org/review/r120514a.pdf,https://www.bis.org/review/r120514a.pdf,On the crisis,"Speech by Mr Carlos Gustavo Cano, Co-Director ...",2012-04-25,Carlos Gustavo Cano,Board member,Male,"Bank of the Republic, Colombia",COL,Carlos Gustavo Cano: On the crisis Speech by M...,NaN,r120514a,English,BIS
28139,https://www.bis.org/review/r231218c.htm,https://www.bis.org/review/r231218c.pdf,Opening speech - 24th meeting of the Regional ...,"Opening speech by Mr Leonardo Villar-Gmez, Gov...",2023-03-23,Leonardo Villar-Gmez,Governor,Male,"Bank of the Republic, Colombia",COL,Leonardo Villar-Gomez: Opening speech - 24th m...,NaN,r231218c,English,BIS
28140,https://www.bis.org/review/r231218d.htm,https://www.bis.org/review/r231218d.pdf,Speech - 25th Treasury Conference,"Speech by Mr Leonardo Villar-Gmez, Governor of...",2023-02-09,Leonardo Villar-Gmez,Governor,Male,"Bank of the Republic, Colombia",COL,Leonardo Villar-Gomez: Speech - 25th Treasury ...,NaN,r231218d,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of the Republic, Colombia
National Bank of Slovakia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
13323,https://www.bis.org/review/r030428b.pdf,https://www.bis.org/review/r030428b.pdf,Approaching the euro,"Speech by Mr Marian Jusko, Governor of the Nat...",2003-04-01,Marian Jusko,Governor,Male,National Bank of Slovakia,SVK,Marian Jusko: Approaching the euro Speech by M...,NaN,r030428b,English,BIS
13494,https://www.bis.org/review/r031104h.pdf,https://www.bis.org/review/r031104h.pdf,Slovakia - perspective place for investments,"Speech by Ms Elena Kohutikova, Deputy Governor...",2003-10-15,Elena Kohutikova,Deputy Governor,Female,National Bank of Slovakia,SVK,Elena Kohutikova: Slovakia - perspective place...,NaN,r031104h,English,BIS
16487,https://www.bis.org/review/r081001b.pdf,https://www.bis.org/review/r081001b.pdf,Euro implementation in Slovakia,"Speech by Mr Ivan Sramko, Governor of the Nati...",2008-09-24,Ivan Sramko,Governor,Male,National Bank of Slovakia,SVK,Ivan Sramko: Euro implementation in Slovakia S...,NaN,r081001b,English,BIS
24624,https://www.bis.org/review/r190117f.htm,https://www.bis.org/review/r190117f.pdf,Opening remarks - Tenth anniversary of the eur...,"Opening remarks by Mr Jozef Makuch, Governor o...",2019-01-11,Jozef Makuch,Governor,Male,National Bank of Slovakia,SVK,______________________________________________...,NaN,r190117f,English,BIS
24625,https://www.bis.org/review/r190117g.htm,https://www.bis.org/review/r190117g.pdf,Closing remarks - Tenth anniversary of the eur...,"Closing remarks by Mr udovit Odor, Deputy Gove...",2019-01-11,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,______________________________________________...,NaN,r190117g,English,BIS
29713,https://nbs.sk/aktuality/uvodne-slovo-guverner...,NaN,Introductory word at the Conference of Govern...,NaN,2021-07-16,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Tasks of NBS (/) Monetary Counti on of the Co ...,vodn slovo guvernra NBS P. Kaimra na Konferenc...,svk_44393_slovak,Slovak,CB websites
29714,https://nbs.sk/aktuality/odbornicka-nbs-mozno-...,NaN,NBS expert: Up to 80 percent of fraud can be d...,NaN,2022-12-09,Jlia illkov,Board member,Female,National Bank of Slovakia,SVK,NBS Expert: Possible up to 80 percentage of fr...,Odbornka NBS: Mono a 80 percent podvodov sa d ...,svk_julia_cillikova_44904,Slovak,CB websites
29715,https://nbs.sk/aktuality/ekonom-lubos-pastor-a...,NaN,Economist ubo Pstor: If gas from Russia stops ...,NaN,2022-07-04,ubo Pstor,Deputy Governor,Male,National Bank of Slovakia,SVK,Economist ubos Pastor: If by Europe will stop ...,Ekonm ubo Pstor: Ak do Eurpy prestane prdi ply...,svk_lubos_pastor_44746,Slovak,CB websites
29716,https://nbs.sk/en/news/lubos-pastor-judging-fu...,NaN,Lubos Pastor: Judging Fund Managers by the Com...,NaN,2023-03-08,ubo Pstor,Deputy Governor,Male,National Bank of Slovakia,SVK,Lubos Pastor: Judging Fund Managers by the Com...,NaN,svk_lubos_pastor_44993,English,CB websites
29717,https://nbs.sk/aktuality/problemom-svb-bolo-aj...,NaN,SVB's problem was also that it made full use o...,NaN,2023-03-20,ubo Pstor,Deputy Governor,Male,National Bank of Slovakia,SVK,The problem of the SV was also that took full ...,"Problmom SV bolo aj to, e naplno vyuvala prcu ...",svk_lubos_pastor_45005,Slovak,CB websites
29718,https://nbs.sk/aktuality/lubos-pastor-slovensk...,NaN,ubo Pstor: Slovakia is still threatened by rec...,NaN,2023-05-26,ubo Pstor,Deputy Governor,Male,National Bank of Slovakia,SVK,ubos Pastor: Slovakia is still threatened by r...,"ubo Pstor: Slovensku stle hroz recesia, m tera...",svk_lubos_pastor_45072,Slovak,CB websites
29719,https://nbs.sk/aktuality/rozhovor-s-profesorom...,NaN,"Choose reason, respect and responsibility (int...",NaN,2023-07-06,ubo Pstor,Deputy Governor,Male,National Bank of Slovakia,SVK,"To choose reason, respect and responsibility (...","Voli rozum, repekt a zodpovednos (rozhovor s p...",svk_lubos_pastor_45113,Slovak,CB websites
29720,https://nbs.sk/aktuality/ludovit-odor-neznesit...,NaN,udovt dor: The Unbearable Ease of Debt (HN Onl...,NaN,2022-06-20,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,udovit Odor: The unbearable ease of indebtedne...,udovt Odor: Neznesiten ahkos zadlovania (HN On...,svk_ludovit_odor_44732,Slovak,CB websites
29721,https://nbs.sk/aktuality/komentar-ludovita-odo...,NaN,Commentary by udovt dor: Thirty years of catch...,NaN,2023-01-10,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,Commentary by udovit Odor: Thirty years of cat...,Komentr udovta Odora: Tridsa rokov dobiehania ...,svk_ludovit_odor_44936,Slovak,CB websites
29722,https://nbs.sk/aktuality/viceguverner-nbs-l-od...,NaN,NBS Deputy Governor . dor: Not only prices but...,NaN,2023-01-23,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,Lieutenant Governor N S . odor: Not only Price...,"Viceguvernr N S . dor: Nielen ceny, ale aj mzd...",svk_ludovit_odor_44949,Slovak,CB websites
29723,https://nbs.sk/aktuality/viceguverner-nbs-l-od...,NaN,NBS Deputy Governor . dor: Is inflation turning?,NaN,2023-02-07,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,"Lieutenant Governor N inflation? Feb 7, 2023 F...",r Viceguvernr N inflcia? Q UDOVT DOR VICEGUVER...,svk_ludovit_odor_44964,Slovak,CB websites
29724,https://nbs.sk/aktuality/ludovit-odor-je-za-ro...,NaN,udovt dor: Is there another global financial c...,NaN,2023-03-21,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,udovit Odor: There is another one around the c...,udovt Odor: Je za rohom alia globlna finann kr...,svk_ludovit_odor_45006,Slovak,CB websites
29725,https://nbs.sk/aktuality/nasa-ekonomika-oproti...,NaN,Our economy lags far behind the West. Accordin...,NaN,2023-04-03,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,Our economy compared to the West is significan...,Naa ekonomika oproti Zpadu vrazne zaostva. Pod...,svk_ludovit_odor_45019,Slovak,CB websites
29726,https://nbs.sk/aktuality/kto-chce-hodnotu-za-p...,NaN,Who wants value for money? (Deputy Governor ud...,NaN,2023-04-18,udovit Odor,Deputy Governor,Male,National Bank of Slovakia,SVK,Who wants value for money? (Deputy Governor ud...,Kto chce hodnotu za peniaze? (viceguvernr udov...,svk_ludovit_odor_45034,Slovak,CB websites
29727,https://nbs.sk/aktuality/je-ferove-povedat-ze-...,NaN,It is fair to say that there are no easy times...,NaN,2022-06-24,Michal Horvth,Senior management,Male,National Bank of Slovakia,SVK,It is fair to say that we are not facing easy ...,"Je frov poveda, e ns neakaj ahk asy, hovor hla...",svk_michal_horvath_44736,Slovak,CB websites
29728,https://nbs.sk/aktuality/zahranicny-vietor-roz...,NaN,The supply on the domestic market is disastrou...,NaN,2022-08-04,Michal Horvth,Senior management,Male,National Bank of Slovakia,SVK,The offer on the domestic market is catastroph...,"Ponuka na domcom trhu je katastroflna, hovor H...",svk_michal_horvath_44777,Slovak,CB websites
29729,https://nbs.sk/aktuality/slovensko-patri-medzi...,NaN,Slovakia is one of the countries with higher i...,NaN,2022-10-21,Michal Horvth,Senior management,Male,National Bank of Slovakia,SVK,Slovakia is one of the countries with higher i...,"Slovensko patr medzi krajiny s vyou inflciou, ...",svk_michal_horvath_44855,Slovak,CB websites
29730,https://nbs.sk/aktuality/hlavny-ekonom-nbs-mic...,NaN,NBS Chief Economist Michal Horvth in Economy T...,NaN,2022-12-22,Michal Horvth,Senior management,Male,National Bank of Slovakia,SVK,Chief Economist N Michal Horvath S In Economic...,Hlavn ekonm N S Michal Horvth v Ekonomika TA3:...,svk_michal_horvath_44917_2,Slovak,CB websites
29731,https://nbs.sk/aktuality/hlavny-ekonom-nbs-mic...,NaN,NBS Chief Economist Michal Horvth in RTVS Morn...,NaN,2022-12-22,Michal Horvth,Senior management,Male,National Bank of Slovakia,SVK,NBS Chief Economist Michal Horvath in RTVS's M...,Hlavn ekonm NBS Michal Horvth v Rann sprvy RTV...,svk_michal_horvath_44917_3,Slovak,CB websites
29732,https://nbs.sk/aktuality/hlavny-ekonom-nbs-mic...,NaN,NBS Chief Economist Michal Horvth warns: The g...,NaN,2022-12-22,Michal Horvth,Senior management,Male,National Bank of Slovakia,SVK,Chief Economist N Michal Horvath S warns: The ...,Hlavn ekonm N S Michal Horvth varuje: Vlda mil...,svk_michal_horvath_44917,Slovak,CB websites
29733,https://nbs.sk/aktuality/ak-vlada-dodrzi-svoje...,NaN,NBS Chief Economist M. Horvth: If the governme...,NaN,2023-01-23,Michal Horvth,Senior management,Male,National Bank of Slovakia,SVK,Chief Economist N S M. Horvath: Ak the governm...,Hlavn ekonm N S M. Horvth: Ak vlda dodr svoje ...,svk_michal_horvath_44949,Slovak,CB websites
29734,https://nbs.sk/informacie-pre-media/rozhovory-...,NaN,Governor P. Kaimr's interview with Bloomberg,NaN,2022-02-18,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Rozhovor guvernera P. Kazimira pre agenturu Bl...,NaN,svk_peter_kazimir_44610,English,CB websites
29735,https://nbs.sk/aktuality/ecb-should-keep-50-bp...,NaN,"ECB should keep 50 bps hike on table, possibly...",NaN,2022-05-31,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,"ECB should keep 50 bps hike on table, possibly...",NaN,svk_peter_kazimir_44712,English,CB websites
29736,https://nbs.sk/aktuality/ecb-chce-v-juli-zvysi...,NaN,ECB wants to raise interest rates in July - Go...,NaN,2022-06-13,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,ECB wants to raise interest rates in July - Go...,ECB chce v jli zvi roky - guvernr Peter Kaimr ...,svk_peter_kazimir_44725,Slovak,CB websites
29737,https://nbs.sk/aktuality/guverner-peter-kazimi...,NaN,Governor Peter Kaimr in the Topic of the day o...,NaN,2022-06-24,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Governor Peter Kazimir in the Topic of the Day...,Guvernr Peter Kaimr v Tme da o prognze vvoja e...,svk_peter_kazimir_44736,Slovak,CB websites
29738,https://nbs.sk/aktuality/ecb-rates-must-rise-a...,NaN,ECB rates must rise above neutral but QT can w...,NaN,2022-10-14,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,ECB rates must rise above neutral but QT can w...,NaN,svk_peter_kazimir_44848,English,CB websites
29739,https://nbs.sk/aktuality/uvodne-slovo-guverner...,NaN,Opening remarks by Governor Peter Kaimr at the...,NaN,2022-11-10,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Uvodne slovo guvernera Petra Kazimira na disku...,NaN,svk_peter_kazimir_44875,English,CB websites
29740,https://nbs.sk/aktuality/guverner-nbs-graf-rok...,NaN,NBS Governor - Chart of the year: Double-digit...,NaN,2022-12-27,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Governor N S - Graf roka: Double-digit inflati...,Guvernr N S - Graf roka: Dvojcifern inflcia zo...,svk_peter_kazimir_44922,Slovak,CB websites
29741,https://nbs.sk/aktuality/sme-na-polceste-nevid...,NaN,"Governor Peter Kaimr: We are halfway, I see no...",NaN,2023-01-23,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,"Governor Peter Kazimir: We are halfway there, ...","Guvernr Peter Kaimr: Sme na polceste, nevidm d...",svk_peter_kazimir_44949,Slovak,CB websites
29742,https://nbs.sk/aktuality/guverner-peter-kazimi...,NaN,Governor Peter Kaimr: There is no rose without...,NaN,2023-02-03,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Governor Peter Kazimir: There is no rose witho...,Guvernr Peter Kaimr: Niet rue bez ta 3. feb 20...,svk_peter_kazimir_44960,Slovak,CB websites
29743,https://nbs.sk/aktuality/uvodne-slovo-guverner...,NaN,Opening remarks by the NBS Governor at the con...,NaN,2023-02-07,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Uvodne slovo guvernera NBS na konferencii Clim...,NaN,svk_peter_kazimir_44964,English,CB websites
29744,https://nbs.sk/aktuality/guverner-peter-kazimi...,NaN,Governor Peter Kaimr: We can sleep peacefully,NaN,2023-03-17,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,PETER KAzIMiR GOVERNOR OF THE NBS PETER KAzIMi...,Guvernr Peter Kaimr: Meme(-te) pokojne spva PE...,svk_peter_kazimir_45002,Slovak,CB websites
29745,https://nbs.sk/aktuality/rozhovor-guvernera-pe...,NaN,Interview of Governor Peter Kaimr for Hospodrs...,NaN,2023-05-14,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Interview of Governor Peter Kazimir for Hospod...,Rozhovor guvernra Petra Kaimra pre Hospodrske ...,svk_peter_kazimir_45060,Slovak,CB websites
29746,https://nbs.sk/aktuality/peter-kazimir-pod-vrc...,NaN,Governor Peter Kaimr: Under the top?,NaN,2023-07-28,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,PETER KAzIMiR GOVERNOR OF THE NBS PETER KAzIMi...,Guvernr Peter Kaimr: Pod vrcholom ? PETER KAIM...,svk_peter_kazimir_45135,Slovak,CB websites
29747,https://nbs.sk/en/news/governor-peter-kazimir-...,NaN,"Governor Peter Kaimr: The long-awaited ""pause""...",NaN,2023-10-30,Peter Kaimr,Governor,Male,National Bank of Slovakia,SVK,Governor Peter Kazimir: The long- expected pau...,NaN,svk_peter_kazimir_45229,English,CB websites
29748,https://nbs.sk/aktuality/analytik-nbs-roman-vr...,NaN,NBS analyst Roman Vrbovsk: We do not see many ...,NaN,2022-12-22,Roman Fusek,Senior management,Male,National Bank of Slovakia,SVK,NBS analyst Roman Vrbovsky: We don't see many ...,Analytik NBS Roman Vrbovsk: Nevidme vea faktor...,svk_roman_fusek_44917_2,Slovak,CB websites
29749,https://nbs.sk/aktuality/riaditel-odboru-ochra...,NaN,Director of the NBS Financial Consumer Protect...,NaN,2022-12-22,Roman Fusek,Senior management,Male,National Bank of Slovakia,SVK,"Roman Fusek, Director of the Financial Consume...",Riadite odboru ochrany finannch spotrebiteov N...,svk_roman_fusek_44917,Slovak,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Slovakia
Central Bank of Solomon Islands

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
15004,https://www.bis.org/review/r060927c.pdf,https://www.bis.org/review/r060927c.pdf,Launching of Solomon Islands' new and revised ...,"Remarks by Mr Rick Houenipwela, Governor of th...",2006-09-02,Rick Houenipwela,Governor,Male,Central Bank of Solomon Islands,SLB,Rick Houenipwela: Launching of Solomon Islands...,NaN,r060927c,English,BIS
16188,https://www.bis.org/review/r080423b.pdf,https://www.bis.org/review/r080423b.pdf,Credit unions - legal & compliance,"Opening address by Mr Rick Houenipwela, Govern...",2008-04-16,Rick Houenipwela,Governor,Male,Central Bank of Solomon Islands,SLB,Rick Houenipwela: Credit unions legal & compl...,NaN,r080423b,English,BIS
17274,https://www.bis.org/review/r091113b.pdf,https://www.bis.org/review/r091113b.pdf,The current state of the Solomon Islands econo...,"Paper presented by Mr Denton Rarawa, Governor ...",2009-09-17,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: The current state of the Solomo...,NaN,r091113b,English,BIS
17384,https://www.bis.org/review/r091218f.pdf,https://www.bis.org/review/r091218f.pdf,Developing strategies for talent management in...,"Speech by Mr Gane A Simbe, Deputy Governor of ...",2009-09-29,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Gane A Simbe: Developing strategies for talent...,NaN,r091218f,English,BIS
18770,https://www.bis.org/review/r110923d.pdf,https://www.bis.org/review/r110923d.pdf,Financial empowerment of women in the Solomon ...,"Address by Mr Gane Simbe, Deputy Governor of t...",2011-08-22,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Gane Simbe: Financial empowerment of women in ...,NaN,r110923d,English,BIS
18771,https://www.bis.org/review/r110923e.pdf,https://www.bis.org/review/r110923e.pdf,Recent economic and financial developments in ...,"Address by Mr Denton Rarawa, Governor of the C...",2011-08-16,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: Recent economic and financial d...,NaN,r110923e,English,BIS
18866,https://www.bis.org/review/r111108c.pdf,https://www.bis.org/review/r111108c.pdf,The credit union movement in Solomon Islands,"Address by Mr Denton Rarawa, Governor of the C...",2011-10-20,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: The credit union movement in So...,NaN,r111108c,English,BIS
19432,https://www.bis.org/review/r120718l.pdf,https://www.bis.org/review/r120718l.pdf,The role coins play in the Solomon Islands' pa...,"Speech by Mr Gane Simbe, Deputy Governor of th...",2012-07-04,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Gane Simbe: The role coins play in the Solomon...,NaN,r120718l,English,BIS
20051,https://www.bis.org/review/r130412h.pdf,https://www.bis.org/review/r130412h.pdf,Financial inclusion,"Opening address by Mr Denton Rarawa, Governor ...",2013-02-12,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: Financial inclusion Opening add...,NaN,r130412h,English,BIS
20353,https://www.bis.org/review/r130918b.pdf,https://www.bis.org/review/r130918b.pdf,Financial inclusion in the Solomon Islands,"Speech by Mr Gane Simbe, Deputy Governor of th...",2013-09-12,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Gane Simbe: Financial inclusion in the Solomon...,NaN,r130918b,English,BIS
20661,https://www.bis.org/review/r131212l.htm,https://www.bis.org/review/r131212l.pdf,The importance of fearing God as you climb you...,"Keynote address by Mr Denton Rarawa, Governor ...",2013-11-02,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: The importance of fearing God a...,NaN,r131212l,English,BIS
21158,https://www.bis.org/review/r140805b.htm,https://www.bis.org/review/r140805b.pdf,Financial inclusion in the Solomon Islands - k...,"Keynote address by Mr Denton Rarawa, Governor ...",2014-06-20,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: Financial inclusion in the Solo...,NaN,r140805b,English,BIS
21548,https://www.bis.org/review/r150205g.htm,https://www.bis.org/review/r150205g.pdf,Financial inclusion in Solomon Islands,"Remarks by Mr Denton Rarawa, Governor of Centr...",2014-12-10,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: Financial inclusion in Solomon ...,NaN,r150205g,English,BIS
21695,https://www.bis.org/review/r150414e.htm,https://www.bis.org/review/r150414e.pdf,Launch of Solomon Islands' new $100 banknote,"Speech by Mr Denton Rarawa, Governor of Centra...",2015-04-10,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: Launch of Solomon Islands new 1...,NaN,r150414e,English,BIS
22627,https://www.bis.org/review/r160720d.htm,https://www.bis.org/review/r160720d.pdf,"2016 Solomon Islands Money Day theme ""Take Par...","Speech by Mr Denton Rarawa, Governor of the Ce...",2016-06-27,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: 2016 Solomon Islands Money Day ...,NaN,r160720d,English,BIS
23231,https://www.bis.org/review/r170502d.htm,https://www.bis.org/review/r170502d.pdf,Empowering Solomon Islands' youth through fina...,"Key address by Mr Denton Rarawa, Governor of t...",2017-03-30,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,[Speech structure uses Problem/Opportunity; So...,NaN,r170502d,English,BIS
25249,https://www.bis.org/review/r191008l.htm,https://www.bis.org/review/r191008l.pdf,Launch of the 2018 CBSI Annual Report,"Remarks by Mr Denton Rarawa, Governor of the C...",2019-05-20,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Denton Rarawa: Launch of the 2018 CBSI Annual ...,NaN,r191008l,English,BIS
25258,https://www.bis.org/review/r191009j.htm,https://www.bis.org/review/r191009j.pdf,Launch of the new $5 polymer banknote,"Speech by Mr Luke Forau, Deputy Governor of th...",2019-05-02,Luke Forau,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Luke Forau: Launch of the new 5 polymer bankno...,NaN,r191009j,English,BIS
29595,https://www.cbsi.com.sb/governorsofficialstate...,http://www.cbsi.com.sb/wpcontent/uploads/2020/...,Governors remarks at the launching of the comm...,NaN,2020-05-13,Luke Forau,Governor,Male,Central Bank of Solomon Islands,SLB,"Statement by CBSI Governor, Dr. Luke Forau at ...",NaN,slb_2019-annual-report-speech-final,English,CB websites
29596,https://www.cbsi.com.sb/89352/,http://www.cbsi.com.sb/wpcontent/uploads/2020/...,Solomon islands money day 2018,NaN,2020-06-30,Luke Forau,Governor,Male,Central Bank of Solomon Islands,SLB,Press Conference Statement On the Release of 2...,NaN,slb_fsr-2019-press-conference-statement,English,CB websites
29597,https://www.cbsi.com.sb/governorsopeningremark...,http://www.cbsi.com.sb/wpcontent/uploads/2017/...,Launching of the 2017 annual report,NaN,2017-05-31,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,"""Digital Financial Services in the face of De-...",NaN,slb_gov_sp-032017piri,English,CB websites
29598,https://www.cbsi.com.sb/37832/,http://www.cbsi.com.sb/wpcontent/uploads/2017/...,Opening remarks by governor at the nps consult...,NaN,2017-05-19,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Building resilience for a vibrant and prospero...,NaN,slb_gov_sp-2016ar,English,CB websites
29599,https://www.cbsi.com.sb/openingremarksgovernor...,http://www.cbsi.com.sb/wpcontent/uploads/2018/...,3rd piri high level conference,NaN,2018-02-19,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Opening remarks by Governor Denton Rarawa at t...,NaN,slb_gov-sp-012018,English,CB websites
29600,https://www.cbsi.com.sb/governorsspeechlaunchi...,http://www.cbsi.com.sb/wpcontent/uploads/2018/...,Launching of 2016 annual report,NaN,2018-05-10,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Remarks by Central Bank of Solomon Islands (CB...,NaN,slb_gov-sp-022018,English,CB websites
29601,https://www.cbsi.com.sb/governorsspeechsolomon...,http://www.cbsi.com.sb/wpcontent/uploads/2018/...,Remarks at the sinpf 40th anniversary,NaN,2018-06-21,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Remarks on the Solomon Islands Monday Day: 42n...,NaN,slb_gov-sp-032018,English,CB websites
29602,https://www.cbsi.com.sb/governorsspeechgoverno...,http://www.cbsi.com.sb/wpcontent/uploads/2018/...,Joint anz/pfip coconut value chain partnership...,NaN,2018-07-05,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,"Remarks by Central Bank Governor, Denton Raraw...",NaN,slb_gov-sp-042018,English,CB websites
29603,https://www.cbsi.com.sb/remarks-by-governor-lu...,https://www.cbsi.com.sb/wp-content/uploads/202...,REMARKS BY GOVERNOR LUKE FORAU AT THE LAUNCH O...,NaN,2023-11-28,Luke Forau,Governor,Male,Central Bank of Solomon Islands,SLB,"CENTRAL BANK of SOLOMON ISLANDS P.O. BOX 634, ...",NaN,slb_governors-remarks-at-the-launch-of-cbdc_28...,English,CB websites
29604,https://www.cbsi.com.sb/speechwestpacussdmobil...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,"Consultative workshop, inclusive insurance",NaN,2014-02-06,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,"Remarks by CBSI Governor, Denton Rarawa at the...",NaN,slb_sp-012014,English,CB websites
29605,https://www.cbsi.com.sb/consultativeworkshopin...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,"Financial inclusion strategy review, national ...",NaN,2016-02-20,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,"Speech by Denton Rarawa, Governor of Central B...",NaN,slb_sp-012016,English,CB websites
29606,https://www.cbsi.com.sb/speechnationalsavingsc...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,"Financial inclusion consultation, workshop for...",NaN,2014-02-24,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,Cowboy Towns and Savings Clubs: Governor's Rem...,NaN,slb_sp-022014,English,CB websites
29607,https://www.cbsi.com.sb/associationfinancialsu...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,Association of financial supervisors of the pa...,NaN,2015-08-24,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,"BRIEF REMARKS BY CBSI GOVERNOR, DENTON RARAWA ...",NaN,slb_sp-022015,English,CB websites
29608,https://www.cbsi.com.sb/speechfinancialinclusi...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,"National savings clubs workshop, opening",NaN,2015-11-19,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,CBSI Governor's Remarks at the opening of the ...,NaN,slb_sp-032015,English,CB websites
29609,https://www.cbsi.com.sb/speechjointanzpfipcoco...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,"Westpac ussd mobile banking services, launch",NaN,2016-08-12,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,REMARKS BY GOVERNOR DENTON RARAWA AT THE LAUNC...,NaN,slb_sp-032016,English,CB websites
29610,https://www.cbsi.com.sb/governorsspeechfinanci...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,Keynote address at the official signing ceremo...,NaN,2015-11-26,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,CENTRAL BANK of SOLOMON ISLANDS Remarks by the...,NaN,slb_sp-042015,English,CB websites
29611,https://www.cbsi.com.sb/speechg2pp2gdigitalfin...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,Remarks by gane simbe at the official opening ...,NaN,2016-10-05,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Pacific Financial Inclusion Programme CENTRAL ...,NaN,slb_sp-042016,English,CB websites
29612,https://www.cbsi.com.sb/speechdeputygovernorsk...,http://www.cbsi.com.sb/wpcontent/uploads/2017/...,Mini small and medium enterprises business loa...,NaN,2017-08-10,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Remarks by Deputy Governor on the official sig...,NaN,slb_sp-042017,English,CB websites
29613,https://www.cbsi.com.sb/governorsremarkssinpf4...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,g2p p2g digital finance workshop,NaN,2016-11-11,Denton Rarawa,Governor,Male,Central Bank of Solomon Islands,SLB,"CENTRAL BANK of SOLOMON ISLANDS P.O. BOX 634, ...",NaN,slb_sp-052016,English,CB websites
29614,https://www.cbsi.com.sb/remarksganesimbeoffici...,http://www.cbsi.com.sb/wpcontent/uploads/2017/...,Remarks at the virtual signing of the grant ag...,NaN,2017-09-11,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,Remarks by Deputy Governor Gane Simbe at the o...,NaN,slb_sp-052017,English,CB websites
29615,https://www.cbsi.com.sb/speechdeputygovernorsr...,http://www.cbsi.com.sb/wpcontent/uploads/2016/...,Remarks at the launching of the solomon island...,NaN,2016-11-28,Gane A Simbe,Deputy Governor,Male,Central Bank of Solomon Islands,SLB,"Remarks by Mr. Gane Simbe, deputy Governor of ...",NaN,slb_sp-062016,English,CB websites
29616,https://www.cbsi.com.sb/governors-official-sta...,https://www.cbsi.com.sb/wp-content/uploads/202...,GOVERNORS OFFICIAL STATEMENT: LAUNCHING OF THE...,NaN,2023-04-27,Luke Forau,Governor,Male,Central Bank of Solomon Islands,SLB,"Statement by CBSI Governor, Dr. Luke Forau at ...",NaN,slb_speech-no_1_23-governors-statement-at-annu...,English,CB websites
29617,https://www.cbsi.com.sb/governorsremarksatthev...,https://www.cbsi.com.sb/wpcontent/uploads/2021...,Statement 2019 financial stability report rel...,NaN,2021-09-09,Luke Forau,Governor,Male,Central Bank of Solomon Islands,SLB,Remarks at the Virtual Signing of the Grant Ag...,NaN,slb_ustda_cbsi_grant-agreement-signing_governo...,English,CB websites
29618,https://www.cbsi.com.sb/governorsremarksatthel...,http://www.cbsi.com.sb/wpcontent/uploads/2021/...,Launching of the 2019 annual report,NaN,2021-04-23,Luke Forau,Governor,Male,Central Bank of Solomon Islands,SLB,Welcome Remarks at the Launching of the Solomo...,NaN,slb_welcome-remarks_gov_nfis3-launch1-23_04_21,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Solomon Islands
National Bank of Kazakhstan

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9544,https://www.nationalbank.kz/file/download/15907,NaN,Statement on the base rate of the National Bank,NaN,2019-09-09,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,The Governor E.Dossaev Statement on the base r...,NaN,kaz_43717_e_a__dossaev_english,English,CB websites
9545,https://www.nationalbank.kz/file/download/15906,NaN,Statement on the base rate of the National Bank,NaN,2019-10-28,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,The Governor E. Dossaevs Statement on the base...,NaN,kaz_43766_e_a__dossaev_english,English,CB websites
9546,https://www.nationalbank.kz/file/download/62906,NaN,"Main Talking Points, Deputy Governor of the Na...",NaN,2021-02-08,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,"Main Talking Points of Aliya Moldabekova, Depu...",NaN,kaz_44235_aliya_moldabekova_english,English,CB websites
9547,https://www.nationalbank.kz/file/download/62896,NaN,Director of Department of Monetary Policy of ...,NaN,2021-02-19,Zhandos Shaimardanov,Senior management,Male,National Bank of Kazakhstan,KAZ,"Zhandos Shaimardanov, Director of Department o...",NaN,kaz_44246_zhandos_shaimardanov_english,English,CB websites
9548,https://www.nationalbank.kz/file/download/67413,NaN,Interview on the results of forecast round for...,NaN,2021-06-08,Akylzhan Baimagambetov,Deputy Governor,Male,National Bank of Kazakhstan,KAZ,Keynotes of the interview by Akylzhan Baimagam...,NaN,kaz_44355_akylzhan_baimagambetov_english,English,CB websites
9549,https://www.nationalbank.kz/file/download/67412,NaN,"Interview, Deputy Governor of the National Ban...",NaN,2021-06-09,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of the interview by Aliya Moldabekova...,NaN,kaz_44356_aliya_moldabekova_english,English,CB websites
9550,https://www.nationalbank.kz/file/download/67509,NaN,Report at a Plenary Session of the Senate of t...,NaN,2021-06-17,Akylzhan Baimagambetov,Deputy Governor,Male,National Bank of Kazakhstan,KAZ,NBK report at a Plenary Session of the Senate ...,NaN,kaz_44364_akylzhan_baimagambetov_english,English,CB websites
9551,https://www.nationalbank.kz/file/download/68275,NaN,Keynotes About Situation on Currency Market i...,NaN,2021-07-13,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Aliya Moldabek...,NaN,kaz_44390_aliya_moldabekova_english,English,CB websites
9552,https://www.nationalbank.kz/file/download/68694,NaN,Reasons Behind Increase in the Base Rate,NaN,2021-07-26,Akylzhan Baimagambetov,Deputy Governor,Male,National Bank of Kazakhstan,KAZ,Keynotes of Deputy Governor of the National Ba...,NaN,kaz_44403_akylzhan_baimagambetov_english,English,CB websites
9553,https://www.nationalbank.kz/file/download/68966,NaN,Meeting of the Government of the Republic of K...,NaN,2021-08-11,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,Report by NBK Governor at the meeting of the G...,NaN,kaz_44419_e_a__dossaev_english,English,CB websites
9554,https://www.nationalbank.kz/file/download/68962,NaN,Situation on Foreign Exchange Market in July 2...,NaN,2021-08-12,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Aliya Moldabek...,NaN,kaz_44420_aliya_moldabekova_english,English,CB websites
9555,https://www.nationalbank.kz/file/download/69158,NaN,Meeting of the Government of the Republic of K...,NaN,2021-08-24,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,Report of NBK Governor at the meeting of the G...,NaN,kaz_44432_e_a__dossaev_english,English,CB websites
9556,https://www.nationalbank.kz/file/download/69863,NaN,Tapering of Monetary Incentives and Continued ...,NaN,2021-09-10,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Aliya Moldabek...,NaN,kaz_44449_aliya_moldabekova_english,English,CB websites
9557,https://www.nationalbank.kz/file/download/70568,NaN,n the global correction of the financial marke...,NaN,2021-10-11,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Aliya Moldabek...,NaN,kaz_44480_aliya_moldabekova_english,English,CB websites
9558,https://www.nationalbank.kz/file/download/70580,NaN,Meeting of the Government of the Republic of K...,NaN,2021-10-12,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,Report of NBK Governor at the meeting of the G...,NaN,kaz_44481_e_a__dossaev_english,English,CB websites
9559,https://www.nationalbank.kz/file/download/70678,NaN,KZT Devaluation Against Ruble Amid Rising Oil ...,NaN,2021-10-19,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Aliya Moldabek...,NaN,kaz_44488_aliya_moldabekova_english,English,CB websites
9560,https://www.nationalbank.kz/file/download/71079,NaN,Base Rate Decision,NaN,2021-10-26,Akylzhan Baimagambetov,Deputy Governor,Male,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Akylzhan Baima...,NaN,kaz_44495_akylzhan_baimagambetov_english,English,CB websites
9561,https://www.nationalbank.kz/file/download/71220,NaN,Pressure on EM Currencies and Growing Income o...,NaN,2021-11-09,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Aliya Moldabek...,NaN,kaz_44509_aliya_moldabekova_english,English,CB websites
9562,https://www.nationalbank.kz/file/download/71255,NaN,Meeting of the Government of the Republic of K...,NaN,2021-11-10,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,Report of NBK Governor at the meeting of the G...,NaN,kaz_44510_e_a__dossaev_english,English,CB websites
9563,https://www.nationalbank.kz/file/download/71251,NaN,IX Congress of Financiers of Kazakhstan,NaN,2021-11-12,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,"Report of E.A. Dossaev, NBK Governor IX Congre...",NaN,kaz_44512_e_a__dossaev_english,English,CB websites
9564,https://www.nationalbank.kz/file/download/71407,NaN,Consumer Goods became the main drivers of Imports,NaN,2021-11-17,Meruyert Almagambetova,Senior management,Male,National Bank of Kazakhstan,KAZ,Consumer Goods became the main drivers of Impo...,NaN,kaz_44517_meruyert_almagambetova_english,English,CB websites
9565,https://www.nationalbank.kz/file/download/71432,NaN,Tenge exceeded 430 per USD for the first time ...,NaN,2021-11-19,Nurzhan Tursunkhanov,Senior management,Male,National Bank of Kazakhstan,KAZ,Tenge exceeded 430 per USD for the first time ...,NaN,kaz_44519_nurzhan_tursunkhanov_english,English,CB websites
9566,https://www.nationalbank.kz/file/download/71604,NaN,National Bank: tenge adequately responded to n...,NaN,2021-11-24,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,National Bank: tenge adequately responded to n...,NaN,kaz_44524_aliya_moldabekova_english,English,CB websites
9567,https://www.nationalbank.kz/file/download/71930,NaN,Base Rate Decision,NaN,2021-12-07,Akylzhan Baimagambetov,Deputy Governor,Male,National Bank of Kazakhstan,KAZ,Press-Release 30 The base rate remains unchang...,NaN,kaz_44537_akylzhan_baimagambetov_english,English,CB websites
9568,https://www.nationalbank.kz/file/download/72002,NaN,Volatility on Global Markets and Reasons of Te...,NaN,2021-12-08,Aliya Moldabekova,Deputy Governor,Female,National Bank of Kazakhstan,KAZ,Keynotes of NBK Deputy Governor Aliya Moldabek...,NaN,kaz_44538_aliya_moldabekova_english,English,CB websites
9569,https://www.nationalbank.kz/file/download/72008,NaN,Meeting of the Government of the Republic of K...,NaN,2021-12-09,Erbolat Dossaev,Governor,Male,National Bank of Kazakhstan,KAZ,Report of NBK Governor at the meeting of the G...,NaN,kaz_44539_e_a__dossaev_english,English,CB websites
9570,https://www.nationalbank.kz/file/download/72515,NaN,Counter-cyclical fiscal rule is the balance be...,NaN,2021-12-24,Olzhas Kubenbaev,Senior management,Male,National Bank of Kazakhstan,KAZ,Counter-cyclical fiscal rule is the balance be...,NaN,kaz_44554_olzhas_kubenbaev_english,English,CB websites
9571,NaN,https://www.nationalbank.kz/file/download/76950,Statement of Chairman of the National Bank of ...,NaN,2022-04-27,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,On the decision of the Chairman of the Nationa...,". 2022 , 27 , - ! . 2...",kaz_g_pirmatov_44678,Kazakh,CB websites
9572,NaN,https://www.nationalbank.kz/file/download/88888,Statement of Chairman of the National Bank of ...,NaN,2023-02-24,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of Chairman of the National Bank of ...,"2023 24 , ! ! , ! - ...",kaz_galymzhan_pirmatov_44981,Kazakh,CB websites
9573,NaN,https://www.nationalbank.kz/file/download/94544,Statement of Chairman of the National Bank of ...,NaN,2023-08-25,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,The National Bank of The Republic of Kazakhsta...,".. 2023 25 , ! ! ! ! - ...",kaz_go_pirmatov_45163,Kazakh,CB websites
9574,NaN,https://www.nationalbank.kz/file/download/73041,Keynotes of the NBK Governor to a meeting of t...,NaN,2022-01-12,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Keynotes of the NBK Governor to a meeting of t...,NaN,kaz_pirmatov_go_44573,English,CB websites
9575,NaN,https://www.nationalbank.kz/file/download/78069,Statement of the Chairman of the National Bank...,NaN,2022-06-07,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of the Chairman of the National Bank...,".. 2022 ,7 , - ! . ...",kaz_pirmatov_go_44719,Kazakh,CB websites
9576,NaN,https://www.nationalbank.kz/file/download/80419,Statement on the base rate of the National Ban...,NaN,2022-09-05,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement on the base rate of the National Ban...,".. 2022 5 , - ! . ...",kaz_pirmatov_go_44809,Kazakh,CB websites
9577,NaN,https://www.nationalbank.kz/file/download/84557,Statement of the Chairman of the National Bank...,NaN,2022-10-26,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of Chairman of the National Bank of ...,".. 2022 26 , ! . . . ...",kaz_pirmatov_go_44860,Kazakh,CB websites
9578,NaN,https://www.nationalbank.kz/file/download/85527,Statement of the Chairman of the National Bank...,NaN,2022-12-05,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of Chairman of the National Bank of ...,".. 2022 ,5 , , ! ! ! - ...",kaz_pirmatov_go_44900,Kazakh,CB websites
9579,NaN,https://www.nationalbank.kz/file/download/94473,Statement of the Chairman of the National Bank...,NaN,2023-01-13,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,The National Bank of The Republic of Kazakhsta...,".. 2023 13 , ! ! ! ! - ...",kaz_pirmatov_go_44939,Kazakh,CB websites
9580,NaN,https://www.nationalbank.kz/file/download/90530,Statement of Chairman of the National Bank of ...,NaN,2023-04-07,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of the Chairman of the National Bank...,".. 2023 ,7 , ! ! ! ! - ...",kaz_pirmatov_go_45023,Kazakh,CB websites
9581,NaN,https://www.nationalbank.kz/file/download/91820,Statement of the Chairman of the National Bank...,NaN,2023-05-26,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of the Chairman of the National Bank...,".. 2023 , 26 , ! ! ! ! -...",kaz_pirmatov_go_45072,Kazakh,CB websites
9582,NaN,https://www.nationalbank.kz/file/download/92932,Statement of Chairman of the National Bank of ...,NaN,2023-07-05,Galymzhan Pirmatov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of Chairman of the National Bank of ...,".. 2023 ,5 , ! , ! ! - ...",kaz_pirmatov_go_45112,Kazakh,CB websites
9583,NaN,https://www.nationalbank.kz/file/download/95732,Statement of Chairman of the National Bank of ...,NaN,2023-10-06,Timur Suleimenov,Governor,Male,National Bank of Kazakhstan,KAZ,The National Bank of The Republic of Kazakhsta...,".. 2023 6 , ! ! ! - 16%-...",kaz_suleimenov_tm_45205,Kazakh,CB websites
9584,NaN,https://www.nationalbank.kz/file/download/96728,Statement of the Chairman of the National Bank...,NaN,2023-11-24,Timur Suleimenov,Governor,Male,National Bank of Kazakhstan,KAZ,Statement of the Chairman of the National Bank...,".. 2023 24 , ! ! ! ! - ...",kaz_suleimenov_tm_45254,Kazakh,CB websites
9585,NaN,https://www.nationalbank.kz/file/download/97333,Report of The Deputy Chairman of the National ...,NaN,2023-12-12,Vitaliy Tutushkin,Deputy Governor,Male,National Bank of Kazakhstan,KAZ,Report of The Deputy Chairman of the National ...,- 2023 - . ! ! ...,kaz_v_tutushkin_45272,Kazakh,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Kazakhstan
Central Bank of Nepal

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
11321,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Remark Notes at RBI Conference,NaN,2012-02-01,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Second International Research Conference on Mo...,NaN,npl_40940_dr._yuba_raj_khatiwada_english,English,CB websites
11322,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,SEACEN Keynote Address Summary,NaN,2012-03-19,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Current and Future Challenges to Monetary Poli...,NaN,npl_40987_dr._yuba_raj_khatiwada_english,English,CB websites
11323,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,SEACEN Keynote Address,NaN,2012-03-19,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Current and Future Challenges to Monetary Poli...,NaN,npl_40987_yuba_raj_khatiwada_english,English,CB websites
11324,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Remarks at Seminar on Microfinance & Social Bu...,NaN,2012-12-21,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Governor Dr. Yuba Raj Khatiwada's Remarks Semi...,NaN,npl_41264_dr._yuba_raj_khatiwada_english,English,CB websites
11325,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Address to SAARCFINANCE Seminar on Regulation ...,NaN,2013-03-20,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,"SAARCFINANCE Seminar on ""Regulation and Superv...",NaN,npl_41353_dr._yuba_raj_khatiwada_english,English,CB websites
11326,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,"Remarks at the UNESCAP Ministerial Meeting, Ba...",NaN,2013-04-30,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Forward Looking Macroeconomic Policies for Inc...,NaN,npl_41394_dr._yuba_raj_khatiwada_english,English,CB websites
11327,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Keynote Speech Governor APRACA Dhulikhell,NaN,2013-09-03,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Keynote Speech by Governor Dr. Yuba Raj Khatiw...,NaN,npl_41520_dr._yuba_raj_khatiwada_english,English,CB websites
11328,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Macro-financial Linkages Keynote Speech revise...,NaN,2013-10-20,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,SEACEN's 30th Anniversary Conference Kuala Lum...,NaN,npl_41567_dr._yuba_raj_khatiwada_english,English,CB websites
11329,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Keynote Speech at SEACEN Training Pokhara 28Oc...,NaN,2013-10-28,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,"Keynote Speech by Dr. Yuba Raj Khatiwada, Gove...",NaN,npl_41575_dr._yuba_raj_khatiwada_english,English,CB websites
11330,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Presentation Paper at 1st National Cooperative...,NaN,2014-03-27,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,"Cooperatives, Economic Democracy and Human Sec...",NaN,npl_41725_dr._yuba_raj_khatiwada_english,English,CB websites
11331,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Speech at SAARC Payments Council Program in Ka...,NaN,2014-05-09,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,15th SAARC Payments Council Meeting & 1st SPC ...,NaN,npl_41768_dr._yuba_raj_khatiwada_english,English,CB websites
11332,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Address at 19th SAARCFINANCE Coordinators Meet...,NaN,2014-05-18,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,19th SAARCFINANCE COORDINATORS' MEETING 18-19 ...,NaN,npl_41777_dr._yuba_raj_khatiwada_english,English,CB websites
11333,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Presentation at SEACEN Program in Malaysia,NaN,2014-08-07,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Central Bank Governance and Emerging Issues fo...,NaN,npl_41858_dr._yuba_raj_khatiwada_english,English,CB websites
11334,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Speech at RMA Bhutan,NaN,2014-08-28,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Monetary Policy and Reserves Management under ...,NaN,npl_41879_dr._yuba_raj_khatiwada_english,English,CB websites
11335,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Speech on Financial Stability to SEANZA Govern...,NaN,2014-08-30,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Macroeconomic Environment and Financial Sector...,NaN,npl_41881_dr._yuba_raj_khatiwada_english,English,CB websites
11336,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Opening Address at 20th SAARCFINANCE Coordinat...,NaN,2014-09-04,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,20TH SAARCFINANCE COORDINATORS' MEETING & SEMI...,NaN,npl_41886_dr._yuba_raj_khatiwada_english,English,CB websites
11337,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Keynote speech on Key Challenges of the Financ...,NaN,2015-04-13,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,Key Challenges of the Financial System in Nepa...,NaN,npl_42107_dr._chiranjibi_nepal_english,English,CB websites
11338,NaN,https://www.nrb.org.np/ofg/speech_for_44th_acu...,Speech for 44th ACU Board Meeting hosted by Ba...,NaN,2015-06-13,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,Speech by Governor Dr. Chiranjibi Nepal At the...,NaN,npl_42168_dr._chiranjibi_nepal_english,English,CB websites
11339,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Key Note remarks for National Conference on Fi...,NaN,2015-08-13,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,National Conference on Financial Inclusion in ...,NaN,npl_42229_dr._chiranjibi_nepal_english,English,CB websites
11340,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Delivered Key Note Remarks for National Launch...,NaN,2016-07-15,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,National Launch Ceremony on Financial Inclusio...,NaN,npl_42566_dr._chiranjibi_nepal_english,English,CB websites
11341,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Key Note Speech for 30th SEANZA Governors Symp...,NaN,2016-08-26,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,Financial Inclusion: Banking the Unbanked1 Cha...,NaN,npl_42608_dr._chiranjibi_nepal_english,English,CB websites
11342,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Addresses RMA Interaction Program in Bhutan,NaN,2016-09-29,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"Royal Monetary Authority of Bhutan, Thimpu 29 ...",NaN,npl_42642_dr._chiranjibi_nepal_english,English,CB websites
11343,NaN,https://www.nrb.org.np/contents/uploads/2019/1...,Inaugural Address at IFC Training Program,NaN,2017-04-03,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"IFC Training Program on ""Project Finance"" Pokh...",NaN,npl_42828_dr._chiranjibi_nepal_english,English,CB websites
11344,NaN,https://www.nrb.org.np/contents/uploads/2020/1...,Opening Remarks on G-24/ AFI Policymakers Roun...,NaN,2020-10-19,Maha Prasad Adhikari,Governor,Male,Central Bank of Nepal,NPL,Opening Remarks delivered by the Governor of N...,NaN,npl_44123_mr._maha_prasad_adhikari_english,English,CB websites
11345,NaN,https://www.nrb.org.np/contents/uploads/2023/0...,Innovation: Nepals Journey towards a More Incl...,NaN,2023-04-27,Maha Prasad Adhikari,Governor,Male,Central Bank of Nepal,NPL,Maintaining macroeconomic stability including ...,' - ...,npl_governor-speech-2080_edited,Nepali,CB websites
11346,NaN,https://www.nrb.org.np/contents/uploads/2022/0...,Full details of the statement made by Governor...,NaN,2022-04-27,Maha Prasad Adhikari,Governor,Male,Central Bank of Nepal,NPL,Economy recovery and external sector pressure ...,- ...,npl_nrb-67th-anniversary-governors-speech-01-14,Nepali,CB websites
11347,NaN,https://www.nrb.org.np/contents/uploads/2023/1...,Empowering Financial Inclusion through Financial,NaN,2023-09-07,Maha Prasad Adhikari,Governor,Male,Central Bank of Nepal,NPL,Special Address delivered by Mr. Maha Prasad A...,NaN,npl_talking-points-fintech-fest-final-3,English,CB websites
20674,https://www.bis.org/review/r131217b.htm,https://www.bis.org/review/r131217b.pdf,Emerging global financial issues of common int...,"Welcome remarks by Dr Yuba Raj Khatiwada, Gove...",2013-11-21,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Yuba Raj Khatiwada: Emerging global financial ...,NaN,r131217b,English,BIS
20741,https://www.bis.org/review/r140205d.htm,https://www.bis.org/review/r140205d.pdf,Business ethics for a prosperous Nepal,"Remarks by Dr Yuba Raj Khatiwada, Governor of ...",2014-01-17,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Yuba Raj Khatiwada: Business ethics for a pros...,NaN,r140205d,English,BIS
21042,https://www.bis.org/review/r140606b.htm,https://www.bis.org/review/r140606b.pdf,Overview of Nepal's recent macroeconomic perfo...,"Speech by Dr Yuba Raj Khatiwada, Governor of t...",2014-05-23,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Yuba Raj Khatiwada: Overview of Nepals recent ...,NaN,r140606b,English,BIS
21473,https://www.bis.org/review/r141209d.htm,https://www.bis.org/review/r141209d.pdf,Development of regional capital markets in Asi...,"Speech by Dr Yuba Raj Khatiwada, Governor of t...",2014-11-20,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Yuba Raj Khatiwada: Development of regional ca...,NaN,r141209d,English,BIS
21474,https://www.bis.org/review/r141209e.htm,https://www.bis.org/review/r141209e.pdf,SEACEN - enhancing collaboration with other gl...,"Response address by Dr Yuba Raj Khatiwada, Gov...",2014-11-20,Yuba Raj Khatiwada,Governor,Male,Central Bank of Nepal,NPL,Yuba Raj Khatiwada: SEACEN enhancing collabor...,NaN,r141209e,English,BIS
23097,https://www.bis.org/review/r170313g.htm,https://www.bis.org/review/r170313g.pdf,Emerging opportunities and challenges of finan...,"Keynote address by Dr Chiranjibi Nepal, Govern...",2016-11-09,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"Regional Forum on ""Emerging Opportunities and ...",NaN,r170313g,English,BIS
23100,https://www.bis.org/review/r170314d.htm,https://www.bis.org/review/r170314d.pdf,Financial institutions/alternative investments...,"Special address by Dr Chiranjibi Nepal, Govern...",2017-03-03,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,Nepal Investment Summit 2017 Special address b...,NaN,r170314d,English,BIS
23112,https://www.bis.org/review/r170316c.htm,https://www.bis.org/review/r170316c.pdf,Shifting the financial paradigm - courage to a...,"Address by Dr Chiranjibi Nepal, Governor of th...",2017-03-07,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,9th Global Alliance for Banking on Values (GAB...,NaN,r170316c,English,BIS
23476,https://www.bis.org/review/r170817b.htm,https://www.bis.org/review/r170817b.pdf,Expanding financial access to rural people in ...,"Closing remarks by Dr Chiranjibi Nepal, Govern...",2017-05-08,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,UNNATI-Access to Finance (A2F) Partnerships La...,NaN,r170817b,English,BIS
23482,https://www.bis.org/review/r170821b.htm,https://www.bis.org/review/r170821b.pdf,Current economic and financial developments in...,"Address by Dr Chiranjibi Nepal, Governor of th...",2017-07-13,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"46th ACU Board of Directors Meeting Colombo, S...",NaN,r170821b,English,BIS
23483,https://www.bis.org/review/r170824a.htm,https://www.bis.org/review/r170824a.pdf,Macro-prudential policies in SAARC countries,"Inaugural address by Dr Chiranjibi Nepal, Gove...",2017-06-08,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"SAARCFINANCE Seminar on ""Macro-prudential Poli...",NaN,r170824a,English,BIS
23564,https://www.bis.org/review/r171003a.htm,https://www.bis.org/review/r171003a.pdf,Development of rural financing institutions an...,"Address by Dr Chiranjibi Nepal, Governor of th...",2017-09-10,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"CICTAB Program on ""Development of Rural Financ...",NaN,r171003a,English,BIS
24276,https://www.bis.org/review/r180831e.htm,https://www.bis.org/review/r180831e.pdf,Closing remarks - 21st Asia/Pacific Group on M...,"Closing remarks by Dr Chiranjibi Nepal, Govern...",2018-07-27,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"Closing Remarks by Dr. Chiranjibi Nepal, Gover...",NaN,r180831e,English,BIS
24683,https://www.bis.org/review/r190214c.htm,https://www.bis.org/review/r190214c.pdf,The economic importance and key role of banks ...,"Address by Dr Chiranjibi Nepal, Governor of th...",2019-02-01,Chiranjibi Nepal,Governor,Male,Central Bank of Nepal,NPL,"Address by Dr. Chiranjibi Nepal, Governor, Nep...",NaN,r190214c,English,BIS
28117,https://www.bis.org/review/r231211a.htm,https://www.bis.org/review/r231211a.pdf,Maha Prasad Adhikari: Special address - Asian ...,"Special address by Mr Maha Prasad Adhikari, Go...",2023-11-09,Maha Prasad Adhikari,Governor,Male,Central Bank of Nepal,NPL,Maha Prasad Adhikari: Special address - Asian ...,NaN,r231211a,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Nepal
Central Bank of Brazil

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1176,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,Launch of the 'Sustainability Dimension' of Ag...,Opening speech for the launch of the Sustainab...,2020-09-08,Fernanda Nechio,Deputy Governor,Female,Central Bank of Brazil,BRA,Opening speech for the launch of the Sustainab...,NaN,bra_agenda_bc_sustainability__opening_speech_d...,English,CB websites
1177,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,The global economic and monetary policy outlook,UBS High-level macro event,2019-07-02,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,Apontamentos do presidente do Banco Central do...,NaN,bra_apontamentos_pres_rcn_ubs_global_economy_2...,English,CB websites
1178,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,"Economic outlook, monetary policy and the role...",Notes by the President of the Central Bank of ...,2019-04-10,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,"Estados Unidos, de 10 a 14 de abril de 2019. A...",NaN,bra_apontamentos_presidente_roberto_campos_eve...,English,CB websites
1179,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,Speech - BCB Autonomy Law Enactment Ceremony -...,Speech by Roberto Campos Neto Governor of Banc...,2021-02-24,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,"Brasilia - DF, February 24, 2021 Autonomy Law ...",NaN,bra_autonomy_banco_central_do_brasil_law_bcb_g...,English,CB websites
1180,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Speech by Mr. Diogo Abry Guillen at the Econom...,NaN,2022-05-04,Diogo Abry Guillen,Deputy Governor,Male,Central Bank of Brazil,BRA,"The CENTRAL BANK OF BRAZIL Brasilia, April 5, ...","A BANCO CENTRAL DO BRASIL Braslia, 5 de abril ...",bra_diogo_abry_guillen_44685,Portuguese,CB websites
1181,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,"Remarks by the Director of Economic Policy, Di...",NaN,2023-05-17,Diogo Abry Guillen,Deputy Governor,Male,Central Bank of Brazil,BRA,CENTRAL BANK OF BRAZIL Notes by the Director o...,BANCO CENTRAL DO BRASIL Apontamentos do Direto...,bra_diogo_abry_guillen_45063,Portuguese,CB websites
1182,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Comments by Director Fernanda Guardado at the ...,NaN,2022-10-20,Fernanda Guardado,Deputy Governor,Female,Central Bank of Brazil,BRA,Sustainable Finance: From Pledges to Progress ...,NaN,bra_fernanda_guardado_44854,English,CB websites
1183,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Speech by Director Fernanda Guardado at a meet...,NaN,2022-11-10,Fernanda Guardado,Deputy Governor,Female,Central Bank of Brazil,BRA,"CENTRAL BANK OF BRAZIL Brasilia, November 10, ...","BANCO CENTRAL DO BRASIL Braslia, 10 de novembr...",bra_fernanda_guardado_44875,Portuguese,CB websites
1184,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Speech by the Director of International Affair...,NaN,2023-05-19,Fernanda Guardado,Deputy Governor,Female,Central Bank of Brazil,BRA,HL Seminar on Central Banking Good afternoon R...,NaN,bra_fernanda_guardado_45065,English,CB websites
1185,NaN,https://www.bcb.gov.br/content/about/presentat...,COP 26 - A Financial System for the Net Zero,NaN,2021-11-03,Fernanda Guardado,Deputy Governor,Female,Central Bank of Brazil,BRA,A Financial System for the Net Zero DATE: Wedn...,NaN,bra_fg_cop26_mesa1_evento mark carney_7h15,English,CB websites
1186,NaN,https://www.bcb.gov.br/content/about/presentat...,COP 26 - The Central Banks and Supervisors Net...,NaN,2021-11-03,Fernanda Guardado,Deputy Governor,Female,Central Bank of Brazil,BRA,"""The Central Banks and Supervisors Network for...",NaN,bra_fg_cop26_ngfs,English,CB websites
1187,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,"Notes by the Director of Relationship, Citizen...",NaN,2022-03-29,Maurcio Moura,Deputy Governor,Male,Central Bank of Brazil,BRA,"The CENTRAL BANK OF BRAZIL Brasilia, March 29,...","A BANCO CENTRAL DO BRASIL Braslia, 29 de maro ...",bra_mauricio_moura_44649,Portuguese,CB websites
1188,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Notes by Director Maurcio Moura at the Seminar...,NaN,2022-11-30,Maurcio Moura,Deputy Governor,Male,Central Bank of Brazil,BRA,"The CENTRAL BANK OF BRAZIL Brasilia, November ...","A BANCO CENTRAL DO BRASIL Braslia, 30 de novem...",bra_mauricio_moura_44895,Portuguese,CB websites
1189,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,"Notes by the Director of Relationship, Citizen...",NaN,2023-05-30,Maurcio Moura,Deputy Governor,Male,Central Bank of Brazil,BRA,"The CENTRAL BANK OF BRAZIL Brasilia, May 30, 2...","A BANCO CENTRAL DO BRASIL Braslia, 30 de maio ...",bra_mauricio_moura_45076,Portuguese,CB websites
1190,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Speech by Mr. Renato Dias de Brito Gomes at th...,NaN,2022-04-05,Renato Dias de Brito Gomes,Deputy Governor,Male,Central Bank of Brazil,BRA,"The CENTRAL BANK OF BRAZIL Brasilia, April 5, ...","A BANCO CENTRAL DO BRASIL Braslia, 5 de abril ...",bra_renato_dias_de_brito_gomes_44656,Portuguese,CB websites
1191,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Speech by Director Renato Dias de Brito Gomes ...,NaN,2022-11-21,Renato Dias de Brito Gomes,Deputy Governor,Male,Central Bank of Brazil,BRA,"A BANCO CENTRAL DO BRASIL Brasilia, 21 de nove...",NaN,bra_renato_dias_de_brito_gomes_44886,English,CB websites
1192,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Remarks by President Roberto Campos Neto at th...,NaN,2022-03-22,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,"CENTRAL BANK OF BRAZIL Brasilia (DF), March 22...","BANCO CENTRAL DO BRASIL Braslia (DF), 22 de ma...",bra_roberto_campos_neto_44642,Portuguese,CB websites
1193,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Remarks by President Roberto Campos Neto at th...,NaN,2022-05-18,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,"Bras92lia (DF), May 18, 2022. Notes by the Pre...","BANCO CENTRAL DO BRASIL Brasilia (DF), 18 de m...",bra_roberto_campos_neto_44699,Portuguese,CB websites
1194,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,President Roberto Campos Neto's live remarks o...,NaN,2022-08-30,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,"CENTRAL BANK OF BRAZIL Brasilia-DF, August 30,...","BANCO CENTRAL DO BRASIL Braslia-DF, 30 de agos...",bra_roberto_campos_neto_44803,Portuguese,CB websites
1195,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Notes by President Roberto Campos Neto at the ...,NaN,2022-12-07,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,Notes from President Roberto Campos Neto to th...,Apontamentos do Presidente Roberto Campos Neto...,bra_roberto_campos_neto_44902,Portuguese,CB websites
1196,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Remarks by President Roberto Campos Neto at th...,NaN,2022-12-13,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,CENTRAL BANK OF BRAZIL Notes by President Robe...,BANCO CENTRAL DO BRASIL Apontamentos do Presid...,bra_roberto_campos_neto_44908,Portuguese,CB websites
1197,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Remarks by President Roberto Campos Neto at th...,NaN,2023-02-07,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,Apontamentos para o 2023 Milken South Florida ...,NaN,bra_roberto_campos_neto_44964,English,CB websites
1198,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Remarks by President Roberto Campos Neto at th...,NaN,2023-04-12,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,"CENTRAL BANK OF BRAZIL Brasilia (DF), December...","BANCO CENTRAL DO BRASIL Braslia (DF), 4 de dez...",bra_roberto_campos_neto_45028,Portuguese,CB websites
1199,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Remarks by President Roberto Campos Neto in a ...,NaN,2023-08-02,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,CENTRAL BANK OF BRAZIL Notes by President Robe...,BANCO CENTRAL DO BRASIL Apontamentos do Presid...,bra_roberto_campos_neto_45140,Portuguese,CB websites
1200,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Notes by President Roberto Campos Neto for vid...,NaN,2023-11-28,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,"CENTRAL BANK OF BRAZIL Rio de Janeiro (RJ), No...","BANCO CENTRAL DO BRASIL Rio de Janeiro (RJ), 2...",bra_roberto_campos_neto_45258,Portuguese,CB websites
1201,NaN,https://www.bcb.gov.br/conteudo/home-ptbr/Text...,Speech by President Roberto Campos Neto at the...,NaN,2023-12-15,Roberto Campos Neto,Governor,Male,Central Bank of Brazil,BRA,G20 Finance and Central Bank Deputies Meeting ...,NaN,bra_roberto_campos_neto_45275,English,CB websites
1202,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,Open Letter,Open Letter sent by Banco Central do Brasil's ...,2003-01-21,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Translation of the Open Letter sent by Banco C...,NaN,bra_spch002-200301pri-open_letter-henrique_de_...,English,CB websites
1203,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,Opening speech at G20 Seminar,Monetary and Macro-prudential Policies in a Co...,2011-06-30,Luiz Awazu Pereira da Silva,Deputy Governor,Male,Central Bank of Brazil,BRA,June 30th 2011 G20 Seminar Monetary and Macro-...,NaN,bra_text2011634451101133-luiz_awazu_g20_semina...,English,CB websites
1204,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,Presentation by Central Bank Director Luiz Awa...,Post Crisis challenges for Emerging Markets: A...,2013-03-17,Luiz Awazu Pereira da Silva,Deputy Governor,Male,Central Bank of Brazil,BRA,2013 IIF Latin America Forum at the Inter-Amer...,NaN,bra_text2013634991210202-rev_-_rev_-_2013_03_1...,English,CB websites
1205,https://www.bcb.gov.br/content/about/presentat...,https://www.bcb.gov.br/content/about/presentat...,Remarks by Central Bank Director Luiz Awazu Pe...,From Currency Wars to Policy Peace under the G-20,2013-04-02,Luiz Awazu Pereira da Silva,Deputy Governor,Male,Central Bank of Brazil,BRA,Lunch Panel Session of the April 2nd 2013 Conf...,NaN,bra_text2013635005144194-final_2013_04_02_lapd...,English,CB websites
13243,https://www.bis.org/review/r030131d.pdf,https://www.bis.org/review/r030131d.pdf,Inauguration speech,Inauguration speech delivered by Mr Henrique d...,2003-01-07,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Henrique de Campos Meirelles: Inauguration spe...,NaN,r030131d,English,BIS
13816,https://www.bis.org/review/r040806g.pdf,https://www.bis.org/review/r040806g.pdf,Regulation of capital and financial stability,"Speech by Mr Paulo Sergio Cavalheiro, Deputy G...",2004-07-12,Paulo Sergio Cavalheiro,Deputy Governor,Male,Central Bank of Brazil,BRA,Paulo Sergio Cavalheiro: Regulation of capital...,NaN,r040806g,English,BIS
16448,https://www.bis.org/review/r080915c.pdf,https://www.bis.org/review/r080915c.pdf,Challenges for monetary policy - Brazil and th...,"Speech by Mr Henrique Meirelles, Governor of t...",2008-07-10,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Henrique Meirelles: Challenges for monetary po...,NaN,r080915c,English,BIS
16488,https://www.bis.org/review/r081001c.pdf,https://www.bis.org/review/r081001c.pdf,Good governance in the Brazilian financial system,"Speech by Mr Henrique Meirelles, Governor of t...",2008-09-05,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Henrique Meirelles: Good governance in the Bra...,NaN,r081001c,English,BIS
16517,https://www.bis.org/review/r081016d.pdf,https://www.bis.org/review/r081016d.pdf,Brazil-Argentina Local Currency Payment System,"Speech by Mr Henrique Meirelles, Governor of t...",2008-10-02,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Henrique Meirelles: Brazil-Argentina Local Cur...,NaN,r081016d,English,BIS
16609,https://www.bis.org/review/r081128b.pdf,https://www.bis.org/review/r081128b.pdf,Bretton Woods II - on its way out?,"Speech by Mr Henrique Meirelles, Governor of t...",2008-11-21,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Henrique Meirelles: Bretton Woods II on its w...,NaN,r081128b,English,BIS
16710,https://www.bis.org/review/r090129d.pdf,https://www.bis.org/review/r090129d.pdf,Ten years of floating exchange rates in Brazil,"Speech by Mr Henrique Meirelles, Governor of t...",2009-01-19,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Henrique Meirelles: Ten years of floating exch...,NaN,r090129d,English,BIS
16863,https://www.bis.org/review/r090414b.pdf,https://www.bis.org/review/r090414b.pdf,Regulation and international standards in Braz...,"Speech by Mr Henrique Meirelles, Governor of t...",2009-04-02,Henrique Meirelles,Governor,Male,Central Bank of Brazil,BRA,Henrique Meirelles: Regulation and internation...,NaN,r090414b,English,BIS
20635,https://www.bis.org/review/r131205g.pdf,https://www.bis.org/review/r131205g.pdf,"Global liquidity, capital flows and inflation ...","Keynote address by Mr Alexandre A Tombini, Gov...",2013-11-15,Alexandre Antonio Tombini,Governor,Male,Central Bank of Brazil,BRA,"Alexandre A Tombini: Global liquidity, capital...",NaN,r131205g,English,BIS
21821,https://www.bis.org/review/r150612a.htm,https://www.bis.org/review/r150612a.pdf,Central banking - the next 50 years,Introductory remarks by Mr Alexandre Antonio T...,2015-06-10,Alexandre Antonio Tombini,Governor,Male,Central Bank of Brazil,BRA,Alexandre A Tombini: Central banking the next...,NaN,r150612a,English,BIS
28546,https://www.bis.org/review/r990129b.pdf,https://www.bis.org/review/r990129b.pdf,Mr Lopes' speech before the Economic Affairs C...,Summary of a speech by the new President of th...,1999-01-26,Francisco Lopes,Governor,Male,Central Bank of Brazil,BRA,Mr Lopes speech before the Economic Affairs Co...,NaN,r990129b,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Brazil
Reserve Bank of Malawi

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10609,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Symposium Commemorating 50th Anniversary of th...,NaN,2015-11-23,Charles S R Chuka,Governor,Male,Reserve Bank of Malawi,MWI,Statement of the Governor Mr Charles Chuka at ...,NaN,mwi_42331_charles_chuka,English,CB websites
10610,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Speech at Dinner organised by MCCCI,NaN,2016-08-10,Charles S R Chuka,Governor,Male,Reserve Bank of Malawi,MWI,SPEECH BY THE GOVERNOR OF THE RESERVE BANK OF ...,NaN,mwi_42592_charles_chuka,English,CB websites
10611,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Statement at the Malawi Stock Exchange Symposi...,NaN,2017-07-26,Dalitso Kabambe,Governor,Male,Reserve Bank of Malawi,MWI,"DALITSO KABAMBE, PhD GOVERNOR AT THE MALAWI ST...",NaN,mwi_42942_dalitso_kabambe,English,CB websites
10612,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Speech at the Insurance Institute of Malawi An...,NaN,2017-08-18,Dalitso Kabambe,Governor,Male,Reserve Bank of Malawi,MWI,REGISTRAR OF FINANCIAL INSTITUTIONS REMARKS BY...,NaN,mwi_42965_dalitso_kabambe,English,CB websites
10613,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Speech at the Launch of Counterfeit Currency M...,NaN,2017-08-22,Dalitso Kabambe,Governor,Male,Reserve Bank of Malawi,MWI,DALITSO KABAMBE (PhD) GOVERNOR AT THE LAUNCH O...,NaN,mwi_42969_dalitso_kabambe,English,CB websites
10614,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Remarks at the Institute Of Bankers 3rd Annual...,NaN,2018-08-23,Dalitso Kabambe,Governor,Male,Reserve Bank of Malawi,MWI,"DALITSO KABAMBE, PhD GOVERNOR ATTHE INSTITUTE ...",NaN,mwi_43335_dalitso_kabambe,English,CB websites
10615,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Speech at the 2019 Institute of Bankers Lake C...,NaN,2019-08-30,Dalitso Kabambe,Governor,Male,Reserve Bank of Malawi,MWI,DALITSO KABAMBE (PhD) GOVERNOR INSTITUTE OF BA...,NaN,mwi_43707_dalitso_kabambe,English,CB websites
10616,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,5TH Bankers Conference Amaryllis Hotel,NaN,2020-10-08,Wilson T Banda,Governor,Male,Reserve Bank of Malawi,MWI,"The Governor, Dr Wilson T Banda 5th BANKERS CO...",NaN,mwi_44112_wilson_t._banda,English,CB websites
10617,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Speech at the 2020 ICAM Conference,NaN,2020-11-12,Wilson T Banda,Governor,Male,Reserve Bank of Malawi,MWI,THE GOVERNOR DR WILSON T. BANDA ICAM ANNUAL LA...,NaN,mwi_44147_wilson_t._banda,English,CB websites
10618,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Opening Remarks at the 2020 ECAMA Annual Confe...,NaN,2020-11-19,Wilson T Banda,Governor,Male,Reserve Bank of Malawi,MWI,THE CHAIRMAN OF ECAMA BOARD OF TRUSTEES AND GO...,NaN,mwi_44154_wilson_t._banda,English,CB websites
10619,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Key note at Financial Market Dealers Associati...,NaN,2020-11-28,Wilson T Banda,Governor,Male,Reserve Bank of Malawi,MWI,Reserve Bank of Malawi KEY NOTE ADDRESS BY THE...,NaN,mwi_44163_wilson_t._banda,English,CB websites
10620,https://www.rbm.mw/MediaCenter/GetContentFile/...,https://www.rbm.mw/MediaCenter/GetContentFile/...,Speech at the Official Launch of Investor Awar...,NaN,2020-12-07,Grant Kabango,Deputy Governor,Male,Reserve Bank of Malawi,MWI,Official Launch of the Investor Education Week...,NaN,mwi_44172_grant_p._kabango,English,CB websites
13374,https://www.bis.org/review/r030620e.pdf,https://www.bis.org/review/r030620e.pdf,The importance of financial system modernisati...,"Keynote address by Dr E E Ngalande, Governor o...",2003-04-24,E E Ngalande,Governor,Male,Reserve Bank of Malawi,MWI,E E Ngalande: The importance of financial syst...,NaN,r030620e,English,BIS
15356,https://www.bis.org/review/r070329c.pdf,https://www.bis.org/review/r070329c.pdf,Positive financial and economic developments i...,"Speech by Mr Victor Mbewe, Governor of the Res...",2007-03-16,Victor Mbewe,Governor,Male,Reserve Bank of Malawi,MWI,Victor Mbewe: Positive financial and economic ...,NaN,r070329c,English,BIS
15512,https://www.bis.org/review/r070606e.pdf,https://www.bis.org/review/r070606e.pdf,Information and communications technology in t...,"Opening speech by Mrs Mary C Nkosi, Deputy Gov...",2007-05-14,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Information and communications t...,NaN,r070606e,English,BIS
15580,https://www.bis.org/review/r070628g.pdf,https://www.bis.org/review/r070628g.pdf,Profile of the Reserve Bank of Malawi,"Speech by Mrs Mary C Nkosi, Deputy Governor of...",2007-05-04,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Profile of the Reserve Bank of M...,NaN,r070628g,English,BIS
16031,https://www.bis.org/review/r080212e.pdf,https://www.bis.org/review/r080212e.pdf,Committee of SADC Stock Exchanges,"Speech by Mr Victor Mbewe, Governor of the Res...",2008-01-31,Victor Mbewe,Governor,Male,Reserve Bank of Malawi,MWI,Victor Mbewe: Committee of SADC Stock Exchange...,NaN,r080212e,English,BIS
16157,https://www.bis.org/review/r080409d.pdf,https://www.bis.org/review/r080409d.pdf,Insurance broking services in Malawi,"Speech by Mrs Mary C Nkosi, Deputy Governor of...",2008-03-20,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Insurance broking services in Ma...,NaN,r080409d,English,BIS
16190,https://www.bis.org/review/r080423e.pdf,https://www.bis.org/review/r080423e.pdf,Mobile banking in Malawi,"Address by Mrs Mary C Nkosi, Deputy Governor o...",2008-03-27,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Mobile banking in Malawi Address...,NaN,r080423e,English,BIS
16806,https://www.bis.org/review/r090318e.pdf,https://www.bis.org/review/r090318e.pdf,Risk based supervision in Malawi,"Speech by Mrs Mary C Nkosi, Deputy Governor of...",2009-01-09,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Risk based supervision in Malawi...,NaN,r090318e,English,BIS
16810,https://www.bis.org/review/r090319d.pdf,https://www.bis.org/review/r090319d.pdf,Promoting the development and regulation of ca...,"Speech by Mrs Mary C Nkosi, Deputy Governor of...",2009-01-14,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Promoting the development and re...,NaN,r090319d,English,BIS
16814,https://www.bis.org/review/r090320c.pdf,https://www.bis.org/review/r090320c.pdf,Creating an environment for banks to operate e...,"Speech by Mrs Mary C Nkosi, Deputy Governor of...",2009-01-31,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Creating an environment for bank...,NaN,r090320c,English,BIS
17153,https://www.bis.org/review/r090925b.pdf,https://www.bis.org/review/r090925b.pdf,Co-ordinated regulations for the SADC region,"Address by Dr Perks Ligoya, Governor of the Re...",2009-09-17,Perks M Ligoya,Governor,Male,Reserve Bank of Malawi,MWI,Perks Ligoya: Co-ordinated regulations for the...,NaN,r090925b,English,BIS
17436,https://www.bis.org/review/r100127c.pdf,https://www.bis.org/review/r100127c.pdf,Safeguarding Malawi's foreign exchange reserves,"Speech by Dr Perks M Ligoya, Governor of the R...",2009-12-29,Perks M Ligoya,Governor,Male,Reserve Bank of Malawi,MWI,Perks M Ligoya: Safeguarding Malawis foreign e...,NaN,r100127c,English,BIS
17539,https://www.bis.org/review/r100317b.pdf,https://www.bis.org/review/r100317b.pdf,Improving access to credit in Malawi,"Speech by Dr Perks Ligoya, Governor of the Res...",2010-02-27,Perks M Ligoya,Governor,Male,Reserve Bank of Malawi,MWI,Perks Ligoya: Improving access to credit in Ma...,NaN,r100317b,English,BIS
17544,https://www.bis.org/review/r100318d.pdf,https://www.bis.org/review/r100318d.pdf,The challenge of making sound policy choices,"Speech by Dr Perks M Ligoya, Governor of the R...",2010-03-01,Perks M Ligoya,Governor,Male,Reserve Bank of Malawi,MWI,Perks M Ligoya: The challenge of making sound ...,NaN,r100318d,English,BIS
17899,https://www.bis.org/review/r100812g.pdf,https://www.bis.org/review/r100812g.pdf,Mzuzu branch project site handover and pre-con...,"Speech by Mrs Mary C Nkosi, Deputy Governor of...",2010-08-02,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Mzuzu branch project site handov...,NaN,r100812g,English,BIS
18886,https://www.bis.org/review/r111110j.pdf,https://www.bis.org/review/r111110j.pdf,"""Financing Africa - through crisis and beyond""","Opening remarks by Dr Perks M Ligoya, Governor...",2011-11-07,Perks M Ligoya,Governor,Male,Reserve Bank of Malawi,MWI,Perks M Ligoya: Financing Africa through cris...,NaN,r111110j,English,BIS
19509,https://www.bis.org/review/r120904c.pdf,https://www.bis.org/review/r120904c.pdf,Financial services laws for lawyers,"Keynote address by Dr Grant Kabango, Deputy Go...",2012-06-22,Grant Kabango,Deputy Governor,Male,Reserve Bank of Malawi,MWI,Grant Kabango: Financial services laws for law...,NaN,r120904c,English,BIS
19513,https://www.bis.org/review/r120905b.pdf,https://www.bis.org/review/r120905b.pdf,Reflections on Malawi's economy,"Speech by Mrs Mary C Nkosi, Deputy Governor of...",2012-06-29,Mary C Nkosi,Deputy Governor,Female,Reserve Bank of Malawi,MWI,Mary C Nkosi: Reflections on Malawis economy S...,NaN,r120905b,English,BIS
19514,https://www.bis.org/review/r120905c.pdf,https://www.bis.org/review/r120905c.pdf,Looking at Malawi's future,"Address by Mr Charles S R Chuka, Governor of t...",2012-07-20,Charles S R Chuka,Governor,Male,Reserve Bank of Malawi,MWI,Charles S R Chuka: Looking at Malawis future A...,NaN,r120905c,English,BIS
19655,https://www.bis.org/review/r121017a.pdf,https://www.bis.org/review/r121017a.pdf,Financial and economic challenges for Malawi,"Address by Mr Charles S R Chuka, Governor of t...",2012-09-08,Charles S R Chuka,Governor,Male,Reserve Bank of Malawi,MWI,Charles S R Chuka: Financial and economic chal...,NaN,r121017a,English,BIS
20891,https://www.bis.org/review/r140410c.htm,https://www.bis.org/review/r140410c.pdf,Intermediate banking supervision,"Speech by Mr Charles S R Chuka, Governor of th...",2014-02-24,Charles S R Chuka,Governor,Male,Reserve Bank of Malawi,MWI,Charles S R Chuka: Intermediate banking superv...,NaN,r140410c,English,BIS
21125,https://www.bis.org/review/r140714i.htm,https://www.bis.org/review/r140714i.pdf,Review of the financial sector in Malawi,"Address by Mr Charles S R Chuka, Governor of t...",2014-06-24,Charles S R Chuka,Governor,Male,Reserve Bank of Malawi,MWI,Charles S R Chuka: Review of the financial sec...,NaN,r140714i,English,BIS
23065,https://www.bis.org/review/r170223f.htm,https://www.bis.org/review/r170223f.pdf,Malawi Stock Exchange - contributing to the gr...,"Speech by Mr Charles S R Chuka, Governor of th...",2016-12-01,Charles S R Chuka,Governor,Male,Reserve Bank of Malawi,MWI,Charles S R Chuka: Malawi Stock Exchange - con...,NaN,r170223f,English,BIS
23479,https://www.bis.org/review/r170818b.htm,https://www.bis.org/review/r170818b.pdf,Malawi's Strategy for Financial Inclusion for ...,"Remarks by Mr Dalitso Kabambe, Governor of the...",2017-07-27,Dalitso Kabambe,Governor,Male,Reserve Bank of Malawi,MWI,RESERVE BANK OF MALAWI REMARKS BY DALITSO KABA...,NaN,r170818b,English,BIS
23500,https://www.bis.org/review/r170901c.htm,https://www.bis.org/review/r170901c.pdf,Curbing financial corruption in Malawi,"Speech by Mr Dalitso Kabambe, Governor of the ...",2017-07-11,Dalitso Kabambe,Governor,Male,Reserve Bank of Malawi,MWI,SPEECH BY THE GOVERNOR OF THE RESERVE BANK OF ...,NaN,r170901c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Reserve Bank of Malawi
Central Bank of the United Arab Emirates

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
439,https://centralbank.ae/en/node/604,https://centralbank.ae/sites/default/files/201...,At The Banker's Luncheon Hosted By The Bank Of...,NaN,2008-02-04,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Speech By HE Governor of Central Bank of the U...,NaN,are_04-02-2008,English,CB websites
440,https://centralbank.ae/en/node/602,https://centralbank.ae/sites/default/files/201...,Governor's Speech On Anti-Money Laundering,NaN,2008-11-11,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,_13-7/607/902/M/8(2008)-U Opening Remarks To H...,NaN,are_11-11-2008-arabic,English,CB websites
441,https://centralbank.ae/en/node/603,https://centralbank.ae/sites/default/files/201...,At The High Level Meeting On Financial Stabili...,NaN,2008-10-27,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Welcoming Remarks By H. E. Governor of Central...,NaN,are_27-10-2008,English,CB websites
442,https://centralbank.ae/en/node/613,https://centralbank.ae/sites/default/files/201...,World Economy - On The Edge,NaN,2002-03-27,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,"""The World Economy -On the Edge""Key Note Remar...",NaN,are_37342_sultan_bin_nasser_al-suwaidi,English,CB websites
443,https://centralbank.ae/en/node/612,https://centralbank.ae/sites/default/files/201...,Trends In The Global Economy,NaN,2002-10-29,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,The Trends in the Global Economy What Implicat...,NaN,are_37558_sultan_bin_nasser_al-suwaidi,English,CB websites
444,https://centralbank.ae/en/node/611,https://centralbank.ae/sites/default/files/201...,Perspectives On The Regulation Of Islamic Fina...,NaN,2004-11-11,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Perspectives on the regulation of Islamic Fina...,NaN,are_38302_sultan_bin_nasser_al-suwaidi,English,CB websites
445,https://centralbank.ae/en/node/610,https://centralbank.ae/sites/default/files/201...,4th MEED Retail Banking Conference,NaN,2005-11-29,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,The 4th. MEED Retail Banking Conference Tuesda...,NaN,are_38685_sultan_bin_nasser_al-suwaidi,English,CB websites
446,https://centralbank.ae/en/node/1894,https://centralbank.ae/sites/default/files/202...,Middle East Banking Forum,NaN,2019-11-03,Mubarak Rashed Al Mansoori,Governor,Male,Central Bank of the United Arab Emirates,ARE,"MIDDLE EAST BANKING FORUM November 3,2019 Dist...",NaN,are_43772_h.e_mubarak_rashed_al_mansoori,English,CB websites
447,https://centralbank.ae/en/node/1928,https://centralbank.ae/sites/default/files/202...,14th High-Level Meeting For The Arab Region: G...,NaN,2019-12-11,Mubarak Rashed Al Mansoori,Governor,Male,Central Bank of the United Arab Emirates,ARE,14th High-level Meeting for the Arab region: G...,NaN,are_43810_h.e_mubarak_rashed_al_mansoori,English,CB websites
448,https://centralbank.ae/en/node/2739,https://centralbank.ae/sites/default/files/202...,Opening Speech Of The Future Of Finance Confer...,NaN,2021-10-13,Khaled Mohammed Balama,Governor,Male,Central Bank of the United Arab Emirates,ARE,H.E Khaled Mohammed Balama Governor of the Cen...,NaN,are_44482_h.e_khaled_mohammed_balama,English,CB websites
449,https://centralbank.ae/en/node/2740,https://centralbank.ae/sites/default/files/202...,Day 2 Speech Of The Future Of Finance Conference,NaN,2021-10-14,Khaled Mohammed Balama,Governor,Male,Central Bank of the United Arab Emirates,ARE,H.E Khaled Mohammed Balama Governor of the Cen...,NaN,are_44483_h.e_khaled_mohammed_balama,English,CB websites
450,NaN,https://www.centralbank.ae/media/q5becu2i/cbua...,CBE Governor discusses digital transformation ...,NaN,2022-06-22,Khaled Mohammed Balama,Governor,Male,Central Bank of the United Arab Emirates,ARE,CBE Governor discusses digital transformation ...,...,are_44734,Arabic,CB websites
451,NaN,https://www.centralbank.ae/media/sjqjs1nn/cbua...,CBUAE Governor discusses further enhancements ...,NaN,2022-09-20,Khaled Mohammed Balama,Governor,Male,Central Bank of the United Arab Emirates,ARE,CBUAE Classification: Public aa_x_LqJI iLujxll...,NaN,are_44824,English,CB websites
452,NaN,https://www.centralbank.ae/media/yutmj3zr/gove...,UAE Central Bank Governor Participates in High...,NaN,2023-12-06,Khaled Mohammed Balama,Governor,Male,Central Bank of the United Arab Emirates,ARE,High-Level Meeting on Financial Stability Part...,) 6 2023 :) ...,are_45266,Arabic,CB websites
453,NaN,https://www.centralbank.ae/media/xcukld5m/the-...,The IILMs Governing discusses strategic initia...,NaN,2023-12-13,Khaled Mohammed Balama,Governor,Male,Central Bank of the United Arab Emirates,ARE,CBUAE Classification: Public United Arab Emlra...,NaN,are_45273,English,CB websites
454,https://centralbank.ae/en/node/600,https://centralbank.ae/sites/default/files/201...,At The 18th World Conference Of Banking Instit...,NaN,2009-03-04,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,"Good Morning ,,, Your Excellencies, Ladies & g...",NaN,are_eibfs-4-03-2009,English,CB websites
455,https://centralbank.ae/en/node/599,https://centralbank.ae/sites/default/files/201...,At The General Womens Union On Global Financia...,NaN,2009-03-17,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,H.E. Governor of the Central Bank of the UAE M...,/ 17 2009 6...,are_globalfinancialcrisis,Arabic,CB websites
456,https://centralbank.ae/en/node/594,https://centralbank.ae/sites/default/files/201...,Governor's Speech On Developing Debt Market,NaN,2012-11-08,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,"... ..... Your Excellencies, Ladies and Gentle...",2012 8 ... ..... ...,are_govspeech08112012,Arabic,CB websites
457,https://centralbank.ae/en/node/1157,https://centralbank.ae/sites/default/files/201...,Governor's Speech On Corporate Governance,NaN,2012-03-14,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Speech By: H.E Sultan Bin Nasser Al Suwaidi Th...,NaN,are_govspeech14032012,English,CB websites
458,https://centralbank.ae/en/node/592,https://centralbank.ae/sites/default/files/201...,The Global Financial Markets Forum 2013,NaN,2013-02-27,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,SPEECH BY H.E. GOVERNOR OF CENTRAL BANK OF THE...,NaN,are_govspeech27022013,English,CB websites
459,https://centralbank.ae/en/node/601,https://centralbank.ae/sites/default/files/201...,Central Bank - IFS School Of Finance Agreement,NaN,2009-02-17,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Speech By H.E. Governor of Central Bank of the...,NaN,are_ifs-school-of-finance,English,CB websites
460,https://centralbank.ae/en/node/608,https://centralbank.ae/sites/default/files/201...,While Receiving The Central Bank Governor Of T...,NaN,2006-09-18,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Central Bank of the UAE Press Release Date: 18...,NaN,are_interview18-9-2006,English,CB websites
461,https://centralbank.ae/en/node/597,https://centralbank.ae/sites/default/files/201...,FATF_MENAFATF Governor Remarks,NaN,2010-02-17,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Central Bank of the United Arab Emirates J7 AD...,???? ???????? ??????? ??????? ??????? ?? 7 ???...,are_mena-fatf2010-arabic,Arabic,CB websites
462,https://centralbank.ae/en/node/1158,https://centralbank.ae/sites/default/files/201...,the joint meeting FATF- MENAFATF Plenary Meeti...,NaN,2010-02-17,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,"i r "" --------- National Anti-Money Laundering...",NaN,are_mena-fatf2010,English,CB websites
463,https://centralbank.ae/en/node/595,https://centralbank.ae/sites/default/files/201...,1st Annual World Islamic Banking Conference - ...,NaN,2010-06-14,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Keynote Speech By HE GOVERNOR OF CENTRAL BANK ...,NaN,are_speech--1st-annual-world-islamic-conferenc...,English,CB websites
14953,https://www.bis.org/review/r060831e.pdf,https://www.bis.org/review/r060831e.pdf,Encountering money laundering and terrorist fi...,Inaugural speech by His Excellency Sultan Bin ...,2006-07-02,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: Encountering mon...,NaN,r060831e,English,BIS
15141,https://www.bis.org/review/r061128d.pdf,https://www.bis.org/review/r061128d.pdf,The extended importance of the euro,Speech by His Excellency Sultan Bin Nasser Al-...,2006-11-17,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: The extended imp...,NaN,r061128d,English,BIS
15220,https://www.bis.org/review/r070115d.pdf,https://www.bis.org/review/r070115d.pdf,UAE efforts in encountering money laundering a...,Speech by His Excellency Sultan Bin Nasser Al-...,2006-12-20,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: UAE efforts in e...,NaN,r070115d,English,BIS
15226,https://www.bis.org/review/r070116c.pdf,https://www.bis.org/review/r070116c.pdf,Review of the UAE economy and the central bank...,Speech by His Excellency Sultan Bin Nasser Al-...,2006-12-17,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: Review of the UA...,NaN,r070116c,English,BIS
17466,https://www.bis.org/review/r100205e.pdf,https://www.bis.org/review/r100205e.pdf,The global financial crisis and issues for a r...,Welcoming remarks by H E Sultan Bin Nasser Al-...,2009-11-16,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: The global finan...,NaN,r100205e,English,BIS
17735,https://www.bis.org/review/r100527e.pdf,https://www.bis.org/review/r100527e.pdf,The regulatory partnerships for sustained grow...,"Speech by H E Sultan Bin Nasser Al-Suwaidi, Go...",2010-05-24,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: The regulatory p...,NaN,r100527e,English,BIS
19871,https://www.bis.org/review/r130124d.pdf,https://www.bis.org/review/r130124d.pdf,Recent policy developments for strengthening t...,Welcoming remarks by H E Sultan Bin Nasser Al-...,2012-11-27,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: Recent policy de...,NaN,r130124d,English,BIS
20598,https://www.bis.org/review/r131126a.htm,https://www.bis.org/review/r131126a.pdf,Strengthening financial sector supervision and...,Welcoming remarks by H E Sultan Bin Nasser Al-...,2013-11-18,Sultan Bin Nasser Al-Suwaidi,Governor,Male,Central Bank of the United Arab Emirates,ARE,Sultan Bin Nasser Al-Suwaidi: Strengthening fi...,NaN,r131126a,English,BIS
24524,https://www.bis.org/review/r181129e.htm,https://www.bis.org/review/r181129e.pdf,Opening remarks - 20th International Conferenc...,Opening remarks by H E Mubarak Rashed Al Manso...,2018-11-28,Mubarak Rashed Al Mansoori,Governor,Male,Central Bank of the United Arab Emirates,ARE,Opening Remarks by H.E. the Governor of the Ce...,NaN,r181129e,English,BIS
25247,https://www.bis.org/review/r191008j.htm,https://www.bis.org/review/r191008j.pdf,"""Blockchain & Financial Inclusion""",Opening remarks by H E Mubarak Rashed Al Manso...,2018-12-10,Mubarak Rashed Al Mansoori,Governor,Male,Central Bank of the United Arab Emirates,ARE,Arab #FinTeX Symposium H.E. Governor Opening ...,NaN,r191008j,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of the United Arab Emirates
Central Bank of the Dominican Republic

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2898,https://www.bancentral.gov.do/a/d/2115-discurs...,NaN,Speech at the ceremony of the 61st anniversary...,NaN,2008-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,aaniversaario delBC Speech by Governor Hector ...,aaniversaario delBC Discurso del Gobernador Li...,dom_39744_hector_valdez_albizu_spanish,Spanish,CB websites
2899,NaN,https://cdn.bancentral.gov.do/documents/discur...,Speech to the Association of Industrialists of...,NaN,2008-11-25,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Speech by Governor Hector Valdez Albizu to the...,Discurso del Gobernador H<8e>ctor Valdez Albiz...,dom_39777_hector_valdez_albizu_spanish,Spanish,CB websites
2900,NaN,https://cdn.bancentral.gov.do/documents/discur...,Speech on the occasion of the Sixty-Third Anni...,NaN,2009-10-29,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,SPEECH BY MR. HeCTOR VALDEZ ALBIZU ON THE OCCA...,DISCURSO DEL LIC. H<83>CTOR VALDEZ ALBIZU CON ...,dom_40115_hector_valdez_albizu_spanish,Spanish,CB websites
2901,https://www.bancentral.gov.do/a/d/2075-discurs...,NaN,Governor Speech BC Profile,NaN,2011-01-27,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Firefox about:blank DDiscurso GobernadorPerfil...,Firefox about:blank DDiscurso GobernadorPer<de...,dom_40570_hector_valdez_albizu_spanish,Spanish,CB websites
2902,NaN,https://cdn.bancentral.gov.do/documents/discur...,Speech at the commemoration of the 64th annive...,NaN,2011-10-21,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Speech by Governor Hector Valdez Albizu in the...,Discurso pronunciado por el Gobernador Lic. H<...,dom_40837_hector_valdez_albizu_spanish,Spanish,CB websites
2903,NaN,https://cdn.bancentral.gov.do/documents/discur...,Speech at the XI Regional Conference on Centra...,NaN,2012-07-30,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,CENTRAL BANK OF THE DOMINICAN REPUBLIC WELCOME...,BANCO CENTRAL DE LA REP<f2>BLICA DOMINICANA PA...,dom_41120_hector_valdez_albizu_spanish,Spanish,CB websites
2904,NaN,https://cdn.bancentral.gov.do/documents/notici...,Speech on the occasion of the 65th Anniversary...,NaN,2012-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,SPEECH COMMEMORATING THE 65TH ANNIVERSARY OF T...,DISCURSO DE CONMEMORACI<ee>N DEL 65 ANIVERSARI...,dom_41205_hector_valdez_albizu_spanish,Spanish,CB websites
2905,NaN,https://cdn.bancentral.gov.do/documents/discur...,Speech at the opening ceremony of the exhibiti...,NaN,2013-01-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"Remarks by Mr. Hector Valdez Albizu, Governor ...",Palabras del licenciado H<8e>ctor Valdez Albiz...,dom_41297_hector_valdez_albizu_spanish,Spanish,CB websites
2906,https://www.bancentral.gov.do/a/d/1789-discurs...,NaN,Speech on the 66th Anniversary of the Central ...,NaN,2013-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"For those who speak to you, it is a high honor...",Para quien les habla constituye un alto honor ...,dom_41570_hector_valdez_albizu_spanish,Spanish,CB websites
2907,https://www.bancentral.gov.do/a/d/1676-discurs...,NaN,Speech before the Dominican Association of Exp...,NaN,2014-08-06,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"Speech delivered by Mr. Hector Valdez Albizu, ...",nadordel H<8e>ct . DDicu so ponuncado po lLc s...,dom_41857_hector_valdez_albizu_spanish,Spanish,CB websites
2908,NaN,https://cdn.bancentral.gov.do/documents/discur...,Speech at the launch ceremony of the new famil...,NaN,2014-10-07,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Words of the Governor of the Central Bank of t...,Palabras del Gobernador del Banco Central de l...,dom_41919_hector_valdez_albizu_spanish,Spanish,CB websites
2909,NaN,https://cdn.bancentral.gov.do/documents/discur...,Sixtieth Optimal Anniversary Address of the Ce...,NaN,2014-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Logo BC Sixty-seventh Anniversary Address of t...,Logo BC Discurso sexag<8e>simo s<8e>ptimo aniv...,dom_41935_hector_valdez_albizu_spanish,Spanish,CB websites
2910,https://www.bancentral.gov.do/a/d/1486-discurs...,NaN,Speech before the Dominican Association of Exp...,NaN,2015-09-03,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,nadordel Hect . DDicu so ponuncado po lLc the ...,nadordel H<8e>ct . DDicu so ponuncado po lLc s...,dom_42250_hector_valdez_albizu_spanish,Spanish,CB websites
2911,https://www.bancentral.gov.do/a/d/1459-discurs...,NaN,Speech on the occasion of the Sixty-Eighth Ann...,NaN,2015-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"nadordelBanco Cen erubtocc23de ,BCRDldeoi Hec ...","nadordelBanco Cen erubtocc23de ,BCRDldeoi H<8e...",dom_42300_hector_valdez_albizu_spanish,Spanish,CB websites
2912,https://www.bancentral.gov.do/a/d/1281-discurs...,NaN,Speech on the occasion of the Sixty-Ninth Anni...,NaN,2016-10-20,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,nadordelBanco Central Hec o . Excursion of the...,nadordelBanco Central H<8e>c o . DDiscurso del...,dom_42663_hector_valdez_albizu_spanish,Spanish,CB websites
2913,https://www.bancentral.gov.do/a/d/1122-discurs...,NaN,Seventieth Anniversary Address of the BCRD,NaN,2017-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,about:blank 7120deerubtocde23sLLune el770th An...,about:blank 7120deerubtocde23sLLune el770 Aniv...,dom_43031_hector_valdez_albizu_spanish,Spanish,CB websites
2914,https://www.bancentral.gov.do/a/d/4133-discurs...,NaN,Speech on the occasion of the LXXI anniversary...,NaN,2018-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"p, DDiscurso delseptuagesimoprimeraniversariod...","p, DDiscurso delseptuag<8e>simoprimeraniversar...",dom_43396_hector_valdez_albizu_spanish,Spanish,CB websites
2915,https://www.bancentral.gov.do/a/d/4706-discurs...,NaN,Speech on the Seventy-Second Anniversary of th...,NaN,2019-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"- 1.1.1.1.1 Li , DDiscurso delgobernador ct en...","H<8e>c o . Li , DDiscurso delgobernador ct en ...",dom_43761_hector_valdez_albizu_spanish,Spanish,CB websites
2916,https://www.bancentral.gov.do/a/d/4734-discurs...,NaN,Speech at the 2019 Grand Investor Gala,NaN,2019-12-03,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"- 1.1.1.1.1 Li , DDiscurso delgobernador ct en...","H<8e>c . Li , DDiscurso delgobernador ct enlaG...",dom_43802_hector_valdez_albizu_spanish,Spanish,CB websites
2917,https://www.bancentral.gov.do/a/d/4775-discurs...,NaN,"Speech at the launch of the documents: ""Quarte...",NaN,2020-02-11,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"Firefox Lic , PPalabrasdelGobernadordelBanco C...","Firefox Lic , PPalabrasdelGobernadordelBanco C...",dom_43872_hector_valdez_albizu_spanish,Spanish,CB websites
2918,https://www.bancentral.gov.do/a/d/4938-discurs...,NaN,Speech on the Seventy-Third Anniversary of the...,NaN,2020-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"- DDiscurso delgober Nador T en e , or Valdez ...","H<8e>c , DDiscurso delgober nador t en e , or ...",dom_44127_hector_valdez_albizu_spanish,Spanish,CB websites
2919,https://www.bancentral.gov.do/a/d/5144-discurs...,NaN,Speech at Fintech Market RD 2021,NaN,2021-07-22,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"Firefox Hec , scu so de DDi r lgobernador torV...","Firefox H<8e>c , scu so de DDi r lgobernador t...",dom_44399_hector_valdez_albizu_spanish,Spanish,CB websites
2920,https://www.bancentral.gov.do/a/d/5214-discurs...,NaN,Speech on the Seventy-fourth Anniversary of th...,NaN,2021-10-22,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"DDirde rr t Hec , scu so lgobe nado en e , or ...","DDirde rr t H<8e>c , scu so lgobe nado en e , ...",dom_44491_hector_valdez_albizu_spanish,Spanish,CB websites
2921,https://www.bancentral.gov.do/a/d/5313-concluy...,NaN,The Central Bank's Economic and Financial Week...,NaN,2022-03-10,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Central Bank's Economic and Financial Week con...,Concluye con xito Semana Econmica y Financiera...,dom_hector_valdez_albizu_44630,Spanish,CB websites
2922,https://www.bancentral.gov.do/a/d/5345-bcrd-of...,NaN,BCRD offers hospitality to the secretaries of ...,NaN,2022-04-27,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,BCRD offers entertainment to the secretaries o...,BCRD ofrece agasajo a las secretarias de la in...,dom_hector_valdez_albizu_44678,Spanish,CB websites
2923,https://www.bancentral.gov.do/a/d/5346-bcrd-po...,NaN,BCRD puts four new works into circulation with...,NaN,2022-04-28,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,BCRD puts into circulation four new works with...,BCRD pone en circulacin cuatro nuevas obras en...,dom_hector_valdez_albizu_44679,Spanish,CB websites
2924,https://www.bancentral.gov.do/a/d/5491-discurs...,NaN,Speech by Governor Hctor Valdez Albizu on the ...,NaN,2022-10-21,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"Speech by the governor, Hector Valdez Albizu, ...","Discurso del gobernador, Hctor Valdez Albizu, ...",dom_hector_valdez_albizu_44855,Spanish,CB websites
2925,https://www.bancentral.gov.do/a/d/5501-bcrd-co...,NaN,BCRD concludes its first diploma course on cyb...,NaN,2022-11-01,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,BCRD concludes its first diploma course on cyb...,BCRD concluye su primer diplomado sobre cibers...,dom_hector_valdez_albizu_44866,Spanish,CB websites
2926,https://www.bancentral.gov.do/a/d/5517-palabra...,NaN,Remarks by the Governor of the Central Bank of...,NaN,2022-11-28,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Remarks by the Governor of the Central Bank of...,Palabras del gobernador del Banco Central de l...,dom_hector_valdez_albizu_44893,Spanish,CB websites
2927,https://www.bancentral.gov.do/a/d/5633-palabra...,NaN,Remarks by Governor Hctor Valdez Albizu at the...,NaN,2023-03-20,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Remarks by Governor Hector Valdez Albizu at th...,Palabras del gobernador Hctor Valdez Albizu en...,dom_hector_valdez_albizu_45005,Spanish,CB websites
2928,https://www.bancentral.gov.do/a/d/5691-discurs...,NaN,Speech by the Governor of the Central Bank of ...,NaN,2023-05-24,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Speech by the Governor of the Central Bank of ...,Discurso del gobernador del Banco Central de l...,dom_hector_valdez_albizu_45070,Spanish,CB websites
2929,https://www.bancentral.gov.do/a/d/5787-palabra...,NaN,"Remarks by the Governor of the Central Bank, H...",NaN,2023-10-03,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"Remarks by the governor of the Central Bank, H...",Palabras del gobernador del Banco Central Hcto...,dom_hector_valdez_albizu_45202,Spanish,CB websites
2930,https://www.bancentral.gov.do/a/d/5804-discurs...,NaN,Speech by the Governor of the Central Bank of ...,NaN,2023-10-23,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,Speech by the Governor of the Central Bank of ...,Discurso del gobernador del Banco Central de l...,dom_hector_valdez_albizu_45222,Spanish,CB websites
2931,https://www.bancentral.gov.do/a/d/5820-bcrd-en...,NaN,"BCRD awards the prizes of the ""Juan Pablo Duar...",NaN,2023-11-18,Hctor Valdez Albizu,Governor,Male,Central Bank of the Dominican Republic,DOM,"BCRD awards the prizes of the ""Juan Pablo Duar...",BCRD entrega los premios del Concurso de Econo...,dom_hector_valdez_albizu_45248,Spanish,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of the Dominican Republic
National Bank of Poland

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12048,NaN,https://www.nbp.pl/konferencje/oecd/mowy/berk.pdf,Old lessons and new challenges,NaN,2002-03-21,Jan Marc Berk,Senior management,Male,National Bank of Poland,POL,OLD LESSONS AND NEW CHALLENGES Speech by dr. J...,NaN,pol_37336_jan_marc_berk_english,English,CB websites
12049,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2003...,Report on the implementation of monetary polic...,NaN,2003-07-23,Leszek Balcerowicz,Governor,Male,National Bank of Poland,POL,"Warsaw, 23 July 2003 Speech by Leszek Balcerow...","Warszawa, 23 lipca 2003 r. Wystpienie Leszka B...",pol_37825_leszek_balcerowicz_polish,Polish,CB websites
12050,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2004...,Report on the implementation of monetary polic...,NaN,2004-07-20,Leszek Balcerowicz,Governor,Male,National Bank of Poland,POL,"Warsaw, 20 July 2004 Speech by Leszek Balcerow...","Warszawa, 20 lipca 2004 r. Wystpienie Leszka B...",pol_38188_leszek_balcerowicz_polish,Polish,CB websites
12051,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2006...,Report on the implementation of monetary polic...,NaN,2006-07-18,Leszek Balcerowicz,Governor,Male,National Bank of Poland,POL,"Warsaw, 18 July 2006 Speech by Leszek Balcerow...","Warszawa, 18 lipca 2006 r. Wystpienie Leszka B...",pol_38916_leszek_balcerowicz_polish,Polish,CB websites
12052,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2007...,Report on the implementation of monetary polic...,NaN,2007-07-10,Slawomira Skrzypka,Governor,Male,National Bank of Poland,POL,"Speech by S?awomir Skrzypek, President of the ...","Przemwienie Sawomira Skrzypka, Prezesa NBP, w ...",pol_39273_slawomira_skrzypka_polish,Polish,CB websites
12053,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2008...,Speech,NaN,2008-01-31,Slawomira Skrzypka,Governor,Male,National Bank of Poland,POL,Przemienie Slawomir Skrzypek Of the President ...,Przemienie Sawomira Skrzypka Prezesa NBP przed...,pol_39478_slawomira_skrzypka_polish,Polish,CB websites
12054,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2008...,Report on the implementation of monetary polic...,NaN,2008-07-10,Slawomira Skrzypka,Governor,Male,National Bank of Poland,POL,"Transforming Sawomir Skrzypek, President of th...","Przemienie Sawomira Skrzypka, Prezesa NBP, w d...",pol_39639_slawomira_skrzypka_polish,Polish,CB websites
12055,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2010...,Speech in the Sejm,NaN,2010-07-21,Marek Belka,Governor,Male,National Bank of Poland,POL,Transformation of the President of the NBP in ...,Przemienie Prezesa NBP w Sejmie 21 lipca 2010...,pol_40380_marek_belka_polish,Polish,CB websites
12056,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2011...,Speech in the Sejm,NaN,2011-07-26,Marek Belka,Governor,Male,National Bank of Poland,POL,Transfiguration of the President of the Nation...,Przemienie Prezesa NBP prof. Marka Belki w Sej...,pol_40750_marek_belka_polish,Polish,CB websites
12057,NaN,https://www.nbp.pl/en/publikacje/speeches/Mone...,Monetary policy challenges in a non-euro EU co...,NaN,2014-10-12,Marek Belka,Governor,Male,National Bank of Poland,POL,Monetary policy challenges in a non-euro EU co...,NaN,pol_41924_marek_belka_english,English,CB websites
12058,NaN,https://www.nbp.pl/badania/konferencje/2014/Le...,Building Market Economies in Europe. Lessons a...,NaN,2014-10-24,Marek Belka,Governor,Male,National Bank of Poland,POL,"Speech by Marek Belka, President, Narodowy Ban...",NaN,pol_41936_marek_belka_english,English,CB websites
12059,NaN,https://www.nbp.pl/aktualnosci/wiadomosci_2021...,Report on the activities in 2020,NaN,2021-07-22,Adam Glapinski,Governor,Male,National Bank of Poland,POL,"Warsaw, July 22, 2021 Prof. dr hab. Adam Glapi...","Warszawa, 22 lipca 2021 r. Prof. dr hab. Adam ...",pol_44399_adam_glapinski_polish,Polish,CB websites
12060,NaN,https://www.nbp.pl/en/aktualnosci/2022/sejm202...,Report on the activities in 2021,NaN,2022-06-21,Adam Glapinski,Governor,Male,National Bank of Poland,POL,"Warsaw, 21 July 2022 Prof. Adam Glapiski Gover...",NaN,pol_44733_adam_glapinski_english,English,CB websites
12955,https://www.bis.org/review/r020103d.pdf,https://www.bis.org/review/r020103d.pdf,The optimal timing and path for Poland's entry...,"Speech by Prof Leszek Balcerowicz, President o...",2001-11-23,Leszek Balcerowicz,Governor,Male,National Bank of Poland,POL,Leszek Balcerowicz: The optimal timing and pat...,NaN,r020103d,English,BIS
14664,https://www.bis.org/review/r060321e.pdf,https://www.bis.org/review/r060321e.pdf,"Globalisation - opportunities, threats and imp...","Speech by Mr Krzysztof Rybinski, Deputy Presid...",2006-03-10,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybinski: Globalisation - opportunit...,NaN,r060321e,English,BIS
14679,https://www.bis.org/review/r060331c.pdf,https://www.bis.org/review/r060331c.pdf,"Easier, faster and more economical! Things we ...","Address by Mr Krzysztof Rybinski, Vice-Preside...",2006-03-21,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,"Krzysztof Rybiski: Easier, faster and more eco...",NaN,r060331c,English,BIS
14756,https://www.bis.org/review/r060523b.pdf,https://www.bis.org/review/r060523b.pdf,Inflation targeting and the challenges ahead,"Opening remarks by Mr Krzysztof Rybinski, Depu...",2006-05-18,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Inflation targeting and the...,NaN,r060523b,English,BIS
14835,https://www.bis.org/review/r060623e.pdf,https://www.bis.org/review/r060623e.pdf,Globalisation and its implications for monetar...,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2006-04-06,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Globalisation and its impli...,NaN,r060623e,English,BIS
14849,https://www.bis.org/review/r060705d.pdf,https://www.bis.org/review/r060705d.pdf,Globalization versus financial markets,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2006-04-20,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Globalization versus financ...,NaN,r060705d,English,BIS
14855,https://www.bis.org/review/r060706d.pdf,https://www.bis.org/review/r060706d.pdf,Outlook for Poland's economic and financial si...,"Speech by Mr Krzysztof Rybinski, Deputy Presid...",2006-05-18,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Outlook for Polands economi...,NaN,r060706d,English,BIS
14869,https://www.bis.org/review/r060714f.pdf,https://www.bis.org/review/r060714f.pdf,Global labour market and its limitations reas...,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2006-06-10,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Global labour market and it...,NaN,r060714f,English,BIS
15015,https://www.bis.org/review/r061003d.pdf,https://www.bis.org/review/r061003d.pdf,A day in the life of Homo Sapiens Globalus,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2006-09-21,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: A day in the life of Homo S...,NaN,r061003d,English,BIS
15047,https://www.bis.org/review/r061018c.pdf,https://www.bis.org/review/r061018c.pdf,How to use globalization to improve Poles' liv...,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2006-10-13,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: How to use globalization to...,NaN,r061018c,English,BIS
15048,https://www.bis.org/review/r061018d.pdf,https://www.bis.org/review/r061018d.pdf,Single euro payments area from the point of vi...,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2006-10-10,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Single euro payments area f...,NaN,r061018d,English,BIS
15193,https://www.bis.org/review/r061218e.pdf,https://www.bis.org/review/r061218e.pdf,Global imbalances and implications for emergin...,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2006-12-14,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Global imbalances and impli...,NaN,r061218e,English,BIS
15238,https://www.bis.org/review/r070118c.pdf,https://www.bis.org/review/r070118c.pdf,The euro adoption - assessing benefits and costs,"Address by Mr Krzysztof Rybinski, Deputy Presi...",2007-01-17,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: The euro adoption assessin...,NaN,r070118c,English,BIS
15352,https://www.bis.org/review/r070327d.pdf,https://www.bis.org/review/r070327d.pdf,SEPA and the payment system in Poland,"Speech by Mr Krzysztof Rybinski, Deputy Presid...",2007-03-14,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: SEPA and the payment system...,NaN,r070327d,English,BIS
15554,https://www.bis.org/review/r070620e.pdf,https://www.bis.org/review/r070620e.pdf,The role of the EURO for the future of Poland,"Speech by Mr Krzysztof Rybiski, Deputy Preside...",2007-06-15,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: The role of the EURO for th...,NaN,r070620e,English,BIS
15882,https://www.bis.org/review/r071120c.pdf,https://www.bis.org/review/r071120c.pdf,Innovations in the financial markets globaliz...,"Panel presentation by Mr Krzysztof Rybinski, D...",2007-10-16,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Innovations in the financia...,NaN,r071120c,English,BIS
15896,https://www.bis.org/review/r071127b.pdf,https://www.bis.org/review/r071127b.pdf,Monetary policy challenges resulting from the ...,"Panel discussion by Mr Krzysztof Rybiski, Depu...",2007-11-23,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Monetary policy challenges ...,NaN,r071127b,English,BIS
15897,https://www.bis.org/review/r071127c.pdf,https://www.bis.org/review/r071127c.pdf,Rapid credit growth in converging economies t...,"Closing remarks by Mr Krzysztof Rybiski, Deput...",2007-11-23,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Rapid credit growth in conv...,NaN,r071127c,English,BIS
15904,https://www.bis.org/review/r071128g.pdf,https://www.bis.org/review/r071128g.pdf,Poland and EURO,"Panel speech by Mr Krzysztof Rybiski, Deputy G...",2007-11-26,Krzysztof Rybinski,Deputy Governor,Male,National Bank of Poland,POL,Krzysztof Rybiski: Poland and EURO Panel speec...,NaN,r071128g,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Poland
Central Bank of The Bahamas

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1123,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,Remarks on the Monthly Economic and Financial...,NaN,2019-05-02,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Monthly Economic and Financial Developments (M...,NaN,bhs_2019-06-17-09-36-03-mpc-press-statement,English,CB websites
1124,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,"Remarks at the Blockchain Seminar: ""Digital Cu...",NaN,2018-03-02,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Digital Currency - Extending the Payments Syst...,NaN,bhs_2019-06-18-05-52-09-extended-version-of-we...,English,CB websites
1125,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,Foreign Investment and Exchange Controls Remarks,NaN,2018-02-22,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,FOREIGN INVESTMENT AND EXCHANGE CONTROLS Remar...,NaN,bhs_2019-06-18-05-56-37-governors-speech-to-bc...,English,CB websites
1126,https://www.centralbankbahamas.com/news/speech...,https://www.centralbankbahamas.com/viewPDF/doc...,Speech for CFAL's Educational Retirement Seminar,NaN,2017-10-25,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,"The State of the Bahamian Economy, What can be...",NaN,bhs_2019-06-18-06-56-10-speech-for-cfals-educa...,English,CB websites
1127,https://www.centralbankbahamas.com/news/speech...,https://www.centralbankbahamas.com/viewPDF/doc...,Speech to Rotary Club of East Nassau,NaN,2017-08-31,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,"Financial Literacy, Financial Inclusion and Co...",NaN,bhs_2019-06-18-07-14-06-speech-to-rotary-club-...,English,CB websites
1128,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,Remarks at the 2017 Fidelity Bahamas Economic ...,NaN,2017-01-31,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Q 7\ Co Monetary and Financial Sector Policies...,NaN,bhs_2019-06-19-05-25-26-bahamas-economic-outlo...,English,CB websites
1129,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,Remarks on the Presentation of Hurricane Donat...,NaN,2016-10-20,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Remarks by Governor John Rolle on the Presenta...,NaN,bhs_2019-06-19-06-13-55-press-release,English,CB websites
1130,https://www.centralbankbahamas.com/news/speech...,https://www.centralbankbahamas.com/viewPDF/doc...,Relaxation of Capital Account,NaN,2016-12-08,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,The Evolution of Exchange Controls in The Baha...,NaN,bhs_2019-06-19-10-45-32-relaxation-of-capital-...,English,CB websites
1131,https://www.centralbankbahamas.com/news/other-...,https://www.centralbankbahamas.com/viewPDF/doc...,Nassau Conference Speech,NaN,2018-10-12,CW Littrell,Senior management,Male,Central Bank of The Bahamas,BHS,AVAL# & REDUCING BAHAMIAN AML/CFT REPUTATION R...,NaN,bhs_2019-06-20-08-48-08-nassau-conference-speech-,English,CB websites
1132,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,MPC Press Briefing Remarks,NaN,2019-07-26,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,"MPC Press Briefing Remarks by John Rolle, Gove...",NaN,bhs_2019-07-29-03-30-00-mpc-press-statement-ju...,English,CB websites
1133,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,Remarks on the Monthly Economic and Financial ...,NaN,2019-11-04,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Monthly Economic and Financial Developments (M...,NaN,bhs_2019-11-05-01-33-24-mpc-press-presentation,English,CB websites
1134,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,MPC Press Briefing Remarks,NaN,2020-02-03,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Monetary Policy Committee Press Briefing Remar...,NaN,bhs_2020-02-04-01-42-49-mpc-press-briefing,English,CB websites
1135,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,The Opening Day for Live Trading of Government...,NaN,2020-07-09,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Governor's Remarks The Opening Day for Live Tr...,NaN,bhs_2020-07-10-00-58-16-download-governors-rem...,English,CB websites
1136,https://www.centralbankbahamas.com/news/govern...,https://www.centralbankbahamas.com/viewPDF/doc...,Remarks on the Monthly Economic and Financial ...,NaN,2020-05-04,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Monthly Economic and Financial Developments (M...,NaN,bhs_2020-07-10-01-22-12-download-mpc-press-pre...,English,CB websites
13584,https://www.bis.org/review/r040202f.pdf,https://www.bis.org/review/r040202f.pdf,The Bahamas economy - critical strategic issues,"Remarks by Mr Julian W Francis, Governor of th...",2004-01-20,Julian W Francis,Governor,Male,Central Bank of The Bahamas,BHS,Julian W Francis: The Bahamas economy - critic...,NaN,r040202f,English,BIS
22764,https://www.bis.org/review/r161004m.htm,https://www.bis.org/review/r161004m.pdf,The threat of de-risking in the Bahamas,"Remarks by Mr John A Rolle, Governor of the Ce...",2016-09-09,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,John A Rolle: The threat of de-risking in the ...,NaN,r161004m,English,BIS
23855,https://www.bis.org/review/r180126d.htm,https://www.bis.org/review/r180126d.pdf,The path to exchange control liberalisation - ...,"Remarks by Mr John A Rolle, Governor of the Ce...",2018-01-18,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,The Path to Exchange Control Liberalisation: C...,NaN,r180126d,English,BIS
23923,https://www.bis.org/review/r180312a.htm,https://www.bis.org/review/r180312a.pdf,Exchange control liberalisation and future dev...,"Remarks by Mr John A Rolle, Governor of the Ce...",2018-02-05,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,1 Welcome Remarks Governor John Rolle Seminar ...,NaN,r180312a,English,BIS
24038,https://www.bis.org/review/r180504k.htm,https://www.bis.org/review/r180504k.pdf,"""Get Money Smart Bahamas""","Remarks by Mr John A Rolle, Governor of the Ce...",2018-05-01,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,"John A Rolle: ""Get Money Smart Bahamas"" Remark...",NaN,r180504k,English,BIS
24304,https://www.bis.org/review/r180918d.htm,https://www.bis.org/review/r180918d.pdf,How the Bahamian financial system serves Baham...,"Remarks by MrJohn A Rolle, Governor of the Cen...",2018-09-17,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,How the Bahamian Financial System Serves Baham...,NaN,r180918d,English,BIS
24409,https://www.bis.org/review/r181031f.htm,https://www.bis.org/review/r181031f.pdf,Industry solutions to the withdrawal of corres...,"Opening remarks by Mr John A Rolle, Governor o...",2018-10-29,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,John A Rolle: Industry solutions to the withdr...,NaN,r181031f,English,BIS
24412,https://www.bis.org/review/r181102c.htm,https://www.bis.org/review/r181102c.pdf,Small country interfaces with the world's fina...,"Special address by Mr John A Rolle, Governor o...",2018-10-30,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,SMALL COUNTRY INTERFACES WITH THE WORLDS FINAN...,NaN,r181102c,English,BIS
24487,https://www.bis.org/review/r181121h.htm,https://www.bis.org/review/r181121h.pdf,The foreign exchange constraint on monetary po...,"Remarks by Mr John A Rolle, Governor of the Ce...",2018-11-20,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,The Foreign Exchange Constraint on Monetary Po...,NaN,r181121h,English,BIS
24749,https://www.bis.org/review/r190321a.htm,https://www.bis.org/review/r190321a.pdf,The Bahamian payment system modernisation - ad...,"Speech by Mr John A Rolle, Governor of the Cen...",2019-03-18,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,The Bahamian Payment System Modernisation: Adv...,NaN,r190321a,English,BIS
24777,https://www.bis.org/review/r190329e.htm,https://www.bis.org/review/r190329e.pdf,The importance of financial inclusion in mendi...,"Welcome remarks by Mr John A Rolle, Governor o...",2019-03-26,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,John A Rolle: The importance of financial incl...,NaN,r190329e,English,BIS
24916,https://www.bis.org/review/r190603h.htm,https://www.bis.org/review/r190603h.pdf,Fostering training to enhance the effectivenes...,"Welcome remarks by Mr John A Rolle, Governor o...",2019-05-24,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,John A Rolle: Fostering training to enhance th...,NaN,r190603h,English,BIS
25064,https://www.bis.org/review/r190729k.htm,https://www.bis.org/review/r190729k.pdf,The evolving landscape of AML/CFT in The Bahamas,"Remarks by Mr John A Rolle, Governor of the Ce...",2019-06-26,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,The Evolving Landscape of AML/CFT in The Baham...,NaN,r190729k,English,BIS
25065,https://www.bis.org/review/r190729l.htm,https://www.bis.org/review/r190729l.pdf,45th Anniversary of the Central Bank of The Ba...,"Remarks by Mr John A Rolle, Governor of the Ce...",2019-07-05,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,John A Rolle: 45th Anniversary of the Central ...,NaN,r190729l,English,BIS
25329,https://www.bis.org/review/r191104c.htm,https://www.bis.org/review/r191104c.pdf,Bahamian financial resilience post-natural dis...,"Remarks by Mr John A Rolle, Governor of the Ce...",2019-10-24,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Bahamian Financial Resilience Post-Natural Dis...,NaN,r191104c,English,BIS
25514,https://www.bis.org/review/r200203e.htm,https://www.bis.org/review/r200203e.pdf,Towards a financial sector disaster recovery p...,"Remarks by Mr John A Rolle, Governor of the Ce...",2020-01-16,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,Towards a Financial Sector Disaster Recovery P...,NaN,r200203e,English,BIS
26145,https://www.bis.org/review/r210216g.htm,https://www.bis.org/review/r210216g.pdf,Role of the Bahamian Financial Services Sector...,"Remarks by Mr John A Rolle, Governor of the Ce...",2021-01-14,John A Rolle,Governor,Male,Central Bank of The Bahamas,BHS,John A Rolle: Role of the Bahamian Financial S...,NaN,r210216g,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of The Bahamas
Banque de la Rpublique d'Hati

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7509,https://www.brh.ht/discours-du-gouverneur-au-s...,NaN,Governor's speech at the Finance Summit on 19 ...,NaN,2015-05-19,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Governor's speech at the Finance Summit on Apr...,BRH / Discours du Gouverneur au sommet sur la ...,hti_42143_jean_baden_dubois_french,French,CB websites
7510,https://www.brh.ht/discours-dinstallation-du-g...,NaN,Installation speech by the Governor of the BRH,NaN,2015-12-22,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Installation speech by the Governor of the BRH...,BRH / Discours dinstallation du Gouverneur de ...,hti_42360_jean_baden_dubois_french,French,CB websites
7511,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech on the occasion of the launch of the PR...,NaN,2016-08-26,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on the oc...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42608_jean_baden_dubois_french_2,French,CB websites
7512,https://www.brh.ht/discours-du-gouverneur-de-l...,NaN,Speech on the Economic and Financial Issues Re...,NaN,2016-08-26,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by the Governor of the BRH Mr. Jean Bad...,BRH / Discours du Gouverneur de la BRH Monsieu...,hti_42608_jean_baden_dubois_french,French,CB websites
7513,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech on the occasion of the installation of ...,NaN,2016-08-31,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on the oc...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42613_jean_baden_dubois_french,French,CB websites
7514,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech on the occasion of the opening of the D...,NaN,2016-09-27,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on the oc...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42640_jean_baden_dubois_french,French,CB websites
7515,https://www.brh.ht/allocution-du-gouverneur-je...,NaN,"Speech on October 5, 2016 at the Caribbean Cen...",NaN,2016-10-05,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on Octobe...,BRH / Allocution du Gouverneur Jean Baden Dubo...,hti_42648_jean_baden_dubois_french,French,CB websites
7516,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech on the occasion of the conference debat...,NaN,2017-03-31,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on the oc...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42825_jean_baden_dubois_french,French,CB websites
7517,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech on the occasion of the cocktail of the ...,NaN,2017-04-25,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on the oc...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42850_jean_baden_dubois_french,French,CB websites
7518,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the Workshop on Good Corporate Gover...,NaN,2017-05-16,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois Workshop...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42871_jean_baden_dubois_french_2,French,CB websites
7519,https://www.brh.ht/remarques-par-m-jean-baden-...,NaN,Remarks on the occasion of the 1st Internation...,NaN,2017-05-16,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,"Remarks by Mr. Jean Baden Dubois, Governor of ...","BRH / Remarques par M. Jean Baden Dubois, Gouv...",hti_42871_jean_baden_dubois_french,French,CB websites
7520,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the opening of the Finance Session o...,NaN,2017-06-16,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the op...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42902_jean_baden_dubois_french,French,CB websites
7521,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the launch of the forum on the issue...,NaN,2017-06-29,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the la...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42915_jean_baden_dubois_french_2,French,CB websites
7522,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the Forum on Co-ownership,NaN,2017-06-29,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the Fo...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42915_jean_baden_dubois_french,French,CB websites
7523,https://www.brh.ht/allocution-du-gouverneur-je...,NaN,Speech on the occasion of the 1st decade of th...,NaN,2017-06-30,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on the oc...,BRH / Allocution du Gouverneur Jean Baden Dubo...,hti_42916_jean_baden_dubois_french,French,CB websites
7524,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the Conference on the Economic Trans...,NaN,2017-08-22,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the Co...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_42969_jean_baden_dubois_french,French,CB websites
7525,https://www.brh.ht/discours-du-gouverneur-de-l...,NaN,"Speech at the opening of the Session ""Engaging...",NaN,2017-11-08,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by the Governor of the Bank of the Repu...,BRH / Discours du Gouverneur de la Banque de l...,hti_43047_jean_baden_dubois_french,French,CB websites
7526,https://www.brh.ht/discours-du-gouverneur-de-l...,NaN,Speech of the Governor of the Bank of the Repu...,NaN,2017-12-06,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech of the Governor of the Bank of the Repu...,BRH / Discours du Gouverneur de la Banque de l...,hti_43075_jean_baden_dubois_french_2,French,CB websites
7527,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the opening ceremony of the 2nd Conf...,NaN,2017-12-06,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the op...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_43075_jean_baden_dubois_french,French,CB websites
7528,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,"Speech at the closing ceremony of the ""Economy...",NaN,2017-12-07,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the cl...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_43076_jean_baden_dubois_french,French,CB websites
7529,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the dividend delivery ceremony by NA...,NaN,2018-03-28,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the di...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_43187_jean_baden_dubois_french,French,CB websites
7530,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the opening cocktail of the 2018 edi...,NaN,2018-04-10,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the op...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_43200_jean_baden_dubois_french,French,CB websites
7531,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech at the Financing Agricultural Transform...,NaN,2018-04-11,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois at the Fi...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_43201_jean_baden_dubois_french,French,CB websites
7532,https://www.brh.ht/discours-du-gouverneur-jean...,NaN,Speech on the occasion of the launch of Audit ...,NaN,2018-11-13,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Speech by Governor Jean Baden Dubois on the oc...,BRH / Discours du Gouverneur Jean Baden Dubois...,hti_43417_jean_baden_dubois_french,French,CB websites
7533,https://www.brh.ht/discours-douverture-prononc...,NaN,Opening speech on the occasion of the presenta...,NaN,2018-11-21,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Opening speech delivered by Governor Jean Bade...,BRH / Discours douverture prononc par le Gouve...,hti_43425_jean_baden_dubois_french,French,CB websites
7534,https://www.brh.ht/discours-du-gouverneur-a-lo...,NaN,Speech on the occasion of the transfer of fund...,NaN,2019-03-28,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Governor's speech on the occasion of the trans...,BRH / Discours du Gouverneur loccasion du tra...,hti_43552_jean_baden_dubois_french,French,CB websites
7535,https://www.brh.ht/propos-de-circonstance-de-m...,NaN,Remarks on the occasion of the signature sale ...,NaN,2019-04-11,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Remarks on the occasion of Mr. Jean Baden Dubo...,BRH / Propos de circonstance de Monsieur Jean ...,hti_43566_jean_baden_dubois_french,French,CB websites
7536,https://www.brh.ht/intervention-du-gouverneur-...,NaN,Remarks at the Haiti Constituency Meeting at t...,NaN,2019-04-13,Jean Baden Dubois,Governor,Male,Banque de la Rpublique d'Hati,HTI,Bank of the Republic of Haiti 1. BRH 2. Govern...,Banque de la Rpublique d'Hati 1. BRH 2. Interv...,hti_43568_jean_baden_dubois_french,French,CB websites
7537,https://www.brh.ht/discours-du-docteur-jean-el...,NaN,Speech by Doctor Jean Elie Larrieux Representa...,NaN,2023-05-26,Jean Elie Larrieux,Governor,Male,Banque de la Rpublique d'Hati,HTI,Research... MENU BRH / Speech by Doctor Jean E...,Recherche... MENU BRH / Discours du Docteur Je...,hti_brh_26052023,French,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Banque de la Rpublique d'Hati
Monetary Authority of Macao

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
15350,https://www.bis.org/review/r070327b.pdf,https://www.bis.org/review/r070327b.pdf,Overview of recent financial and economic deve...,"Speech by Mr Anselmo L S Teng, Chairman of the...",2007-03-15,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Overview of recent financial...,NaN,r070327b,English,BIS
15488,https://www.bis.org/review/r070529f.pdf,https://www.bis.org/review/r070529f.pdf,Update of the economic development in Macao,"Opening remarks by Mr Anselmo L S Teng, Chairm...",2007-05-22,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Update of the economic devel...,NaN,r070529f,English,BIS
15534,https://www.bis.org/review/r070612g.pdf,https://www.bis.org/review/r070612g.pdf,Macao and the perspective of syndicated loans,"Speech by Mr Anselmo L S Teng, Chairman of the...",2007-06-07,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Macao and the perspective of...,NaN,r070612g,English,BIS
15571,https://www.bis.org/review/r070627e.pdf,https://www.bis.org/review/r070627e.pdf,Financial innovation and the win-win outcome f...,"Speech by Mr Anselmo L S Teng, Chairman of the...",2007-06-09,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Financial innovation and the...,NaN,r070627e,English,BIS
15634,https://www.bis.org/review/r070724d.pdf,https://www.bis.org/review/r070724d.pdf,Anti-money laundering in financial supervision,"Opening speech by Mr Anselmo L S Teng, Chairma...",2007-07-19,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Anti-money laundering in fin...,NaN,r070724d,English,BIS
15839,https://www.bis.org/review/r071106f.pdf,https://www.bis.org/review/r071106f.pdf,Recent economic and financial developments in ...,"Opening speech by Mr Anselmo L S Teng, Chairma...",2007-10-30,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Recent economic and financia...,NaN,r071106f,English,BIS
16019,https://www.bis.org/review/r080201b.pdf,https://www.bis.org/review/r080201b.pdf,Risk management in financial services,"Opening speech by Mr Anselmo L S Teng, Chairma...",2008-01-28,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Risk management in financial...,NaN,r080201b,English,BIS
16096,https://www.bis.org/review/r080312a.pdf,https://www.bis.org/review/r080312a.pdf,Macaos financial sector - exhibiting steady de...,"Speech by Mr Anselmo L S Teng, Chairman of the...",2008-03-11,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Macaos financial sector exh...,NaN,r080312a,English,BIS
16187,https://www.bis.org/review/r080423a.pdf,https://www.bis.org/review/r080423a.pdf,Corporate governance in the financial sector,"Welcome speech by Mr Anselmo L S Teng, Chairma...",2008-04-22,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Corporate governance in the ...,NaN,r080423a,English,BIS
16322,https://www.bis.org/review/r080618e.pdf,https://www.bis.org/review/r080618e.pdf,Risk and compensation management,"Opening remarks by Mr Anselmo L S Teng, Chairm...",2008-06-14,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Risk and compensation manage...,NaN,r080618e,English,BIS
16867,https://www.bis.org/review/r090415b.pdf,https://www.bis.org/review/r090415b.pdf,Establishing a platform for financial cooperat...,"Speech by Mr Anselmo L S Teng, Chairman of the...",2009-04-06,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Establishing a platform for ...,NaN,r090415b,English,BIS
17102,https://www.bis.org/review/r090902c.pdf,https://www.bis.org/review/r090902c.pdf,Industrial transfer and financial services vie...,"Keynote speech by Mr Anselmo L S Teng, Chairma...",2009-08-14,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Industrial transfer and fina...,NaN,r090902c,English,BIS
17134,https://www.bis.org/review/r090921b.pdf,https://www.bis.org/review/r090921b.pdf,Conference on human resources issues (opening ...,"Welcome remarks by Mr Anselmo L S Teng, Chairm...",2009-09-14,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Conference on human resource...,NaN,r090921b,English,BIS
17135,https://www.bis.org/review/r090921c.pdf,https://www.bis.org/review/r090921c.pdf,Conference on human resources issues (closing ...,"Closing remarks by Mr Anselmo L S Teng, Chairm...",2009-09-16,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: Conference on human resource...,NaN,r090921c,English,BIS
17210,https://www.bis.org/review/r091020d.pdf,https://www.bis.org/review/r091020d.pdf,The economic and financial development of Maca...,"Keynote speech by Mr Anselmo L S Teng, Chairma...",2009-09-29,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: The economic and financial d...,NaN,r091020d,English,BIS
17312,https://www.bis.org/review/r091127c.pdf,https://www.bis.org/review/r091127c.pdf,Development and supervision of BVI business co...,"Opening remarks by Mr Anselmo Teng, Chairman o...",2009-11-23,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Development and supervision of B...,NaN,r091127c,English,BIS
17580,https://www.bis.org/review/r100401c.pdf,https://www.bis.org/review/r100401c.pdf,Macao's financial sector development,"Address by Mr Anselmo Teng, Chairman of the Mo...",2010-03-18,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Macaos financial sector developm...,NaN,r100401c,English,BIS
17734,https://www.bis.org/review/r100527d.pdf,https://www.bis.org/review/r100527d.pdf,The international financial crisis - impact on...,"Speech by Mr Anselmo L S Teng, Chairman of the...",2010-05-17,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo L S Teng: The international financial ...,NaN,r100527d,English,BIS
18163,https://www.bis.org/review/r101208d.pdf,https://www.bis.org/review/r101208d.pdf,"Macao's role as a platform for economic, trade...","Speech by Mr Anselmo Teng, Chairman of the Mon...",2010-11-13,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Macaos role as a platform for ec...,NaN,r101208d,English,BIS
18455,https://www.bis.org/review/r110420f.pdf,https://www.bis.org/review/r110420f.pdf,Macao's financial sector development,"Address by Mr Anselmo Teng, Chairman of the Mo...",2011-03-29,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Macaos financial sector developm...,NaN,r110420f,English,BIS
19017,https://www.bis.org/review/r111230c.pdf,https://www.bis.org/review/r111230c.pdf,Strengthening financial cooperation between Gu...,"Speech by Mr Anselmo Teng, Chairman of the Mon...",2011-12-01,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Strengthening financial cooperat...,NaN,r111230c,English,BIS
19018,https://www.bis.org/review/r111230d.pdf,https://www.bis.org/review/r111230d.pdf,China and Macao - continued financial industry...,"Address by Mr Anselmo Teng, Chairman of the Mo...",2011-12-06,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: China and Macao continued finan...,NaN,r111230d,English,BIS
19431,https://www.bis.org/review/r120718k.pdf,https://www.bis.org/review/r120718k.pdf,Development opportunity arising from cross-bor...,"Speech by Mr Anselmo Teng, Chairman of the Mon...",2012-06-28,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Development opportunity arising ...,NaN,r120718k,English,BIS
20027,https://www.bis.org/review/r130403d.pdf,https://www.bis.org/review/r130403d.pdf,Brief overview of Macao s economy in 2012,"Speech by Mr Anselmo Teng, Chairman of the Mon...",2013-02-26,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Brief overview of Macaos economy...,NaN,r130403d,English,BIS
20030,https://www.bis.org/review/r130404c.pdf,https://www.bis.org/review/r130404c.pdf,Overview of Macao's 2012 financial sector deve...,"Address by Mr Anselmo Teng, Chairman of the Mo...",2013-03-18,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Overview of Macaos 2012 financia...,NaN,r130404c,English,BIS
20159,https://www.bis.org/review/r130605d.pdf,https://www.bis.org/review/r130605d.pdf,Internationalization of the RMB and the role o...,"Address by Mr Anselmo Teng, Chairman of the Mo...",2013-05-26,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Internationalization of the RMB ...,NaN,r130605d,English,BIS
20251,https://www.bis.org/review/r130718e.pdf,https://www.bis.org/review/r130718e.pdf,The ascent of new currencies in a multipolar w...,"Address by Mr Anselmo Teng, Chairman of the Mo...",2013-06-18,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: The ascent of new currencies in ...,NaN,r130718e,English,BIS
20820,https://www.bis.org/review/r140321a.htm,https://www.bis.org/review/r140321a.pdf,Abundant opportunities for the MSAR financial ...,"Speech by Mr Anselmo Teng, Chairman of the Mon...",2014-03-17,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Abundant opportunities for the M...,NaN,r140321a,English,BIS
21153,https://www.bis.org/review/r140731c.htm,https://www.bis.org/review/r140731c.pdf,Monetary Authority of Macao - celebrating 25 y...,"Speech by Mr Anselmo Teng, Chairman of the Mon...",2014-07-10,Anselmo L S Teng,Governor,Male,Monetary Authority of Macao,MAC,Anselmo Teng: Monetary Authority of Macao cel...,NaN,r140731c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Monetary Authority of Macao
Bank of Sierra Leone

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
13809,https://www.bis.org/review/r040727h.pdf,https://www.bis.org/review/r040727h.pdf,Managing Sierra Leone's post-conflict economy,"Keynote address by Mr Mohamed S Fofana, Deputy...",2004-07-12,Mohamed S Fofana,Deputy Governor,Male,Bank of Sierra Leone,SLE,Mohamed S Fofana: Managing Sierra Leones post-...,NaN,r040727h,English,BIS
14956,https://www.bis.org/review/r060901c.pdf,https://www.bis.org/review/r060901c.pdf,Debt reporting in Sierra Leone,"Keynote address by Dr J D Rogers, Governor of ...",2006-08-07,James D Rogers,Governor,Male,Bank of Sierra Leone,SLE,J D Rogers: Debt reporting in Sierra Leone Key...,NaN,r060901c,English,BIS
14960,https://www.bis.org/review/r060901g.pdf,https://www.bis.org/review/r060901g.pdf,Banking developments in Sierra Leone,"Statement by Mr Mohamed S Fofana, Deputy Gover...",2006-07-28,Mohamed S Fofana,Deputy Governor,Male,Bank of Sierra Leone,SLE,Mohamed S Fofana: Banking developments in Sier...,NaN,r060901g,English,BIS
14961,https://www.bis.org/review/r060901h.pdf,https://www.bis.org/review/r060901h.pdf,Tackling money laundering in Sierra Leone,"Statement by Mr Mohamed S Fofana, Deputy Gover...",2006-07-10,Mohamed S Fofana,Deputy Governor,Male,Bank of Sierra Leone,SLE,Mohamed S Fofana: Tackling money laundering in...,NaN,r060901h,English,BIS
15437,https://www.bis.org/review/r070510e.pdf,https://www.bis.org/review/r070510e.pdf,Liquidity forecasting for monetary and fiscal ...,"Keynote address by Dr James D Rogers, Governor...",2007-04-17,James D Rogers,Governor,Male,Bank of Sierra Leone,SLE,James D Rogers: Liquidity forecasting for mone...,NaN,r070510e,English,BIS
15751,https://www.bis.org/review/r071001e.pdf,https://www.bis.org/review/r071001e.pdf,Inauguration of the Sierra Leone Stock Exchang...,"Welcome address by Dr James D Rogers, Governor...",2007-07-27,James D Rogers,Governor,Male,Bank of Sierra Leone,SLE,James D Rogers: Inauguration of the Sierra Leo...,NaN,r071001e,English,BIS
15752,https://www.bis.org/review/r071001f.pdf,https://www.bis.org/review/r071001f.pdf,Sierra Leone Stock Exchange developing the co...,"Opening remarks by Mohamed S Fofana, Deputy Go...",2007-07-27,Mohamed S Fofana,Deputy Governor,Male,Bank of Sierra Leone,SLE,Mohamed S Fofana: Sierra Leone Stock Exchange ...,NaN,r071001f,English,BIS
15759,https://www.bis.org/review/r071003c.pdf,https://www.bis.org/review/r071003c.pdf,"Accountability, transparency and governance in...",Keynote address and statement by Dr James D Ro...,2007-07-17,James D Rogers,Governor,Male,Bank of Sierra Leone,SLE,"James D Rogers: Accountability, transparency a...",NaN,r071003c,English,BIS
16115,https://www.bis.org/review/r080326f.pdf,https://www.bis.org/review/r080326f.pdf,Bank of Sierra Leone Charity Trust Fund,"Keynote address by Mr Mohamed S Fofana, Deputy...",2008-01-25,Mohamed S Fofana,Deputy Governor,Male,Bank of Sierra Leone,SLE,Mohamed S Fofana: Bank of Sierra Leone Charity...,NaN,r080326f,English,BIS
16120,https://www.bis.org/review/r080327f.pdf,https://www.bis.org/review/r080327f.pdf,Benefits of microfinance in Sierra Leone,"Speech by Mr Mohamed S Fofana, Deputy Governor...",2008-02-01,Mohamed S Fofana,Deputy Governor,Male,Bank of Sierra Leone,SLE,Mohamed S Fofana: Benefits of microfinance in ...,NaN,r080327f,English,BIS
17944,https://www.bis.org/review/r100914b.pdf,https://www.bis.org/review/r100914b.pdf,Issues relating to Africa in the context of th...,"Statement by Mr Sheku Sambadeen Sesay, Governo...",2010-08-16,Sheku Sambadeen Sesay,Governor,Male,Bank of Sierra Leone,SLE,Sheku Sambadeen Sesay: Issues relating to Afri...,NaN,r100914b,English,BIS
18325,https://www.bis.org/review/r110302c.pdf,https://www.bis.org/review/r110302c.pdf,"Economic overview, trends and challenges","Statement by Mr Sheku Sambadeen Sesay, Governo...",2011-01-28,Sheku Sambadeen Sesay,Governor,Male,Bank of Sierra Leone,SLE,"Sheku Sambadeen Sesay: Economic overview, tren...",NaN,r110302c,English,BIS
29619,NaN,https://bsl.gov.sl/Gov%20Sanpha%20Koroma%20Spe...,Speech in Freetown,NaN,2002-06-29,Sampha Koroma,Governor,Male,Bank of Sierra Leone,SLE,"SPEECH BY MR J. SANPHA KOROMA, GOVERNOR OF THE...",NaN,sle_37436_sle_sampha_koroma,English,CB websites
29620,NaN,https://bsl.gov.sl/Gov%20Dr%20%20Samura%20M.%2...,Statement,NaN,2008-07-18,Samura Kamara,Governor,Male,Bank of Sierra Leone,SLE,"STATEMENT BY DR SAMURA M W KAMARA GOVERNOR, BA...",NaN,sle_39647_sle_samura_kamara,English,CB websites
29621,NaN,https://bsl.gov.sl/Gov%20Samura's%20Speech%20o...,Keynote address and statement,NaN,2008-07-22,Samura Kamara,Governor,Male,Bank of Sierra Leone,SLE,Key note address and statement by Dr. Samura K...,NaN,sle_39651_sle_samura_kamara,English,CB websites
29622,NaN,https://bsl.gov.sl/Gov%20Sheku%20S.%20Sesay%20...,Press Briefing on the introduction of the new ...,NaN,2009-12-01,Sheku Sambadeen Sesay,Governor,Male,Bank of Sierra Leone,SLE,"SPEECH BY MR. SHEKU SAMBADEEN SESAY GOVERNOR, ...",NaN,sle_40148_sle_sheku_sambadeen_sesay,English,CB websites
29623,NaN,https://bsl.gov.sl/Gov%20Sheku%20S.%20Sesay%20...,Speech at the Governor's annual dinner,NaN,2012-01-27,Sheku Sambadeen Sesay,Governor,Male,Bank of Sierra Leone,SLE,SPEECH BY MR. SHEKU S. SESAY GOVERNOR OF THE B...,NaN,sle_40935_sle_sheku_sambadeen_sesay,English,CB websites
29624,NaN,https://bsl.gov.sl/Gov%20Sheku%20S.%20Sesay%20...,27th meeting of the committee of governors of ...,NaN,2012-07-11,Sheku Sambadeen Sesay,Governor,Male,Bank of Sierra Leone,SLE,DRAFT WELCOME ADDRESS BY MR SHEKU S. SESAY GOV...,NaN,sle_41101_sle_sheku_sambadeen_sesay,English,CB websites
29625,NaN,https://bsl.gov.sl/Gov%20Sheku%20S.%20Sesay%20...,Address to the House of Parliament on the Poli...,NaN,2013-12-01,Sheku Sambadeen Sesay,Governor,Male,Bank of Sierra Leone,SLE,ADDRESS TO THE HOUSE OF PARLIAMENT ON THE POLI...,NaN,sle_41609_sle_sheku_sambadeen_sesay,English,CB websites
29626,NaN,https://bsl.gov.sl/Gov%20Momodu%20L%20Kargbo%2...,Speech at the Governor's business lunch,NaN,2015-08-04,Momodu L Kargbo,Governor,Male,Bank of Sierra Leone,SLE,Speech by the Governor Mr Momodu L Kargbo Gove...,NaN,sle_42220_sle_momodu_l_kargbo,English,CB websites
29627,NaN,https://bsl.gov.sl/Gov%20Dr%20Kaifala%20Marah%...,Speech at the Governor's annual dinner,NaN,2017-02-24,Kaifala Marah,Governor,Male,Bank of Sierra Leone,SLE,GOVERNORS SPEECH AT THE GOVERNORS ANNUAL DINNE...,NaN,sle_42790_sle_kaifala_marah,English,CB websites
29628,NaN,https://bsl.gov.sl/Gov%20Dr%20Patrick%20S%20Co...,Keynote at the Standard Chartered Bank Worksho...,NaN,2017-08-17,Patrick S Conteh,Governor,Male,Bank of Sierra Leone,SLE,KEYNOTE ADDRESS BY DR. PATRICK S. CONTEH GOVER...,NaN,sle_42964_sle_patrick_s_conteh,English,CB websites
29629,NaN,https://bsl.gov.sl/Gov%20Dr%20Patrick%20S%20Co...,Promoting inclusive growth through financial i...,NaN,2018-02-02,Patrick S Conteh,Governor,Male,Bank of Sierra Leone,SLE,PROMOTING INCLUSIVE GROWTH THROUGH FINANCIAL I...,NaN,sle_43133_sle_patrick_s_conteh,English,CB websites
29630,NaN,https://bsl.gov.sl/Gov%20Patrick%20S%20Conteh%...,Keynote address at the Fintech Challenge,NaN,2018-05-15,Patrick S Conteh,Governor,Male,Bank of Sierra Leone,SLE,Sierra Leone FinTech Challenge Announcement of...,NaN,sle_43235_sle_patrick_s_conteh,English,CB websites
29631,NaN,https://bsl.gov.sl/Presentation%20at%20Parliam...,Presentation at the Hearing of the Finance Com...,NaN,2021-01-19,Kaifala Marah,Governor,Male,Bank of Sierra Leone,SLE,Presentation at the Hearing of the Finance Com...,NaN,sle_44215_sle_kelfala_m_kallon,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Sierra Leone
Central Bank of Samoa

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
15924,https://www.bis.org/review/r071204c.pdf,https://www.bis.org/review/r071204c.pdf,Enhancing and strengthening banking supervisor...,"Opening remarks by Mr Philip H Penn, Acting Go...",2007-10-23,Philip H Penn,Governor,Male,Central Bank of Samoa,WSM,Philip H Penn: Enhancing and strengthening ban...,NaN,r071204c,English,BIS
17028,https://www.bis.org/review/r090710d.pdf,https://www.bis.org/review/r090710d.pdf,Preventing money laundering and financing of t...,"Speech by Mr Papal'I T Scanlan, Governor of th...",2009-05-13,Leasi Papali'i Scanlan,Governor,Male,Central Bank of Samoa,WSM,PapaliI T Scanlan: Preventing money laundering...,NaN,r090710d,English,BIS
17447,https://www.bis.org/review/r100129d.pdf,https://www.bis.org/review/r100129d.pdf,Financial inclusion and mobile banking in Samoa,"Address by Mr Leasi Papali'i Scanlan, Governor...",2010-01-20,Leasi Papali'i Scanlan,Governor,Male,Central Bank of Samoa,WSM,Leasi Papalii Scanlan: Financial inclusion and...,NaN,r100129d,English,BIS
17628,https://www.bis.org/review/r100419d.pdf,https://www.bis.org/review/r100419d.pdf,"Samoa's economy, interest rates and the expand...","Address by Mr Leasi Papali'i Tommy Scanlan, Go...",2010-03-25,Leasi Papali'i Scanlan,Governor,Male,Central Bank of Samoa,WSM,"Leasi Papalii Tommy Scanlan: Samoas economy, i...",NaN,r100419d,English,BIS
20963,https://www.bis.org/review/r140514e.htm,https://www.bis.org/review/r140514e.pdf,Educating individuals to manage their personal...,Opening remarks by Ms Maiava Atalina Ainuu Ena...,2014-04-02,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Maiava Atalina Ainuu Enari: Educating individu...,NaN,r140514e,English,BIS
20964,https://www.bis.org/review/r140514f.htm,https://www.bis.org/review/r140514f.pdf,Educating children about money matters,Opening remarks by Ms Maiava Atalina Ainuu Ena...,2014-03-14,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Maiava Atalina Ainuu Enari: Educating children...,NaN,r140514f,English,BIS
34925,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-2/26...,Speech at SAWG Luncheon,NaN,2010-10-26,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,"ADDRESS BY THE GOVERNOR, MS MAIAVA ATALINA AIN...",NaN,wsm_40477_maiava_atalina_ainuu_enari_,English,CB websites
34926,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-2/23...,Tactical analysis and domestic coordination wo...,NaN,2013-03-08,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Governors Speech Enhancing Anti-Money Launderi...,NaN,wsm_41341_maiava_atalina_ainuu_enari_,English,CB websites
34927,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-2/23...,Opening Speech Annual Meeting of the Associati...,NaN,2013-11-01,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Governors Opening Speech Annual Meeting of the...,NaN,wsm_41579_maiava_atalina_ainuu_enari_,English,CB websites
34928,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-2/26...,Speech at the Fitness Firm Samoa's one year An...,NaN,2014-03-01,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,"ADDRESS BY THE GOVERNOR, Ms. MAIAVA ATALINA AI...",NaN,wsm_41699_maiava_atalina_ainuu_enari_,English,CB websites
34929,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-2/28...,Commonwealth Secretariat Speech,NaN,2014-04-14,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Commonwealth Secretariat Speech Washington DC ...,NaN,wsm_41743_maiava_atalina_ainuu_enari_,English,CB websites
34930,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-2/29...,Remarks at ESCAP Launch,NaN,2015-06-01,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Launch of the UNESCAP Publication Economic and...,NaN,wsm_42156_maiava_atalina_ainuu_enari_,English,CB websites
34931,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-3/32...,Intervention at COMSEC Lima Peru,NaN,2015-10-06,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,INTERVENTION BY THE GOVERNOR OF THE CENTRAL BA...,NaN,wsm_42283_maiava_atalina_ainuu_enari_,English,CB websites
34932,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-3/32...,Keynote Address on NFIS Workshop,NaN,2015-11-03,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,______________________________________________...,NaN,wsm_42311_maiava_atalina_ainuu_enari_,English,CB websites
34933,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-4/42...,Intervention Re risking the Derisked Session,NaN,2016-09-09,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Governors Briefing Re-Risking the De-Risking ...,NaN,wsm_42622_maiava_atalina_ainuu_enari_,English,CB websites
34934,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-4/42...,Intervention The PIRI Journey Session,NaN,2016-09-09,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Governors Briefing The PIRI Journey Friday 9t...,NaN,wsm_42622_maiava_atalina_ainuu_enari_2,English,CB websites
34935,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-4/42...,Intervention on Gender Gap and Equality,NaN,2016-09-09,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Governors Intervention on Closing the Gender G...,NaN,wsm_42622_maiava_atalina_ainuu_enari_3,English,CB websites
34936,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-6/61...,Welcome address,NaN,2018-06-06,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,Welcome address by Central Bank of Samoa Gover...,Welcome address by Central Bank of Samoa Gover...,wsm_43257_maiava_atalina_ainuu_enari_,Samoan,CB websites
34937,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-6/61...,Keynote speech,NaN,2018-06-06,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,"MINISTER OF FINANCE, HON. SILI EPA TUIOTI,KEYN...","MINISTER OF FINANCE, HON. SILI EPA TUIOTI, KEY...",wsm_43257_maiava_atalina_ainuu_enari_2,Samoan,CB websites
34938,NaN,https://www.cbs.gov.ws/assets/Uploads/DMS-7/71...,Remarks at FfD Ministerial Dialogue,NaN,2019-04-16,Maiava Atalina Ainuu Enari,Governor,Female,Central Bank of Samoa,WSM,"MAIAVA ATALINA AINUU-ENARI, REMARKS AT THE UND...",NaN,wsm_43571_maiava_atalina_ainuu_enari_,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Samoa
Bank of Latvia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10065,https://www.bank.lv/component/content/article/...,NaN,Augst inflcija Latvij: ko obrd dart un ko nedart?,NaN,2022-08-05,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,High inflation in Latvia: what to do and what ...,NaN,lva__44778,English,CB websites
10066,https://www.bank.lv/en/component/content/artic...,NaN,Elevated inflation in Latvia: what to do and w...,NaN,2022-08-22,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,Elevated inflation in Latvia: what to do and w...,NaN,lva__44795,English,CB websites
10067,https://www.bank.lv/en/component/content/artic...,NaN,ECB's Kazaks pushes back on rate cut bets as c...,NaN,2023-01-15,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,ECB's Kazaks pushes back on rate cut bets as c...,NaN,lva__44941,English,CB websites
10068,https://www.bank.lv/en/component/content/artic...,NaN,ECB's Kazaks keeps door open to rate hikes if ...,NaN,2023-09-20,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,ECB's Kazaks keeps door open to rate hikes if ...,NaN,lva__45189,English,CB websites
10069,https://www.bank.lv/en/component/content/artic...,NaN,ECB Must Quell Inflation In One Attempt,NaN,2023-09-25,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,ECB Must Quell Inflation In One Attempt Marti...,NaN,lva__45194,English,CB websites
10070,https://www.bank.lv/en/component/content/artic...,NaN,Message from Governor of Latvijas Banka,NaN,2020-01-14,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,Message from Governor of Latvijas Banka Publis...,NaN,lva_43844_martins_kazaks,English,CB websites
10071,https://www.bank.lv/en/component/content/artic...,NaN,Opening remarks for Latvijas Banka conference,NaN,2020-09-25,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,Opening remarks by Martis Kazaks for Latvijas ...,NaN,lva_44099_martins_kazaks,English,CB websites
10072,https://www.bank.lv/en/component/content/artic...,NaN,Sustainable Finance for climate-neutral Europe,NaN,2020-10-02,Martins Kazaks,Governor,Male,Bank of Latvia,LVA,Sustainable Finance for climateneutral Europe ...,NaN,lva_44106_martins_kazaks,English,CB websites
12550,https://www.bis.org/review/r000531c.pdf,https://www.bis.org/review/r000531c.pdf,Macroeconomic stability - a crucial preconditi...,"Speech by Mr Einar Repse, Governor of the Bank...",2000-05-19,Einar Repse,Governor,Male,Bank of Latvia,LVA,Einar Repse: Macroeconomic stability - a cruci...,NaN,r000531c,English,BIS
12883,https://www.bis.org/review/r010927b.pdf,https://www.bis.org/review/r010927b.pdf,Links between the Central Bank and financial m...,"Speech by Mr Einars Repse, Governor of the Ban...",2001-09-19,Einar Repse,Governor,Male,Bank of Latvia,LVA,Einars Repse: Links between the Central Bank a...,NaN,r010927b,English,BIS
13211,https://www.bis.org/review/r021127d.pdf,https://www.bis.org/review/r021127d.pdf,General economic developments and banking in L...,"Speech by Mr Ilmars Rimsevics, Governor of the...",2002-11-27,Ilmars Rimsevics,Governor,Male,Bank of Latvia,LVA,Ilmars Rimsevics: General economic development...,NaN,r021127d,English,BIS
13233,https://www.bis.org/review/r030116b.pdf,https://www.bis.org/review/r030116b.pdf,General economic developments and banking in L...,"Notes by Mr Ilmars Rimsevics, Governor of the ...",2002-12-31,Ilmars Rimsevics,Governor,Male,Bank of Latvia,LVA,Ilmars Rimsevics: General economic development...,NaN,r030116b,English,BIS
13948,https://www.bis.org/review/r041110b.pdf,https://www.bis.org/review/r041110b.pdf,The Latvian strategy for the euro transition,"Opening remarks by Mr Ilmars Rimsevics, Govern...",2004-10-25,Ilmars Rimsevics,Governor,Male,Bank of Latvia,LVA,Ilmars Rimsevics: The Latvian strategy for the...,NaN,r041110b,English,BIS
15377,https://www.bis.org/review/r070412d.pdf,https://www.bis.org/review/r070412d.pdf,Standing firm against manipulations with Lats'...,"Article by Mr Ilmars Rimsevics, Governor of th...",2007-02-16,Ilmars Rimsevics,Governor,Male,Bank of Latvia,LVA,Ilmars Rimsevis: Standing firm against manipul...,NaN,r070412d,English,BIS
17976,https://www.bis.org/review/r100927c.pdf,https://www.bis.org/review/r100927c.pdf,Structural reforms to pave the way to prosperi...,"Speech by Mr Ilmrs Rimvis, Governor of the Ban...",2010-09-23,Ilmars Rimsevics,Governor,Male,Bank of Latvia,LVA,Ilmars Rimsevis: Structural reforms to pave th...,NaN,r100927c,English,BIS
22225,https://www.bis.org/review/r160114f.htm,https://www.bis.org/review/r160114f.pdf,Review of the Latvian economy and challenges f...,"Introductory statement by Mr Ilmrs Rimvis, Gov...",2015-12-04,Ilmars Rimsevics,Governor,Male,Bank of Latvia,LVA,Ilmars Rimsevis: Review of the Latvian economy...,NaN,r160114f,English,BIS
24367,https://www.bis.org/review/r181015g.htm,https://www.bis.org/review/r181015g.pdf,Payments in the 22nd century - future starts t...,"Introductory statement by Ms Zoja Razmusa, Dep...",2018-10-03,Zoja Razmusa,Deputy Governor,Female,Bank of Latvia,LVA,Zoja Razmusa: Payments in the 22nd century - f...,NaN,r181015g,English,BIS
28733,https://www.bis.org/review/r991111b.pdf,https://www.bis.org/review/r991111b.pdf,Mr Repse describes general economic developmen...,"Notes delivered by Mr Einars Repse, Governor B...",1999-10-13,Einar Repse,Governor,Male,Bank of Latvia,LVA,Mr Repse describes general economic developmen...,NaN,r991111b,English,BIS
28736,https://www.bis.org/review/r991115c.pdf,https://www.bis.org/review/r991115c.pdf,Mr Repse gives a short speech on monetary poli...,"Speech given by Mr Einars Repse, Governor of t...",1999-11-11,Einar Repse,Governor,Male,Bank of Latvia,LVA,Mr Repse gives a short speech on monetary poli...,NaN,r991115c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Latvia
Central Bank of So Tom and Prncipe

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
29687,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,COBSTP Inauguration Speech,NaN,2005-07-11,Maria do Carmo Silveira,Governor,Female,Central Bank of So Tom and Prncipe,STP,Central Bank of S. Tome Principe 11/06/2005-DI...,Banco Central de S. Tom<8e> Pr<92>ncipe 11/06/...,stp_38544_portuguese,Portuguese,CB websites
29688,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Economic Balance Sheet 2005,NaN,2005-12-29,Maria do Carmo Silveira,Governor,Female,Central Bank of So Tom and Prncipe,STP,Econmic Balance of the Year 2005 Summary of th...,Balan<8d>o Econmico do ano 2005 S<92>ntese da ...,stp_38715_portuguese,Portuguese,CB websites
29689,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Economic Balance Sheet 2007,NaN,2007-12-28,Arlindo Afonso Carvalho,Governor,Male,Central Bank of So Tom and Prncipe,STP,Econico Balance Sheet of the year 2007 Speech ...,Balan<8d>o Econico do ano 2007 Discurso profer...,stp_39444_portuguese,Portuguese,CB websites
29690,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Inauguration Speech,NaN,2008-04-19,Arlindo Afonso Carvalho,Governor,Male,Central Bank of So Tom and Prncipe,STP,Econmic Balance of the Year 2008 Speech given ...,Balan<8d>o Econmico do ano 2008 Discurso profe...,stp_39557_portuguese,Portuguese,CB websites
29691,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Speech by Inauguration of OCBSTP,NaN,2008-08-07,Arlindo Afonso Carvalho,Governor,Male,Central Bank of So Tom and Prncipe,STP,GOVERNOR'S SPEECH ON THE OCCASION OF THE INAUG...,DISCURSO DO GOVERNADOR POR OCASI<cc>O DA INAUG...,stp_39667_portuguese,Portuguese,CB websites
29692,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Speech by Inauguration of the New Sat Insurance,NaN,2008-08-17,Arlindo Afonso Carvalho,Governor,Male,Central Bank of So Tom and Prncipe,STP,"Mr President of the Repblica, Mr Interim Presi...",Exmo. Senhor Presidente da Repblica Exmo. Senh...,stp_39677_portuguese,Portuguese,CB websites
29693,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Speech on the Occasion of the 16th Anniversary...,NaN,2008-08-26,Arlindo Afonso Carvalho,Governor,Male,Central Bank of So Tom and Prncipe,STP,SPEECH BY THE GOVERNOR ON THE OCCASION OF THE ...,DISCURSO DO SENHOR GOVERNADOR POR OCASI<cc>O D...,stp_39686_portuguese,Portuguese,CB websites
29694,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Economic Balance Speech of the Year 2008,NaN,2008-12-29,Arlindo Afonso Carvalho,Governor,Male,Central Bank of So Tom and Prncipe,STP,Econmic Balance of the Year 2008 Speech given ...,Balan<8d>o Econmico do ano 2008 Discurso profe...,stp_39811_portuguese,Portuguese,CB websites
29695,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Speech on the Occasion of the 17th Anniversary...,NaN,2009-08-29,Lus Fernando Moreira de Sousa,Governor,Male,Central Bank of So Tom and Prncipe,STP,SPEECH BY THE GOVERNOR ON THE OCCASION OF THE ...,DISCURSO DO SENHOR GOVERNADOR POR OCASI<cc>O D...,stp_40054_portuguese,Portuguese,CB websites
29696,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Economic Balance Speech of the Year 2009,NaN,2009-12-29,Lus Fernando Moreira de Sousa,Governor,Male,Central Bank of So Tom and Prncipe,STP,Econmic Balance of the Year 2009 Speech given ...,Balan<8d>o Econmico do ano 2009 Discurso profe...,stp_40176_portuguese,Portuguese,CB websites
29697,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Speech on the occasion of the 18th Anniversary...,NaN,2010-08-26,Lus Fernando Moreira de Sousa,Governor,Male,Central Bank of So Tom and Prncipe,STP,SPEECH BY THE GOVERNOR ON THE OCCASION OF THE ...,DISCURSO DO SENHOR GOVERNADOR POR OCASI<cc>O D...,stp_40416_portuguese,Portuguese,CB websites
29698,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Economic Balance Sheet 2010,NaN,2010-12-29,Lus Fernando Moreira de Sousa,Governor,Male,Central Bank of So Tom and Prncipe,STP,Econmic Balance of the Year 2010 Speech given ...,Balan<8d>o Econmico do ano 2010 Discurso profe...,stp_40541_portuguese,Portuguese,CB websites
29699,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Afriland First Bank Inauguration Speech,NaN,2011-03-31,Maria do Carmo Silveira,Governor,Female,Central Bank of So Tom and Prncipe,STP,"31/03/2011 Excellencies Ladies and gentlemen, ...","31/03/2011 Excel<90>ncias, Meus senhores eminh...",stp_40633_portuguese,Portuguese,CB websites
29700,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Economic Balance Speech of the Year 2012,NaN,2012-12-28,Maria do Carmo Silveira,Governor,Female,Central Bank of So Tom and Prncipe,STP,International conjuncture The international si...,Conjuntura internacional A conjuntura internac...,stp_41271_portuguese,Portuguese,CB websites
29701,NaN,https://bcstp.st/Upload/Documentos/DEFUALT/Int...,Speech on the Occasion of the 25th Anniversary...,NaN,2017-08-25,Hlio Silva Vaz de Almeida,Governor,Male,Central Bank of So Tom and Prncipe,STP,"Prime Minister and Head of Government, Excelle...","Senhor Primeiro Ministro e Chefe do Governo, E...",stp_42972_portuguese,Portuguese,CB websites
29702,NaN,https://bcstp.st/Upload/New_DOC/Balanco_Econom...,Balanco Economico of the year 2017,NaN,2017-12-29,Hlio Silva Vaz de Almeida,Governor,Male,Central Bank of So Tom and Prncipe,STP,Economic Balance Sheet 2017 On behalf of the B...,Balan<8d>o Econ<97>mico 2017 Em nome do Consel...,stp_43098_portuguese,Portuguese,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of So Tom and Prncipe
Central Bank of Aruba

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
0,https://www.cbaruba.org/readBlob.do?id=10756,NaN,President speech Managing the Economy as if th...,NaN,2021-12-08,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Managing the Economy as if the Future Really M...,NaN,abw_10756,English,CB websites
1,https://www.cbaruba.org/readBlob.do?id=7515,NaN,Speech President of the CBA 4th Annual Future ...,NaN,2019-11-01,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Safeguarding our Future: Strategies for an Aru...,NaN,abw_7515,English,CB websites
2,https://www.cbaruba.org/readBlob.do?id=7518,NaN,Speech Symposium President Semeleer CBA,NaN,2019-09-06,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,FOSTERING ECONOMIC RESILIENCE IN ARUBA; FROM R...,NaN,abw_7518,English,CB websites
3,https://www.cbaruba.org/readBlob.do?id=7548,NaN,Integrity Koninkrijk Seminar,NaN,2016-10-28,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,"Presentation by Mrs Jeanette R. Semeleer, Pres...","Voordracht door mevrouw Jeanette R. Semeleer, ...",abw_7548,Dutch,CB websites
4,https://www.cbaruba.org/readBlob.do?id=7554,NaN,Speech by the President at the BES seminar hel...,NaN,2010-03-29,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Ongoing changes in the supervisory landscape a...,NaN,abw_7554,English,CB websites
5,https://www.cbaruba.org/readBlob.do?id=7566,NaN,Conference on Financial Technology and the Fut...,NaN,2016-11-11,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Centrale Bank van Aruba The next disruptive wa...,NaN,abw_7566,English,CB websites
6,https://www.cbaruba.org/readBlob.do?id=7569,NaN,Digital Transformation and the future of gover...,NaN,2018-11-02,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Centrale Bank van Aruba Digital transformation...,NaN,abw_7569,English,CB websites
7,https://www.cbaruba.org/readBlob.do?id=7572,NaN,Economic vulnerability and resilience of Aruba...,NaN,2018-09-11,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Centrale Bank van Aruba Economic vulnerability...,NaN,abw_7572,English,CB websites
8,https://www.cbaruba.org/readBlob.do?id=7584,NaN,Good governance in the public sector management,NaN,2019-01-16,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Centrale Bank van Aruba Good governance in the...,NaN,abw_7584,English,CB websites
9,https://www.cbaruba.org/readBlob.do?id=7608,NaN,Speech by drs K Polvliet on the opening of Atr...,NaN,2004-04-23,K Polvliet,Board member,Male,Central Bank of Aruba,ABW,INSURANCE SUPERVISION IN A GLOBALIZING FINANCI...,NaN,abw_7608,English,CB websites
10,https://www.cbaruba.org/readBlob.do?id=7611,NaN,Closing speech RegTech 2017,NaN,2017-11-03,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,When Regulators become Innovators: Industries ...,NaN,abw_7611,English,CB websites
11,https://www.cbaruba.org/readBlob.do?id=7644,NaN,Sound Corporate and Public Governance,NaN,2016-03-10,Prakash Mungra,Board member,Male,Central Bank of Aruba,ABW,Sound Corporate and Public Governance: A brief...,NaN,abw_7644,English,CB websites
12,https://www.cbaruba.org/readBlob.do?id=7647,NaN,Speech at launch of the Annual Report 2003,NaN,2004-06-10,A Caram,Governor,Male,Central Bank of Aruba,ABW,PROMOTING FINANCIAL STABILITY REQUIRES ADDITIO...,BEVORDERING FINANCILE STABILITEIT VEREIST EXTR...,abw_7647,Dutch,CB websites
13,https://www.cbaruba.org/readBlob.do?id=7671,NaN,Address on the official opening of the new Ar...,NaN,2004-11-20,R Henriquez,Governor,Male,Central Bank of Aruba,ABW,A REFLECTION OF PERSEVERANCE AND RESILIENCE Ad...,NaN,abw_7671,English,CB websites
14,NaN,https://www.cbaruba.org/readBlob.do?id=13621,SPEECH DELIVERED BY MR PRAKASH MUNGRA,NaN,2023-03-22,Prakash Mungra,Board member,Male,Central Bank of Aruba,ABW,Speech delivered by Mr. Prakash Mungra Executi...,NaN,abw_prakash_mungra_45007,English,CB websites
17373,https://www.bis.org/review/r091216e.pdf,https://www.bis.org/review/r091216e.pdf,To dollarize or not to dollarize - the Central...,"Speech by Ms Jeanette R Semeleer, President of...",2009-08-24,Jeanette R Semeleer,Governor,Female,Central Bank of Aruba,ABW,Jeanette R Semeleer: To dollarize or not to do...,NaN,r091216e,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Aruba
Central Bank of Armenia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
485,NaN,https://www.cba.am/EN/particlesspeeches/Digita...,Digital transformation of Armenia's financial ...,NaN,2022-01-25,Martin Galstyan,Governor,Male,Central Bank of Armenia,ARM,Digital transformation of Armenias financial s...,NaN,arm_digital_transformation__m._galstyan,English,CB websites
486,NaN,https://www.cba.am/AM/particlesspeeches/Dram30...,CB President Martin Galsty's address to the 30...,NaN,2023-11-22,Martin Galstyan,Governor,Male,Central Bank of Armenia,ARM,"Martin Galstyan, Central Bank of Armenia, at t...","30 , , , ...",arm_dram30_mg_speech_22.11.2023,Armenian,CB websites
487,NaN,cba.am/AM/particlesspeeches/Governor_Opening-C...,Central Bank President Martin Galsty's opening...,NaN,2023-11-12,Martin Galstyan,Governor,Male,Central Bank of Armenia,ARM,CaseKey 2023 Business Problem Solution Competi...,CaseKey 2023 12 2023 20...,arm_governor_opening-casekey_2023_gala,Armenian,CB websites
488,NaN,https://www.cba.am/AM/particlesspeeches/IMF_Al...,CB president's address at the opening of a reg...,NaN,2023-06-09,Martin Galstyan,Governor,Male,Central Bank of Armenia,ARM,INTERNATIONAL MONETARY FUND (IMF) Development ...,"() , () , , 9- , 2023 , ...",arm_imf_almaty_speech_15.06.2023,Armenian,CB websites
489,NaN,https://www.cba.am/AM/particlesspeeches/MG_End...,"Address by Martin Galsty, president of the Cen...",NaN,2023-12-28,Martin Galstyan,Governor,Male,Central Bank of Armenia,ARM,"President of the Republic of Armenia, Captain ...",", , , , , , , 2024...",arm_mg_end-of-year_speech_28.12.2023,Armenian,CB websites
490,NaN,cba.am/AM/particlesspeeches/Opening_Remarks-30...,"The opening remarks of Martin Galsty, presiden...",NaN,2023-09-02,Martin Galstyan,Governor,Male,Central Bank of Armenia,ARM,"The opening remarks of Martin Galsty, presiden...","30-. , 2, 2023 , ...",arm_opening_remarks-30th_anniversary_of_dram,Armenian,CB websites
491,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Farewell message on the end of the central ban...,NaN,2020-06-12,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,12.06.2020 Arthur Javadyan's farewell message ...,"12.06.2020 , 12 , ...",arm_speech_12.06.2020,Armenian,CB websites
492,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Speech on a bank employee's day,NaN,2019-11-22,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,"22.11.2019 Mr. Arthur Javadyan, president of t...","22.11.2019 : 22- , ...",arm_speech_22.11.2019,Armenian,CB websites
493,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Speech at a traditional 2015 anniversary recep...,NaN,2015-12-25,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,"Address by Mr. Arthur Javadyan, president of t...","2015 . , , ` : ...",arm_speech_25.12.2015,Armenian,CB websites
494,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Speech at the 2018 anniversary reception at th...,NaN,2018-12-25,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,"Arthur Javadyan, president of the Central Bank...","- 2018 , , , : 2018 , ...",arm_speech_25.12.2018,Armenian,CB websites
495,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Speech at a traditional 2014 anniversary recep...,NaN,2014-12-26,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,"Mr. Arthur Javadyan, president of the Central ...","2014 . , , : , ...",arm_speech_26.12.2014,Armenian,CB websites
496,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Reception at the Central Bank,NaN,2019-12-27,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,MAMLO MESSAGE 27.12.2019 Timothy's reception a...,"27.12.2019 25.12.2019 . , ...",arm_speech_27.12.2019,Armenian,CB websites
497,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Speech at the end of 2021 at the CB,NaN,2021-12-27,Martin Galstyan,Governor,Male,Central Bank of Armenia,ARM,"Dear Mr. Master, Who are you? Who are you? The...",", , , 2021 , , , ...",arm_speech_27.12.2021,Armenian,CB websites
498,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Speech at a traditional 2016 anniversary recep...,NaN,2016-12-28,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,"Mr. Arthur Javadyan, president of the Central ...","2016 . , , : 2017 , ...",arm_speech_28.12.2016,Armenian,CB websites
499,NaN,https://www.cba.am/AM/particlesspeeches/Speech...,Speech at a traditional 2018 anniversary recep...,NaN,2017-12-28,Arthur Javadyan,Governor,Male,Central Bank of Armenia,ARM,"Address by Arthur Javadyan , president of the ...","- 2017 , , , ...",arm_speech_28.12.2017,Armenian,CB websites
14946,https://www.bis.org/review/r060830c.pdf,https://www.bis.org/review/r060830c.pdf,The Basel recommendations - approaches and rea...,"Speech by Mr Tigran Sargsyan, Chairman of Cent...",2006-06-07,Tigran Sargsyan,Governor,Male,Central Bank of Armenia,ARM,Tigran Sargsyan: The Basle recommendations - a...,NaN,r060830c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Armenia
Central Bank of Eswatini

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
30063,https://www.centralbank.org.sz/speeches/,NaN,Welcome and opening remarks,NaN,2018-11-12,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,Welcome and Opening Remarks By Mr. Mhlabuhlang...,NaN,swz_dg_speech_crisis_binder_and_deposit_guaran...,English,CB websites
30064,https://www.centralbank.org.sz/speeches/,NaN,FinTech Challenge Media Briefing,NaN,2017-01-01,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,FINTECH CHALLENGE MEDIA BRIEFING By Majozi V. ...,NaN,swz_fintech-challenge-media-briefing-speech,English,CB websites
30065,https://www.centralbank.org.sz/speeches/,NaN,Remarks: official launch of the FinTech Challenge,NaN,2015-06-15,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS REMARKS: OFFICIAL LAUNCH OF THE FINT...,NaN,swz_fintechchallenge-governorspeech,English,CB websites
30066,https://www.centralbank.org.sz/speeches/,NaN,Talking Points: Global Money Week Prize Presen...,NaN,2017-06-12,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,Central Bank of Swaziland Umntsholi WeMaSwati ...,NaN,swz_globalmoneyweekpresentations-12july2017,English,CB websites
30067,https://www.centralbank.org.sz/speeches/,NaN,Talking notes on the integrated annual report ...,NaN,2019-10-09,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS TALKING NOTES ON THE 2018/19 INTEGRA...,NaN,swz_governor_ir_presentation_09_oct_2019,English,CB websites
30068,https://www.centralbank.org.sz/speeches/,NaN,Speech at the Launch of Currency Museum,NaN,2021-11-10,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS SPEECH LAUNCH OF CURRENCY MUSEUM VEN...,NaN,swz_governor-speech-oct-2021,English,CB websites
30069,https://www.centralbank.org.sz/speeches/,NaN,Annual monetary policy statement address,NaN,2015-06-12,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,Programme Director Honourable Minister of Fina...,NaN,swz_governorannualmonetarypolicystatementspeech,English,CB websites
30070,https://www.centralbank.org.sz/speeches/,NaN,Annual Monetary policy Statement Address,NaN,2019-05-02,Mhlabuhlangene P. Dlamini,Deputy Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS ANNUAL MONETARY POLICY STATEMENT ADD...,NaN,swz_governors_annual_monetary_policy_statement...,English,CB websites
30071,https://www.centralbank.org.sz/speeches/,NaN,Opening remarks on the post budget seminar,NaN,2020-02-20,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS OPENING REMARKS ON THE POST BUDGET S...,NaN,swz_governors_opening_remarks_pbs_2020,English,CB websites
30072,https://www.centralbank.org.sz/speeches/,NaN,Membership in the EFWG,NaN,2020-12-07,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,SPEECH TITLE: CBE MEMBERSHIP IN THE EFWG Event...,NaN,swz_governors_remarks_eswatini_fintech_working...,English,CB websites
30073,https://www.centralbank.org.sz/speeches/,NaN,Remarks: Signing of MOU,NaN,2020-12-02,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS REMARKS SIGNING OF MOU Event: Signin...,NaN,swz_governors_remarks_signing_of_moa_with_comp...,English,CB websites
30074,https://www.centralbank.org.sz/speeches/,NaN,Annual Monetary policy Statement Address,NaN,2020-06-18,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS ANNUAL MONETARY POLICY STATEMENT ADD...,NaN,swz_governors-annual-monetary-statementaddress...,English,CB websites
30075,https://www.centralbank.org.sz/speeches/,NaN,Opening remarks by the chairperson of the Eswa...,NaN,2019-10-23,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,OPENING REMARKS BY THE CHAIRPERSON OF THE ESWA...,NaN,swz_opening_remarks_by_the_cbe_governor_and_ch...,English,CB websites
30076,https://www.centralbank.org.sz/speeches/,NaN,Post budget speech,NaN,2014-06-12,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,POST BUDGET SEMINAR 2014 C:\Users\Nonod\Deskto...,NaN,swz_postbudgetseminar2014,English,CB websites
30077,https://www.centralbank.org.sz/speeches/,NaN,Talking notes on the relaunch of the export cr...,NaN,2021-09-17,Majozi V. Sithole,Governor,Male,Central Bank of Eswatini,SWZ,GOVERNORS TALKING NOTES ON THE RELAUNCH OF THE...,NaN,swz_speech17092021eswatini,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Eswatini
Banco Central del Paraguay

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12437,https://www.bcp.gov.py/asumio-nuevo-presidente...,NaN,New president of the Central Bank assumed office.,Con la presencia del Presidente de la Repblica...,2013-10-03,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,"Mr. President of the Republic, Horacio Cartes ...",DISCURSO POSESI<ee>N DE CARGO PRESIDENTE BANCO...,pry_41550_spanish,Spanish,CB websites
12438,https://www.bcp.gov.py/xi-reunion-del-comite-r...,NaN,XI Regional Meeting of the Latin American Comm...,El Presidente del Banco Central del Paraguay (...,2014-03-26,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,Members of the International Association of De...,DISCURSO XI REUNION DEL COMITE REGIONAL DE AME...,pry_41724_spanish,Spanish,CB websites
12439,https://www.bcp.gov.py/asumio-nuevo-miembro-de...,NaN,New member assumed the position on the BCP Boa...,COMPROMETI SU ESFUERZO PARA IMPULSAR CAMBIOS E...,2014-10-20,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,"Minister of Finance, Mr. President of the Cent...","Se<96>or Ministro de Hacienda, Se<96>or Presid...",pry_41932_spanish,Spanish,CB websites
12440,https://www.bcp.gov.py/en-el-bcp-expertos-inte...,NaN,International experts gave lectures on best in...,"CONFERENCIA ORGANIZADA CON EL FMI, BID, y BM L...",2014-10-21,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,Representatives of International Organizations...,Se<96>ores Representantes de Organismos Intern...,pry_41933_spanish,Spanish,CB websites
12441,https://www.bcp.gov.py/presidente-del-bcp-habl...,NaN,President of BCP spoke at the opening of the I...,"El titular del Banco Central del Paraguay, Car...",2014-11-27,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,"ADEFI Annual Congress Thursday, November 27 La...",Congreso anual de la ADEFI Jueves 27 de noviem...,pry_41970_spanish,Spanish,CB websites
12442,https://www.bcp.gov.py/carlos-carvallo-asumio-...,NaN,Carlos Carvallo assumed as a new member of the...,Esta maana a las 11 en el saln Auditorio del B...,2015-05-11,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,Many thanks to the President of the Central Ba...,Muchas gracias al presidente del Banco Central...,pry_42135_spanish,Spanish,CB websites
12443,https://www.bcp.gov.py/el-bcp-presento-moneda-...,NaN,BCP presented a commemorative coin for the vis...,El Banco Central del Paraguay present una mone...,2015-07-06,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,Commemorative Coin - Visit of Pope Francis Ope...,Moneda Conmemorativa - Visita del Papa Francis...,pry_42191_spanish,Spanish,CB websites
12444,https://www.bcp.gov.py/presidente-del-bcp-dest...,NaN,President of BCP highlights Paraguay as the ho...,Esta maana se llev a cabo el lanzamiento de la...,2016-08-01,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,LAUNCH OF THE IDB/IIC BOARD OF GOVERNORS 2017 ...,LANZAMIENTO ASAMBLEA DE GOBERNADORES BID/CII 2...,pry_42583_spanish,Spanish,CB websites
12445,https://www.bcp.gov.py/bcp-y-csj-firmaron-conv...,NaN,BCP and CSJ signed an interinstitutional coope...,"Esta maana, en la Sala de Reuniones de la Pres...",2016-09-01,Carlos Fernndez Valdovinos,Governor,Male,Banco Central del Paraguay,PRY,Speech President BCP agreement Supreme Court ...,Discurso presidente BCP <d0> convenio Corte Su...,pry_42614_spanish,Spanish,CB websites
12446,https://www.bcp.gov.py/asumio-nueva-titular-de...,NaN,New head of the Superintendence of Insurance a...,Asumi esta maana la nueva titular de la Superi...,2019-03-29,Fernanda Carron,Senior management,Female,Banco Central del Paraguay,PRY,SPEECH OF POSSESSION TO THE OFFICE OF INSURANC...,DISCURSO DE POSECION AL CARGO DE SUPERINTENDEN...,pry_43553_spanish,Spanish,CB websites
12447,https://www.bcp.gov.py/asumio-liana-caballero-...,NaN,Liana Caballero assumed as a new member of the...,Liana Caballero Krause asumi esta maana como n...,2019-04-25,Liana Caballero Krause,Board member,Female,Banco Central del Paraguay,PRY,"His Excellency, Mr. Benigno Lopez, Minister of...","Su Excelencia, Don Benigno L<97>pez, Ministro ...",pry_43580_spanish,Spanish,CB websites
12448,https://www.bcp.gov.py/fernando-filartiga-cant...,NaN,Fernando Filrtiga Cantero assumed as a new mem...,Fernando Jess Filrtiga Cantero asumi esta maan...,2020-02-14,Fernando Filartiga,Board member,Male,Banco Central del Paraguay,PRY,"Mr. oscar Orue, Undersecretary of State for Ta...","Se<96>or <ee>scar Oru<8e>, Subsecretario de Es...",pry_43875_spanish,Spanish,CB websites
12449,https://www.bcp.gov.py/maria-fernanda-carron-y...,NaN,Mara Fernanda Carron and Humberto Colmn assume...,Este jueves; Mara Fernanda Carron y Humberto C...,2021-11-18,Carvallo,Senior management,Male,Banco Central del Paraguay,PRY,"Good day Your Excellency, Dr. Oscar Lamosas, M...","Muy Buen d<92>a Su Excelencia, Dr. Oscar Lamos...",pry_44518_spanish,Spanish,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Banco Central del Paraguay
National Bank of Rwanda

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
28928,NaN,https://www.bnr.rw/news-publications/news/spee...,Speech at the MTN Group Regulatory and Public ...,NaN,2017-09-18,Monique Nsanzabaganwa,Deputy Governor,Female,National Bank of Rwanda,RWA,The of the National Bank of Rwanda Commissione...,NaN,rwa_42996_english,English,CB websites
28929,NaN,https://www.bnr.rw/news-publications/news/spee...,Talking points (RBA Gala Dinner),NaN,2017-12-01,John Rwangombwa,Governor,Male,National Bank of Rwanda,RWA,GOVERNORd5S TALKING POINTS d0 RBA Gala Dinner ...,NaN,rwa_43070_english,English,CB websites
28930,NaN,https://www.bnr.rw/news-publications/news/spee...,Speech at the 4th East African Central Banks A...,NaN,2018-01-23,John Rwangombwa,Governor,Male,National Bank of Rwanda,RWA,Governord5s Remarks Launch Ceremony at London ...,NaN,rwa_43123_english,English,CB websites
28931,NaN,https://www.bnr.rw/news-publications/news/spee...,Corporate Governance Training for Banks,NaN,2018-03-13,Monique Nsanzabaganwa,Deputy Governor,Female,National Bank of Rwanda,RWA,Governor's High Level Regio nal Financial Stab...,NaN,rwa_43172_english,English,CB websites
28932,NaN,https://www.bnr.rw/news-publications/news/spee...,speech at Cooperatives' Contributions to Peace...,NaN,2019-10-17,Monique Nsanzabaganwa,Deputy Governor,Female,National Bank of Rwanda,RWA,"Opening Remarks for the 8,h ICPAR Annual Train...",NaN,rwa_43755_english,English,CB websites
28933,NaN,https://www.bnr.rw/news-publications/news/spee...,Speech at ICA GLOBAL Conference Cooperatives f...,NaN,2019-10-18,Monique Nsanzabaganwa,Deputy Governor,Female,National Bank of Rwanda,RWA,... LAUNCH OF THE SECOND PHASE OF THE DIGITAL ...,NaN,rwa_43756_english,English,CB websites
28934,NaN,https://www.bnr.rw/news-publications/news/spee...,Journey to a cashless economy,NaN,2019-10-30,John Rwangombwa,Governor,Male,National Bank of Rwanda,RWA,ICA GLOBAL CONFERENCE COOPERATIVES for DEVELOP...,NaN,rwa_43768_english,English,CB websites
28935,NaN,https://www.bnr.rw/news-publications/news/spee...,Remarks at a High Level Regional Financial Sta...,NaN,2019-12-09,John Rwangombwa,Governor,Male,National Bank of Rwanda,RWA,Governor's High Level Regio nal Financial Stab...,NaN,rwa_43808_english,English,CB websites
28936,NaN,https://www.bnr.rw/news-publications/news/spee...,Remarks at London Stock Exchange,NaN,2020-01-20,John Rwangombwa,Governor,Male,National Bank of Rwanda,RWA,Governord5s Remarks Launch Ceremony at London ...,NaN,rwa_43850_english,English,CB websites
28937,NaN,https://www.bnr.rw/news-publications/news/spee...,Policy Seminar Speech 2020,NaN,2020-09-22,Monique Nsanzabaganwa,Deputy Governor,Female,National Bank of Rwanda,RWA,Theme: Monetary policy in times of crisis: Glo...,NaN,rwa_44096_english,English,CB websites
28938,NaN,https://www.bnr.rw/news-publications/news/spee...,Opening remarks at the AACB extraordinary virt...,NaN,2020-11-26,John Rwangombwa,Governor,Male,National Bank of Rwanda,RWA,The of the National Bank of Rwanda Commissione...,NaN,rwa_44161_english,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/National Bank of Rwanda
Reserve Bank of Zimbabwe

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
35025,NaN,https://www.rbz.co.zw/documents/publications/s...,Speaking Notes on the International Day for Women,NaN,2014-03-08,Charity Dhliwayo,Governor,Female,Reserve Bank of Zimbabwe,ZWE,SPEAKING NOTES ON THE INTERNATIONAL WOMENd5S D...,NaN,zwe_41706_charity_dhliwayo_english,English,CB websites
35026,NaN,https://www.rbz.co.zw/documents/publications/s...,The official Launch of the US$100 Million AFRE...,NaN,2014-03-22,Charity Dhliwayo,Governor,Female,Reserve Bank of Zimbabwe,ZWE,REMARKS BY ACTING GOVERNOR RESERVE BANK OF ZIM...,NaN,zwe_41720_charity_dhliwayo_english,English,CB websites
35027,NaN,https://www.rbz.co.zw/documents/publications/s...,Acceptance Speech,NaN,2014-05-07,John Mangudya,Governor,Male,Reserve Bank of Zimbabwe,ZWE,Press Release:... Issued by the Governor of th...,NaN,zwe_41766_john_mangudya_english,English,CB websites
35028,NaN,https://www.rbz.co.zw/documents/publications/s...,Opening Remarks at the SADC and MEFMI Regional...,NaN,2015-04-27,Charity Dhliwayo,Deputy Governor,Female,Reserve Bank of Zimbabwe,ZWE,"Opening Remarks by Dr. C. L. Dhliwayo, Deputy ...",NaN,zwe_42121_charity_dhliwayo_english,English,CB websites
35029,NaN,https://www.rbz.co.zw/documents/publications/s...,Closing Remarks at the SADC And MEFMI Regional...,NaN,2015-04-29,Charity Dhliwayo,Deputy Governor,Female,Reserve Bank of Zimbabwe,ZWE,MEFMI/SADC REGIONAL SEMINAR FOR FINANCIAL SECT...,NaN,zwe_42123_charity_dhliwayo_english,English,CB websites
35030,NaN,https://www.rbz.co.zw/documents/publications/s...,Opening Remarks at the RBZ and World Bank Work...,NaN,2015-07-15,Charity Dhliwayo,Deputy Governor,Female,Reserve Bank of Zimbabwe,ZWE,Opening Remarks by Dr. C. L. Dhliwayo Acting G...,NaN,zwe_42200_charity_dhliwayo_english,English,CB websites
35031,NaN,https://www.rbz.co.zw/documents/publications/s...,Remarks at the Banking Finance and Insurance Expo,NaN,2015-07-29,Charity Dhliwayo,Deputy Governor,Female,Reserve Bank of Zimbabwe,ZWE,"Remarks by Dr. C. L. Dhliwayo Deputy Governor,...",NaN,zwe_42214_charity_dhliwayo_english,English,CB websites
35032,NaN,https://www.rbz.co.zw/documents/publications/s...,Presentation on the Tourism Support Facility,NaN,2018-01-12,John Mangudya,Governor,Male,Reserve Bank of Zimbabwe,ZWE,"RESERVE BANK OF ZIMBABWE GOVERNOR, DR J.P. MAN...",NaN,zwe_43112_j_p_mangudya_english,English,CB websites
35033,NaN,https://www.rbz.co.zw/documents/publications/s...,The 2018 Microfinance Excellence and Appreciat...,NaN,2018-12-14,Jesimen Chipika,Deputy Governor,Female,Reserve Bank of Zimbabwe,ZWE,KEY NOTEADDRESS BY DR. J. T. CHIPIKA DEPUTY GO...,NaN,zwe_43448_jesimen_chipika_english,English,CB websites
35034,NaN,https://www.rbz.co.zw/documents/publications/s...,Joint National Fintech Steering Committee & In...,NaN,2019-08-01,K. Mlambo,Senior management,Male,Reserve Bank of Zimbabwe,ZWE,WELCOME ADDRESS BY DR. K. MLAMBO CO-CHAIR OF N...,NaN,zwe_43678_k_mlambo_english,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Reserve Bank of Zimbabwe
Central Bank of Suriname

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
29703,NaN,https://www.cbvs.sr/images/content/publicaties...,Address by the Governor for Suriname,NaN,2011-03-28,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,Annual Meeting of the Boards of Governors CALG...,NaN,sur_40630_gillmore_hoefdraad_english,English,CB websites
29704,NaN,https://www.cbvs.sr/images/content/publicaties...,IMF-CARTAC Course on National Account Statistics,NaN,2012-02-06,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,Remarks at the Opening Session of the IMF-CART...,NaN,sur_40945_gillmore_hoefdraad_english,English,CB websites
29705,NaN,https://www.cbvs.sr/images/content/publicaties...,Opening remarks,NaN,2012-02-13,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,"Opening Remarks by Mr. Gillmore Hoefdraad, Gov...",NaN,sur_40952_gillmore_hoefdraad_english,English,CB websites
29706,NaN,https://www.cbvs.sr/images/content/publicaties...,Statement Governor at Annual Meeting of Govern...,NaN,2012-03-01,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,"In the name of ALLAH, the Most Gracious, the M...",NaN,sur_40969_gillmore_hoefdraad_english,English,CB websites
29707,NaN,https://www.cbvs.sr/images/content/publicaties...,Address by the Governor for Suriname,NaN,2012-03-19,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,Annual Meeting of the Boards of Governors MONT...,NaN,sur_40987_gillmore_hoefdraad_english,English,CB websites
29708,NaN,https://www.cbvs.sr/images/content/publicaties...,Highlights of 2012 and a Preview of 2013,NaN,2012-12-28,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,Central Bank of Suriname: Highlights of 2012 a...,NaN,sur_41271_gillmore_hoefdraad_english,English,CB websites
29709,NaN,https://www.cbvs.sr/images/content/governors/L...,Launch of interim member country partnership s...,NaN,2013-11-26,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,LAUNCH OF INTERIM MEMBER COUNTRY PARTNERSHIP S...,LAUNCH OF INTERIM MEMBER COUNTRY PARTNERSHIP S...,sur_41604_gillmore_hoefdraad_dutch,Dutch,CB websites
29710,NaN,https://www.cbvs.sr/images/content/governors/2...,Financial stability Seminar,NaN,2014-07-08,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,Financial stability Seminar Ladies and gentlem...,NaN,sur_41828_gillmore_hoefdraad_english,English,CB websites
29711,NaN,https://www.cbvs.sr/images/content/governors/2...,Welcome speech of Governor,NaN,2014-10-13,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,Welcome speech of Governor Gillmore Hoefdraad ...,NaN,sur_41925_gillmore_hoefdraad_english,English,CB websites
29712,NaN,https://www.cbvs.sr/images/content/governors/2...,The way forward,NaN,2015-03-11,Gillmore Hoefdraad,Governor,Male,Central Bank of Suriname,SUR,The way forward Sound Policies and Institution...,NaN,sur_42074_gillmore_hoefdraad_english,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Suriname
Maldives Monetary Authority

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10130,http://www.mma.gov.mv/#/speeches/Speech01.html,NaN,Opening Ceremony of the Commercial Bank of Mal...,NaN,2016-09-26,Azeema Adam,Governor,Female,Maldives Monetary Authority,MDV,"Speech01.html Speech by Dr. Azeema Adam, Gover...",NaN,mdv_42639_azeema_adam,English,CB websites
10131,http://www.mma.gov.mv/#/speeches/Speech02.html,NaN,Opening Ceremony of Maldives Accountants Forum...,NaN,2017-11-06,Ahmed Naseer,Governor,Male,Maldives Monetary Authority,MDV,"Speech02.html Speech by Mr. Ahmed Naseer, Gove...",NaN,mdv_43045_ahmed_naseer,English,CB websites
10132,http://www.mma.gov.mv/#/speeches/Speech06.html,NaN,18th SAARC Payments Council Meeting,NaN,2018-08-13,Ahmed Naseer,Governor,Male,Maldives Monetary Authority,MDV,Speech06.html GOVERNORS OPENING REMARKS 18TH S...,NaN,mdv_43325_ahmed_naseer,English,CB websites
10133,http://www.mma.gov.mv/#/speeches/Speech13.html,NaN,15th Anniversary of Amana Takaful,NaN,2019-07-14,Ali Hashim,Governor,Male,Maldives Monetary Authority,MDV,Speech13.html SPEECH BY GOVERNOR OF MMA AT 15T...,NaN,mdv_43660_ali_hashim,English,CB websites
24271,https://www.bis.org/review/r180829f.htm,https://www.bis.org/review/r180829f.pdf,The role of institutional investors in long-te...,"Keynote speech by Mr Ahmed Naseer, Governor of...",2018-05-22,Ahmed Naseer,Governor,Male,Maldives Monetary Authority,MDV,Ahmed Naseer: The role of institutional invest...,NaN,r180829f,English,BIS
24599,https://www.bis.org/review/r181224a.htm,https://www.bis.org/review/r181224a.pdf,The need to regulate virtual currency,"Keynote speech by Mr Ahmed Naseer, Governor of...",2018-11-27,Ahmed Naseer,Governor,Male,Maldives Monetary Authority,MDV,Ahmed Naseer: The need to regulate virtual cur...,NaN,r181224a,English,BIS
24603,https://www.bis.org/review/r181224e.htm,https://www.bis.org/review/r181224e.pdf,Financial inclusion within the Maldives,"Keynote speech by Mr Ahmed Naseer, Governor of...",2018-11-16,Ahmed Naseer,Governor,Male,Maldives Monetary Authority,MDV,Ahmed Naseer: Financial inclusion within the M...,NaN,r181224e,English,BIS
24891,https://www.bis.org/review/r190521g.htm,https://www.bis.org/review/r190521g.pdf,The need for increased efficiency and dynamism...,"Speech by Mr Ahmed Naseer, Governor of the Mal...",2019-02-11,Ahmed Naseer,Governor,Male,Maldives Monetary Authority,MDV,Ahmed Naseer: The need for increased efficienc...,NaN,r190521g,English,BIS
26748,https://www.bis.org/review/r211230p.htm,https://www.bis.org/review/r211230p.pdf,Current state of the Maldives' economy and out...,"Remarks by Mr Ali Hashim, Governor of the Mald...",2021-08-22,Ali Hashim,Governor,Male,Maldives Monetary Authority,MDV,Ali Hashim: Current state of the Maldives econ...,NaN,r211230p,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Maldives Monetary Authority
Central Bank of Belize

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1170,https://www.centralbank.org.bz/docs/default-so...,NaN,Charting a Monetary Policy for the 1990s.,NaN,1991-05-21,Carla Barnett,Deputy Governor,Female,Central Bank of Belize,BLZ,Address to the Ministry of Economic Developmen...,NaN,blz_charting_a_monetary_policy_for_the_1990,English,CB websites
1171,https://www.centralbank.org.bz/docs/default-so...,NaN,Welcome Address for the 49th Annual Monetary S...,NaN,2017-11-08,A. Joy Grant,Governor,Female,Central Bank of Belize,BLZ,/ CENTRAL BANK of BELIZE 49th Annual Monetary ...,NaN,blz_governor_a_joy_grant_welcome_address_for_t...,English,CB websites
1172,https://www.centralbank.org.bz/docs/default-so...,NaN,Looking Beyond the Year 2000: The Implications...,NaN,1994-03-31,Carla Barnett,Deputy Governor,Female,Central Bank of Belize,BLZ,library CENTRAL BANK OF BELIZE FIFTH ANNUAL SI...,NaN,blz_looking_beyond_the_year_2000,English,CB websites
1173,https://www.centralbank.org.bz/docs/default-so...,NaN,Perspectives on Safety and Soundness,NaN,1994-08-08,Carla Barnett,Deputy Governor,Female,Central Bank of Belize,BLZ,LIBRARY OttNTRAL BANK OF BELIZE PERSPECTIVES O...,NaN,blz_perspectives_on_safety_and_soundness,English,CB websites
1174,https://www.centralbank.org.bz/docs/default-so...,NaN,"The Global Financial Crisis, its effect on Bel...",NaN,2009-06-18,Glenford Ysaguirre,Governor,Male,Central Bank of Belize,BLZ,"The Global Financial Crisis, its effect on Bel...",NaN,blz_the_global_financial_crisis_its_effect_on_...,English,CB websites
1175,https://www.centralbank.org.bz/docs/default-so...,NaN,The Role of Regional Central Banks in the Supe...,NaN,1992-06-01,Ricardo Pelayo,Board member,Male,Central Bank of Belize,BLZ,UBRARY CENTRAL BANK OF BELIZE BELIZE The Role ...,NaN,blz_the_role_of_regional_central_banks_in_the_...,English,CB websites
18612,https://www.bis.org/review/r110623h.pdf,https://www.bis.org/review/r110623h.pdf,From the global financial crisis to more robus...,"Feature address by Mr Glenford Ysaguirre, Gove...",2011-06-16,Glenford Ysaguirre,Governor,Male,Central Bank of Belize,BLZ,Glenford Ysaguirre: From the global financial ...,NaN,r110623h,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Belize
Banque Centrale des Comores

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1929,NaN,http://www.banque-comores.km/DOCUMENTS/Discour...,Speech on the occasion of the official ceremon...,NaN,2011-12-13,Younoussa Imani,Governor,Male,Banque Centrale des Comores,COM,Speech by the Governor of the Central Bank of ...,Discours du Gouverneur de la Banque centrale d...,com_40890_younoussa_imani_french,French,CB websites
1930,NaN,http://www.banque-comores.km/DOCUMENTS/Allocut...,Reducing the costs of money transfers by migra...,NaN,2013-01-31,Younoussa Imani,Governor,Male,Banque Centrale des Comores,COM,"Restitution workshop of the study ""Reducing th...","Restitution workshop of the study ""Reducing th...",com_41305_younoussa_imani_french,French,CB websites
1931,NaN,http://www.banque-comores.km/DOCUMENTS/Discour...,Speech at the seminar on banknote authentication,NaN,2013-11-28,Younoussa Imani,Governor,Male,Banque Centrale des Comores,COM,SEMINAR ON TICKET AUTHENTICATION Address by th...,SEMINAIRE SUR LAUTHENTIFICATION DES BILLETS Al...,com_41606_younoussa_imani_french,French,CB websites
1932,NaN,http://www.banque-comores.km/DOCUMENTS/Discour...,Speech at the opening ceremony of the microfin...,NaN,2013-12-31,Younoussa Imani,Governor,Male,Banque Centrale des Comores,COM,"Ministers, Distinguished representatives of th...","Messieurs les Ministres, Mesdames et Messieurs...",com_41639_younoussa_imani_french,French,CB websites
1933,NaN,http://www.banque-comores.km/DOCUMENTS/Discour...,Speech at the official launch ceremony of the ...,NaN,2014-01-02,Younoussa Imani,Governor,Male,Banque Centrale des Comores,COM,Speech of the Governor of the Central Bank of ...,Discours du Gouverneur de la Banque Centrale d...,com_41641_younoussa_imani_french,French,CB websites
1934,NaN,http://www.banque-comores.km/DOCUMENTS/Discour...,Address on the occasion of the presentation of...,NaN,2014-02-18,Younoussa Imani,Governor,Male,Banque Centrale des Comores,COM,Ceremony of presentation of the Insignia of Of...,Crmonie de remise des Insignes dOfficier de lO...,com_41688_younoussa_imani_french,French,CB websites
1935,https://banque-comores.km/article/show/voeux-d...,NaN,New Year I Greetings from the Governor of the ...,NaN,2023-01-25,Younoussa Imani,Governor,Male,Banque Centrale des Comores,COM,New Year I New Year's greetings from the Gover...,Le Mercredi 25 Janv. 2023 11H 26 Discours Nou...,com_younoussa_imani_44951,French,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Banque Centrale des Comores
Central Bank of Montenegro

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10448,https://www.cbcg.me/en/public-relations/media/...,NaN,Speech at passing the Law on Central Bank in t...,NaN,2000-10-04,Ljubia Krgovi,Governor,Male,Central Bank of Montenegro,MNE,At passing the Law on Central Bank in the Mont...,NaN,mne_36803_ljubisa_krgovic_english,English,CB websites
10449,https://www.cbcg.me/en/public-relations/media/...,NaN,Speech at opening the money exhibition,NaN,2001-12-23,Ljubia Krgovi,Governor,Male,Central Bank of Montenegro,MNE,At opening the money exhibition on December 23...,NaN,mne_37248_ljubisa_krgovic_english,English,CB websites
10450,https://www.cbcg.me/en/public-relations/media/...,NaN,Speech at the First Anniversary of the CBM,NaN,2002-04-03,Ljubia Krgovi,Governor,Male,Central Bank of Montenegro,MNE,At the First Anniversary of the CBM 03/04/2002...,NaN,mne_37349_ljubisa_krgovic_english,English,CB websites
10451,https://www.cbcg.me/en/public-relations/media/...,https://www.cbcg.me/slike_i_fajlovi/eng/fajlov...,Key Note Speech at the Conference of Banking S...,NaN,2006-04-10,Ljubia Krgovi,Governor,Male,Central Bank of Montenegro,MNE,Key Note Speech of the President of the Counci...,NaN,mne_38817_ljubisa_krgovic_english,English,CB websites
10452,https://www.cbcg.me/en/public-relations/media/...,NaN,Speech on the international seminar The Europe...,NaN,2011-03-22,Radoje ugi,Governor,Male,Central Bank of Montenegro,MNE,Speech of the CBM Governor Radoje .ugi. on the...,NaN,mne_40624_radoje_zugic_english,English,CB websites
10453,https://www.cbcg.me/en/public-relations/media/...,NaN,Speech on the Sixth EU-SE Europe Summit entitl...,NaN,2017-05-03,Radoje ugi,Governor,Male,Central Bank of Montenegro,MNE,Speech of the CBM Governor Radoje .ugi. on the...,NaN,mne_42858_radoje_zugic_english,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Montenegro
Central Bank of Costa Rica

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2007,NaN,https://www.bccr.fi.cr/comunicacion-y-prensa/D...,Commemorative Conference of the 60th Anniversa...,NaN,2012-08-27,Rodrigo Bolaos Zamora,Governor,Male,Central Bank of Costa Rica,CRI,Presentation by Rodrigo Bolanos Zamora Preside...,Presentacin de Rodrigo Bolaos Zamora President...,cri_41148_rodrigo_bolanos_zamora_spanish,Spanish,CB websites
2008,NaN,https://www.bccr.fi.cr/comunicacion-y-prensa/D...,"The Central Bank, inflation and economic growth",NaN,2016-05-10,Olivier Castro Prez,Governor,Male,Central Bank of Costa Rica,CRI,"The Central Bank, inflation and economic growt...",E:\Trabajos\Identidad BCCR\Encabezado-comunica...,cri_42500_olivier_castro_perez_spanish,Spanish,CB websites
2009,NaN,https://www.bccr.fi.cr/comunicacion-y-prensa/D...,"Competitiveness, exchange rate, employment and...",NaN,2016-06-03,Olivier Castro Prez,Governor,Male,Central Bank of Costa Rica,CRI,"Competitiveness, exchange rate, employment and...",E:\Trabajos\Identidad BCCR\Encabezado-comunica...,cri_42524_olivier_castro_perez_spanish,Spanish,CB websites
2010,NaN,https://www.bccr.fi.cr/comunicacion-y-prensa/D...,The BCCR and the foreign exchange market,NaN,2016-06-20,Eduardo Prado Ziga,Board member,Male,Central Bank of Costa Rica,CRI,The BCCR and the foreign exchange market San J...,E:\Trabajos\Identidad BCCR\Encabezado-comunica...,cri_42541_eduardo_prado_zuniga_spanish,Spanish,CB websites
2011,NaN,https://www.bccr.fi.cr/comunicacion-y-prensa/D...,Speech at the presentation of the 2016-2017 Ma...,NaN,2016-08-03,Olivier Castro Prez,Governor,Male,Central Bank of Costa Rica,CRI,Review of the Macroeconomic Programme 2016-201...,Revisin del Programa Macroeconmico 2016-2017 S...,cri_42585_olivier_castro_perez_spanish,Spanish,CB websites
2012,NaN,https://www.bccr.fi.cr/comunicacion-y-prensa/D...,A message on the occasion of the bicentenary o...,NaN,2021-09-15,Rodrigo Cubero Brealey,Governor,Male,Central Bank of Costa Rica,CRI,of our independence Rodrigo Cubero Brealey Pre...,de nuestra independencia Rodrigo Cubero Breale...,cri_44454_rodrigo_cubero_brealey_spanish,Spanish,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Costa Rica
Central Bank of Lesotho

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9951,https://www.centralbank.org.ls/index.php/news/...,https://www.centralbank.org.ls/images/featured...,Official Launch of the Money Month Event 2017,The Deputy Governor of the Central Bank of Les...,2017-10-02,Mathabo Makenete,Deputy Governor,Female,Central Bank of Lesotho,LSO,SPEECH BY THE DEPUTY GOVERNOR OF THE CENTRAL B...,NaN,lso_2017_10_02_makenete,English,CB websites
9952,https://www.centralbank.org.ls/index.php/news/...,https://www.centralbank.org.ls/images/Public_A...,The Lesotho Money Month Campaign Launched,The Lesotho Money Month event was officially l...,2018-10-01,Mathabo Makenete,Deputy Governor,Female,Central Bank of Lesotho,LSO,GREETINGS 1. I am pleased to welcome you all t...,NaN,lso_2018_10_01_makenete,English,CB websites
9953,https://www.centralbank.org.ls/index.php/news/...,https://www.centralbank.org.ls/images/Public_A...,RNB Properties Ltd becomes the first company t...,Speech by the Governor of the CentralCank of L...,2021-12-06,Retselisitsoe Matlanyane,Governor,Female,Central Bank of Lesotho,LSO,Good morning 1. I feel honoured and privileged...,NaN,lso_2021_12_06_matlanyane,English,CB websites
9954,https://www.centralbank.org.ls/index.php/news/...,https://www.centralbank.org.ls/images/Public_A...,CBL donates 40 tablets to children with disabi...,It is a great pleasure and honour to be here f...,2021-12-28,Retselisitsoe Matlanyane,Governor,Female,Central Bank of Lesotho,LSO,REMARKS BY THE GOVERNOR OF THE CENTRAL BANK OF...,NaN,lso_2021_12_28_matlanyane,English,CB websites
9955,https://www.centralbank.org.ls/images/Public_A...,https://www.centralbank.org.ls/images/Public_A...,Speech by the Governor of the Central Bank of ...,NaN,2023-07-13,Dr. E. M. Letete,Governor,Male,Central Bank of Lesotho,LSO,SPEECH BY THE GOVERNOR OF THE CENTRAL BANK OF ...,NaN,lso_em_letete_13072023,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Lesotho
Qatar Central Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12450,http://www.qcb.gov.qa/English/Publications/Spe...,NaN,Address to theMinister of Foreign Affairs Egmo...,NaN,2009-05-15,Abdulla bin Mohammed bin Saud Al Thani,Governor,Male,Qatar Central Bank,QAT,Address of H.E. The Prime Minister Minister of...,NaN,qat_39948_abdulla_bin_mohammed_bin_saud_al_thani,English,CB websites
12451,http://www.qcb.gov.qa/English/Publications/Rep...,NaN,Address welcoming the Irish delegation at the ...,NaN,2010-12-09,Abdulla bin Mohammed bin Saud Al Thani,Governor,Male,Qatar Central Bank,QAT,"In the Name of God, Most Gracious, Most Mercif...",NaN,qat_40521_abdulla_bin_mohammed_bin_saud_al_thani,English,CB websites
12452,http://www.qcb.gov.qa/English/Publications/Spe...,NaN,Address to the Islamic Financial Stability Forum,NaN,2013-12-10,Abdulla bin Mohammed bin Saud Al Thani,Governor,Male,Qatar Central Bank,QAT,Islamic Financial Stability Forum Speech Thank...,NaN,qat_41618_abdulla_bin_mohammed_bin_saud_al_thani,English,CB websites
12453,http://www.qcb.gov.qa/English/Publications/Spe...,NaN,"Speech at the Carnegie Mellon University, Qatar",NaN,2016-11-14,Abdulla bin Mohammed bin Saud Al Thani,Governor,Male,Qatar Central Bank,QAT,Speech by H.E The Governor of Qatar Central Ba...,NaN,qat_42688_abdulla_bin_mohammed_bin_saud_al_thani,English,CB websites
12454,NaN,https://web.archive.org/web/20220805174329/htt...,Speech of His Excellency Sheikh Bandar bin Sau...,NaN,2022-05-29,Sheikh Bandar bin Saud Al Thani,Governor,Male,Qatar Central Bank,QAT,Kalima Usually you Yakhbandarbn Mohammed Bin S...,292022 ...,qat_sheikh_bandar_bin_saud_al_thani_29052022,Arabic,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Qatar Central Bank
Central Bank of Liberia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
9941,https://www.cbl.org.lr/media/press-releases/sp...,NaN,Speech at Launch of the National Financial Inc...,NaN,2019-12-18,Musa Dukuly,Deputy Governor,Male,Central Bank of Liberia,LBR,(/) Central Bank of Liberia (/) I take this op...,NaN,lbr_20191218_musa_dukuly,English,CB websites
9942,https://www.cbl.org.lr/index.php/media/press-r...,NaN,Second Batch of New L$100 Arrives,NaN,2022-02-09,"J. Aloysius Tarlue, Jr",Governor,Male,Central Bank of Liberia,LBR,Central Bank of Liberia (/) Second Batch of Ne...,NaN,lbr_j_aloysius_tarlue_jr_44601,English,CB websites
9943,https://www.cbl.org.lr/index.php/media/press-r...,NaN,"CBL, Commercial Banks Sign Memorandum of Under...",NaN,2022-02-16,"J. Aloysius Tarlue, Jr",Governor,Male,Central Bank of Liberia,LBR,"(/) Central Bank of Liberia (/) CBL, Commercia...",NaN,lbr_j_aloysius_tarlue_jr_44608,English,CB websites
9944,https://www.cbl.org.lr/index.php/media/press-r...,NaN,"Encouraged by Prospects of Economic Growth, CB...",NaN,2022-03-16,"J. Aloysius Tarlue, Jr",Governor,Male,Central Bank of Liberia,LBR,Central Bank of Liberia (/) Encouraged by Pros...,NaN,lbr_j_aloysius_tarlue_jr_44636,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Liberia
Bank of Guyana

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7211,NaN,https://bankofguyana.org.gy/bog/images/communi...,Launch of the 50th Republic Anniversary Coin,NaN,2020-06-15,Gobind Ganga,Governor,Male,Bank of Guyana,GUY,BANK OF GUYANA GOVERNORS PRESS CONFERENCE LAUN...,NaN,guy_guyana_2020,English,CB websites
19329,https://www.bis.org/review/r120601a.pdf,https://www.bis.org/review/r120601a.pdf,An evolving financial services landscape in th...,"Welcome remarks by Mr Lawrence Williams, Gover...",2012-05-24,Lawrence Williams,Governor,Male,Bank of Guyana,GUY,Lawrence Williams: An evolving financial servi...,NaN,r120601a,English,BIS
19352,https://www.bis.org/review/r120612j.pdf,https://www.bis.org/review/r120612j.pdf,Leveraging central banks' IT investments for s...,"Opening remarks by Mr Lawrence Williams, Gover...",2012-06-04,Lawrence Williams,Governor,Male,Bank of Guyana,GUY,Lawrence Williams: Leveraging central banks IT...,NaN,r120612j,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Guyana
Banco Central de Reserva De El Salvador

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
29632,https://www.bcr.gob.sv/documental/,NaN,"Opening Speech at the Seminar ""Impact of Remit...",NaN,2007-05-01,Luz Mara de Portillo,Governor,Female,Banco Central de Reserva De El Salvador,SLV,"Opening speech of the seminar ""Impact of Remit...",Discurso de apertura de seminario Impacto de l...,slv_discurso_de_apertura_de_seminario,Spanish,CB websites
29633,https://www.bcr.gob.sv/documental/,NaN,Speech at Redibacen Conference,NaN,2019-03-27,Oscar Cabrera,Governor,Male,Banco Central de Reserva De El Salvador,SLV,"OPENING SPEECH OF REDIBACEN CONFERENCE ""ANALYS...",DISCURSO INAUGURACIN DE CONFERENCIA REDIBACEN ...,slv_discurso_del_presidente_bcr_dr_oscar_cabre...,Spanish,CB websites
29634,https://www.bcr.gob.sv/documental/,NaN,Speech at the Signing of the Regional Treaty o...,NaN,2007-04-01,Laura Ayala de Flores,Senior management,Female,Banco Central de Reserva De El Salvador,SLV,Speech for the signing of the Regional Treaty ...,Discurso por la firma del Tratado Regional de ...,slv_discurso_por_la_firma_del_tratado_regional...,Spanish,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Banco Central de Reserva De El Salvador
Cayman Islands Monetary Authority

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
14385,https://www.bis.org/review/r050815e.pdf,https://www.bis.org/review/r050815e.pdf,Look forward briefing - 2005/2006,"Remarks by Mr Timothy Ridley, Chairman of the ...",2005-07-20,Timothy Ridley,Governor,Male,Cayman Islands Monetary Authority,CYM,Timothy Ridley: Look forward briefing - 2005/2...,NaN,r050815e,English,BIS
15107,https://www.bis.org/review/r061113e.pdf,https://www.bis.org/review/r061113e.pdf,Reading the tea leaves whither the private tr...,"Remarks by Mr Timothy Ridley, Chairman of the ...",2006-10-25,Timothy Ridley,Governor,Male,Cayman Islands Monetary Authority,CYM,Timothy Ridley: Reading the tea leaves whithe...,NaN,r061113e,English,BIS
15572,https://www.bis.org/review/r070627f.pdf,https://www.bis.org/review/r070627f.pdf,What makes the Cayman Islands a successful int...,"Background paper by Mr Timothy Ridley, Chairma...",2007-06-12,Timothy Ridley,Governor,Male,Cayman Islands Monetary Authority,CYM,Timothy Ridley: What makes the Cayman Islands ...,NaN,r070627f,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Cayman Islands Monetary Authority
Bank of the Republic of Burundi

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
614,NaN,https://www.brb.bi/sites/default/files/Discour...,Speech at the opening of the conference on dev...,NaN,2021-08-20,Dieudonn Murengerantwari,Governor,Male,Bank of the Republic of Burundi,BDI,Speech of the Governor of the BRB at the Confe...,Discours de Monsieur le Gouverneur de la BRB ...,bdi_2021_08_20_murengerantwari,French,CB websites
615,https://www.brb.bi/sites/default/files/Opening...,https://www.brb.bi/sites/default/files/Opening...,"Opening speech of the Governor, Dieudonn MUREN...",NaN,2023-03-17,Dieudonn Murengerantwari,Governor,Male,Bank of the Republic of Burundi,BDI,"P.O. Box 1096 ARUSHA, TANZANIA Tel: 255-27-216...",NaN,bdi_45002,English,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of the Republic of Burundi
Reserve Bank of Vanuatu

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
14976,https://www.bis.org/review/r060911e.pdf,https://www.bis.org/review/r060911e.pdf,Overview of the Vanuatu economic performance,"Presentation by Mr Peter Tari, Deputy Governor...",2006-06-07,Peter Tari,Deputy Governor,Male,Reserve Bank of Vanuatu,VUT,Peter Tari: Overview of the Vanuatu economic p...,NaN,r060911e,English,BIS
19870,https://www.bis.org/review/r130124c.pdf,https://www.bis.org/review/r130124c.pdf,Financial inclusion in Vanuatu,"Keynote address by Mr Odo Tevi, Governor of th...",2012-08-09,Odo Tevi,Governor,Male,Reserve Bank of Vanuatu,VUT,Odo Tevi: Financial inclusion in Vanuatu Keyno...,NaN,r130124c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Reserve Bank of Vanuatu
Bank of Tanzania

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
20677,https://www.bis.org/review/r131217f.pdf,https://www.bis.org/review/r131217f.pdf,Addressing the challenges of financial inclusi...,"Welcome and opening remarks by Mr Benno Ndulu,...",2013-12-12,Benno Ndulu,Governor,Male,Bank of Tanzania,TZA,Benno Ndulu: Addressing the challenges of fina...,NaN,r131217f,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Tanzania
Central Bank of Gambia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
14947,https://www.bis.org/review/r060830d.pdf,https://www.bis.org/review/r060830d.pdf,Human resource management for economic develop...,"Keynote address by Mr Famara L Jatta, Governor...",2006-07-24,Famara L Jatta,Governor,Male,Central Bank of Gambia,GMB,Famara L Jatta: Human resource management for ...,NaN,r060830d,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Tanzania', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Gambia
Bank of Guatemala

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
19193,https://www.bis.org/review/r120328b.pdf,https://www.bis.org/review/r120328b.pdf,Recent economic trends and policy issues,"Presentation by Mr Edgar Barqun, President of ...",2012-03-17,Edgar Barqun,Governor,Male,Bank of Guatemala,GTM,Edgar Barquin: Recent economic trends and poli...,NaN,r120328b,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Tanzania', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Gambia', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Bank of Guatemala
Banque Centrale de Mauritanie

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
10527,https://www.bcm.mr/m-le-gouverneur-nous-sommes...,NaN,"We are invited, particularly in our developing...",NaN,2019-11-04,Abdel Aziz Ould Dahi,Governor,Male,Banque Centrale de Mauritanie,MRT,"MR. GOVERNOR: WE ARE INVITED, PARTICULARLY IN ...","M. LE GOUVERNEUR : NOUS SOMMES INVIT<83>S, PAR...",mrt_2019_11_04_governor_french,French,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guatemala', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Tanzania', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Gambia', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Banque Centrale de Mauritanie
Central Bank of Bolivia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
18042,https://www.bis.org/review/r101022d.pdf,https://www.bis.org/review/r101022d.pdf,The role of central banks in macroprudential r...,"Opening remarks by Mr Gabriel Loza Telleria, A...",2010-09-29,Gabriel Loza Telleria,Governor,Male,Central Bank of Bolivia,BOL,Gabriel Loza Telleria: The role of central ban...,NaN,r101022d,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guatemala', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Tanzania', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale de Mauritanie', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Gambia', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Bolivia
Central Bank of Jordan

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
17967,https://www.bis.org/review/r100922c.pdf,https://www.bis.org/review/r100922c.pdf,The international monetary system - too big to...,"Speech by Mr Umayya Toukan, Governor of the Ce...",2010-08-28,Umayya Toukan,Governor,Male,Central Bank of Jordan,JOR,Umayya Toukan: The international monetary syst...,NaN,r100922c,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guatemala', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Tanzania', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale de Mauritanie', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bolivia', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Gambia', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Jordan
Central Bank of Ecuador

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
14128,https://www.bis.org/review/r050314h.pdf,https://www.bis.org/review/r050314h.pdf,Overview of activities undertaken by the Centr...,"Speech by Mr Polibio Cordoba, President of the...",2005-02-17,Polibio Cordoba,Governor,Male,Central Bank of Ecuador,ECU,Polibio Cordoba: Overview of activities undert...,NaN,r050314h,English,BIS

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guatemala', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Tanzania', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale de Mauritanie', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bolivia', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Eswatini', 'Central Bank of Gambia', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Jordan', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Central Bank of Ecuador
Banco Central de Venezuela

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
34924,NaN,https://www.bcv.org.ve/discurso-del-presidente...,Speech during the G-24 Ministers' Meeting,NaN,1998-04-15,Antonio Casas Gonzalez,Governor,Male,Banco Central de Venezuela,VEN,SPEECH BY PRESIDENT ANTONIO CASAS GONZALEZ DUR...,http://www.finanzasdigital.com/wp-content/uplo...,ven_1998_casas_gonzalez_spanish,Spanish,CB websites

['Austrian National Bank', 'Banco Central de Nicaragua', 'Banco Central de Reserva De El Salvador', 'Banco Central del Paraguay', 'Bangladesh Bank', 'Bank Al-Maghrib', 'Bank Indonesia', 'Bank of Albania', 'Bank of Algeria', 'Bank of Botswana', 'Bank of Cabo Verde', 'Bank of Canada', 'Bank of England', 'Bank of Estonia', 'Bank of Finland', 'Bank of France', 'Bank of Ghana', 'Bank of Greece', 'Bank of Guatemala', 'Bank of Guyana', 'Bank of Israel', 'Bank of Italy', 'Bank of Jamaica', 'Bank of Japan', 'Bank of Korea', 'Bank of Latvia', 'Bank of Lithuania', 'Bank of Mauritius', 'Bank of Mexico', 'Bank of Mozambique', 'Bank of Namibia', 'Bank of Papua New Guinea', 'Bank of Portugal', 'Bank of Russia', 'Bank of Sierra Leone', 'Bank of Slovenia', 'Bank of Spain', 'Bank of Tanzania', 'Bank of Thailand', 'Bank of the Republic of Burundi', 'Bank of the Republic, Colombia', 'Bank of Uganda', 'Bank of Zambia', 'Banque Centrale de Mauritanie', 'Banque Centrale des Comores', "Banque de la Rpublique d'Hati", 'Board of Governors of the Federal Reserve', 'Bulgarian National Bank', 'Cayman Islands Monetary Authority', 'Central Bank of Argentina', 'Central Bank of Armenia', 'Central Bank of Aruba', 'Central Bank of Bahrain', 'Central Bank of Barbados', 'Central Bank of Belize', 'Central Bank of Bolivia', 'Central Bank of Bosnia and Herzegovina', 'Central Bank of Brazil', 'Central Bank of Chile', 'Central Bank of Costa Rica', 'Central Bank of Curaao and Sint Maarten', 'Central Bank of Cyprus', 'Central Bank of Ecuador', 'Central Bank of Eswatini', 'Central Bank of Gambia', 'Central Bank of Hungary', 'Central Bank of Iceland', 'Central Bank of Ireland', 'Central Bank of Jordan', 'Central Bank of Kenya', 'Central Bank of Kuwait', 'Central Bank of Lesotho', 'Central Bank of Liberia', 'Central Bank of Luxembourg', 'Central Bank of Malaysia', 'Central Bank of Malta', 'Central Bank of Montenegro', 'Central Bank of Nepal', 'Central Bank of Nigeria', 'Central Bank of Samoa', 'Central Bank of Seychelles', 'Central Bank of So Tom and Prncipe', 'Central Bank of Solomon Islands', 'Central Bank of Sri Lanka', 'Central Bank of Suriname', 'Central Bank of The Bahamas', 'Central Bank of the Dominican Republic', 'Central Bank of the Philippines', 'Central Bank of the Republic of Kosovo', 'Central Bank of the Republic of Turkey', 'Central Bank of the United Arab Emirates', 'Central Bank of Trinidad and Tobago', 'Central Bank of Uruguay', 'Croatian National Bank', 'Czech National Bank', 'De Nederlandsche Bank', 'Deutsche Bundesbank', 'Eastern Caribbean Central Bank', 'European Central Bank', 'Federal Reserve Bank of Atlanta', 'Federal Reserve Bank of Boston', 'Federal Reserve Bank of Chicago', 'Federal Reserve Bank of Cleveland', 'Federal Reserve Bank of Dallas', 'Federal Reserve Bank of Kansas City', 'Federal Reserve Bank of Minneapolis', 'Federal Reserve Bank of New York', 'Federal Reserve Bank of Philadelphia', 'Federal Reserve Bank of Richmond', 'Federal Reserve Bank of San Francisco', 'Federal Reserve Bank of St Louis', 'Hong Kong Monetary Authority', 'Maldives Monetary Authority', 'Monetary Authority of Macao', 'Monetary Authority of Singapore', 'National Bank of Angola', 'National Bank of Belgium', 'National Bank of Cambodia', 'National Bank of Denmark', 'National Bank of Kazakhstan', 'National Bank of Poland', 'National Bank of Romania', 'National Bank of Rwanda', 'National Bank of Serbia', 'National Bank of Slovakia', 'National Bank of the Republic of North Macedonia', 'National Bank of Ukraine', 'Norges Bank', "People's Bank of China", 'Qatar Central Bank', 'Reserve Bank of Australia', 'Reserve Bank of Fiji', 'Reserve Bank of India', 'Reserve Bank of Malawi', 'Reserve Bank of New Zealand', 'Reserve Bank of Vanuatu', 'Reserve Bank of Zimbabwe', 'Saudi Central Bank', 'South African Reserve Bank', 'State Bank of Pakistan', 'Sveriges Riksbank', 'Swiss National Bank']
creating ../Data/Speeches/speeches_by_central_bank/Banco Central de Venezuela

In [30]:
df_original = pd.read_csv('../Data/Speeches/cleaned_speeches.csv', sep='\t')

In [31]:
df_original.groupby('speechID')#['nWords'].sum().astype(float).describe()  # 1200 speeches, average 5900 words, median 4400

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
0,1,developments-in-uk-financial-markets,1,Developments in UK financial markets Speech gi...,43,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
1,1,developments-in-uk-financial-markets,2,"""The UKs new monetary framework Perhaps the si...",146,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
2,1,developments-in-uk-financial-markets,3,The framework put in place with that announcem...,33,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
3,1,developments-in-uk-financial-markets,4,"""First, the target the Bank of England is to p...",79,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
4,1,developments-in-uk-financial-markets,5,"""Secondly, it is then the responsibility of th...",120,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88401,1495,cost-of-capital-and-uk-business-investment-sli...,17,Sales surprises and the marginal propensity to...,149,False,False,False,2024-05-17,CATHERINE L MANN,True,False,False
88402,1503,remarks-given-by-swati-dhingra-at-econdat-2024...,10,Bank of England Page 12 Appendix Chart 8: Cent...,44,False,False,False,2024-05-10,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False