In [1]:
import pandas as pd

initial import

In [31]:
pd.read_csv('../Data/Speeches/cleaned_speeches.csv',sep='\t')

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
0,1,developments-in-uk-financial-markets,1,Developments in UK financial markets Speech gi...,43,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
1,1,developments-in-uk-financial-markets,2,"""The UKs new monetary framework Perhaps the si...",146,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
2,1,developments-in-uk-financial-markets,3,The framework put in place with that announcem...,33,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
3,1,developments-in-uk-financial-markets,4,"""First, the target the Bank of England is to p...",79,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
4,1,developments-in-uk-financial-markets,5,"""Secondly, it is then the responsibility of th...",120,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88401,1495,cost-of-capital-and-uk-business-investment-sli...,17,Sales surprises and the marginal propensity to...,149,False,False,False,2024-05-17,CATHERINE L MANN,True,False,False
88402,1503,remarks-given-by-swati-dhingra-at-econdat-2024...,10,Bank of England Page 12 Appendix Chart 8: Cent...,44,False,False,False,2024-05-10,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False

descriptive stats

In [32]:
df= pd.read_csv('../Data/Speeches/cleaned_speeches.csv',sep='\t')

In [33]:
df.speechID.value_counts() # 912 speeches of varying number of paragraphs

speechID
976     557
919     442
273     392
292     375
970     365
       ...
1416      1
1511      1
1359      1
1503      1
1330      1
Name: count, Length: 1202, dtype: int64

In [34]:
df

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
0,1,developments-in-uk-financial-markets,1,Developments in UK financial markets Speech gi...,43,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
1,1,developments-in-uk-financial-markets,2,"""The UKs new monetary framework Perhaps the si...",146,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
2,1,developments-in-uk-financial-markets,3,The framework put in place with that announcem...,33,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
3,1,developments-in-uk-financial-markets,4,"""First, the target the Bank of England is to p...",79,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
4,1,developments-in-uk-financial-markets,5,"""Secondly, it is then the responsibility of th...",120,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88401,1495,cost-of-capital-and-uk-business-investment-sli...,17,Sales surprises and the marginal propensity to...,149,False,False,False,2024-05-17,CATHERINE L MANN,True,False,False
88402,1503,remarks-given-by-swati-dhingra-at-econdat-2024...,10,Bank of England Page 12 Appendix Chart 8: Cent...,44,False,False,False,2024-05-10,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False

In [35]:
df.groupby('speechID')['nWords'].sum().astype(float).describe() # 1200 speeches, average 5900 words, median 4400

count      1202.000000
mean       5971.695507
std        6161.393909
min           2.000000
25%        2675.250000
50%        4411.500000
75%        7323.000000
max      107165.000000
Name: nWords, dtype: float64

In [36]:
df['para']

0        Developments in UK financial markets Speech gi...
1        "The UKs new monetary framework Perhaps the si...
2        The framework put in place with that announcem...
3        "First, the target the Bank of England is to p...
4        "Secondly, it is then the responsibility of th...
                               ...
88401    Sales surprises and the marginal propensity to...
88402    Bank of England Page 12 Appendix Chart 8: Cent...
88403    Analytical Toolkit Fools Gold: refinements to ...
88404    Analytical Toolkit Fools Gold: forecast refine...
88405    Research design to understand mechanisms Granu...
Name: para, Length: 88406, dtype: object

In [40]:
df[df['speechID'] == 5].sort_values('para')

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
206,5,the-inflation-target-five-years-on,70,"""(ii) The Inflation Report will continue, ...",117,True,False,False,1997-10-29,MERVYN KING,True,False,False
207,5,the-inflation-target-five-years-on,71,"""(iii) Appearances before the Treasury Sele...",65,True,False,False,1997-10-29,MERVYN KING,True,False,False
209,5,the-inflation-target-five-years-on,73,"""(iv) The MPC is required to send an open ...",163,True,False,False,1997-10-29,MERVYN KING,True,False,False
210,5,the-inflation-target-five-years-on,74,"""(v) Finally, the MPC is accountable to t...",61,True,False,False,1997-10-29,MERVYN KING,True,False,False
242,5,the-inflation-target-five-years-on,106,"""* Inflation is measured as the annual increas...",27,False,False,False,1997-10-29,MERVYN KING,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,5,the-inflation-target-five-years-on,65,Transparency is desirable because it improves ...,24,True,False,False,1997-10-29,MERVYN KING,True,False,False
221,5,the-inflation-target-five-years-on,85,What has been the experience of countries with...,10,False,False,False,1997-10-29,MERVYN KING,True,False,False
223,5,the-inflation-target-five-years-on,87,What is the role of inflation forecasts?,7,False,False,False,1997-10-29,MERVYN KING,True,False,False
224,5,the-inflation-target-five-years-on,88,Why is openness and transparency important?,6,False,False,False,1997-10-29,MERVYN KING,True,False,False
238,5,the-inflation-target-five-years-on,102,percent 10.0,2,False,False,False,1997-10-29,MERVYN KING,True,False,False

In [41]:
df[['because' in i and 'inflation' in i for i in df['para']]]#['para'].values

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
176,5,the-inflation-target-five-years-on,40,"""Many supply shocks are price level effects. F...",206,True,False,False,1997-10-29,MERVYN KING,True,False,False
389,9,economic-policy-with-and-without-forecasts,22,"""We have tried to interest universities in thi...",1081,False,False,False,1998-05-14,ALAN BUDD,True,False,False
439,10,edward-george-institute-of-directors,35,"""Now there are those - perhaps even one or two...",88,False,False,False,1998-11-19,EDDIE GEORGE,True,False,False
461,12,edward-george-tuc-congression,2,"""Let me start with what is perhaps your bigges...",133,False,False,False,1998-09-15,EDDIE GEORGE,True,False,False
469,12,edward-george-tuc-congression,10,"""But, even if we agree on the objective, that ...",145,False,False,False,1998-09-15,EDDIE GEORGE,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88268,1378,monetary-policy-with-a-steady-hand-speech-by-h...,13,Retaining flexibility is important. And given ...,327,False,False,False,2022-02-09,HUW PILL,True,False,False
88280,1388,on-returning-inflation-back-to-target-speech-b...,4,It is often said that monetary policy should l...,533,False,False,False,2022-01-21,CATHERINE L MANN,True,False,False
88305,1395,the-state-of-financial-stability-speech-by-jon...,3,"Such corrections happen every day, of course. ...",428,False,False,False,2022-03-02,JON CUNLIFFE,True,True,True
88312,1395,the-state-of-financial-stability-speech-by-jon...,10,"To be clear, a period of adjustment to bring t...",498,False,False,False,2022-03-02,JON CUNLIFFE,True,True,True
88370,1494,climate-change-the-macroeconomy-and-monetary-p...,11,Inflation Impacts what does the literature say...,109,False,False,False,2024-04-25,ANDREW BAILEY,True,True,True

In [39]:
df.date= pd.to_datetime(df.date, format='%Y-%m-%d')
df.sort_values('date')

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
69,3,edward-george-queen-elizabeth-conference-centre,1,"""Speech by the Governor at the Queen Elizabeth...",128,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
92,3,edward-george-queen-elizabeth-conference-centre,24,"""And I conclude, thirdly, that there remains s...",34,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
91,3,edward-george-queen-elizabeth-conference-centre,23,"""I conclude, secondly, that the markets see cu...",30,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
90,3,edward-george-queen-elizabeth-conference-centre,22,"""I conclude, first, that markets at present ar...",79,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
89,3,edward-george-queen-elizabeth-conference-centre,21,"""What can we conclude from all this, Mr Chairm...",22,False,False,False,1997-02-25,EDDIE GEORGE,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88389,1507,speech-slides-by-jonathan-haskel-on-uk-inflati...,2,"1. Some questions about inflation, uncertainty...",28,False,False,False,2024-07-08,JONATHAN HASKEL,True,False,False
88395,1511,uk-inflation-whats-done-and-whats-to-come-spee...,25,Bank of England Page 29 Price inflation CPI pu...,844,False,False,False,2024-07-08,JONATHAN HASKEL,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False

In [1]:
df = pd.read_csv(r"C:\Users\339306\Downloads\CBS_dataset_v1.0.csv",nrows = 100)

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\339306\Downloads\CBS_dataset_v1.0.csv")

In [7]:
df['Language'].value_counts()

Language
English             30140
Spanish               834
German                698
Italian               612
Portuguese            537
French                361
Albanian              333
Finnish               312
Swedish               231
Dutch                 222
Thai                  201
Greek                  84
Icelandic              82
Norwegian              81
Chinese                78
Turkish                74
Indonesian             67
Bulgarian              63
Korean                 59
Croatian               57
Macedonian             56
Hebrew                 44
Danish                 42
Russian                35
Lithuanian             34
Slovak                 30
Arabic                 22
Czech                  16
Kazakh                 14
Armenian               14
Slovenian              13
Creole                 12
Polish                  9
Khmer                   6
French and Dutch        5
Bosnian                 3
Nepali                  2
Filipino                2
Samoan                  2
Name: count, dtype: int64

In [11]:
df[df['Language']=='English']['CentralBank'].value_counts()

CentralBank
Board of Governors of the Federal Reserve    2658
European Central Bank                        2522
Bank of England                              1354
Reserve Bank of India                        1071
Central Bank of the Philippines               990
                                             ...
Central Bank of Bolivia                         1
Central Bank of Jordan                          1
Bank of the Republic of Burundi                 1
Central Bank of Ecuador                         1
Central Bank of Uruguay                         1
Name: count, Length: 132, dtype: int64

In [13]:
pd.to_datetime(df['Date']).min(),pd.to_datetime(df['Date']).max()

(Timestamp('1986-01-06 00:00:00'), Timestamp('2023-12-29 00:00:00'))

In [18]:
print(df[df['Language']=='English'][['text','Date']].iloc[-1])

text    Speeches\n\nBeyond Short-Term Interests\n\nJac...
Date                                           2003-11-21
Name: 35486, dtype: object

In [19]:
import os

In [20]:
os.listdir("../Data/Speeches/")

['cleaned_speeches.csv', 'speechContent.txt', 'speechMetadata.csv']

In [41]:
for i in df[df['Language']=='English']['CentralBank'].value_counts().iloc[0:50].reset_index().iterrows():
    print(i)
    #print(df[df['Language']=='English'][df['CentralBank']==i]['text'].values[0][:100])
    print('\n')

(0, CentralBank    Board of Governors of the Federal Reserve
count                                               2658
Name: 0, dtype: object)


(1, CentralBank    European Central Bank
count                           2522
Name: 1, dtype: object)


(2, CentralBank    Bank of England
count                     1354
Name: 2, dtype: object)


(3, CentralBank    Reserve Bank of India
count                           1071
Name: 3, dtype: object)


(4, CentralBank    Central Bank of the Philippines
count                                      990
Name: 4, dtype: object)


(5, CentralBank    Monetary Authority of Singapore
count                                      914
Name: 5, dtype: object)


(6, CentralBank    Deutsche Bundesbank
count                          903
Name: 6, dtype: object)


(7, CentralBank    Bank of Japan
count                    826
Name: 7, dtype: object)


(8, CentralBank    Central Bank of Ireland
count                              728
Name: 8, dtype: object)


(9, CentralBank    Central Bank of Malaysia
count                               699
Name: 9, dtype: object)


(10, CentralBank    Reserve Bank of Australia
count                                641
Name: 10, dtype: object)


(11, CentralBank    Bank of Canada
count                     640
Name: 11, dtype: object)


(12, CentralBank    Federal Reserve Bank of New York
count                                       614
Name: 12, dtype: object)


(13, CentralBank    Sveriges Riksbank
count                        532
Name: 13, dtype: object)


(14, CentralBank    Federal Reserve Bank of Atlanta
count                                      527
Name: 14, dtype: object)


(15, CentralBank    Swiss National Bank
count                          493
Name: 15, dtype: object)


(16, CentralBank    South African Reserve Bank
count                                 453
Name: 16, dtype: object)


(17, CentralBank    Federal Reserve Bank of San Francisco
count                                            449
Name: 17, dtype: object)


(18, CentralBank    Bank of France
count                     435
Name: 18, dtype: object)


(19, CentralBank    Hong Kong Monetary Authority
count                                   434
Name: 19, dtype: object)


(20, CentralBank    Bank of Italy
count                    428
Name: 20, dtype: object)


(21, CentralBank    Bank of Spain
count                    419
Name: 21, dtype: object)


(22, CentralBank    Federal Reserve Bank of Chicago
count                                      418
Name: 22, dtype: object)


(23, CentralBank    Bank of Uganda
count                     365
Name: 23, dtype: object)


(24, CentralBank    Federal Reserve Bank of Cleveland
count                                        353
Name: 24, dtype: object)


(25, CentralBank    Norges Bank
count                  308
Name: 25, dtype: object)


(26, CentralBank    Bank of Albania
count                      299
Name: 26, dtype: object)


(27, CentralBank    Bank of Thailand
count                       291
Name: 27, dtype: object)


(28, CentralBank    De Nederlandsche Bank
count                            283
Name: 28, dtype: object)


(29, CentralBank    Federal Reserve Bank of Philadelphia
count                                           282
Name: 29, dtype: object)


(30, CentralBank    Bank of Finland
count                      282
Name: 30, dtype: object)


(31, CentralBank    Central Bank of Kenya
count                            275
Name: 31, dtype: object)


(32, CentralBank    State Bank of Pakistan
count                             267
Name: 32, dtype: object)


(33, CentralBank    Federal Reserve Bank of Richmond
count                                       266
Name: 33, dtype: object)


(34, CentralBank    Central Bank of Hungary
count                              263
Name: 34, dtype: object)


(35, CentralBank    Bangladesh Bank
count                      254
Name: 35, dtype: object)


(36, CentralBank    Federal Reserve Bank of St Louis
count                                       252
Name: 36, dtype: object)


(37, CentralBank    Reserve Bank of New Zealand
count                                  252
Name: 37, dtype: object)


(38, CentralBank    Federal Reserve Bank of Boston
count                                     231
Name: 38, dtype: object)


(39, CentralBank    Federal Reserve Bank of Dallas
count                                     230
Name: 39, dtype: object)


(40, CentralBank    Bank of Mauritius
count                        228
Name: 40, dtype: object)


(41, CentralBank    People's Bank of China
count                             221
Name: 41, dtype: object)


(42, CentralBank    Bulgarian National Bank
count                              201
Name: 42, dtype: object)


(43, CentralBank    Bank of Greece
count                     198
Name: 43, dtype: object)


(44, CentralBank    Central Bank of the Republic of Turkey
count                                             197
Name: 44, dtype: object)


(45, CentralBank    Bank of Zambia
count                     196
Name: 45, dtype: object)


(46, CentralBank    Bank of Portugal
count                       185
Name: 46, dtype: object)


(47, CentralBank    National Bank of Serbia
count                              173
Name: 47, dtype: object)


(48, CentralBank    Federal Reserve Bank of Kansas City
count                                          170
Name: 48, dtype: object)


(49, CentralBank    Reserve Bank of Fiji
count                           169
Name: 49, dtype: object)

In [40]:
df.iloc[-1]

URL              https://fraser.stlouisfed.org/title/statements...
PDF              https://fraser.stlouisfed.org/files/docs/histo...
Title            Beyond Short-Term Interests : Atlanta Regional...
Subtitle                                                       NaN
Date                                                    2003-11-21
Authorname                                              Jack Guynn
Role                                                      Governor
Gender                                                        Male
CentralBank                        Federal Reserve Bank of Atlanta
Country                                                        USA
text             Speeches\n\nBeyond Short-Term Interests\n\nJac...
text_original                                                  NaN
Filename                        beyond-short-term-interests-521702
Language                                                   English
Source                                                    Archives
Name: 35486, dtype: object

In [36]:
for i in df[(df['Language']=='English') & (df['CentralBank']=='Bank of England')].sort_values('Date').sort_values('Date').iloc[-1]['text'].split('.'):
    print(i)

Bank of England Page 1 Monetary policy as engineering? - soeech by Sarah Breeden Given at the Institute of International Finance's Talking Policy Series 19 December 2023 Bank of England Page 2 Speech 1
 This is my first speech as a Deputy Governor and member of the Monetary Policy Committee (MPC) at the Bank of England
 I am going to use the speech to describe my approach to monetary policy and how I am applying it to the situation the MPC currently finds itself in
 I can think of few better places to do so than a 'Talking Policy' seminar, and I am very grateful to have been invited along to speak to you all today
 2
 I will focus on a few important questions
 Where is the economy now? How did we get here? What could happen next? What does that mean for my approach to monetary policymaking? And finally, why is that approach the right thing for the economy? Where is the economy now? 3
 Monetary policymakers like to talk about uncertainty
 But it is fair to say that working out what the state of the UK economy is and where it's heading is especially uncertain at the moment
 There are measurement issues?, volatility in the data and exceptionally large data revisions
* The bottom line is that it is more difficult to extract a clear signal from the noise
* That said, I will start by briefly painting a picture of what I think is happening in the economy in general terms
 4
 First, economic activity has been practically flat since the end of 2022
 That is of course stronger than the MPC and other forecasters expected this time last year, in part because of the adjustment to energy supply headwinds and the steep fall in energy prices since then
 But in historical terms it is very weak
 GDP has grown by about 0
5% over the past year, which compares to average annual growth of 1
5% since the Global Financial Crisis - itself a period of low growth by historical standards
 5
 Second, the labour market is loosening but it remains tight
 The survey-based employment indicators point to a tentative slowdown in hiring
 The level of vacancies has fallen from a peak of 1
3 million in the middle of last year to just under a million in the latest data
 But that is still more than 100,000 above its pre-Covid level, which itself was elevated by historical standards
 And importantly, whilst wage growth has finally begun to fall it is still greater than 7% on most measures, which given the current weakness in productivity growth in the UK is several percentage points higher than a level that, if sustained, would be consistent with the inflation target
 6
 Third, inflation has been falling over the past year but it remains far too high
 It peaked at 11
1% in October 2022 and was 4
6% in the October data
 A naive calculation would imply that we have done more than two thirds of the work to get inflation back to target
 1 Alan Greenspan called uncertainty the 'defining characteristic' of the monetary policy landscape
 2 For example, the ONS is dealing with issues caused by a decline in the response rate to the Labour Force Survey, which is the MPC's most important source of information on the unemployment rate
 3 For example, the revision to the final UK PMI for September 2023 was the 3rd largest since records began
 4 My colleague Ben Broadbent yesterday set out some challenges around understanding the state of the UK economy at the moment, and how the MPC's usual policymaking approach focuses on a range of indicators
 5 In the MPC's November 2022 forecast GDP was expected to fall by 2% over the year to Q4 2023
 6 Bank staff estimate that the rate of trend productivity growth in the economy as a whole is around 1%
 In combination with inflation of 2%, that implies nominal wage growth of 3% on average, all else equal
 Bank of England Page 3 But much of the fall in inflation so far owes to base effects: the mechanical counterpart of the unprecedented increase in the level of energy prices that came to an end just over a year ago, with a much smaller contribution so far from the significant monetary policy tightening
' Taken at face value, the MPC's November forecast implies that inflation will not return to the 2% target for another two years, so we expect to have a way to go
 How did we get here? 7
 It is worth stepping back to review how we got here
 I think a few points of context are particularly important to bear in mind
 First, the UK economy has been hit by a series of unprecedented shocks
 The UK's departure from the European Union coincided with a once-in-a-hundred year pandemic during which much of the UK and global economies were shut down
 The process of reopening those economies met with supply chain frictions that pushed up materially on the prices of globally traded goods
 Then in 2022 Russia staged an unprovoked and unjustified invasion of Ukraine, starting the biggest war in Europe for 80 years, and pushing up European energy prices by many multiples as a consequence
 Most of these shocks - but of course not all of them - have affected other advanced economies too
 All have contributed to volatility in economic activity and inflation
 Second, high inflation since 2021, which was initially caused by imported goods and energy prices, has led to the emergence of second-round effects on wages and prices in the UK
 This process has been supported by exceptional tightness in the labour market, and has been stubborn even in the face of the shocks I just described
 These second-round effects have contributed to persistence in inflation in the UK and, albeit to a lesser extent, in other advanced economies
' 10
 Third, demand has been resilient and supply has been very weak
 The tight labour 11 market and elevated inflation - especially for goods and services that tend to have a larger domestic cost component - point to a UK economy that is operating at or above capacity
 But the data suggest that economic activity has been flat
 That implies that supply has been very weak, which is a natural consequence of some of the shocks I mentioned earlier

 These have combined to deliver a series of significant forecast surprises in the UK and other advanced economies
 Focusing on the UK, until very recently inflation had been much higher over the past couple of years than we had expected
 And as I said before, economic activity has been more resilient than we expected
 Chart 1 shows that the scale of these surprises - based on one-year-ahead forecasts - has been larger than at any point since the Global Financial Crisis
1'' Some of the surprises, for example in 7 As I said in my parliamentary appointment questionnaire, inflation could have been three to five percentage points higher at its peak had the MPC not increased Bank Rate at all
 8 The Governor Andrew Bailey has described this as 'a time of macroeconomic upheaval'
 See a recent speech by my colleague Jonathan Haskel for more on this
 10 When inflation and wage growth are high, they also tend to be more volatile, which adds to issues around extracting a signal from the data
 I return to this idea later in the speech
 11 The MPC's forecasts condition on market expectations for Bank Rate and energy prices, among other things
 Part of the increase in forecast surprises has been driven by volatility in those variables
 Bank of England Page 4 late 2022, looked like textbook supply shocks, with stronger inflation coming at the same time as weaker GDP
 More recently GDP has been much stronger than our forecasts a year ago, with inflation weaker than expected, suggesting some unwind of prior supply shocks
 Chart 1: Over the past few years the MPC have had to deal with larger forecast surprises than at any point since the Global Financial Crisis @) One-year-ahead forecast surprises (data minus forecast, pp) 7 6 e e 5 Late 2022 ---" e 4 e) e 3 ee e a 25 @ 2008-2020 eed 1 ry e@ Since 2020 fo 05 1 -2 -3 -25 -20 15 -10 5 0 5 GDP growth Source: Bank of England, ONS (a) The chart shows the difference between quarterly data outturns for year on year growth in GDP and CPI inflation and the MPC's modal forecast for those variables made one year earlier
 The forecasts condition on market expectations for Bank Rate, energy prices and other factors at the time the forecasts were made
 12
In general these surprises tend to have been serially correlated - particularly for inflation - meaning that positive surprises tend to have been followed by further positive surprises
'? These large inflation surprises have been common across advanced economies, including the US and the euro area
 13
To state the obvious, this context has made monetary policymaking difficult
 I have learned two important lessons
 First inflation and wage growth have been stronger than our models would have predicted, suggesting greater second-round effects than I would have expected before this inflationary episode
 Second, there is more uncertainty than usual about the speed and scale of the monetary transmission mechanism, especially given the unprecedented tightening we have seen
 14
What I take from this is that we are in a state of the world where monetary policymaking is best considered as engineering rather than science
 The shocks and data surprises are too large for us to have any hope of understanding the detail of what is happening in a complex system and fine tuning economic outcomes through our 12 The trailing two year correlation between the one-year-ahead quarter-on-quarter inflation surprise and its own lag increased to around 0
7-0
8 over the past year and a half
 The BIS have also shown that one-year- ahead inflation surprises have been positively correlated with two-year-ahead surprises historically
 Bank of England Page 5 models
 Instead - like engineers - we should pay attention to real world outcomes and adjust accordingly
? 15
 That means we have had to remain open-minded to make sure that we continually learn how the economy is responding to these shocks
 We have had to remain humble about how well economic models perform when movements in important variables are 'out of sample' - in other words historically unprecedented
 We have had to place more emphasis than usual on what we know has happened, or is happening, in the economy and acknowledge that future projections are more uncertain than usual
'* And given the uncertainty around the things we are simply unable to observe but that matter a lot now for policy - most obviously trends in supply - we have had to rely more on extracting signals from so-called 'late cycle' indicators, such as inflation and wage growth, rather than indicators of economic activity
' 16
One approach that I think helpful is to think through a range of possible scenarios for the UK economy, where those scenarios reflect how real world outcomes have differed from our expectations - our lessons learned from engineering, if you like
 Why is scenario analysis helpful? 17
Scenarios enable us to explore policy relevant potential outcomes rather than focusing only on the thing that is most likely to happen
 It's an approach we often use in financial stability - including on the Financial Policy Committee - where policymakers are inherently interested in tail outcomes rather than the central case, which naturally requires analysis of scenarios
 But I have also found scenario analysis to be a useful guide for monetary policymaking during a time of major shocks
 And I hope through explaining the role that scenario analysis has had in my own thinking on monetary policy I can make the case for the MPC to do more of it in the future
 18
So what are the relevant scenarios for the UK economy at the moment? In my view the potential distribution of inflation outcomes is wider than it used to be - by which I mean that the probabilities of meaningfully above and meaningfully below target inflation are much higher than we might usually expect - and I have less confidence than I used to in any given inflation profile coming to pass
 19
 Similarly, whilst the MPC's latest forecast implies that inflation is most likely to be 1
9% in two years - and the mean, or expected value, is 2
2% - there is a material probability that it could be much higher or much lower
* 13 I would like to thank Tim Jackson (an engineer and my husband) for inspiring the theme of this speech, although I have since discovered that Professor Gregory Mankiw also used the analogy in the 2000s here
 14 See, for example, the February 2023 MPC minutes, which mentioned "additional weight being put on recent strength in the labour market and inflation data, and relatively less on the medium-term projections'
 15 See a recent speech by my colleague Ben Broadbent, which covers this theme
 He also covered the theme in his speech yesterday
 16 See a recent speech by my former colleague Silvana Tenreyro, which contains more discussion of the fan charts and of forecasting in the face of major economic shocks
 Bank of England Page 6 What are the relevant scenarios? 20
1 am going to set out two scenarios in this speech, reflecting two states of the world that would have very different implications for inflation and for monetary policy
 These scenarios have informed my approach to setting policy, and in particular how I've approached setting policy in an environment where there are these competing risks
'" 21
Chart 2 shows in (I should emphasise) illustrative terms what these scenarios could look like
 In one scenario - the 'low inflation scenario' - there is a negative shock and demand weakens much more quickly than expected as the MPC's previous tightening in monetary policy takes hold
 Ultimately, and assuming for now no change in the path of Bank Rate, inflation would fall well below target
 In the other scenario - the 'high inflation scenario' - inflation remains stubbornly persistent as a result of continued and strengthened second-round effects
 ' Chart 2: Illustrative high and low inflation scenarios for the UK economy, alongside the MPC's most likely forecast in November 2023 @) Inflation in scenarios (percent) 12 November 2023 (market rates) -- High inflation: second-round effects Low inflation: weaker demand 2021 2022 2023 2024 2025 2026 Source: Bank of England (a) The chart shows the MPC's November 2023 modal forecast for CPI inflation, conditioned on market expectations for Bank Rate at that time
 The high inflation scenario could be thought of as one in which, for instance, the labour market remains tight and second-round effects are very significant
 The low inflation scenario could instead be thought of as one in which the economy is hit by negative demand shocks that reduce demand materially relative to the November forecast
 The scenarios should be interpreted as illustrative only
 22
This of course begs the question of how policy should respond in these states of the world
 That is impossible to describe in the abstract
 But one possible window into it is 17 The MPC's November 2023 minutes touched on a similar theme, saying that the 'decision whether to increase or to maintain Bank Rate at this meeting was again finely balanced between the risks of not tightening policy enough when underlying inflationary pressures could prove more persistent, and the risks of tightening policy too much given the impact of policy that was still to come through'
 18 My colleague Huw Pill called this 'intrinsic inflation persistence' in a recent speech
 Bank of England Page 7 the so-called 'optimal policy projection'
1 This is just one particular, simple, representation of how interest rates might have to respond to the scenarios, and in this version it assumes that the policymaker is focused only on returning inflation to target
 It is clearly just a straw person
 But it is nevertheless a useful yardstick to size quite how material these scenarios could be for Bank Rate
 Chart 3: Estimated optimal monetary policy response to high and low inflation scenarios for the UK economy, assuming the policymaker places no weight on output stabilisation, for illustrative purposes ) Bank Rate in scenarios (percent) 10 eee History 9 -- High inflation: second-round effects 8 Low inflation: weaker demand 7 6 5 4 3 2 1 0 2021 2022 2023 2024 2025 2026 Source: Bank of England (a) The chart shows the estimated 'optimal policy projection' associated with the high and low inflation scenarios
 See this annex for further details
 In these scenarios - which are designed to focus on potential inflation outcomes, rather than any trade-offs with output stabilisation - we assume a lambda parameter of zero, and some preference for interest rate smoothing
 The high inflation scenario assumes that the labour market remains tight and second-round effects are very significant
 The low inflation scenario assumes that the economy is hit by negative demand shocks that reduce demand materially relative to the November forecast
 The scenarios should be interpreted as illustrative only
 23
Chart 3 shows how in this thought experiment the scenarios would, unsurprisingly, have very different implications for Bank Rate
 In the low inflation scenario, Bank Rate would fall from the end of this year onwards, to prevent inflation from falling materially below target
 In the high inflation scenario, Bank Rate would rise throughout 2024 to bring inflation down, before broadly stabilising somewhere well above 6%
? 24
Let me underline, these scenarios are meant to be illustrative only and not a precise read on what I think monetary policy would have to do
 The projection has a number of 19 See the annex to this previous speech by my colleague Ben Broadbent for more on the details of the 'optimal policy projection'
 In these particular illustrative scenarios - which are designed to focus on potential inflation outcomes, rather than the potential trade-off with output stabilisation - we assume a lambda parameter of zero
 20 In both cases, the optimal policy projection would of course deliver a path for inflation that is closer to target than the underlying inflation scenarios
 Bank of England Page 8 unrealistic simplifying assumptions, including that everyone knows and understands the path for the economy
 It also depends on a precise estimate of the monetary transmission mechanism, which is very uncertain as I noted above
 But it does show the potential for very different paths for Bank Rate depending on which scenario we find ourselves in
 Monetary policy from here 25
How might such scenario analysis be useful in considering policy? It is impossible to place precise probabilities on the likelihood of either of these scenarios, although I think the MPC's modal forecast is more likely to occur than either of them
 Nevertheless understanding how a policymaker would respond in either scenario is useful to anyone who is interested in understanding the outlook for policy from here
 The approach also underlines how, when there are significant risks, policy may need to be nimble as we learn more about which state of the world we might be in
 (Indeed, in much the same way, my colleague Ben Broadbent talked yesterday about trading off timeliness against forming a better understanding of what's going on in the economy
*') That process of working out what's going on should rely on the accumulation of evidence rather than any individual data point
 Finally, in my view, the high inflation scenario would be clearly the more costly scenario - and it is therefore the most important scenario to lean against when we are setting monetary policy
 26
Where does that leave monetary policy over the next few months? The economy is moving in the right direction to return inflation to the 2% target, but our job isn't done
 The question I am focused on is whether there is evidence of more persistent inflationary pressures which means we may need to tighten further
 Regardless, monetary policy still needs to be restrictive for an extended period of time to keep pushing down on inflation and to return it sustainably to target
 27

In [42]:
for i in os.listdir("../Data/Speeches/speeches_by_central_bank/"):
    if i in df[df['Language']=='English']['CentralBank'].value_counts().index:
        print(i)
        speeches = df[(df['Language']=='English') & (df['CentralBank']==i)]#['text']#.values[0][:100]
        display(speeches)
        speeches.to_csv(f"../Data/Speeches/speeches_by_central_bank/{i}/{i}.csv", index=False, sep='\t')

Bank of Canada

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
1310,https://www.bankofcanada.ca/2004/03/adjusting-...,NaN,Adjusting to Global Economic Change,Remarks: David Dodge - An event hosted by the ...,2004-03-16,David Dodge,Governor,Male,Bank of Canada,CAN,Adjusting to Global Economic Change Remarks Da...,NaN,can_adjusting-global-economic-change-16032004,English,CB websites
1311,https://www.bankofcanada.ca/2004/03/asia-globa...,NaN,Asia and the Global Economy,Remarks: Paul Jenkins - University of British ...,2004-03-30,Paul Jenkins,Deputy Governor,Male,Bank of Canada,CAN,Asia and the Global Economy Remarks Paul Jenki...,NaN,can_asia-global-economy-30032004,English,CB websites
1312,https://www.bankofcanada.ca/2020/08/closing-re...,https://www.bankofcanada.ca/wp-content/uploads...,Closing remarks,Closing Remarks by Carolyn A. Wilkins Senior D...,2020-08-26,Carolyn Wilkins,Deputy Governor,Female,Bank of Canada,CAN,Closing Remarks by Carolyn A. Wilkins Senior D...,NaN,can_closing-remarks-2020-08-26,English,CB websites
1313,https://www.bankofcanada.ca/2002/05/convocatio...,NaN,Convocation address,Remarks: David Dodge - Graduating Class of the...,2002-05-24,David Dodge,Governor,Male,Bank of Canada,CAN,Convocation address Remarks David Dodge - Form...,NaN,can_convocation-address-24052002,English,CB websites
1314,https://www.bankofcanada.ca/2001/05/opening-st...,https://www.bankofcanada.ca/wp-content/uploads...,Release of the Monetary Policy Report,Opening Statement: David Dodge,2001-05-01,David Dodge,Governor,Male,Bank of Canada,CAN,Release of the Monetary Policy Report 1 May 20...,NaN,can_opening-statement-010501,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28629,https://www.bis.org/review/r990528b.pdf,https://www.bis.org/review/r990528b.pdf,Mr Thiessen's statement on the Bank of Canada'...,Opening statement of the Governor of the Bank ...,1999-05-26,Gordon Thiessen,Governor,Male,Bank of Canada,CAN,Mr Thiessens statement on the Bank of Canadas ...,NaN,r990528b,English,BIS
28634,https://www.bis.org/review/r990603b.pdf,https://www.bis.org/review/r990603b.pdf,Mr Thiessen evaluates the performance of the C...,"Address by the Governor of the Bank of Canada,...",1999-06-02,Gordon Thiessen,Governor,Male,Bank of Canada,CAN,Mr Thiessen evaluates the performance of the C...,NaN,r990603b,English,BIS
28690,https://www.bis.org/review/r990927a.pdf,https://www.bis.org/review/r990927a.pdf,Mr Thiessen gives an update on the Canadian ec...,"Speech by Mr Gordon Thiessen, Governor of the ...",1999-09-23,Gordon Thiessen,Governor,Male,Bank of Canada,CAN,Mr Thiessen gives an update on the Canadian ec...,NaN,r990927a,English,BIS
28729,https://www.bis.org/review/r991108a.pdf,https://www.bis.org/review/r991108a.pdf,Mr Thiessen reviews the challenges for Canadia...,"Remarks by Mr Gordon Thiessen, Governor of the...",1999-11-02,Gordon Thiessen,Governor,Male,Bank of Canada,CAN,Mr Thiessen reviews the challenges for Canadia...,NaN,r991108a,English,BIS
28756,https://www.bis.org/review/r991210a.pdf,https://www.bis.org/review/r991210a.pdf,Mr Thiessen clarifies some points regarding th...,"Remarks by Gordon Thiessen, Governor of the Ba...",1999-12-06,Gordon Thiessen,Governor,Male,Bank of Canada,CAN,Mr Thiessen clarifies some points regarding th...,NaN,r991210a,English,BIS

Bank of England

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
6472,https://www.bankofengland.co.uk/speech/2002/a-...,https://www.bankofengland.co.uk/-/media/boe/fi...,A Picture of European Unemployment: Success an...,NaN,2002-12-06,Stephen Nickell,Board member,Male,Bank of England,GBR,A Picture of European Unemployment: Success an...,NaN,gbr_2002_a-picture-of-european-unemployment-su...,English,CB websites
6473,https://www.bankofengland.co.uk/speech/2004/a-...,https://www.bankofengland.co.uk/-/media/boe/fi...,A Picture of European Unemployment: Success an...,NaN,2004-03-26,Stephen Nickell,Board member,Male,Bank of England,GBR,A Picture of European Unemployment: Success an...,NaN,gbr_2004_a-picture-of-european-unemployment-su...,English,CB websites
6474,https://www.bankofengland.co.uk/speech/2004/so...,https://www.bankofengland.co.uk/-/media/boe/fi...,Some Current Issues in UK Monetary Policy,NaN,2004-07-28,Charles Bean,Board member,Male,Bank of England,GBR,Some Current Issues in UK Monetary Policy Spee...,NaN,gbr_2004_some-current-issues-in-uk-monetary-po...,English,CB websites
6475,https://www.bankofengland.co.uk/speech/2005/ch...,https://www.bankofengland.co.uk/-/media/boe/fi...,Speech by Charles Bean,NaN,2005-08-26,Charles Bean,Board member,Male,Bank of England,GBR,"Speech given by Charles Bean, Chief Economist,...",NaN,gbr_2005_charles-bean-jackson-hole-symposium,English,CB websites
6476,https://www.bankofengland.co.uk/speech/2006/ch...,https://www.bankofengland.co.uk/-/media/boe/fi...,Jackson Hole Symposium,NaN,2006-08-26,Charles Bean,Board member,Male,Bank of England,GBR,Jackson Hole Symposium Comments by Charles Bea...,NaN,gbr_2006_charles-bean-jackson-hole-symposium,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28637,https://www.bis.org/review/r990611a.pdf,https://www.bis.org/review/r990611a.pdf,Mr. George gives an address on recent changes ...,"Speech given by Mr E A J George, Governor of t...",1999-06-10,Eddie A J George,Governor,Male,Bank of England,GBR,Mr. George gives an address on recent changes ...,NaN,r990611a,English,BIS
28680,https://www.bis.org/review/r990913a.pdf,https://www.bis.org/review/r990913a.pdf,the middle way (Central Bank Articles and Spe...,"Speech delivered by Mr Mervyn King, Deputy Gov...",1999-09-09,Mervyn King,Deputy Governor,Male,Bank of England,GBR,Mr King gives a speech on reforming the intern...,NaN,r990913a,English,BIS
28712,https://www.bis.org/review/r991015b.pdf,https://www.bis.org/review/r991015b.pdf,"Mr King speaks about interest rates, policy an...","Speech given by Mr Mervyn King, Deputy Governo...",1999-10-11,Mervyn King,Deputy Governor,Male,Bank of England,GBR,"Mr King speaks about interest rates, policy an...",NaN,r991015b,English,BIS
28751,https://www.bis.org/review/r991206b.pdf,https://www.bis.org/review/r991206b.pdf,Mr Clementi comments on the systemic aspects o...,"Speech given by Mr David Clementi, Deputy Gove...",1999-12-02,David Clementi,Deputy Governor,Male,Bank of England,GBR,Mr Clementi comments on the systemic aspects o...,NaN,r991206b,English,BIS
28754,https://www.bis.org/review/r991208a.pdf,https://www.bis.org/review/r991208a.pdf,"Mr George looks at past, present and future ch...","Speech given by Mr Eddie George, Governor of t...",1999-12-07,Eddie A J George,Governor,Male,Bank of England,GBR,"Mr George looks at past, present and future ch...",NaN,r991208a,English,BIS

Board of Governors of the Federal Reserve

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12456,https://www.bis.org/review/r000114a.pdf,https://www.bis.org/review/r000114a.pdf,Mr Ferguson compares Asian and Latin American ...,"Remarks by Mr Roger W Ferguson Jr, Vice-Chairm...",2000-01-07,Roger W Ferguson,Deputy Governor,Male,Board of Governors of the Federal Reserve,USA,Mr Ferguson compares Asian and Latin American ...,NaN,r000114a,English,BIS
12457,https://www.bis.org/review/r000117a.pdf,https://www.bis.org/review/r000117a.pdf,Mr Greenspan discusses technology and the US e...,"Remarks by Mr Alan Greenspan, Chairman of the ...",2000-01-13,Alan Greenspan,Governor,Male,Board of Governors of the Federal Reserve,USA,Mr Greenspan discusses technology and the US e...,NaN,r000117a,English,BIS
12458,https://www.bis.org/review/r000117b.pdf,https://www.bis.org/review/r000117b.pdf,Mr Gramlich focuses on inflation targeting (C...,"Remarks by Mr Edward M Gramlich, Member of the...",2000-01-13,Edward M Gramlich,Board member,Male,Board of Governors of the Federal Reserve,USA,Mr Gramlich focuses on inflation targeting Rem...,NaN,r000117b,English,BIS
12461,https://www.bis.org/review/r000124b.pdf,https://www.bis.org/review/r000124b.pdf,Mr Meyer gives his views on the sustainability...,"Remarks by Mr Laurence H Meyer, Member of the ...",2000-01-20,Laurence H Meyer,Board member,Male,Board of Governors of the Federal Reserve,USA,Mr Meyer gives his views on the sustainability...,NaN,r000124b,English,BIS
12471,https://www.bis.org/review/r000216a.pdf,https://www.bis.org/review/r000216a.pdf,Mr Greenspan gives a testimony on over-the-cou...,"Testimony of Mr Alan Greenspan, Chairman of th...",2000-02-10,Alan Greenspan,Governor,Male,Board of Governors of the Federal Reserve,USA,Mr Greenspan gives a testimony on over-the-cou...,NaN,r000216a,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35471,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Basel II and H.R. 2043 : Testimony before the ...,NaN,2003-06-19,Roger W Ferguson,Deputy Governor,Male,Board of Governors of the Federal Reserve,USA,"Testimony of Vice Chairman Roger W. Ferguson, ...",NaN,basel-ii-hr-2043-36988,English,Archives
35472,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Natural Gas Supply : Testimony before the Comm...,NaN,2003-07-10,Alan Greenspan,Governor,Male,Board of Governors of the Federal Reserve,USA,For release on delivery\n10:00 a.m. EDT\nJuly ...,NaN,natural-gas-supply-8794,English,Archives
35477,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Statement on His Renomination to the Board : T...,NaN,2003-10-14,Ben S Bernanke,Board member,Male,Board of Governors of the Federal Reserve,USA,For release on delivery\n10:00 a.m. EDT\nOctob...,NaN,statement-renomination-board-8885,English,Archives
35478,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Statement on His Renomination as Vice Chairman...,NaN,2003-10-14,Roger W Ferguson,Deputy Governor,Male,Board of Governors of the Federal Reserve,USA,For release on delivery\n10:00 a.m. EDT\nOctob...,NaN,statement-renomination-vice-chairman-board-36942,English,Archives
35479,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Power Outages and the Financial System : Testi...,NaN,2003-10-20,Mark W Olson,Board member,Male,Board of Governors of the Federal Reserve,USA,Power outages and the financial system\nBefore...,NaN,power-outages-financial-system-36585,English,Archives

Central Bank of the Philippines

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
11583,https://www.bsp.gov.ph/SitePages/MediaAndResea...,https://www.bsp.gov.ph/Lists/Speeches%20list/A...,On the Maharlika Investment Fund,NaN,2023-02-01,Felipe M Medalla,Governor,Male,Central Bank of the Philippines,PHL,Media and Research - Speeches On the Maharlika...,NaN,phl_bsp-speeches-1003,English,CB websites
11584,https://www.bsp.gov.ph/SitePages/MediaAndResea...,https://www.bsp.gov.ph/Lists/Speeches%20list/A...,A Conversation with the Financial Markets on P...,NaN,2023-02-02,Felipe M Medalla,Governor,Male,Central Bank of the Philippines,PHL,Media and Research - Speeches A Conversation w...,NaN,phl_bsp-speeches-1004,English,CB websites
11585,https://www.bsp.gov.ph/SitePages/MediaAndResea...,https://www.bsp.gov.ph/Lists/Speeches%20list/A...,Bringing Paleng-QR Ph Plus to Pasig,NaN,2023-03-03,Felipe M Medalla,Governor,Male,Central Bank of the Philippines,PHL,Magandang umaga sa inyong lahat. I knew I was ...,NaN,phl_bsp-speeches-1010,English,CB websites
11586,https://www.bsp.gov.ph/SitePages/MediaAndResea...,https://www.bsp.gov.ph/Lists/Speeches%20list/A...,Examining Economic Policymaking in the Philipp...,NaN,2023-03-02,Felipe M Medalla,Governor,Male,Central Bank of the Philippines,PHL,Media and Research - Speeches Examining Econom...,NaN,phl_bsp-speeches-1011,English,CB websites
11587,https://www.bsp.gov.ph/SitePages/MediaAndResea...,https://www.bsp.gov.ph/Lists/Speeches%20list/A...,From Nowhere to Now Here: The CRD as a Step To...,NaN,2023-04-25,Felipe M Medalla,Governor,Male,Central Bank of the Philippines,PHL,Media and Research - Speeches From Nowhere to ...,NaN,phl_bsp-speeches-1017,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27833,http://www.bis.org/review/r230718o.htm,http://www.bis.org/review/r230718o.pdf,Felipe M Medalla: Navigating the road ahead - ...,"Speech by Mr Felipe M Medalla, Governor of Ban...",2023-07-03,Felipe M Medalla,Governor,Male,Central Bank of the Philippines,PHL,Felipe M Medalla: Navigating the road ahead - ...,NaN,r230718o,English,BIS
27847,http://www.bis.org/review/r230731f.htm,http://www.bis.org/review/r230731f.pdf,Eli M Remolona: Navigating the road ahead - lo...,"Speech by Mr Eli M Remolona Jr, Governor of Ba...",2023-07-28,Eli M Remolona,Deputy Governor,Male,Central Bank of the Philippines,PHL,Eli M Remolona: Navigating the road ahead - lo...,NaN,r230731f,English,BIS
27880,http://www.bis.org/review/r230905h.htm,http://www.bis.org/review/r230905h.pdf,Eli M Remolona: Rising to the challenge - the ...,"Speech by Mr Eli M Remolona, Jr, Governor of B...",2023-08-14,Eli M Remolona,Deputy Governor,Male,Central Bank of the Philippines,PHL,Eli M Remolona: Rising to the challenge - the ...,NaN,r230905h,English,BIS
27998,https://www.bis.org/review/r231026h.htm,https://www.bis.org/review/r231026h.pdf,"Stability, sustainability, and inclusivity for...","Speech by Mr Eli M Remolona, Jr, Governor of B...",2023-09-14,Eli M Remolona,Governor,Male,Central Bank of the Philippines,PHL,"Eli M Remolona: Stability, sustainability, and...",NaN,r231026h,English,BIS
27999,https://www.bis.org/review/r231026j.htm,https://www.bis.org/review/r231026j.pdf,Eli M Remolona: Welcome message - 2nd Digital ...,"Welcome message by Mr Eli M Remolona, Jr, Gove...",2023-10-24,Eli M Remolona,Deputy Governor,Male,Central Bank of the Philippines,PHL,Eli M Remolona: Welcome message - 2nd Digital ...,NaN,r231026j,English,BIS

European Central Bank

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
2976,https://www.ecb.europa.eu/press/key/date/2000/...,NaN,One year with the euro,"Speech delivered by Dr Sirkka Hmlinen, Mem...",2000-01-08,Sirkka Hmlinen,Board member,Female,European Central Bank,ECB,One year with the euro Speech delivered by Dr ...,NaN,ecb_000108.en,English,CB websites
2977,https://www.ecb.europa.eu/press/key/date/2000/...,NaN,Opening Remarks at a Hearing of the Committee ...,"Professor Otmar Issing, Member of the Board o...",2000-01-10,Otmar Issing,Board member,Male,European Central Bank,ECB,Opening Remarks at a Hearing of the Committee ...,NaN,ecb_000110.en,English,CB websites
2978,https://www.ecb.europa.eu/press/key/date/2000/...,NaN,The international impact of the euro,"Speech delivered by Christian Noyer, Vice...",2000-01-13,Christian Noyer,Deputy Governor,Male,European Central Bank,ECB,The international impact of the euro Speech de...,NaN,ecb_000113.en,English,BIS
2979,https://www.ecb.europa.eu/press/key/date/2000/...,NaN,The role of the central bank in encouraging an...,"Speech given by Christian Noyer, Vice-Pres...",2000-01-21,Christian Noyer,Deputy Governor,Male,European Central Bank,ECB,The role of the central bank in encouraging an...,NaN,ecb_000121.en,English,BIS
2980,https://www.ecb.europa.eu/press/key/date/2000/...,NaN,The euro area - first experience and perspectives,"by Professor Otmar Issing, Member of the Boar...",2000-01-26,Otmar Issing,Board member,Male,European Central Bank,ECB,The euro area - first experience and perspecti...,NaN,ecb_000126.en,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28610,https://www.bis.org/review/r990510b.htm,https://www.bis.org/review/r990510b.pdf,Mr Duisenberg reports on the outcome of the la...,NaN,1999-05-06,Willem F Duisenberg,Board member,Female,European Central Bank,ECB,Mr Duisenberg reports on the outcome of the la...,NaN,r990510b,English,BIS
28657,https://www.bis.org/review/r990716a.htm,https://www.bis.org/review/r990716a.pdf,Mr Duisenberg's statement on the European Unio...,NaN,1999-07-15,Willem F Duisenberg,Board member,Female,European Central Bank,ECB,Mr Duisenbergs statement on the European Union...,NaN,r990716a,English,BIS
28681,https://www.bis.org/review/r990914a.htm,https://www.bis.org/review/r990914a.pdf,Mr Duisenberg reports on the outcome of the la...,NaN,1999-09-09,Willem F Duisenberg,Board member,Female,European Central Bank,ECB,Mr Duisenberg reports on the outcome of the la...,NaN,r990914a,English,BIS
28705,https://www.bis.org/review/r991012b.htm,https://www.bis.org/review/r991012b.pdf,Mr Duisenberg and Mr Noyer report on the outco...,NaN,1999-10-07,Willem F Duisenberg,Board member,Female,European Central Bank,ECB,Mr Duisenberg and Mr Noyer report on the outco...,NaN,r991012b,English,BIS
28731,https://www.bis.org/review/r991109a.htm,https://www.bis.org/review/r991109a.pdf,Mr Duisenberg reports on the outcome of the la...,NaN,1999-11-04,Willem F Duisenberg,Board member,Female,European Central Bank,ECB,Mr Duisenberg reports on the outcome of the la...,NaN,r991109a,English,BIS

Federal Reserve Bank of Atlanta

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
21557,https://www.bis.org/review/r150210f.htm,https://www.bis.org/review/r150210f.pdf,A potentially momentous year for policy,"Speech by Mr Dennis Lockhart, President and Ch...",2015-01-12,Dennis Lockhart,Governor,Male,Federal Reserve Bank of Atlanta,USA,Dennis Lockhart: A potentially momentous year ...,NaN,r150210f,English,BIS
21558,https://www.bis.org/review/r150210g.htm,https://www.bis.org/review/r150210g.pdf,Considerations on the path to policy normaliza...,"Speech by Mr Dennis Lockhart, President and Ch...",2015-02-06,Dennis Lockhart,Governor,Male,Federal Reserve Bank of Atlanta,USA,Dennis Lockhart: Considerations on the path to...,NaN,r150210g,English,BIS
30992,https://www.atlantafed.org/news/speeches/2000/...,NaN,The Economic Outlook for 2000,NaN,2000-01-24,Jack Guynn,Governor,Male,Federal Reserve Bank of Atlanta,USA,SPEECHES The Economic Outlook for 2000 Remarks...,NaN,usa_000124-guynn,English,CB websites
30994,https://www.atlantafed.org/news/speeches/2000/...,NaN,An Outlook - And a Look Within,NaN,2000-03-03,Jack Guynn,Governor,Male,Federal Reserve Bank of Atlanta,USA,SPEECHES An Outlook - And a Look Within Remark...,NaN,usa_000303-guynn,English,CB websites
31000,https://www.atlantafed.org/news/speeches/2000/...,NaN,The Role of Low Inflation in the Current Expan...,NaN,2000-06-05,Jack Guynn,Governor,Male,Federal Reserve Bank of Atlanta,USA,SPEECHES The Role of Low Inflation in the Curr...,NaN,usa_000605-guynn,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34008,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,The Economic Outlook for the United States and...,NaN,1995-07-24,Robert P Forrestal,Governor,Male,Federal Reserve Bank of Atlanta,USA,THE ECONOMIC OUTLOOK FOR THE UNITED STATES AND...,NaN,usa_robert_p_forrestal_1995_7_24,English,Archives
34009,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,The Economic Outlook for the United States and...,NaN,1995-08-10,Robert P Forrestal,Governor,Male,Federal Reserve Bank of Atlanta,USA,THE ECONOMIC OUTLOOK FOR THE UNITED STATES AND...,NaN,usa_robert_p_forrestal_1995_8_10,English,Archives
34010,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,Latin America's Economic Boom: The U.S. Perspe...,NaN,1995-09-15,Robert P Forrestal,Governor,Male,Federal Reserve Bank of Atlanta,USA,LATIN AMERICA'S ECONOMIC BOOM: THE U.S. PERSPE...,NaN,usa_robert_p_forrestal_1995_9_15,English,Archives
34011,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,The National and International Economic Outloo...,NaN,1995-09-07,Robert P Forrestal,Governor,Male,Federal Reserve Bank of Atlanta,USA,THE NATIONAL AND INTERNATIONAL ECONOMIC OUTLOO...,NaN,usa_robert_p_forrestal_1995_9_7,English,Archives
35486,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Beyond Short-Term Interests : Atlanta Regional...,NaN,2003-11-21,Jack Guynn,Governor,Male,Federal Reserve Bank of Atlanta,USA,Speeches\n\nBeyond Short-Term Interests\n\nJac...,NaN,beyond-short-term-interests-521702,English,Archives

Federal Reserve Bank of Boston

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
17687,https://www.bis.org/review/r100507e.pdf,https://www.bis.org/review/r100507e.pdf,Considering the routes to a policy destination,"Speech by Mr Eric S Rosengren, President and C...",2010-05-05,Eric S Rosengren,Governor,Male,Federal Reserve Bank of Boston,USA,Eric S Rosengren: Considering the routes to a ...,NaN,r100507e,English,BIS
18417,https://www.bis.org/review/r110408e.pdf,https://www.bis.org/review/r110408e.pdf,Two key questions about the economic recovery,"Remarks by Mr Eric S Rosengren, President and ...",2011-01-14,Eric S Rosengren,Governor,Male,Federal Reserve Bank of Boston,USA,Eric S Rosengren: Two key questions about the ...,NaN,r110408e,English,BIS
18422,https://www.bis.org/review/r110411e.pdf,https://www.bis.org/review/r110411e.pdf,"The role of ""financial myths"" in financial crises","Remarks by Mr Eric S Rosengren, President and ...",2011-02-28,Eric S Rosengren,Governor,Male,Federal Reserve Bank of Boston,USA,Eric S Rosengren: The role of financial myths ...,NaN,r110411e,English,BIS
18543,https://www.bis.org/review/r110603d.pdf,https://www.bis.org/review/r110603d.pdf,A look inside a key economic debate - how shou...,"Remarks by Mr Eric S Rosengren, President and ...",2011-05-04,Eric S Rosengren,Governor,Male,Federal Reserve Bank of Boston,USA,Eric S Rosengren: A look inside a key economic...,NaN,r110603d,English,BIS
18547,https://www.bis.org/review/r110606b.pdf,https://www.bis.org/review/r110606b.pdf,A US perspective on strengthening financial st...,"Speech by Mr Eric S Rosengren, President and C...",2011-05-24,Eric S Rosengren,Governor,Male,Federal Reserve Bank of Boston,USA,Eric S Rosengren: A US perspective on strength...,NaN,r110606b,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34727,https://www.bostonfed.org/news-and-events/spee...,NaN,"U.S. Retail Payments: Change, Challenge and Op...",NaN,2002-05-08,Cathy E Minehan,Governor,Female,Federal Reserve Bank of Boston,USA,"U.S. Retail Payments: Change, Challenge and Op...",NaN,usa_us-retail-payments-change-challenge-and-op...,English,CB websites
34728,https://www.bostonfed.org/news-and-events/spee...,NaN,U.S. Retail Payments: Opportunities and Challe...,NaN,2004-06-17,Cathy E Minehan,Governor,Female,Federal Reserve Bank of Boston,USA,U.S. Retail Payments: Opportunities and Challe...,NaN,usa_us-retail-payments-opportunities-and-chall...,English,CB websites
34731,https://www.bostonfed.org/news-and-events/spee...,NaN,Vermont Economic Outlook Conference,NaN,2003-01-10,Cathy E Minehan,Governor,Female,Federal Reserve Bank of Boston,USA,Vermont Economic Outlook Conference By Cathy E...,NaN,usa_vermont-economic-outlook-conference,English,CB websites
34854,https://www.bostonfed.org/news-and-events/spee...,https://www.bostonfed.org/-/media/Documents/ne...,Preserving Homeownership: Progress Needed to P...,NaN,2009-07-16,Paul Willen,Senior management,Male,Federal Reserve Bank of Boston,USA,TESTIMONY OF Paul S. Willen Senior Economist a...,NaN,usa_willen071609,English,CB websites
34913,https://www.bostonfed.org/news-and-events/spee...,NaN,Working Women: The Dream and the Challenge,NaN,2000-12-04,Cathy E Minehan,Governor,Female,Federal Reserve Bank of Boston,USA,Working Women: The Dream and the Challenge By ...,NaN,usa_working-women-the-dream-and-the-challenge,English,CB websites

Federal Reserve Bank of Chicago

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
18756,https://www.bis.org/review/r110916e.pdf,https://www.bis.org/review/r110916e.pdf,The Fed's dual mandate responsibilities and ch...,"Speech by Charles L Evans, President of the Fe...",2011-09-07,Charles L Evans,Governor,Male,Federal Reserve Bank of Chicago,USA,Charles L Evans: The Feds dual mandate respons...,NaN,r110916e,English,BIS
18833,https://www.bis.org/review/r111019c.pdf,https://www.bis.org/review/r111019c.pdf,The Fed's dual mandate responsibilities - main...,"Speech by Charles L Evans, President of the Fe...",2011-10-17,Charles L Evans,Governor,Male,Federal Reserve Bank of Chicago,USA,Charles L Evans: The Feds dual mandate respons...,NaN,r111019c,English,BIS
19038,https://www.bis.org/review/r120112a.pdf,https://www.bis.org/review/r120112a.pdf,A risk management approach to monetary policy,"Speech by Charles L Evans, President of the Fe...",2011-12-05,Charles L Evans,Governor,Male,Federal Reserve Bank of Chicago,USA,Charles L Evans: A risk management approach to...,NaN,r120112a,English,BIS
19162,https://www.bis.org/review/r120319a.pdf,https://www.bis.org/review/r120319a.pdf,Managing monetary policy risks,"Speech by Mr Charles L Evans, President of the...",2012-01-11,Charles L Evans,Governor,Male,Federal Reserve Bank of Chicago,USA,Charles L Evans: Managing monetary policy risk...,NaN,r120319a,English,BIS
19163,https://www.bis.org/review/r120319b.pdf,https://www.bis.org/review/r120319b.pdf,Monetary policy communications and forward gui...,"Speech by Mr Charles L Evans, President of the...",2012-03-16,Charles L Evans,Governor,Male,Federal Reserve Bank of Chicago,USA,Charles L Evans: Monetary policy communication...,NaN,r120319b,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35474,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"Opening Remarks, Is Midwest Manufacturing at a...",NaN,2003-09-30,Michael Moskow,Governor,Male,Federal Reserve Bank of Chicago,USA,IS MIDWEST MANUFACTURING AT A CROSSROADS?\nFED...,NaN,opening-remarks-midwest-manufacturing-a-crossr...,English,Archives
35475,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,U.S. Economic Outlook : Business Week CEO Lead...,NaN,2003-10-02,Michael Moskow,Governor,Male,Federal Reserve Bank of Chicago,USA,BUSINESS WEEK CEO LEADERSHIP FORUM\n\nEvanston...,NaN,us-economic-outlook-581486,English,Archives
35480,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"Opening Remarks, Conference on Geography of Au...",NaN,2003-11-03,Michael Moskow,Governor,Male,Federal Reserve Bank of Chicago,USA,CONFERENCE ON GEOGRAPHY OF AUTO PRODUCTION\nWI...,NaN,opening-remarks-conference-geography-auto-prod...,English,Archives
35482,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Formulating and Communicating U.S. Monetary Po...,NaN,2003-11-13,Michael Moskow,Governor,Male,Federal Reserve Bank of Chicago,USA,9TH INTERNATIONAL FINANCIAL AND ECONOMIC FORUM...,NaN,formulating-communicating-us-monetary-policy-5...,English,Archives
35485,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,U.S. Economic Outlook : [Speech Before the] Ch...,NaN,2003-11-20,Michael Moskow,Governor,Male,Federal Reserve Bank of Chicago,USA,CHICAGOLAND CHAMBER OF COMMERCE / WBBM NEWSRAD...,NaN,us-economic-outlook-581490,English,Archives

Federal Reserve Bank of Cleveland

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
31964,https://www.clevelandfed.org/en/newsroom-and-e...,https://www.clevelandfed.org/~/media/content/e...,"The Economic Outlook, Monetary Policy, and Get...",The Cleveland Association for Business Economi...,2014-09-24,Loretta J Mester,Governor,Female,Federal Reserve Bank of Cleveland,USA,Inflation and Monetary Policy: Six Research Qu...,NaN,usa_2014-ic-inflation-and-monetary-policy-speech,English,CB websites
33028,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,The Outlook for the 1990s and Beyond : Address...,NaN,1992-10-12,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,Outlook for the 1990s and Beyond Jerry L. Jord...,NaN,usa_jerry_l_jordan_1992_10_12,English,Archives
33029,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,Remarks at the Federal Reserve Bank of St. Lou...,NaN,1992-10-16,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,REMARKS BY JERRY L. JORDAN AT THE * . grat. 4 ...,NaN,usa_jerry_l_jordan_1992_10_16,English,Archives
33030,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,Introductory Remarks for Jerry Jordan's Addres...,NaN,1992-10-20,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,Introductory remarks for Jerry Jordan's addres...,NaN,usa_jerry_l_jordan_1992_10_20,English,Archives
33031,https://fraser.stlouisfed.org/files/docs/histo...,https://fraser.stlouisfed.org/title/statements...,Remarks to Baldwin-Wallace Luncheon Club,NaN,1992-10-23,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,Jerry Jordan's Remarks to Baldwin-Wallace Lunc...,NaN,usa_jerry_l_jordan_1992_10_23,English,Archives
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35334,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"The Functions and Future of Banking : Remarks,...",NaN,2000-09-15,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,The Functi...,NaN,functions-future-banking-475262,English,Archives
35340,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,The Information and Communication Revolution: ...,NaN,2000-09-26,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,...,NaN,information-communication-revolution-economics...,English,Archives
35341,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,New Directions in Community Reinvestment : Wel...,NaN,2000-09-28,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,...,NaN,new-directions-community-reinvestment-475264,English,Archives
35346,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Darryl Francis: Maverick in the Formulation of...,NaN,2000-10-19,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,Darryl Francis: ...,NaN,darryl-francis-maverick-formulation-monetary-p...,English,Archives
35378,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,The Origins and Evolution of Central Banking :...,NaN,2001-05-21,Jerry L Jordan,Governor,Male,Federal Reserve Bank of Cleveland,USA,FRB Cleveland - The Origins and Evol...f C...,NaN,origins-evolution-central-banking-475266,English,Archives

Federal Reserve Bank of Dallas

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
18588,https://www.bis.org/review/r110620a.pdf,https://www.bis.org/review/r110620a.pdf,Containing (or restraining) systemic risk - th...,"Remarks by Mr Richard W Fisher, President and ...",2011-06-06,Richard W Fisher,Governor,Male,Federal Reserve Bank of Dallas,USA,Richard W Fisher: Containing (or restraining) ...,NaN,r110620a,English,BIS
18674,https://www.bis.org/review/r110803a.pdf,https://www.bis.org/review/r110803a.pdf,An economic overview - what's next? Rememberin...,"Remarks by Mr Richard W Fisher, President and ...",2011-07-13,Richard W Fisher,Governor,Male,Federal Reserve Bank of Dallas,USA,Richard W Fisher: An economic overview whats ...,NaN,r110803a,English,BIS
18675,https://www.bis.org/review/r110803b.pdf,https://www.bis.org/review/r110803b.pdf,ndale Pues! Get on with advancing hispanic pro...,"Remarks by Mr Richard W Fisher, President and ...",2011-06-16,Richard W Fisher,Governor,Male,Federal Reserve Bank of Dallas,USA,Richard W Fisher: andale Pues! Get on with adv...,NaN,r110803b,English,BIS
18708,https://www.bis.org/review/r110822e.pdf,https://www.bis.org/review/r110822e.pdf,Connecting the dots - Texas employment growth;...,"Remarks by Mr Richard W Fisher, President and ...",2011-08-17,Richard W Fisher,Governor,Male,Federal Reserve Bank of Dallas,USA,Richard W Fisher: Connecting the dots Texas e...,NaN,r110822e,English,BIS
18758,https://www.bis.org/review/r110919b.pdf,https://www.bis.org/review/r110919b.pdf,Of moose and men (with no reference to Steinbeck),"Remarks by Mr Richard W Fisher, President and ...",2011-09-12,Richard W Fisher,Governor,Male,Federal Reserve Bank of Dallas,USA,Richard W Fisher: Of moose and men (with no re...,NaN,r110919b,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35437,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Problems Making the Case for the Market: Good ...,NaN,2002-10-22,Robert D McTeer,Governor,Male,Federal Reserve Bank of Dallas,USA,Speeches by Bob McTeer\nProblems Making the Ca...,NaN,problems-making-case-market-good-intentions-go...,English,Archives
35446,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Reflections and Confessions of an Erstwhile Ec...,NaN,2002-11-24,Robert D McTeer,Governor,Male,Federal Reserve Bank of Dallas,USA,Speeches by Bob McTeer\nReflections and Confes...,NaN,reflections-confessions-erstwhile-economist-59...,English,Archives
35453,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Remarks before the Risk Management Association...,NaN,2003-03-08,Robert D McTeer,Governor,Male,Federal Reserve Bank of Dallas,USA,Speeches by Bob McTeer\nRemarks before the Ris...,NaN,remarks-risk-management-association-napa-valle...,English,Archives
35465,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,The Prodigal Son as Central Banker : H. Parker...,NaN,2003-05-13,Robert D McTeer,Governor,Male,Federal Reserve Bank of Dallas,USA,Speeches by Bob McTeer\nThe Prodigal Son as Ce...,NaN,prodigal-son-central-banker-593984,English,Archives
35466,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"Commencement Address to Economics Graduates, U...",NaN,2003-05-17,Robert D McTeer,Governor,Male,Federal Reserve Bank of Dallas,USA,Speeches by Bob McTeer\nCommencement Address t...,NaN,commencement-address-economics-graduates-unive...,English,Archives

Federal Reserve Bank of Kansas City

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
16456,https://www.bis.org/review/r080916f.pdf,https://www.bis.org/review/r080916f.pdf,Central banks: changing markets - changing man...,"Speech by Mr Thomas M Hoenig, President & CEO ...",2008-09-01,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,Thomas M Hoenig: Central banks: changing marke...,NaN,r080916f,English,BIS
17507,https://www.bis.org/review/r100226e.pdf,https://www.bis.org/review/r100226e.pdf,Knocking on the central bank's door,"Speech by Mr Thomas M Hoenig, President of the...",2010-02-16,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,Thomas M Hoenig: Knocking on the central banks...,NaN,r100226e,English,BIS
17557,https://www.bis.org/review/r100324e.pdf,https://www.bis.org/review/r100324e.pdf,Are community banks important?,"Speech by Mr Thomas M Hoenig, President of the...",2010-03-18,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,Thomas M Hoenig: Are community banks important...,NaN,r100324e,English,BIS
17573,https://www.bis.org/review/r100329e.pdf,https://www.bis.org/review/r100329e.pdf,The financial foundation for Main Street,"Speech by Mr Thomas M Hoenig, President of the...",2010-03-24,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,Thomas M Hoenig: The financial foundation for ...,NaN,r100329e,English,BIS
17697,https://www.bis.org/review/r100511e.pdf,https://www.bis.org/review/r100511e.pdf,Leverage - the double-edged sword,"Written statement by Mr Thomas M Hoenig, Presi...",2010-05-06,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,Thomas M Hoenig: Leverage the double-edged sw...,NaN,r100511e,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34493,https://www.kansascityfed.org/documents/2557/s...,https://www.kansascityfed.org/documents/2557/s...,Low Inflation and the Economic Outlook,"Outlook 1998: The Economy, Technology, and Trade",1998-01-22,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,LOW INFLATION AND THE ECONOMIC OUTLOOK Comment...,NaN,usa_speeches-outlook,English,CB websites
34494,https://www.kansascityfed.org/documents/2459/s...,https://www.kansascityfed.org/documents/2459/s...,The Economic Outlook in 2004: Challenges for M...,NaN,2004-01-08,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,The Economic Outlook in 2004 Challenges for Mo...,NaN,usa_speeches-topekarotary1-8-04,English,CB websites
34495,https://www.kansascityfed.org/documents/2075/s...,https://www.kansascityfed.org/documents/2075/s...,The U.S. Economy in 2003,NaN,2003-05-13,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,The U.S. Economy in 2003 Thomas M. Hoenig Fede...,NaN,usa_speeches-usecon2003,English,CB websites
34496,https://www.kansascityfed.org/documents/1787/s...,https://www.kansascityfed.org/documents/1787/s...,Comments on the Volcker Rule Activity Restrict...,NaN,2010-03-02,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,Comments on the Volcker Rule Activity Restrict...,NaN,usa_speeches-volckerrulecomments030210,English,CB websites
34497,https://www.kansascityfed.org/documents/1713/s...,https://www.kansascityfed.org/documents/1713/s...,It's Not Over 'Til It's Over: Leadership and F...,The William Taylor Memorial Lecture,2010-10-10,Thomas M Hoenig,Governor,Male,Federal Reserve Bank of Kansas City,USA,ITS NOT OVER TIL ITS OVER: LEADERSHIP AND FINA...,NaN,usa_speeches-william-taylor-hoenig-10-10-10,English,CB websites

Federal Reserve Bank of New York

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12506,https://www.bis.org/review/r000328a.pdf,https://www.bis.org/review/r000328a.pdf,Mr McDonough discusses sound banking systems: ...,"Speech by Mr William J McDonough, President of...",2000-03-24,William J McDonough,Governor,Male,Federal Reserve Bank of New York,USA,Mr McDonough discusses sound banking systems: ...,NaN,r000328a,English,BIS
12510,https://www.bis.org/review/r000403b.pdf,https://www.bis.org/review/r000403b.pdf,Mr McDonough comments on the implications for ...,"Speech by Mr William J McDonough, President of...",2000-03-30,William J McDonough,Governor,Male,Federal Reserve Bank of New York,USA,Mr McDonough comments on the implications for ...,NaN,r000403b,English,BIS
12519,https://www.bis.org/review/r000412a.pdf,https://www.bis.org/review/r000412a.pdf,Future challenges for bankers and bank supervi...,"Remarks by Mr William J McDonough, President o...",2000-04-06,William J McDonough,Governor,Male,Federal Reserve Bank of New York,USA,William J McDonough: Future challenges for ban...,NaN,r000412a,English,BIS
12565,https://www.bis.org/review/r000622b.pdf,https://www.bis.org/review/r000622b.pdf,Update on the major initiative to revise the 1...,"Speech by Mr William J McDonough, President an...",2000-06-19,William J McDonough,Governor,Male,Federal Reserve Bank of New York,USA,William J McDonough: Update on the major initi...,NaN,r000622b,English,BIS
12577,https://www.bis.org/review/r000713b.pdf,https://www.bis.org/review/r000713b.pdf,The foundation of financial stability (Centra...,"Speech by Mr William J McDonough, President an...",2000-07-08,William J McDonough,Governor,Male,Federal Reserve Bank of New York,USA,William J McDonough: The foundation of financi...,NaN,r000713b,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34917,https://www.newyorkfed.org/newsevents/speeches...,NaN,"Act Now, and Choose Wisely",Remarks at the 2021 ISDA North America Conference,2021-10-27,Nathaniel Wuerffel,Senior management,Male,Federal Reserve Bank of New York,USA,"10/03/2022, 21:26 Act Now, and Choose Wisely S...",NaN,usa_wue211027,English,CB websites
34918,https://www.newyorkfed.org/newsevents/speeches...,NaN,Wuerffel: Lessons from the Market Functioning ...,NaN,2023-03-03,Nathaniel Wuerffel,Senior management,Male,Federal Reserve Bank of New York,USA,SPTTCrf Lessons from the Market Functioning Pu...,NaN,usa_wuerffel_44988,English,CB websites
34923,https://www.newyorkfed.org/newsevents/speeches...,NaN,Zobel: The Ample Reserves Framework and Balanc...,NaN,2022-09-08,Patricia Zobel,Senior management,Female,Federal Reserve Bank of New York,USA,SPEECH The Ample Reserves Framework and Balanc...,NaN,usa_zobel_44812,English,CB websites
35171,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,The Federal Reserve System's Supervision and R...,NaN,1998-04-02,Ernest T Patrikis,Deputy Governor,Male,Federal Reserve Bank of New York,USA,THE ...,NaN,federal-reserve-systems-supervision-regulation...,English,Archives
35350,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,The Growing Importance of Financial Literacy E...,NaN,2001-01-12,Jamie B Stewart,Deputy Governor,Male,Federal Reserve Bank of New York,USA,SPEECH\n\n\nStewart: The Growing Importance of...,NaN,growing-importance-financial-literacy-educatio...,English,Archives

Federal Reserve Bank of Philadelphia

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
18574,https://www.bis.org/review/r110615a.pdf,https://www.bis.org/review/r110615a.pdf,A credible commitment to normalization,"Speech by Mr Charles I Plosser, President and ...",2011-06-06,Charles I Plosser,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Charles I Plosser: A credible commitment to no...,NaN,r110615a,English,BIS
18604,https://www.bis.org/review/r110622g.pdf,https://www.bis.org/review/r110622g.pdf,The US economic outlook and the normalization ...,"Speech by Mr Charles I Plosser, President and ...",2011-06-09,Charles I Plosser,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Charles I Plosser: The US economic outlook and...,NaN,r110622g,English,BIS
18802,https://www.bis.org/review/r111004d.pdf,https://www.bis.org/review/r111004d.pdf,Economic outlook,"Speech by Mr Charles I Plosser, President and ...",2011-09-29,Charles I Plosser,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Charles I Plosser: Economic outlook Speech by ...,NaN,r111004d,English,BIS
18825,https://www.bis.org/review/r111014b.pdf,https://www.bis.org/review/r111014b.pdf,Outlook and a perspective on monetary policy,Text of the Farash Distinguished Lecture by Mr...,2011-10-12,Charles I Plosser,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Charles I Plosser: Outlook and a perspective o...,NaN,r111014b,English,BIS
18884,https://www.bis.org/review/r111110h.pdf,https://www.bis.org/review/r111110h.pdf,Strengthening our monetary policy framework th...,"Speech by Mr Charles I Plosser, President and ...",2011-11-08,Charles I Plosser,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Charles I Plosser: Strengthening our monetary ...,NaN,r111110h,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35469,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Flexible Commitment or Inflation Targeting for...,NaN,2003-06-10,Anthony M Santomero,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Flexible Commitment or Inflation Targeting for...,NaN,flexible-commitment-inflation-targeting-us-589505,English,Archives
35476,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Monetary Policy in the Post 9/11 Environment: ...,NaN,2003-10-02,Anthony M Santomero,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Monetary Policy in the Post 9/11 Environment: ...,NaN,monetary-policy-post-9-11-environment-stabilit...,English,Archives
35481,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Great Expectations : Beliefs in Economics and ...,NaN,2003-11-05,Anthony M Santomero,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Great Expectations: Beliefs in Economics and M...,NaN,great-expectations-589507,English,Archives
35483,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Perspectives on the Jobless Recovery : The Phi...,NaN,2003-11-14,Anthony M Santomero,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Perspectives on the Jobless Recovery\nPresente...,NaN,perspectives-jobless-recovery-589508,English,Archives
35484,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"Monetary Policy: Stability Through Change, Phi...",NaN,2003-11-18,Anthony M Santomero,Governor,Male,Federal Reserve Bank of Philadelphia,USA,Monetary Policy: Stability Through Change\nPre...,NaN,monetary-policy-stability-change-philadelphia-...,English,Archives

Federal Reserve Bank of Richmond

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
21559,https://www.bis.org/review/r150210h.htm,https://www.bis.org/review/r150210h.pdf,"Economic outlook, January 2015","Speech by Mr Jeffrey M Lacker, President of th...",2015-01-09,Jeffrey M Lacker,Governor,Male,Federal Reserve Bank of Richmond,USA,"Jeffrey M Lacker: Economic outlook, January 20...",NaN,r150210h,English,BIS
21563,https://www.bis.org/review/r150212c.htm,https://www.bis.org/review/r150212c.pdf,"Education, Innovation and Economic Growth","Speech by Mr Jeffrey M Lacker, President of th...",2015-02-10,Jeffrey M Lacker,Governor,Male,Federal Reserve Bank of Richmond,USA,"Jeffrey M Lacker: Education, Innovation and Ec...",NaN,r150212c,English,BIS
32387,https://www.richmondfed.org/press_room/speeche...,NaN,"Economic Outlook, January 2018",NaN,2018-01-05,Kartik Athreya,Deputy Governor,Male,Federal Reserve Bank of Richmond,USA,Home / News / Speeches / Kartik B Athreya / 20...,NaN,usa_athreya_speech_20180105,English,CB websites
32388,https://www.richmondfed.org/press_room/speeche...,NaN,Challenges for Policymakers in a Low Interest ...,NaN,2018-05-25,Kartik Athreya,Deputy Governor,Male,Federal Reserve Bank of Richmond,USA,Home / News / Speeches / Kartik B Athreya / 20...,NaN,usa_athreya_speech_20180525,English,CB websites
32389,https://www.richmondfed.org/press_room/speeche...,NaN,Keeping Economic Education Relevant in a Turbu...,NaN,2020-10-01,Kartik Athreya,Deputy Governor,Male,Federal Reserve Bank of Richmond,USA,Home / News / Speeches / Kartik B Athreya / 20...,NaN,usa_athreya_speech_20201001,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34708,https://www.richmondfed.org/press_room/speeche...,NaN,Recession Revisited,President Tom Barkin discusses whats driving t...,2023-08-03,Tom Barkin,Governor,Male,Federal Reserve Bank of Richmond,USA,FEDERAL RESERVE BANK OF RICHMOND Richmond Balt...,NaN,usa_tom_barkin_45141,English,CB websites
34709,https://www.richmondfed.org/press_room/speeche...,NaN,The New Job Hierarchy,President Tom Barkin explores whats happening ...,2023-09-28,Tom Barkin,Governor,Male,Federal Reserve Bank of Richmond,USA,FEDERAL RESERVE BANK OF RICHMOND Richmond Balt...,NaN,usa_tom_barkin_45197,English,CB websites
34710,https://www.richmondfed.org/press_room/speeche...,NaN,Looking Beyond Recent Data,President Tom Barkin discusses what he is hear...,2023-10-17,Tom Barkin,Governor,Male,Federal Reserve Bank of Richmond,USA,FEDERAL RESERVE BANK OF RICHMOND Richmond Balt...,NaN,usa_tom_barkin_45216,English,CB websites
34711,https://www.richmondfed.org/press_room/speeche...,NaN,Whats Next for the Economy?,President Tom Barkin explores potential paths ...,2023-11-09,Tom Barkin,Governor,Male,Federal Reserve Bank of Richmond,USA,FEDERAL RESERVE BANK OF RICHMOND Richmond Balt...,NaN,usa_tom_barkin_45239,English,CB websites
34712,https://www.richmondfed.org/press_room/speeche...,NaN,The Housing Challenge,President Tom Barkin shares how communities in...,2023-11-15,Tom Barkin,Governor,Male,Federal Reserve Bank of Richmond,USA,Fill FEDERAL RESERVE BANK Illlll OF RICHMOND8 ...,NaN,usa_tom_barkin_45245,English,CB websites

Federal Reserve Bank of San Francisco

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12623,https://www.bis.org/review/r001005c.pdf,https://www.bis.org/review/r001005c.pdf,Monetary policy in a new environment - the US ...,"Speech by Mr Robert T Parry, President and Chi...",2000-09-28,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,Robert T Parry: Monetary policy in a new envir...,NaN,r001005c,English,BIS
14381,https://www.bis.org/review/r050810g.pdf,https://www.bis.org/review/r050810g.pdf,Views on the economy and implications for mone...,"Speech by Ms Janet L Yellen, President and CEO...",2005-07-29,Janet L Yellen,Governor,Female,Federal Reserve Bank of San Francisco,USA,Janet L Yellen: Views on the economy and impli...,NaN,r050810g,English,BIS
19134,https://www.bis.org/review/r120302b.pdf,https://www.bis.org/review/r120302b.pdf,The economic outlook and monetary policy,"Presentation by Mr John C Williams, President ...",2012-03-01,John C Williams,Governor,Male,Federal Reserve Bank of San Francisco,USA,John C Williams: The economic outlook and mone...,NaN,r120302b,English,BIS
30993,https://www.frbsf.org/files/000124.pdf,https://www.frbsf.org/files/000124.pdf,National Association for Business Economics\r\...,NaN,2000-01-24,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,National Association for Business Economics Lo...,NaN,usa_000124,English,CB websites
30995,https://www.frbsf.org/files/000329.pdf,https://www.frbsf.org/files/000329.pdf,European Banking and Financial Forum\r\nPrague...,NaN,2000-03-29,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,"For delivery Wednesday, March 29, 2000, at app...",NaN,usa_000329,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35048,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Economic Trends in California and the Nation :...,NaN,1996-02-29,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,EMBARGOED UNTIL 2/29/96 ...,NaN,economic-trends-california-nation-3742,English,Archives
35052,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Economic Trends in California and the Nation :...,NaN,1996-03-05,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,Employers Group\n ...,NaN,economic-trends-california-nation-3785,English,Archives
35054,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Economic Trends in the West and the Nation : W...,NaN,1996-03-08,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,...,NaN,economic-trends-west-nation-3800,English,Archives
35067,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Global Payments in the 21st Century: A Central...,NaN,1996-04-17,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,...,NaN,global-payments-21st-century-a-central-banker-...,English,Archives
35087,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,Honorary Degree Acceptance Remarks : Southern ...,NaN,1996-06-01,Robert T Parry,Governor,Male,Federal Reserve Bank of San Francisco,USA,...,NaN,honorary-degree-acceptance-remarks-3690,English,Archives

Federal Reserve Bank of St Louis

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
31947,https://www.stlouisfed.org/from-the-president/...,https://www.stlouisfed.org/from-the-president/...,"A Perspective on the U.S. Economy,",Northwest Arkansas Convention Center,2008-06-04,James Bullard,Governor,Male,Federal Reserve Bank of St Louis,USA,"7:00 a.m. CDT June 4, 2008 A Perspective on th...",NaN,usa_2008-06-04,English,CB websites
31948,https://www.stlouisfed.org/from-the-president/...,https://www.stlouisfed.org/from-the-president/...,Remarks on the U.S. Economy and the State of t...,Fluno Center for Executive Education,2008-06-06,James Bullard,Governor,Male,Federal Reserve Bank of St Louis,USA,"Embargoed until 12:30 p.m. CDT June 6, 2008 Re...",NaN,usa_2008-06-06,English,CB websites
31949,https://www.stlouisfed.org/from-the-president/...,https://www.stlouisfed.org/from-the-president/...,"Remarks on the U.S. Economy,",Macroeconomics Advisers Quarterly Outlook Meeting,2008-06-11,James Bullard,Governor,Male,Federal Reserve Bank of St Louis,USA,"12:00 p.m CDT June 11, 2008 Remarks on the U.S...",NaN,usa_2008-06-11,English,CB websites
31951,https://www.stlouisfed.org/annual-report/2010,NaN,The Fed's Dual Mandate: Lessons of the 1970s,NaN,2011-04-26,James Bullard,Governor,Male,Federal Reserve Bank of St Louis,USA,2010 Annual Report 2010 Home Many Moving Parts...,NaN,usa_2010,English,CB websites
31956,https://www.stlouisfed.org/annual-report/2012/...,NaN,The St. Louis Fed's New Center for Household F...,NaN,2013-05-30,James Bullard,Governor,Male,Federal Reserve Bank of St Louis,USA,2012 Annual Report 2012 Home President's Messa...,NaN,usa_2012_president,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35126,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"""Electronic Money, Inflation, and the Role of ...",NaN,1997-04-25,Thomas C Melzer,Governor,Male,Federal Reserve Bank of St Louis,USA,EMBARGOED UNTIL 7:00 ...,NaN,electronic-money-inflation-role-fed-payments-s...,English,Archives
35130,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"""A Credible Monetary Policy Sustains Growth"" :...",NaN,1997-06-04,Thomas C Melzer,Governor,Male,Federal Reserve Bank of St Louis,USA,EMBARGOED UNTIL 9:15 ...,NaN,a-credible-monetary-policy-sustains-growth-18803,English,Archives
35143,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"""Would Lower Inflation Reduce Growth?"" : Remar...",NaN,1997-10-07,Thomas C Melzer,Governor,Male,Federal Reserve Bank of St Louis,USA,EMBARGOED UNTIL 8:00 a...,NaN,would-lower-inflation-reduce-growth-18804,English,Archives
35146,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"""Price Stability Policies for Growth"" : Remark...",NaN,1997-10-28,Thomas C Melzer,Governor,Male,Federal Reserve Bank of St Louis,USA,"EMBARGOED UNTIL 11:00 a.m.,...",NaN,price-stability-policies-growth-18805,English,Archives
35157,https://fraser.stlouisfed.org/title/statements...,https://fraser.stlouisfed.org/files/docs/histo...,"Statement, Audio Press Conference",NaN,1998-01-21,Thomas C Melzer,Governor,Male,Federal Reserve Bank of St Louis,USA,EMBARGOED UNTIL CONCL...,NaN,statement-audio-press-conference-18806,English,Archives

Monetary Authority of Singapore

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
12470,https://www.bis.org/review/r000203c.pdf,https://www.bis.org/review/r000203c.pdf,Mr Lim gives a policymaker's perspective on th...,"Opening remarks by Mr Lim Hng Kiang, Member of...",2000-02-02,Lim Hng Kiang,Board member,Male,Monetary Authority of Singapore,SGP,Mr Lim gives a policymakers perspective on the...,NaN,r000203c,English,BIS
12513,https://www.bis.org/review/r000405b.pdf,https://www.bis.org/review/r000405b.pdf,Financial sector liberalisation - going global...,"Speech by Mr Lee Hsien Loong, Chairman of the ...",2000-04-03,Lee Hsien Loong,Governor,Male,Monetary Authority of Singapore,SGP,Lee Hsien Loong: Financial sector liberalisati...,NaN,r000405b,English,BIS
12570,https://www.bis.org/review/r000626b.pdf,https://www.bis.org/review/r000626b.pdf,Separation of financial and non-financial acti...,"Speech by DPM Lee Hsien Loong, Chairman of the...",2000-06-21,Lee Hsien Loong,Governor,Male,Monetary Authority of Singapore,SGP,Lee Hsien Loong: Separation of financial and n...,NaN,r000626b,English,BIS
12587,https://www.bis.org/review/r000803b.pdf,https://www.bis.org/review/r000803b.pdf,The economic outlook and monetary policy in Si...,"Statement by Mr Koh Yong Guan, Managing Direct...",2000-07-27,Koh yong Guan,Senior management,Male,Monetary Authority of Singapore,SGP,Koh Yong Guan: The economic outlook and moneta...,NaN,r000803b,English,BIS
12602,https://www.bis.org/review/r000907a.pdf,https://www.bis.org/review/r000907a.pdf,Capital markets in the new economy (Central B...,"Speech by Mr Lee Hsien Loong, Chairman of the ...",2000-09-06,Lee Hsien Loong,Governor,Male,Monetary Authority of Singapore,SGP,Lee Hsien Loong: Capital markets in the new ec...,NaN,r000907a,English,BIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29590,https://www.mas.gov.sg/news/speeches/2023/stre...,NaN,Strengthening Supervision Through Collaborativ...,NaN,2023-03-22,Tan Keng Heng,Senior management,Male,Monetary Authority of Singapore,SGP,Strengthening Supervision Through Collaborativ...,NaN,sgp_tan_keng_heng_45007,English,CB websites
29591,https://www.mas.gov.sg/news/speeches/2023/over...,NaN,"Speech by Mr Tan Kiat How, Senior Minister of ...",NaN,2023-05-23,Tan Kiat How,Board member,Male,Monetary Authority of Singapore,SGP,"Speech by Mr Tan Kiat How, Senior Minister of ...",NaN,sgp_tan_kiat_how_45069,English,CB websites
29592,https://www.mas.gov.sg/news/speeches/2023/sing...,NaN,"""Singapore's National AI Programme in the Real...",NaN,2023-11-14,Tan Kiat How,Board member,Male,Monetary Authority of Singapore,SGP,"""Singapore's National Al Programme in the Real...",NaN,sgp_tan_kiat_how_45244,English,CB websites
29593,https://www.mas.gov.sg/news/speeches/2022/resp...,NaN,Responding to a Perfect Long Storm Transcript...,NaN,2022-03-09,Tharman Shanmugaratnam,Governor,Male,Monetary Authority of Singapore,SGP,Responding to a Perfect Long Storm - Transcrip...,NaN,sgp_tharman_shanmugaratnam_44629,English,CB websites
29594,https://www.mas.gov.sg/news/speeches/2022/rema...,NaN,"Remarks by Mr Tharman Shanmugaratnam, Senior M...",NaN,2022-12-02,Tharman Shanmugaratnam,Governor,Male,Monetary Authority of Singapore,SGP,"Remarks by Mr Tharman Shanmugaratnam, Senior M...",NaN,sgp_tharman_shanmugaratnam_44897,English,CB websites

Reserve Bank of India

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source
7917,https://www.rbi.org.in/Scripts/BS_SpeechesView...,https://rbidocs.rbi.org.in/rdocs/Speeches/PDFs...,Indias Economic Reforms: Reflections on the Un...,Indias Economic Reforms: Reflections on the Un...,2017-12-11,Vijay Joshi,Deputy Governor,Male,Reserve Bank of India,IND,Indias Economic Reforms: Reflections on the Un...,NaN,ind_02sp10021840cf3ece274447f1824d42d94c41a427...,English,CB websites
7918,https://www.rbi.org.in/Scripts/BS_SpeechesView...,https://rbidocs.rbi.org.in/rdocs/Speeches/PDFs...,Future of Rural Banking,Future of Rural Banking,1999-12-04,Yaga Venugopal Reddy,Deputy Governor,Male,Reserve Bank of India,IND,Future of Rural Banking* Respected Professor K...,NaN,ind_10428,English,CB websites
7919,https://www.rbi.org.in/Scripts/BS_SpeechesView...,https://rbidocs.rbi.org.in/rdocs/Speeches/PDFs...,Finance and Development Which Way Now? - Bima...,Finance and Development Which Way Now?,1999-12-06,Bimal Jalan,Governor,Male,Reserve Bank of India,IND,Finance and Development Which Way Now? The An...,NaN,ind_10445,English,CB websites
7920,https://www.rbi.org.in/Scripts/BS_SpeechesView...,https://rbidocs.rbi.org.in/rdocs/Speeches/PDFs...,"""Is Inflation Dead"" - Some Comments","""Is Inflation Dead"" - Some Comments",2000-02-02,Yaga Venugopal Reddy,Deputy Governor,Male,Reserve Bank of India,IND,"""Is Inflation Dead"" - Some Comments* Honourabl...",NaN,ind_11265,English,CB websites
7921,https://www.rbi.org.in/Scripts/BS_SpeechesView...,https://rbidocs.rbi.org.in/rdocs/Speeches/PDFs...,Agenda for Banking in the Millenium,Agenda for Banking in the Millenium,2000-02-09,Bimal Jalan,Governor,Male,Reserve Bank of India,IND,Agenda for Banking in the Millenium* Thank you...,NaN,ind_11444,English,CB websites
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28531,https://www.bis.org/review/r981221b.pdf,https://www.bis.org/review/r981221b.pdf,Mr Jalan looks towards a more vibrant banking ...,Inaugural address by the Governor of the Reser...,1998-12-16,Bimal Jalan,Governor,Male,Reserve Bank of India,IND,Mr Jalan looks towards a more vibrant banking ...,NaN,r981221b,English,BIS
28549,https://www.bis.org/review/r990205b.pdf,https://www.bis.org/review/r990205b.pdf,Mr Talwar considers emerging trends in supervi...,"Speech by Mr S P Talwar, a Deputy Governor of ...",1999-01-27,S P Talwar,Deputy Governor,Male,Reserve Bank of India,IND,Mr Talwar considers emerging trends in supervi...,NaN,r990205b,English,BIS
28560,https://www.bis.org/review/r990215c.pdf,https://www.bis.org/review/r990215c.pdf,Mr Reddy discusses issues in fixed income mark...,"Inaugural address by Dr Y V Reddy, a Deputy Go...",1999-11-02,Yaga Venugopal Reddy,Governor,Male,Reserve Bank of India,IND,Mr Reddy discusses issues in fixed income mark...,NaN,r990215c,English,BIS
28631,https://www.bis.org/review/r990531b.pdf,https://www.bis.org/review/r990531b.pdf,Mr Reddy discusses monetary policy in India (...,"Speech by Y.V. Reddy, Deputy Governor of the R...",1999-05-26,Yaga Venugopal Reddy,Governor,Male,Reserve Bank of India,IND,Mr Reddy discusses monetary policy in India Sp...,NaN,r990531b,English,BIS
28638,https://www.bis.org/review/r990615b.pdf,https://www.bis.org/review/r990615b.pdf,Mr Reddy looks at external debt policies in em...,Speech by the Deputy Governor of the Reserve B...,1999-06-11,Yaga Venugopal Reddy,Governor,Male,Reserve Bank of India,IND,Mr Reddy looks at external debt policies in em...,NaN,r990615b,English,BIS

In [30]:
df_original = pd.read_csv('../Data/Speeches/cleaned_speeches.csv', sep='\t')

In [31]:
df_original.groupby('speechID')#['nWords'].sum().astype(float).describe()  # 1200 speeches, average 5900 words, median 4400

,speechID,speechName,paraNum,para,nWords,isFootnote,isGraphic,isEndMatter,date,speaker,isMPC,isFPC,isPRC
0,1,developments-in-uk-financial-markets,1,Developments in UK financial markets Speech gi...,43,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
1,1,developments-in-uk-financial-markets,2,"""The UKs new monetary framework Perhaps the si...",146,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
2,1,developments-in-uk-financial-markets,3,The framework put in place with that announcem...,33,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
3,1,developments-in-uk-financial-markets,4,"""First, the target the Bank of England is to p...",79,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
4,1,developments-in-uk-financial-markets,5,"""Secondly, it is then the responsibility of th...",120,False,False,False,1997-11-18,IAN PLENDERLEITH,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88401,1495,cost-of-capital-and-uk-business-investment-sli...,17,Sales surprises and the marginal propensity to...,149,False,False,False,2024-05-17,CATHERINE L MANN,True,False,False
88402,1503,remarks-given-by-swati-dhingra-at-econdat-2024...,10,Bank of England Page 12 Appendix Chart 8: Cent...,44,False,False,False,2024-05-10,SWATI DHINGRA,True,False,False
88403,1520,monetary-policy-lessons-from-the-pandemic.pdf,3,Analytical Toolkit Fools Gold: refinements to ...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88404,1520,monetary-policy-lessons-from-the-pandemic.pdf,5,Analytical Toolkit Fools Gold: forecast refine...,19,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False
88405,1520,monetary-policy-lessons-from-the-pandemic.pdf,6,Research design to understand mechanisms Granu...,126,False,False,False,2024-10-14,SWATI DHINGRA,True,False,False